### ISSUE TITLE
Tests for solid-start

### ISSUE THREAD

**Issue by nksaraf** [solidjs/solid-start#100]
We need a good suite of:
* unit tests for APIs
* e2e tests for some of the examples that test our functionality

We should then run these as Github Actions.. we need confidence across the adapters

**Comment by atk** [comment]
I'll gladly help with the tests. I would currently advise using either vitest or uvu for the unit tests. SvelteKit uses uvu. Vitest currently runs only with pnpm, but since we're using that anyway, this shouldn't be an issue. Both options are viable, uvu is faster, but slightly less convenient.

**Comment by nksaraf** [comment]
Yeah I too was thinking vitest should be a good option, we already know how to configure it.. the scope of the testing is a question in my mind.. we have these core APIs like server and createForm that we want to unit test.. maybe some of the server handlers.. but also seems to me that the most valuable tests are going to be the e2e playwright tests and that make sure everything works well together

**Comment by atk** [comment]
uvu works with playwright, too. But vitest is definitely more comfortable. So vitest it is?

**Comment by nksaraf** [comment]
We have started adding an integration test suite with playwright, and unit tests with vitest in https://github.com/solidjs/solid-start/tree/main/test

We could definitely use contributions there as we expand our test suite!
