### ISSUE TITLE
[Bug?]: `with-authjs` template project fails to install with dependency errors

### ISSUE THREAD

**Issue by chris31415926535** [solidjs/solid-start#1007]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The default solid-start template `with-authjs` fails with the following dependency errors on install:

```
> npm install

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: authtest@undefined
npm ERR! Found: solid-start@0.3.3
npm ERR! node_modules/solid-start
npm ERR!   solid-start@"^0.3.3" from the root project
npm ERR!   peer solid-start@"*" from solid-start-aws@0.3.3
npm ERR!   node_modules/solid-start-aws
npm ERR!     peerOptional solid-start-aws@"*" from solid-start@0.3.3
npm ERR!   7 more (solid-start-cloudflare-pages, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer solid-start@"^0.2.15" from @solid-auth/base@2.0.3
npm ERR! node_modules/@solid-auth/base
npm ERR!   @solid-auth/base@"^2.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Expected behavior 🤔

Npm should install the packages without dependency errors.

### Steps to reproduce 🕹

Steps:

At command line:

1. `npm init solid@latest`
2. Choose template "with-authjs"
3. Complete setup wizard: SSR, TS
4. `npm install`

### Context 🔦

Trying to set up and run the template solid-start project with Auth.js integration. It worked with prior versions of solid-start, but I'm not sure when the dependency issues began.

Thanks for all your work on this great project!

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
