### ISSUE TITLE
[Bug?]: solid-start-static build doesn't work with "(home).tsx" style filenames

### ISSUE THREAD

**Issue by elliotwaite** [solidjs/solid-start#1012]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If I run `solid-start build` while using the `solid-start-static` Vite adapter, the route at `src/routes/index.tsx` produces an output file at `dist/public/index.html` as expected. However, if I change the `src/routes/index.tsx` filename to `src/routes/(home).tsx`, then the `dist/public/index.html` file is no longer produced.

It seems like the `solid-start-static` Vite adapter doesn't properly handle the alternative index filename style (e.g. `(home).tsx`).

As a temporary workaround, I can fix the issue by adding the missing routes to the `prerenderRoutes` option of the Vite plugin:
```
export default defineConfig({
  plugins: [solid({ adapter: staticAdapter(), prerenderRoutes: ["/"] })],
})
```
However, it seems like this shouldn't be required.

### Expected behavior 🤔

I expected the route at `src/routes/(home).tsx` to produce the `dist/public/index.html` file when building using the `solid-start-static` adapter.

### Steps to reproduce 🕹

Steps:

1. `npm init solid@latest`
    * `Where do you want to create the app? › my-app`
    * `Which template do you want to use? › bare`
    * `Server Side Rendering? › n`
    * `Use TypeScript? › y`
2. `cd my-app`
3. `npm add --save-dev solid-start-static`
4. Edit `vite.config.ts` to be:
```
import solid from "solid-start/vite"
import staticAdapter from "solid-start-static"
import { defineConfig } from "vite"

export default defineConfig({
  plugins: [solid({ adapter: staticAdapter() })],
})
```
5. Rename `src/routes/index.tsx` to `src/routes/(home).tsx`
6. `npm run build`
7. Notice that `dist/public/index.html` does not exist.

### Context 🔦

I am trying to build the site for static hosting.

### Your environment 🌎

```shell
OS: macOS Ventura 13.2.1
solid-start: 0.3.3
solid-start-static: 0.3.3
```

**Comment by edivados** [comment]
Looks like the router does not generate the same path for a renamed index as it would for a index file. This causes the static adapter to behave this way. Opened a PR.
