### ISSUE TITLE
[Documentation] Custom base path

### ISSUE THREAD

**Issue by devinrhode2** [solidjs/solid-start#1013]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I believe it may be useful to some folks, to add a documentation page around setting a custom `base` url.

I would like to document one caveat: When running `npm run build && npm run start`, it seems that the assets are not loading from the provided base url. A hack I am using is changing my `build` script to `solid-start build; rsync -a ./dist/public/ ./dist/public/YOUR_BASE_URL/;`, where `YOUR_BASE_URL` is the same value present in vite.config.ts.

### Motivation 🔦

Solid app is being deployed to `pre-existing.domain.com/new_path/`

**Comment by devinrhode2** [comment]
It seems ajax requests are hitting `domain.com/_m` and aren't prefixed.

I suppose solid-start needs to be patched to prefix ajax request urls with `BASE_URL`

While an nginx server can map `domain.com/base/` to `solid-start-server:2227/`, the code that ends up in the browser needs to actually make a request to `domain.com/base/`, otherwise it will fail.

Patching with package-patch doesn't seem too hard.

**Comment by devinrhode2** [comment]
I was doing a simple test with links.

Create a new solid app:
```
npm init solid@latest

create-solid version 0.2.31

Welcome to the SolidStart setup wizard!

There are definitely bugs and some feature might not work yet.
If you encounter an issue, have a look at https://github.com/solidjs/solid-start/issues and open a new one, if it is not already tracked.

✔ Where do you want to create the app? … mfcore2
✔ Which template do you want to use? › bare
✔ Server Side Rendering? … yes
✔ Use TypeScript? … yes
found matching commit hash: b2a09b38f13024b706fe71e572c4231c92d4d15b
```

Create a `routes/foo/about.tsx` file:
```tsx file=src/routes/foo/about.tsx
import { A } from '@solidjs/router';
import { Title } from 'solid-start';

export default function About() {
  return (
    <main>
      <Title>/foo/about</Title>
      <h1>/foo/about</h1>
      <A href="/foo/learn">Go to /foo/learn</A>
    </main>
  );
}
```

```tsx file=src/routes/foo/learn.tsx
import { A } from '@solidjs/router';
import { Title } from 'solid-start';

export default function Learn() {
  return (
    <main>
      <Title>/foo/learn</Title>
      <h1>/foo/learn</h1>
      <A href="/foo/about">Go to /foo/about</A>
    </main>
  );
}
```

`npm run build && npm run start`

Open `localhost:3000/foo/about`. Notice you can load the page fine, and clicking between about and learn pages.

Then set `base: '/foo'` in `vite.config.ts`.

First issue we notice is that css doesn't load:
<img width="1268" alt="ScreenShot 2023-08-18 at 12 58 04@2x" src="https://github.com/solidjs/solid-start/assets/539816/e394f2f5-5d8f-45ec-bf01-86f7f172e060">

That is easily fixed with an ` rsync -a ./dist/public/ ./dist/public/YOUR_BASE_URL/;` after the build runs.

Loading a page now shows this:
<img width="1247" alt="ScreenShot 2023-08-18 at 12 52 20@2x" src="https://github.com/solidjs/solid-start/assets/539816/c08b3b33-1c69-4199-9a60-3355c85d5f0b">

Clicking the `/foo/about` or `/foo/learn` link shows this:
<img width="1261" alt="ScreenShot 2023-08-18 at 12 59 28@2x" src="https://github.com/solidjs/solid-start/assets/539816/70193c81-3878-4f5d-a272-dca72c438714">

**Comment by devinrhode2** [comment]
This yielded some strange results:
<img width="1199" alt="ScreenShot 2023-08-18 at 13 19 20@2x" src="https://github.com/solidjs/solid-start/assets/539816/ce8fed5e-2ae6-4b12-ad36-1a934edbc7d3">

**Comment by devinrhode2** [comment]
Ok, here's patch for ajax urls:
```diff
diff --git a/node_modules/solid-start/server/server-functions/babel.js b/node_modules/solid-start/server/server-functions/babel.js
index 285cd4e..18e2fe4 100644
--- a/node_modules/solid-start/server/server-functions/babel.js
+++ b/node_modules/solid-start/server/server-functions/babel.js
@@ -6,7 +6,7 @@
 import crypto from "crypto";
 import nodePath from "path";
 
-const INLINE_SERVER_ROUTE_PREFIX = "/_m";
+const INLINE_SERVER_ROUTE_PREFIX = (process.env.SERVER_FNS_BASE_PATHNAME || '') + "/_m";
 
 /** @typedef {{ refs: Set<import('@babel/core').NodePath<import('@babel/core').types.Identifier>>,  filename: string, done: {}, servers: number; opts: { minify: boolean; root: string; ssr: boolean; } }} State */
 ```

Just run:
```sh
npx patch-package solid-start
```

**Comment by devinrhode2** [comment]
FTR I am manually prefixing all application urls and additionally have a base folder in routes which corresponds to my deployed base path, which also matches SERVER_FNS_BASE_PATHNAME and is the same as the rsync base path. This path mostly won't change for me, otherwise I'd be readily cleaning this up, and I probably will clean it up once I have a moment.

**Comment by devinrhode2** [comment]
Ok. So without the `vite.config.ts` `base` url, (`import.meta.env.BASE_URL`), all my static assets (js files, namely) are not prefixed.

Due to my deployment environment, I can't intercept the urls somehow. If the requests go to `domain.com/assets/*.js` instead of `domain.com/base-path/assets/*.js, they will fail and there's nothing I can do about it (besides telling my boss our deployment env is no bueno)

**Comment by devinrhode2** [comment]
I guess I have a suspicion about a hack that will work, but it's not good in that it really shouldn't be contributed upstream.

BASE_URL is only really used in one place, the base path is passed into the router. So... what I can do is add back in `base: '/foo'`, but then add an additional patch in `solid-start` so that the BASE_URL is completely ignored by the router.

Perhaps we could contribute this upsteam, because of the bug mentioned in my second comment: https://github.com/solidjs/solid-start/issues/1013#issuecomment-1684253444

Maybe it's better to leave it broken, so someone comes along with a real fix one day, instead of a work-around?

This is a minor issue, but I guess if anyone is searching the issues/google for how to handle a base path in solid, they'll at least see this thread I've created.

**Comment by devinrhode2** [comment]
Here's the patch that I think should work, file is `node_modules/solid-start/entry-client/StartClient.tsx`

**Comment by iainmerrick** [comment]
I'm interested in getting this working. I'd like to set `base` in `vite.config` to make a website that can be hosted in a subdirectory of an existing domain, and I don't think there's another way to do it.

`base` works fine in Vite, but not in a Solid Start project (I'm seeing the same errors @devinrhode2 reports above), so I think this is actually a bug, not just a documentation task.

**Comment by iainmerrick** [comment]
Aha, in fact `base` works fine in Solid Start with the default adapter (at least in `dev`) mode. So if there's a bug I think it's in the Cloudflare adapter.

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
