### ISSUE TITLE
pnpm build && pnpm start - TypeError: Cannot read properties of undefined (reading 'default')

### ISSUE THREAD

**Issue by btakita** [solidjs/solid-start#102]
The route jsx files are transpiled after the `const routes = $ROUTES;` routes definition. Explicitly importing the routes tsx files before importing Routes fixes the issue.

```js
  p.then(mod => resolved = mod.default);
```

`TypeError: Cannot read properties of undefined (reading 'default')`

**Comment by btakita** [comment]
For some reason, the transpiled output `Promise.resolve().then(index$1)` does not act the same as `queueMicrotask`. It immediately executes & `index$1` is undefined since it is defined later in the transpiled file.

**Comment by btakita** [comment]
The problem was a top level `await`, which stalled the initial pass in the server index.js file. Since the route modules were defined after the routes array, `index$1` was not defined when the lazy route was run. If there is a top-level await, the route modules will need to be defined before the routes array.

**Comment by nksaraf** [comment]
Looks like stale issue for which we don't a solution yet. If the problem persists, you could reopen this..
