### ISSUE TITLE
[Bug?]: Meta tags with the same name, but different props are merged and only the last on his rendered

### ISSUE THREAD

**Issue by coppy-team** [solidjs/solid-start#1036]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If I'm trying to add several meta tags with the same name, only the last one is rendered:
```typescript
<Meta
    name="theme-color"
    content="hsl(215 30% 96%)"
    media="(prefers-color-scheme: light)"
/>
<Meta
    name="theme-color"
    content="hsl(215 15% 20%)"
    media="(prefers-color-scheme: dark)"
/>
```

On the html page I see only the last meta tag:
```html
<meta name="theme-color" content="hsl(215 15% 20%)"  media="(prefers-color-scheme: dark)" >
```

### Expected behavior 🤔

It seems like this might be an expected behavior and we usually want to merge those tags. But in this case we want to keep both tags, because they use different media queries.

I think tangential issue is that typing for `Meta` component (and `meta` tag) do not expect the `media` attribute.

### Context 🔦

I'm trying to set up the color for the Safari tab bar. And I want to set different color depending on the user selected theme.

**Comment by ryansolid** [comment]
I believe this was fixed in latest Solid Meta.
