### ISSUE TITLE
[Bug?]: A href navigation then event?.request?.headers?.get("cookie") is null

### ISSUE THREAD

**Issue by kimutaiRop** [solidjs/solid-start#1037]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

when I navigate to a page, then my `useRouteData` using `createServerData` to get route data  fails to get the cookies this occurs only when using `A` navigation link provided by solidstart

this also happens if i click logout button which clears the cookies, the cookies are cleared but still when I use the history button in the browser to go back to previous page, the middleware does not seem to redirect me to login page despited having restricted, 

This are confirmed behaviors since when I refresh the page then everything works for that route as expected:
 (get redirected to login if am not logged in)
 (the cookies from headers are available if logged in)

### Expected behavior 🤔

I should be able to get the cookies no matter how i navigate the page using either 'a' tag provided by html or `A` provided by solid start
For the middleware it seem like it is not being executed in every navigation I make yet I think it should be executed in every page change

### Steps to reproduce 🕹

Steps:

1. create blank project
2. set cookies in a login page
3. use middleware to protect `/about`
4. use createServerData$ to access cookies on navigation using `A` for instance from '/` to '/about` 
5. use browser history to go back to `/about` from `/login`

### Context 🔦

I have
```javascript
export function routeData() {
  return createServerData$(async () => {
    const event = useServerContext();
    const cookie = () =>
      parseCookie(
        isServer
          ? event?.request?.headers?.get("cookie") ?? ""
          : document.cookie
      );
    let cookies = cookie();
    console.log(cookies);
     // code to fetch data here
    return response;
  });
}

const ClientNetwork = () => {
  let clents = useRouteData<typeof routeData>();
  return (
    <main class="flex flex-col h-screen  space-y-6 ">
   </main>
  )
}
export default ClientNetwork
```

when i refresh  `console.log(cookies);` prints cookie object and empty object when using `A`

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
