### ISSUE TITLE
[Bug?]: "A" Component causes FOUC and weird props

### ISSUE THREAD

**Issue by caseybaggz** [solidjs/solid-start#1038]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After much [research](https://github.com/chakra-ui/panda/discussions/1259) migrating my SS app to use Panda-CSS I have come to find out the `A` tag is doing some weird stuff when combined with Panda CSS.

When using a native `<a>` element:
<img width="396" alt="Screenshot 2023-08-30 at 1 49 43 PM" src="https://github.com/solidjs/solid-start/assets/4819738/a51e8447-04be-4c89-936c-ae73b68c0471">

When using the Solid-start `<A>` Component:
<img width="405" alt="Screenshot 2023-08-30 at 1 50 08 PM" src="https://github.com/solidjs/solid-start/assets/4819738/817a0f80-e98c-4fb2-982f-6f1bb0dc2edc">

This compilation is causing some major FOUC on the browser rendering mentioned in the above issue.

### Expected behavior 🤔

SS components should not be adding any extra props that are not from the user or enhance a11y of the component itself.

### Steps to reproduce 🕹

Steps:

1. Create a basic SS app
2. Add Panda CSS
3. Create a `<A>` component with custom styles via Panda
4. See FOUC and weird props

### Context 🔦

This started appearing recently in my large app using the latest version of SS. I know we are moving to Astro in the future, but this is a blocker for me to publicly release my app.

**Comment by ryansolid** [comment]
Yeah this looks like a Solid compilation bug on the serverside class merging.. I will take a look.

**Comment by ryansolid** [comment]
So Panda adds this stuff. If I was to guess it has to do with escaping.. because writing what is there works fine, but I see escaped quotes and my guess is whatever is combining this on the server is getting tripped up by it. It'd be great to see actual project and inspect what the transform is doing.

**Comment by caseybaggz** [comment]
@anubra266 adding you here since this might be beneficial to Panda configuration.

@ryansolid what's also interesting is that I also created a [new example project](https://github.com/caseybaggz/rando) (albeit not a real world example) and it works fine. However, in my real world example that is now a large scale SS app using panda...it does exist.

It's a private repo, so I can't share the link to that one or else I would. 🙈

**Comment by anubra266** [comment]
@caseybaggz Is the escape thingy still an issue?

**Comment by caseybaggz** [comment]
> 

@anubra266 from my perspective, yes - I'm still having to use a local altered version of the SS `A` tag to prevent the FOUC.

**Comment by anubra266** [comment]
@caseybaggz I'm referring to the styles that were leaking to the html as props. Do you still have them?
![CleanShot 2023-09-06 at 21 46 38@2x](https://github.com/solidjs/solid-start/assets/30869823/ef449ee7-cceb-4bdf-9de4-77125a40c69e)

**Comment by caseybaggz** [comment]
> @caseybaggz I'm referring to the styles that were leaking to the html as props. Do you still have them? ![CleanShot 2023-09-06 at 21 46 38@2x](https://user-images.githubusercontent.com/30869823/266136668-ef449ee7-cceb-4bdf-9de4-77125a40c69e.png)

Yeah, that's what I was talking about. 😄
