### ISSUE TITLE
[Bug?]: `pnpm dev` broken on node >= v20, cannot find package `parse-multipart-data`

### ISSUE THREAD

**Issue by peterhirn** [solidjs/solid-start#1040]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using Node >= v20 `pnpm dev` fails with `Error: Cannot find package ... \parse-multipart-data\package.json`.

[x] Node v19 works
[x] `pnpm build` works
[x] `pnpm start` works

I looked into this issue but couldn't figure out why this is happening. `parse-multipart-data` is imported like any other package in `solid-start`. Adding `parse-multipart-data` to my `package.json` also doesn't resolve the issue.

Sorry if this is only broken on my machine. I removed node_modules and the shared pnpm store and re-installed everything from scratch before testing this.

### Steps to reproduce 🕹

```console
nvm use 20
pnpm create solid
pnpm i
pnpm dev
```

```
> solid-start dev

 solid-start dev 
 version  0.3.5
 adapter  node
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Cannot find package 'C:\Users\User\Documents\Projects\private\solid-start-tests\show-hydration-issue\node_modules\.pnpm\solid-start@0.3.5_@solidjs+meta@0.28.6_@solidjs+router@0.8.3_solid-js@1.7.11_solid-start-node@0.3.5_vite@4.4.9\node_modules\parse-multipart-data\package.json' imported from C:\Users\User\Documents\Projects\private\solid-start-tests\show-hydration-issue\node_modules\.pnpm\solid-start@0.3.5_@solidjs+meta@0.28.6_@solidjs+router@0.8.3_solid-js@1.7.11_solid-start-node@0.3.5_vite@4.4.9\node_modules\solid-start\node\fetch.js
Did you mean to import parse-multipart-data@1.5.0/node_modules/parse-multipart-data/dist/multipart.js?
    at legacyMainResolve (node:internal/modules/esm/resolve:188:26)
    at packageResolve (node:internal/modules/esm/resolve:769:14)
    at moduleResolve (node:internal/modules/esm/resolve:831:20)
    at defaultResolve (node:internal/modules/esm/resolve:1036:11)
    at DefaultModuleLoader.resolve (node:internal/modules/esm/loader:251:12)
    at DefaultModuleLoader.getModuleJob (node:internal/modules/esm/loader:140:32)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:33)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Your environment 🌎

```shell
Windows 10
```

**Comment by edivados** [comment]
Hmmm... can't reproduce with a fresh bare template. I am on

```console
OS: Windows 10
Node: 20.5.1
pnpm: 8.7.0
```

@peterhirn Out of curiosity can you give your exact node version and pnpm version? Also what template did you use?

**Comment by peterhirn** [comment]
Hey, thanks a lot for trying to reproduce! Looks like this really is only broken on my machine.

I tested a couple of node versions, including `v20.5.1` and I'm currently on pnpm `v8.7.1`. The template I selected was `bare` + `typescript`.

Since it works for you I'll give it another shot, cleaning up everything as good as possible and start over.
