### ISSUE TITLE
[Bug?]: `with-vitest` example broken after upgrading `@testing-library/jest-dom` (partial fix included)

### ISSUE THREAD

**Issue by peterhirn** [solidjs/solid-start#1044]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After upgrading `@testing-library/jest-dom` to >= `v6` the tests fail with some package lookup error.

I fixed the problem here https://github.com/peterhirn/solid-start-with-vitest, starting from the `with-vitest` example.

If you think my fixes are good I can squash them and open a PR to patch `examples/with-vitest` (I didn't test the non-Typescript variant yet, not sure if even relevant anymore).

I also switched from `@vitest/coverage-c8` to `@vitest/coverage-v8` (`c8` is deprecated)

Aggregated changes: https://github.com/peterhirn/solid-start-with-vitest/compare/6a6cc3c017272381c1305b582d350dae48e7782d..master

### Update

I just realized there is still a import problem when using `<Routes>`. After adding this example test from https://github.com/solidjs/solid-testing-library

```ts
  it("uses params", async () => {
    const App = () => (
      <Routes>
        <Route path="/ids/:id" component={() => <p>Id: {useParams()?.id}</p>} />
        <Route path="/" component={() => <p>Start</p>} />
      </Routes>
    );
    const { findByText } = render(() => <App />, { location: "ids/1234" });
    expect(await findByText("Id: 1234")).not.toBeFalsy();
  });
```

the tests fail with

```sh
Error: Cannot find module 'C:\my-app-vitest\node_modules\.pnpm\@solidjs+router@0.8.3_solid-js@1.7.11\node_modules\@solidjs\router\dist\integration' imported from C:\my-app-vitest\node_modules\.pnpm\@solidjs+router@0.8.3_solid-js@1.7.11\node_modules\@solidjs\router\dist\routing.js
```

### Update 2

I added two  more very simple tests for `<Home/>` and `<PageNotFound />`. Unfortunately the latter tries to pull `@solidjs/router` and fails. I don't know how to proceed here.

I'm also very confused by the vitest setting `deps.optimizer.web.include`.
- when removed all tests fail
- when removing only the `include` part I get warnings about "multiple instances of Solid", but tests still pass
- the content of `include` seems to be irrelevant, eg. this still works without any warnings
```ts
    deps: {
      optimizer: {
        web: {
          include: [],
        },
      },
    },
```

### Update 3 (2023-09-23)

Ryan mentioned on his [stream](https://www.youtube.com/watch?v=WBH7Ewa--Qg) yesterday that he's working on rebasing all examples on vinxi. This issue might be obsolete soon.

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
