### ISSUE TITLE
Child routes under root

### ISSUE THREAD

**Issue by Malmz** [solidjs/solid-start#107]
Is it possible to have child routes under the root path. It is possible with solid-app-router but I can't see how to do it with file path routing. 

Something like this example
```jsx
<Route path='/' element={<div>Onion starts here <Outlet /></div>}>
  <Route path='layer1' element={<div>Another layer <Outlet /></div>}>
    <Route path='layer2' element={<div>Innermost layer</div>}></Route>
  </Route>
</Route>
```

**Comment by Malmz** [comment]
Just to clarify a bit, im wondering how to have child routes in an <Outlet/> in routes/index.tsx

**Comment by ryansolid** [comment]
I suspect this might not work currently at the root but the theoretical structure would be:
> /index
> -- /layer1
> -- -- layer2.tsx
> -- layer1.tsx
> index.tsx

If it doesn't work we should fix it.

**Comment by Malmz** [comment]
Just tried this. For `pages/index/about.tsx` i get the route `localhost/index/about`

**Comment by ryansolid** [comment]
Yeah that's what I was afraid of.. we aren't properly checking against index specifically. But that's what it should do so this is a bug, missing part of the implementation.

**Comment by ryansolid** [comment]
Should be fix in the latest "alpha.78"

**Comment by knpwrs** [comment]
I have the following file structure:

```tsx
src/routes
├── [...404].tsx
├── index
│   ├── auth
│   │   └── login.tsx
│   └── auth.tsx
└── index.tsx

2 directories, 4 files
```

Both `index.tsx` and `auth.tsx` are essentially:

```tsx
import { Outlet } from 'sold-start';

export default function ComponentName() { // Either Index or Auth
  return <Outlet />
}
```

And `login.tsx` is simply:

```tsx
export default function Login() {
  return <h2>Login!</h2>
}
```

When I visit `/auth/login`, however, my 404 route renders. Has this bug re-emerged or am I doing something wrong? The idea is for anything under `/auth/*` to be nested under the index layout.

**Comment by chaoky** [comment]
This no longer works, use this pattern instead:
```
src/routes
├── (home)
│   ├── foo <- resolves to localhost/foo
├── (auth)
│   ├── bar <- resolves to localhost/bar
├── (auth).tsx <- layout file will apply to everything under the (auth) folder
└── (home).tsx <- layout file will apply to everything under the (home) folder
```
