### ISSUE TITLE
[Bug?]: Hide menu when click on link in doc

### ISSUE THREAD

**Issue by maximyurevich** [solidjs/solid-start#1072]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![Screenshot_2023-09-29-18-36-08-380_com android chrome](https://github.com/solidjs/solid-start/assets/21293376/111dfba7-5d7a-429a-9418-20760371b4fe)

### Expected behavior 🤔

Menu hide when click on link

### Steps to reproduce 🕹

Steps:

1. Click on link in menu

### Context 🔦

Chrome for Android 

### Your environment 🌎

Android

**Comment by ryansolid** [comment]
I have made the docs an MPA + Islands now so this happens automatically. This didn't really fix the issue directly but it solves it.
