### ISSUE TITLE
[Bug]: localStorage.debug is overwritten in dev-mode

### ISSUE THREAD

**Issue by indeyets** [solidjs/solid-start#1083]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In dev-mode, `localStorage.debug` is overwritten with `'start*'` string

### Expected behavior 🤔

existing value of this variable is kept, but `'start*'` is appended to it, when necessary

### Steps to reproduce 🕹

Steps:

1. set `localStorage.debug` to some value. for example `test:*`
2. run solid-start in dev-mode, refresh the page
3. check value of `localStorage.debug`

### Context 🔦

This variable is used by [debug()](https://github.com/debug-js/debug) package.

Here's the relevant code: https://github.com/solidjs/solid-start/blob/main/packages/start/entry-client/mount.tsx#L13-L14

It was introduced by @nksaraf originally, as far as I can see.

I can provide the patch, but want to discuss what is the ultimate desired behaviour here. I suggest to maintain whatever is currently stored there and append `start:*`. I'm not sure what was the intention of using `import.meta.env.DEBUG` and if it needs to be supported.

**Comment by nksaraf** [comment]
I agree that we should append to any existing value instead of overwriting.

**Comment by indeyets** [comment]
@nksaraf why did you use `import.meta.env.DEBUG` there? is it used by any real code or I can skip that part?

**Comment by nksaraf** [comment]
I probably added that for the use case you are describing where people would want to override.. but you can remove it. its easier to let user add their own thing and us appending to it.
