### ISSUE TITLE
[Bug?]: solid-start-file-system-router not generating sourcemaps

### ISSUE THREAD

**Issue by elijah629** [solidjs/solid-start#1088]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

`solid-start-file-system-router` does not generate sourcemaps. This is seen as vite shows an error during build:
```
(solid-start-file-system-router plugin) Sourcemap is likely to be incorrect: a plugin (solid-start-file-system-router) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```

### Expected behavior 🤔

It should generate source maps

### Steps to reproduce 🕹

Steps:

1. Create a new solid-start project
2. Configure vite.config.js to have source maps enabled in `build`
3. `npm run build`
4. Error that no source maps were created
5. You can verify this by checking for them in devtools

### Your environment 🌎

```
  System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 7.95 GB / 15.22 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.5.1/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
    pnpm: 8.6.2 - ~/.nvm/versions/node/v20.5.1/bin/pnpm
  Browsers:
    Brave Browser: 118.1.59.120
  npmPackages:
    vite: ^4.4.9 => 4.5.0 
```

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
