### ISSUE TITLE
[Bug?]: Unable to find DOM nodes for hydration when using a Dynamic inside of `when` in a Show

### ISSUE THREAD

**Issue by gabrielmfern** [solidjs/solid-start#1089]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The following code will throw hydration errors when running with SSR enabled.

```tsx
function FakeComponent(props: ParentProps) {
  return <div>{props.children}</div>;
}

function FakeComponentWrapper(props: ParentProps) {
  return <Dynamic component={FakeComponent} children={props.children} />;
}

export default function MyPage() {
  return (
    <main>
      <Title>My page</Title>
      <Show when={<FakeComponentWrapper>123</FakeComponentWrapper>}>
        <FakeComponentWrapper>123</FakeComponentWrapper>
      </Show>
    </main>
  );
}
```

You will be met with hydration errors pointing to this component once you enable SSR.

### Expected behavior 🤔

The component should render and hydrate properly without any problems.

### Steps to reproduce 🕹

Steps:

1. Create a solid-start project
2. Choose any page then add the markup I mentioned before with the page's code as well
3. Enable SSR
4. Run in dev mode and try opening it

### Context 🔦

The weird duplication for reproduction I wrote with the component twice there would be in a situation where you receive the JSX markup as a prop and try to only render if it is defined, so this is an actual problem I've had with what I am building.

### Your environment 🌎

```shell
Binaries
    Node: v20.8.0
    pnpm: 8.8.0
npmPackages:
    solid-js: 1.8.3
    solid-start: 0.3.7
```

**Comment by ryansolid** [comment]
This is similar to https://github.com/solidjs/solid/issues/1977 and is Solid rather than Start concern.
In general you never want to do this because you are rendering twice. Like creating all the DOM nodes twice. Once in the condition and once in the result.
