### ISSUE TITLE
[Bug?]:  resource `onHydrated` not invoked when fetcher resolves too quickly

### ISSUE THREAD

**Issue by ardeora** [solidjs/solid-start#1099]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm using `renderStream` in my solid-start app to enable streaming SSR. 

I have resource in `index.tsx`

```ts
const [data] = createResource(
  async () => {
    await new Promise((r) => setTimeout(r, 10));
    return 'hello';
  },
  {
    onHydrated(k, info) {
      console.log('onHydrated Callback called', k, info);
    },
  }
);
``` 

The `onHydrated` callback is never called 😔 

If I increase the timeout range to `1000ms` then I see the callback being fired!

```ts
const [data] = createResource(
  async () => {
    await new Promise((r) => setTimeout(r, 1000));
    return 'hello';
  },
  {
    onHydrated(k, info) {
      // This will now fire!
      console.log('onHydrated Callback called', k, info);
    },
  }
);
``` 

### Expected behavior 🤔

I expect the `onHydrated` callback to fire regardless of when the fetcher resolves. Be it 1ms or 1000ms

### Steps to reproduce 🕹

Steps:
Please checkout the reproduction here https://stackblitz.com/edit/github-tnibxm?file=src%2Froutes%2Findex.tsx
1. Try changing the setInterval timeout to `1000` instead of `10`
2. You should then see the `onHydrated` callback on that resource being invoked

### Context 🔦

I came across this issue when implementing something with `@tanstack/solid-query`. Sadly this issue also causes problem downstream in other data fetching libraries.

See here: https://github.com/TanStack/query/issues/6256

We use the `onHydrated` callback extensively to rehydrate the queries fetched on the server back in the client. If the `onHydrated` callback is not invoked in some cases, the queries are never correctly hydrated and causes the client side cache to get confused

**Comment by ofarukaydin** [comment]
Just to add: If I increase timeout to 150 and refresh few times, I start getting hydration errors

**Comment by ardeora** [comment]
> Just to add: If I increase timeout to 150 and refresh few times, I start getting hydration errors

Yep! Noticed this too right around 100ms is when they start becoming flaky

**Comment by ardeora** [comment]
https://github.com/solidjs/solid/commit/80ca972fd3d6e227cd832ca1cb4eff9a4dd5226a The latest version of solid-js has fixed this issue so closing it for now. Thank you so much Ryan!

**Comment by apatrida** [comment]
latest verison being which?  @ardeora 

I just tried solid-start 0.3.9 and solidjs 1.8.5 and it completly breaks.
