### ISSUE TITLE
[Bug?]: @vercel/blob - Using `put` breaks the `vercel` deployment of edge components.

### ISSUE THREAD

**Issue by eztinkerdreams** [solidjs/solid-start#1105]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Please see [@vercel/storage issue #440](https://github.com/vercel/storage/issues/440#issuecomment-1787040040)

I'm not certain that this is even an issue with `solid-start` however. I have been directed to ask here if this is something you think is an issue with `solid-start`  

### Expected behavior 🤔

I should be able to use the `vercel` command to deploy an edge function that uses `@vercel/blob` function to the edge that uses the `put` function from that library. When I try this I get the errors.

```
Error: The Edge Function "render" is referencing unsupported modules:
        - vercel/path0/dist/index.mjs: net, http, stream, querystring, stream/web, node:stream, worker_threads, perf_hooks, util/types, tls, console, url, zlib, string_decoder, diagnostics_channel
```

### Steps to reproduce 🕹

See: [Issue #440](https://github.com/vercel/storage/issues/440#issuecomment-1783019809)

I have attached a `.zip` of an example that produces this issue.
[issue-440.zip](https://github.com/solidjs/solid-start/files/13217157/issue-440.zip)

### Context 🔦

Sorry for the cross post, if you find that this is not an issue with `solid-start` you can just close this issue.

### Your environment 🌎

```shell
Software:

    System Software Overview:

      System Version: macOS 13.0.1 (22A400)
      Kernel Version: Darwin 22.1.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day, 20 hours, 33 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,2
      Model Number: MK1A3LL/A
      Chip: Apple M1 Max
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 32 GB
      System Firmware Version: 8419.41.10
      OS Loader Version: 8419.41.10
      Activation Lock Status: Enabled
```

```
Vercel CLI 32.5.0
```

```
{
  "scripts": {
    "dev": "solid-start dev",
    "build": "solid-start build",
    "start": "solid-start start"
  },
  "type": "module",
  "private": true,
  "devDependencies": {
    "solid-start-vercel": "^0.2.26",
    "typescript": "^5.0.4",
    "vite": "^4.3.8"
  },
  "dependencies": {
    "@solidjs/meta": "^0.28.5",
    "@solidjs/router": "^0.8.2",
    "@vercel/blob": "^0.14.1",
    "solid-js": "^1.7.5",
    "solid-start": "^0.2.26",
    "undici": "^5.22.1"
  },
  "engines": {
    "node": "18.x"
  }
}

```

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
