### ISSUE TITLE
[Bug?]: Error: Hydration Mismatch with component from node_modules

### ISSUE THREAD

**Issue by qlaffont** [solidjs/solid-start#1110]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I try to import a component from the current project no issue

If I export the same component to another project, i have an hydration issue : 
```
Error: Failed attempt to create new DOM elements during hydration. Check that the libraries you are using support hydration.
    at create (dev.js:124:37)
    at fn (dev.js:129:120)
    at index.tsx:127:3
    at Icon (index.tsx:146:10)
    at dev.js:552:12
    at untrack (dev.js:442:12)
    at Object.fn (dev.js:548:37)
    at runComputation (dev.js:698:22)
    at updateComputation (dev.js:681:3)
    at devComponent (dev.js:559:3)
dev.js:278 Uncaught (in promise) Error: Hydration Mismatch. Unable to find DOM nodes for hydration key: 0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-0-1-0-0-3-0-0
    at getNextElement (dev.js:278:37)
    at ErrorBoundary.tsx:32:3
    at ErrorMessage (ErrorBoundary.tsx:59:79)
    at dev.js:552:12
    at untrack (dev.js:442:12)
    at Object.fn (dev.js:548:37)
    at runComputation (dev.js:698:22)
    at updateComputation (dev.js:681:3)
    at devComponent (dev.js:559:3)
    at createComponent (dev.js:1265:17)
```

### Expected behavior 🤔

Should render the component without hydration issue.

### Steps to reproduce 🕹

Steps:

1. Create a solid-start project (A) and create a component
2. Create a solid-start project (B) with SSR Enabled, Install project A as deps (PNPM)
3. Import component into project B in src/routes/index.tsx
4. Go to this page 

### Your environment 🌎

```shell
System : POP OS 22.04

Node : v18.18.2

PNPM : 8.7.5

    "solid-js": "1.8.5",
    "solid-start": "^0.3.9",
    (Same between project A and B)
```

VITE CONFIG :

```
import legacy from '@vitejs/plugin-legacy';
import solid from 'solid-start/vite';
import imagemin from 'unplugin-imagemin/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [
    solid({
      ssr: true,
    }),
    legacy({
      targets: ['defaults', 'not IE 11'],
    }),
    imagemin(),
  ],
});

```

**Comment by qlaffont** [comment]
I have created a sample reproduction :

- Project who export a cmp : https://github.com/qlaffont/solid-start-cmp
- Project who use this cmp : https://github.com/qlaffont/solid-start-project / https://github.com/qlaffont/solid-start-project/blob/master/src/routes/index.tsx

**Comment by gabrielmfern** [comment]
also having this issue

**Comment by wakaztahir** [comment]
Me too experienced this issue

**Comment by gabrielmfern** [comment]
@wakaztahir @qlaffont I found that this was a problem on build, Solid builds differently for server and client, maybe using something like [this](https://github.com/solidjs-community/tsup-preset-solid) can help you guys as well, I got this fixed using the rollup preset that supports this.
You guys can also look at the differences on the solid playground that has different output modes for each type of compilation.

**Comment by gabrielmfern** [comment]
Helpful resource: https://www.youtube.com/watch?v=0zadjVUV7zM&list=PLU7qJA_m4fneqc9S7MvJAEB5JNBeafxA8&index=3&t=3054s

**Comment by gabrielmfern** [comment]
this is probably not an issue with Solid Start itself, but just a warning that our code really doesn't support hydration as it mentions

**Comment by qlaffont** [comment]
@gabrielmfern for me is not related with the code because i use the same code and if the component is on the project i have no hydration issue

**Comment by gabrielmfern** [comment]
> @gabrielmfern for me is not related with the code because i use the same code and if the component is on the project i have no hydration issue

I didn't mean a problem directly with the code, I meant a problem in our end not in Solid Start's.
The same happened exact thing was happening to me, as I mentioned if you want to import the library you'll need to compile in a specific way for Solid to run hydration properly. The error doesn't happen when you have the code in the project because when building/running dev with vite it already generates the code for hydration properly.

**Comment by qlaffont** [comment]
I understand you point but i'm importing the source code and not the compiled version of the component so for me it doesn't make sense

**Comment by gabrielmfern** [comment]
> I understand you point but i'm importing the source code and not the compiled version of the component so for me it doesn't make sense

maybe it won't fail if you add noExternal: ['PACKAGE_NAME'] to your ssr vite config

**Comment by gabrielmfern** [comment]
@qlaffont were you able to fix it?

**Comment by robertwach** [comment]
The error starts happening barely a few minutes after you initialise the project (I'm using the drizzle starter) and with every save/hmr the error pops up. This is a huge barrier for those trying out solid start for the first time.

**Comment by ryansolid** [comment]
@robertwach Hydration mismatches can happen for a number of reasons. It is more likely that these issues are unrelated. If you have a reproduction I recommend reporting a seperate issue.

**Comment by robertwach** [comment]
> @robertwach Hydration mismatches can happen for a number of reasons. It is more likely that these issues are unrelated. If you have a reproduction I recommend reporting a seperate issue.

Thanks for the quick reply, I fixed the issue by just changing the starter template to prisma. Much appreciation for this amazing framework.
