### ISSUE TITLE
[Bug?]: node adaptor wrong content type header 

### ISSUE THREAD

**Issue by shawnyu5** [solidjs/solid-start#1112]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Trying to deploy a solid js app, with the node adapter in kubernetes. Getting the following error when I open the application in the browser:

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

Most things I've read tells me this is most likely an application issue, that the server should be configured properly to set the correct content type headers. However this behavior only happens when the app is deployed in K8s, not locally, or deployed in vercel.

### Expected behavior 🤔

The app should load as normal

### Steps to reproduce 🕹

Steps:

1. Create a k8s deployment, and a Service pointing to the deployment.
2. Set up an ingress to be able to access the app on the local web browser.
3. Open app in local web browser

### Context 🔦

Trying to deploy the application in Kubernetes

### Your environment 🌎

```shell
System:
 OS: arch
Binaries:
 Node: v20.9.0
```

**Comment by shawnyu5** [comment]
Just tried the same deployment method with a next js app. it is able to deploy successfully. This leads me to believe its the node adaptor not setting the right content headers

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
