### ISSUE TITLE
[Feature?]: Vite 5 / Rollup 4 support

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-start#1123]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Lots of good stuff here:

Vite 5
- https://vitejs.dev/blog/announcing-vite5
- https://vitejs.dev/guide/migration#deprecate-cjs-node-api

Rollup 4
- https://github.com/rollup/rollup/blob/master/CHANGELOG.md#400
- https://rollupjs.org/migration/

**Comment by birkskyum** [comment]
See:
- https://github.com/nksaraf/vinxi/issues/28

**Comment by LexSwed** [comment]
I assumed that vite 5 support was added here:
https://github.com/solidjs/solid-start/commit/620b638cde2ed7245ee43ddd9d0c1fae8618bba3

**Comment by birkskyum** [comment]
that was just a first stepa

> I assumed that vite 5 support was added here: [620b638](https://github.com/solidjs/solid-start/commit/620b638cde2ed7245ee43ddd9d0c1fae8618bba3)

that was a first steps, fixing simple usage of solidj.js with vite outside of Start, i.e. to make a SPA without a server part. With the 0.4 version of solid start where the dependency graph is start -> vinxi -> vite, it's necessary to update this in vinxi, followed by start as well.

**Comment by nksaraf** [comment]
Yup I had got it working earlier but found some issues in my projects where rollup 5 would choke on some syntax in some old libs.

I will add this back with optional support for falling back to vite 4 via overriding npm/yarn/pnpm resolutions.

**Comment by nksaraf** [comment]
Added this back in `vinxi@0.0.54`. I haven't made vite 5 the default, but you can use it by getting your own version of vite using npm/yarn/pnpm resolutions or overrides.

**Comment by birkskyum** [comment]
Thanks!

**Comment by nksaraf** [comment]
Please confirm if this actually works I haven't tried it out outside my repo

**Comment by birkskyum** [comment]
@nksaraf , it works :) Thanks!

- https://github.com/solidjs/solid-start/issues/1177#issuecomment-1869455621
