### ISSUE TITLE
[Bug?]: Cloudflare adapter fails to inject d1 databases in local environment

### ISSUE THREAD

**Issue by mr-14** [solidjs/solid-start#1130]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

D1 database defined in `vite.config.js` does NOT get injected into `env` when calling `createServerData$`

### Expected behavior 🤔

D1 database defined in `vite.config.js` should get injected into `env` when calling `createServerData$`

### Steps to reproduce 🕹

Steps:

1. Create a bare SolidStart project using the [starter](https://start.solidjs.com/getting-started/project-setup)
2. Install `solid-start-cloudflare-pages` and add d1Databases adapter by following the [deploy-a-solid-site](https://developers.cloudflare.com/pages/framework-guides/deploy-a-solid-site/) guide
```
import solid from 'solid-start/vite'
import { defineConfig } from 'vite'
import cloudflare from 'solid-start-cloudflare-pages'

export default defineConfig({
	plugins: [ solid({ adapter: cloudflare({ d1Databases: ['my_database'] }) }) ]
})

```
3. Edit `src/routes/index.jsx` to fetch data from d1 databases
```
import { Title, useRouteData } from 'solid-start'
import { createServerData$ } from 'solid-start/server'

export function routeData() {
	return createServerData$(async (_, { env }) => {
		const sql = 'SELECT * FROM app WHERE id = ?'
		return await env.my_database.prepare(sql).bind('1').first()
	})
}

export default function Home() {
	const data = useRouteData()

	return (
		<main>
			<Title>Test</Title>
			<h1>{data()?.name}</h1>
		</main>
	)
}
```

I omitted the sql codes to generate the schema. The above code will error out upon calling `env.my_database.prepare` since `env.my_database` is undefined.

I also want to mention that the code works on production environment which lead me to believe that the issue has something to do with the adapter.

Thanks!

### Context 🔦

I would like to use SolidStart with Cloudflare Pages and would like to use the setup in my local environment to speed up development.

### Your environment 🌎

```shell
System: Ubuntu 22.04.3 LTS
NODE: v18.16.0
NPM: 9.5.1
solid-start: ^0.3.10
solid-start-cloudflare-pages: ^0.3.10
```

**Comment by shripadk** [comment]
I think this is because `solid-start-cloudflare-pages` is still using Miniflare 2 instead of Miniflare 3. The `__D1_BETA__` prefix was deprecated.

**Comment by asterikx** [comment]
I confirm this bug. `d1Databases` are not injected, while `kvNamespaces` work just fine. Is there any workaround for the time being?

As far as I understand `solid-start-cloudflare-pages` will be replaced by Nitro at some point. However, Nitro is also only using Miniflare 2 at the moment according to https://github.com/solidjs/solid-start/issues/263#issuecomment-1609889986.

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
