### ISSUE TITLE
[Bug?]: Error: Cannot serialize function without reference ID.

### ISSUE THREAD

**Issue by MarByteBeep** [solidjs/solid-start#1142]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

very simple `createRouteData` example below will cause some infinite loop and a number of errors reported on server:

```ts
import { createRouteData } from 'solid-start';

async function sleep(ms: number) {
	return new Promise((resolve) => setTimeout(resolve, ms));
}

export default function Test() {
	const data = createRouteData(async () => {
		// comment line below, and all works fine 
		const response = await fetch('/api/test');

		await sleep(2000);
		return 'Test';
	});

	return <div>{data()}</div>;
}
```

It seems to choke on relative URLs, `http://localhost/api/test` works fine, `/api/test` does not.

Another thing I observed is that page doesn't immediately show, it waits for 2 seconds.

### Expected behavior 🤔

Waiting for an async fetch to finish shouldn't cause some infinite loop
Also the page should not wait 2 seconds before displaying anything.

### Steps to reproduce 🕹

Steps:

1. Make component `Test` with above example
2. Run it

### Your environment 🌎

```shell
"solid-start-node": "^0.3.10",
"typescript": "^4.9.5",
"vite": "^4.4.9"
"@solid-primitives/keyboard": "^1.2.5",
"@solidjs/meta": "^0.29.1",
"solid-js": "^1.8.7",
"solid-start": "^0.3.10",
"node": "18"
```

**Comment by ryansolid** [comment]
In setting up for SolidStart's next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
