### ISSUE TITLE
[Bug?]: Router "base" property is flaky

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-start#1158]
UPDATE (moving focus from base prop in vite.config to base prop on Router): For repro instructions, see https://github.com/solidjs/solid-start/issues/1158#issuecomment-1867734373

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently the /_build is the default base path:

https://github.com/solidjs/solid-start/blob/cfe17fa2da37726ef59be347efbef4d8274b74aa/packages/start/config/index.js#L156

### Expected behavior 🤔

I expected either `/` or '' to be the default base path unless set otherwise. If i set it to these values, my routes return nothing.

### Steps to reproduce 🕹

- npm create solid.
- choose `bare` template

set the vite config to:

```ts
export default defineConfig({
  base: "/test/"
});
```

- launch the dev server and go to `http://localhost:3000/test/
- result is that page isn't found, and that it's still only on http://localhost:3000

### Context 🔦

I'm making a SSG docs site, on a subpath like this example.com/subpath/routes  and thus need to set the base to /subpath/

this is to some extend a remake of the now obsolete
- https://github.com/solidjs/solid-start/issues/831#event-11292396040

### Your environment 🌎

```shell
@solidjs/start 0.4
@solidjs/router 0.10
macos - arm64
chrome 120
```

**Comment by ryansolid** [comment]
@nksaraf was there a reason for this?

**Comment by nksaraf** [comment]
The internal routers have their own base paths. /_build is similar to /_next. This `base` issue is a bug and the solution is two-step:

1. solid-start should wire the `base` config to vinxi's `server.baseURL` config which is passed to nitro.
2. Vinxi should make sure that the `baseURL` is applied correctly during development, it probably already works fine in production.

**Comment by birkskyum** [comment]
Interesting. I stumbled upon /_build when I used `import.meta.env.BASE_URL` in an app, which per Vitejs docs is:

> import.meta.env.BASE_URL: {string} the base url the app is being served from. This is determined by the [base config option](https://vitejs.dev/config/shared-options#base).

so it would seem like a bug that it's picking up the internals.

**Comment by nksaraf** [comment]
Hmm and you want it to be the BASE_URL for the whole app. Mind you that the client assets are served on the `/_build` path regardless. We could switch the `import.meta.env.BASE_URL` to be app's base URL instead of the internal client router's base.

**Comment by birkskyum** [comment]
Yes, I'd like it to be the BASE_URL for the whole app. It's so I can make a static build of the site, and put it on a github pages which isn't the root domain. Setting the base and calling appending links with import.meta.env.BASE_URL was how I got it in the old solid-start. There might be a more elegant way to do it.

**Comment by nksaraf** [comment]
Yup I think @solidjs/router accepts a base prop that does exactly this. And accounts for it during SPA routing.

**Comment by birkskyum** [comment]
That is quite very interesting! It appear to be quite flaky though. I tried setting it in the `basic` template, to `/offset`:

```ts
    <Router
      base="/offset"
      root={(props) => (
        <MetaProvider>
          <Title>SolidStart - Basic</Title>
          <A href="/">Index</A>
          <A href="/about">About</A>
          <Suspense>{props.children}</Suspense>
        </MetaProvider>
      )}
    >
```

and then when i go to the /about page it does direct to /offset/about which is great, but I get a "Page not Found", and when I refresh on  /offset/about it **can** find that page. ( note: I applied #1170 )

**Comment by nksaraf** [comment]
@ryansolid is this an issue for @solidjs/router

**Comment by birkskyum** [comment]
@nksaraf , you're right - i made an issue just for that in here:
- https://github.com/solidjs/solid-router/issues/334

**Comment by nksaraf** [comment]
I think some issues with the `base` being used properly across the system still need things fixed in solid-start and vinxi, so better to keep this open.

**Comment by Brendan-csel** [comment]
Just adding a note here that with the API change to remove nested `<Routes>`s the proposed solution is to instead have nested `<Routers>` with appropriate base paths - so more than one `<Router>` per app.

**Comment by birkskyum** [comment]
I've been using an app level base until now, because i didn't know about the router-specific base which I'm not attempting to use

**Comment by nksaraf** [comment]
Could you try `vinxi@0.0.55`. This should be fixed in that. Passing `server.baseURL` should give you the correct url in `import.meta.env.SERVER_BASE_URL`. And your entire app will be served at `server.baseURL`.

**Comment by nksaraf** [comment]
Reopen if this is still an issue.

**Comment by birkskyum** [comment]
even when setting the server.baseURL I get undefined from `import.meta.env.SERVER_BASE_URL`. I don't see any mentions of `SERVER_BASE_URL` mentioned in this [PR](https://github.com/nksaraf/vinxi/commit/5d9499fe76cbfe6a7e398b5b47a95d7a229a094e) - is it set properly?

**Comment by nksaraf** [comment]
https://github.com/nksaraf/vinxi/pull/56/files this is the full PR changeset. You can see it used in multiple places. Are you sure you are on 0.0.55?

**Comment by nksaraf** [comment]
I tried this again and it looks like it works:

```ts
import { defineConfig } from "@solidjs/start/config";

export default defineConfig({
  start: {
    server: {
      baseURL: "/base",
    },
  },
});
```


```ts app.tsx
// @refresh reload
import { MetaProvider, Title } from "@solidjs/meta";
import { A, Router } from "@solidjs/router";
import { FileRoutes } from "@solidjs/start";
import { Suspense } from "solid-js";
import "./app.css";

export default function App() {
  return (
    <Router
      base={import.meta.env.SERVER_BASE_URL}
      root={(props) => (
        <MetaProvider>
          <Title>SolidStart - Basic</Title>
          <A href="/">Index</A>
          <A href="/about">About</A>
          <Suspense>{props.children}</Suspense>
        </MetaProvider>
      )}
    >
      <FileRoutes />
    </Router>
  );
}
```

also @ryansolid looks like lower case `a` links are not picking up the `base` from the router, but uppsercase `A` links are.
