### ISSUE TITLE
[Bug?]: can't prerender routes using `npm install`

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-start#1162]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

initializing the `basic` template, and enabling prerender with this vite config (setting ssr: true doesn't change things):

```ts
import { defineConfig } from "@solidjs/start/config";

export default defineConfig({
  start: {
    server: {
      prerender: {
        crawlLinks: true, // (or routes: ["/"], both break)
      },
    },
  },
});
```

then running `npm run build` gives this error:

```sh

┌────────────────────────────────────────┐
│ ⚙  Preparing app for node-server...    │
└────────────────────────────────────────┘
vinxi hook app:build:nitro:config                                                                                 11:43:20 PM
vinxi hook app:build:nitro:assets:copy:start                                                                      11:43:20 PM
✔ Generated public .output/public                                                                          vinxi 11:43:20 PM
vinxi hook app:build:nitro:assets:copy:end                                                                        11:43:20 PM
vinxi hook app:build:nitro:prerender:start                                                                        11:43:20 PM
ℹ Initializing prerenderer                                                                                 vinxi 11:43:20 PM

 ERROR  Should be provided by compiler                                                                            11:43:20 PM

  at .vinxi/prerender/index.mjs:1232:7
  at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
  at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
  at async prerender (node_modules/nitropack/dist/shared/nitro.0a84349b.mjs:56:26)
  at async createBuild (node_modules/vinxi/lib/build.js:306:2)
  at async Object.run (node_modules/vinxi/bin/cli.mjs:156:5)
  at async runCommand (node_modules/citty/dist/index.mjs:316:16)
  at async runCommand (node_modules/citty/dist/index.mjs:307:11)
  at async runMain (node_modules/citty/dist/index.mjs:441:7) 



 ERROR  Should be provided by compiler                                                                            11:43:20 PM

```

### Expected behavior 🤔

I expected not getting an error here

### Steps to reproduce 🕹

Steps:

1. npm create solid
2. choose bare
3. update vite.config.ts with crawlLinks flag
4. **npm install** (important step, as yarn, pnpm i or bun i will work as expected)
5. npm run build

### Your environment 🌎

```shell
deps

    "@solidjs/meta": "^0.29.2",
    "@solidjs/router": "^0.10.5",
    "@solidjs/start": "^0.4.0",
    "solid-js": "^1.8.7",
    "vinxi": "0.0.52"

macos arm
chrome 120
```

**Comment by birkskyum** [comment]
@atilafassina have you managed to prerender anything so far with start/vinxi?

**Comment by ryansolid** [comment]
Interestingly our docs are pre-rendered using this technique. And all CSR uses prerendering. Maybe this is a combo with server functions. That compiler error looks similar to when you access a server function that hasn't been transformed.

**Comment by birkskyum** [comment]
I used the solid-start docs to narrow down what goes wrong, and it turns out that it breaks as explained above when using `npm` and works as expected when using `pnpm` (like in the case of the solid-start/docs)

**Comment by ryansolid** [comment]
Hmm.. I wonder if this is why @nksaraf had the resolution code (that was breaking prerendering for me) before. What was happening before was completely different so I can't use that as any basis. But its odd that package manager would impact this so.

**Comment by nksaraf** [comment]
This usually means something went wrong with the fs-router.. i'll look into it ,gotta admit haven't used npm in a while. Wondering if I can reproduce this in a stackblitz.

**Comment by birkskyum** [comment]
I haven't been able to run the [basic example of start 0.4 in stackblitz](https://stackblitz.com/github/solidjs/solid-start/tree/main/examples/basic) as is, because I get this error:

```sh
[h3] [unhandled] TypeError: Cannot read properties of undefined (reading 'assets')
    at get assets [as assets] (/home/projects/pariwmzoo.github/node_modules/.pnpm/@solidjs+start@0.4.2_solid-js@1.8.7_vinxi@0.0.54_vite@5.0.10/node_modules/@solidjs/start/server/StartServer.tsx:50:109)
```

**Comment by nksaraf** [comment]
@birkskyum I tried your repro setup:

<img width="1492" alt="Screenshot 2023-12-22 at 6 24 56 AM" src="https://github.com/solidjs/solid-start/assets/11255148/92e0180a-c7a8-4fbb-9648-01914258ff15">

Seems to work for me.. Mind making a repo or something on stackblitz with the error you are describing. Have you got the latest versions of stuff?

**Comment by brenelz** [comment]
I was able to replicate on `"vinxi": "0.0.52"` but 0.0.54 seems to have it fixed

**Comment by birkskyum** [comment]
@brenelz , you're very right -  0.0.53 was the latest when I opened the ticket, and updating to 0.0.54 did the trick. Thanks you all

**Comment by atilafassina** [comment]
> @atilafassina have you managed to prerender anything so far with start/vinxi?

Sorry @birkskyum. I was absolutely disconnected on vacation, only catching up with things now... 😬
