### ISSUE TITLE
[Bug?]: Angolia Search is pulling results from previous version of the site

### ISSUE THREAD

**Issue by eztinkerdreams** [solidjs/solid-start#1167]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Searching for 'Show' renders link to 
https://start.solidjs.com/api/createRouteAction#show-a-pending-indicator-for-an-action-in-progress
This link does not work.
![2023-12-21_08-37-54](https://github.com/solidjs/solid-start/assets/7387907/818da2a9-472f-4b6c-bfd7-a65b166d2514)

### Expected behavior 🤔

Ability to see examples of how to use the `<Show />` component.

### Steps to reproduce 🕹

Steps:

1. Search for Show on the solid start website
![2023-12-21_08-40-13](https://github.com/solidjs/solid-start/assets/7387907/6788d1bd-9cdf-4eba-8a1d-e30966956058)

2. Click on the link provided 'Show a pending indicator for an action in progress'
![2023-12-21_08-37-54](https://github.com/solidjs/solid-start/assets/7387907/2a4a2f07-53a6-489b-983c-2de86dba6340)

### Context 🔦

Google Chrome
Version 120.0.6099.109 (Official Build) (arm64)

**Comment by ryansolid** [comment]
Thanks. Yeah the search is out of date for some reason. We need to get that updated. That section no longer exists.

**Comment by ryansolid** [comment]
This appears to be fixed. It doesn't clear your local search history it appears but it won't appear in new searches.
