### ISSUE TITLE
[Bug?]: version 0.4.0-beta.2 is not published in NPM registry.

### ISSUE THREAD

**Issue by utkukaratas** [solidjs/solid-start#1168]
version 0.4.0-beta.2 is not published in NPM registry. OTOH docs are talking about 0.4.0 features like "use server".

latest NPM version is 0.3.10.

**Comment by asterikx** [comment]
The package name has been changed to `@solidjs/start` (see https://github.com/solidjs/solid-start/discussions/1159).

**Comment by ryansolid** [comment]
Thanks.
