### ISSUE TITLE
[Bug?]: Error with multiple routing group layouts

### ISSUE THREAD

**Issue by JAD3N** [solidjs/solid-start#1173]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The dev server crashes with this error:
```
/home/jaden/Projects/my-app/node_modules/@solidjs/start/server/StartServer.tsx:35
          const part = globalThis.MANIFEST[false ? "ssr" : "client"].inputs[segment["$component"].src];
                                                                                   ^

TypeError: Cannot read properties of undefined (reading '$component')
    at eval (/home/jaden/Projects/my-app/node_modules/@solidjs/start/server/StartServer.tsx:35:84)
```

### Expected behavior 🤔

Both groups should work.

### Steps to reproduce 🕹

Steps:

1. `bunx create-solid@latest`
2. `bun i`
3. Add 2 routing groups with a test route in each at the same level (in my example I called them group1, group2 and test1, test2).
4. Add 2 nested route files `(group1).tsx` and `(group2).tsx` in the routes folder.
5. `bun run dev`
6. Navigate to `(group1)/test1.tsx` route `/test1` and it'd load fine.
7. Navigate to `(group2)/test2.tsx` route `/test2` and it'd crash.

### Context 🔦

I'm trying to have different layouts for different sections of a site (i.e. auth and main site etc).

**Comment by birkskyum** [comment]
Could be a https://github.com/solidjs/solid-router bug

**Comment by JAD3N** [comment]
> Could be a https://github.com/solidjs/solid-router bug?

If I make a small tweak to the file that causes the crash, the pages loads the correct route. So my best guess is that when the Solid Start server is collecting assets to send it's trying to access the wrong group.
