### ISSUE TITLE
[Bug?]: CSS module styles injected after hydration; in `dev`?

### ISSUE THREAD

**Issue by LexSwed** [solidjs/solid-start#1175]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using CSS modules, so 
```ts
// text-field.tsx
import styles from './style.module.css';
const TextField = (props) => <div class={styles.textField}><label class={styles.label} /><input class={styles.input} /></div>

const SomeRoute = () => {
  return (
  <section class="container flex flex-col gap-4">
    <TextField label="Field label" placeholder="Enter something" />
  </section>)
}
```
The `TextField` styles chunk is not included in the initial HTML, it's loaded lazily after the component is rendered.

See isolated example with text field:
![image](https://github.com/solidjs/solid-start/assets/13509022/90dd576d-f865-4805-9c5c-4430a9e2adc4)

![image](https://github.com/solidjs/solid-start/assets/13509022/c73f309d-4b95-4645-b11e-dea4da99f075)

I also see the warning form Seroval(?) when using CSS modules:

![image](https://github.com/solidjs/solid-start/assets/13509022/218c9e58-f940-439b-8f94-15348d47d665)

### Expected behavior 🤔

CSS used for the elements on first render pass is included on the page (as inline styles or separate CSS file in prod env).

### Steps to reproduce 🕹

Steps:

1. Create a component that uses CSS modules.
2. Use it in a route (maybe `createAsync` usage is required to reproduce).
3. See that while component is indeed rendered in the initial HTML on the server, its styles are not included.
4. This leads to flash of unstyled content.

### Your environment 🌎

```shell
Node 20
Vite 5.0.10
vite-plugin-solid 2.8.0
vinxi 0.0.54
solid-start 0.4.2
solid-js latest
```

**Comment by srikrsna** [comment]
I see this too. Just to add to the repro steps, in the `basic` template changing the `Counter.css` to a css module `Counter.module.css` will trigger the warning

**Comment by nksaraf** [comment]
Yeah seems like our Module CSS handling is insufficient. Filing this issue in vinxi where it will need to be fixed.

**Comment by nksaraf** [comment]
Should be fixed in `vinxi@0.0.55`. please try that and reopen this issue if it still doesn't work.

**Comment by albertoforni** [comment]
I tested it and it works. Thanks

**Comment by arackaf** [comment]
Hmm I'm seeing this behavior now, on a new "bare" project scaffolded. Vinxi I have is 0.3.10

Looking at the SSR page source, it looks like the <link> tags with the styles are not being send down from the server.
