### ISSUE TITLE
[Bug?]: Issue with context who don't return the value

### ISSUE THREAD

**Issue by qlaffont** [solidjs/solid-start#1185]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hello I have a very strange bug with the new solid-start template : 
- I have a library who is package with tsup and tsup-preset-solid : https://github.com/qlaffont/rosetty-solid
- When I try to import my provider to access to my context and call it in my app sometimes I can access to the context value and sometimes I got undefined
- If i rebuild with tsup -> It will work 1 time and the other time is breaking but no changes have been made on the code

It's very frustrating... Can someone can help me, it is very strange and it is blocking me to make the migration to new solid start for my company.

The issue is not an HMR issue because when I stop the server and restart it, the issue persist.

### Expected behavior 🤔

Context should return value

### Context 🔦

YouTube Video about the issue : https://youtu.be/fydxXDyOrCE
More details here : https://discord.com/channels/722131463138705510/1189503397091606548

**Comment by qlaffont** [comment]
Library Code : 
![image](https://github.com/solidjs/solid-start/assets/10044790/367e4677-a9fe-4a25-9d5f-d5fb246c033f)

app.tsx : 
![image](https://github.com/solidjs/solid-start/assets/10044790/39c12134-71fd-4673-ae1b-a05ab267f862)


home.tsx :
![image](https://github.com/solidjs/solid-start/assets/10044790/5443c38e-bd85-4450-b24d-86b4b34d328b)

**Comment by ryansolid** [comment]
This was a bug in rosetty-solid 1.0.74. It appears they were bundling a duplicate version of solid. version 1.0.75 seems to have corrected that.

**Comment by qlaffont** [comment]
@ryansolid yes I'm agree with you but I don't understand why I have the error "Uncaught SyntaxError: ambiguous indirect export: default".

I have package the rosetty-solid with tsup and tsup solid ...
Can you help me to understand ? 

You can found the repro here : https://github.com/qlaffont/test-cmp

**Comment by qlaffont** [comment]
@ryansolid  ?

**Comment by qlaffont** [comment]
@ryansolid 1 month I have the issue without a solution ... I'm desperate .... Are you interested in a bounty to solve this bug ? 50 $ ?

**Comment by qlaffont** [comment]
Issue fix for context issue with tsup : https://github.com/egoist/tsup/issues/998

solid and other library was included in project

**Comment by qlaffont** [comment]
Finally we found the issue, it comes with dayjs. I have switch to date-fns and it works
