### ISSUE TITLE
[Bug?]: `use server` works only if `start: { ssr: false }` is set

### ISSUE THREAD

**Issue by leaysgur** [solidjs/solid-start#1186]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Call server function like

```jsx
import { createSignal } from "solid-js";

const serverFn = async () => {
  "use server";
  return ["Hello", "from", "server"];
};

export default function App() {
  const [messages, setMessages] = createSignal(["Not", "ready", "yet"]);

  const fetchMessages = async () => {
    setMessages(["Loading", "..."]);
    serverFn()
      .then((d) => setMessages(d))
      .catch((e) => setMessages(["Error:", e.message]));
  };

  return (
    <main>
      <h1>Test Server Function!</h1>
      <button class="increment" onClick={fetchMessages}>
        Fetch
      </button>
      <pre>{JSON.stringify(messages())}</pre>
    </main>
  );
}
```

ends up with

```
Error: $R is not defined
```

It seems `POST /_server` returns response with `($R["server-fn:0"]=[],($R=>$R[0]=["Hello","from","server"])($R["server-fn:0"]));` w/ status code 200.

### Expected behavior 🤔

Error should not be thrown.

If `start: { ssr: false }` is set in `vite.config.js`(= Select SSR ? No at `create-solid`), it works without error.

### Steps to reproduce 🕹

Steps:

1. `npm init solid@latest`
2. Select SSR ? **Yes** / TypeScript ? No / Template ? Bare
3. Update `src/app.jsx` like above and `npm run dev`
4. Click button

### Your environment 🌎

```shell
"@solidjs/start": "^0.4.2",
"solid-js": "^1.8.7",
"vinxi": "0.0.54"

Node.js v21.2.0
```

**Comment by lxsmnsyc** [comment]
hmmm weird, I thought we fixed this

**Comment by lxsmnsyc** [comment]
Can I ask what does your initial server html look like? Solid should automatically declare `$R` here

**Comment by leaysgur** [comment]
Thank you for the fix! 😉
