### ISSUE TITLE
[Bug?]: global styles are removed when accessing routes

### ISSUE THREAD

**Issue by bigmistqke** [solidjs/solid-start#1191]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Global style injected in root at `app.tsx` gets removed when accessing `routes/subroute`.
This happens both with `ssr: false` as `ssr: true`

https://github.com/solidjs/solid-start/assets/10504064/e9581ea8-650f-4ff7-947b-0a1ac939af22

### Expected behavior 🤔

Global style to be preserved.

### Steps to reproduce 🕹

Steps:

1. make 'index.css' file with `body {background: red}`
2. add 'import './index.css' file in `src/app.tsx`
3. add `<FileRouter/>`
4. add `routes/index.tsx`, `routes/0.tsx`, `routes/1.tsx`
5. add `<a href="./0"/>` or `<A href="./0"/>`  for route 0 and 1
6. pnpm run dev
7. switch between routes
8. notice background changes from red to unstyled, and how in devtools css-stylesheat appears and dissapears

**Comment by bigmistqke** [comment]
Localised the issue: it was due to some shenanigans I was doing with `<FileRoutes/>`

```tsx
<Router>
  {
     (() => {
          const routes = <FileRoutes />
          ...
          return routes
     })()
  }
</Router>
```

I probably should be using `import.meta.glob` instead, or maybe a feature request would be a proper way to hook into `FileRoutes` definitions.

**Comment by nksaraf** [comment]
what do you want to do with the FileRoutes? You can get access to the raw routes defintions by importing from `vinxi/routes` (not documented but give it a try)

**Comment by bigmistqke** [comment]
the usecase was to get a list of routes to use it in a enu. I will give `vinxi/routes` a go!
