### ISSUE TITLE
[Bug?]:  Cannot read properties of null (reading 'cloneEvent') 

### ISSUE THREAD

**Issue by baptistemanson** [solidjs/solid-start#1199]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I installed solidstart as such:
![image](https://github.com/solidjs/solid-start/assets/5444992/e19fcd96-1760-4c95-b529-478d580e6720)
√ Where do you want to create the app? ... aowp-bat
√ Which template do you want to use? » with-auth
√ Server Side Rendering? ... yes
√ Use TypeScript? ... yes
found matching commit hash: a9b4b0532f76ce9f0c20545b4f6732a126771a7f

On windows 11.
When booting up, I get: 
```
TypeError: Cannot read properties of null (reading 'cloneEvent')
    at Object.apply (node_modules/@solidjs/start/config/server-fns-runtime.jsx:19:41)
    at Module.cachedFn (node_modules/@solidjs/router/dist/data/cache.js:85:7)
    at load (src/routes/index.tsx?pick=route:6:37)
```

### Expected behavior 🤔

I was expecting the server to work.

### Steps to reproduce 🕹

Steps:

1.  npm init solid@latest
2. cd my-folder/
3. npm i
4. npm run dev -- --open

### Your environment 🌎

```shell
System: Windows 11
Node v18.16.1
Chrome Version 120.0.6099.130 (Official Build) (64-bit)
```

**Comment by asterikx** [comment]
I experience the same error. It goes away as I remove the `export const route = { ... }` from my routes files, so I guess it has something to do with it.

**Comment by nksaraf** [comment]
Hmm weird, i'll give it a try agian

**Comment by alveshelio** [comment]
I'm having the same problem and I can confirm that @asterikx answer makes the error go away.
If you click "Clear errors and retry", the error will go away too.

This error only happens in development mode, in production everything seems to work just fine. I've done a `pnpm run build` and `pnpm run start` and no errror.

**Comment by aellerton** [comment]
I can confirm the above behaviour.

Further, and possibly related to the routes, if I add a file `routes/about.tsx` with content like this:

```tsx
export default function About() {
  return (
    <main>
      <h2>About</h2>
      <p>This page intentionally blank</p>
    </main>
  );
}
```

then if you click the link to /about it will give a 404, but if you reload the page on that URL it works fine.

**Comment by carere** [comment]
I got the same problem on `0.0.62`, and removing the route object works fine, but I need to load some data upon switching to that route 😅

**Comment by carere** [comment]
Ok with further looking, I get the error on a fresh `pnpm dev`, then if i Hot Reload my page, the error goes away (I think that the load data was cache and retrieved).
Do you guys have the same behavior ?

**Comment by hansoksendahl** [comment]
@carere No, I do not have the same behavior.

I get `ERR_CONNECTION_REFUSED` errors on repeat after forcing a hot reload.

**Comment by aellerton** [comment]
For me the 404 appears when I soft navigate to the page (ie click a link)
but if I then reload fully in the browser the page works fine. Probably
something silly but I would have thought this would work out of the box.

**Comment by bartoszkrawczyk2** [comment]
Same issue here. It works with `export const route = { ... }`, but when I use `"use server"` in cache it crashes with the same error.

**Comment by carere** [comment]
It seems I don't have the error anymore with the latest version of vinxi / solid-start

**Comment by ryansolid** [comment]
> It seems I don't have the error anymore with the latest version of vinxi / solid-start

That's good so likely Vinxi version mismatch or something. Can others retry and let me know.

**Comment by asterikx** [comment]
> That's good so likely Vinxi version mismatch or something. Can others retry and let me know.

@ryansolid can confirm that I don't have the error anymore on the latest version of vinxi & solid-start.

**Comment by ryansolid** [comment]
That's 2 good enough for me. Reopen if still an issue.
