### ISSUE TITLE
[Bug?]: @solidjs/start 0.4.2 unmet peer vinxi@^0.0.54: found 0.0.59

### ISSUE THREAD

**Issue by NazarenoCavazzon** [solidjs/solid-start#1202]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The routing system doesn't work correctly when using the last version of vinxi (0.0.59), adding files to the routes directory doesn't work if I don't change the ssr to true then to false again, nested routes also doesn't work at all. Changing the version to 0.0.54 fixed that problem.

### Expected behavior 🤔

Routing should work as intended

### Steps to reproduce 🕹

Steps:

1. Create a new project with bunjs.
2. Check you're using vinxi 0.0.59.
3. Test routing behaviour with ssr disabled.

### Context 🔦

I'm doing a web app and had a lot of problems with routing. I created the project very recently.

### Your environment 🌎

```shell
System: MacOS Sonoma 14.0, M1 Pro
Node Version: v18.8.0
I'm using pnpm
```

**Comment by lxsmnsyc** [comment]
one of NPM's weird version resolution. It's strict for 0.0.x but not when it is >0.1.x

**Comment by ryansolid** [comment]
Yeah updated and released. Should be good now.

**Comment by NazarenoCavazzon** [comment]
Forgot to say thanks! @ryansolid
