### ISSUE TITLE
[Bug?]: Build without SSR throw error on prerender  "Should be provided by compiler"

### ISSUE THREAD

**Issue by ivanjoz** [solidjs/solid-start#1209]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When building with ssr: false, I get the error "Should be provided by compiler".
Doesn't generate a .html anywhere

### Expected behavior 🤔

generate a .html file that serves as an entry point like a conventional SPA

### Steps to reproduce 🕹

Steps:

1. npm init solid@latest
2. choose: Which template do you want to use?  = basic
3. choose: Server Side Rendering? = no
4. choose: Use TypeScript? = yes
5. npm install
6. npm run build

package.json:
`{
  "name": "demo1",
  "type": "module",
  "scripts": {
    "dev": "vinxi dev",
    "build": "vinxi build",
    "start": "vinxi start"
  },
  "dependencies": {
    "@solidjs/meta": "^0.29.2",
    "@solidjs/router": "^0.10.5",
    "@solidjs/start": "^0.4.2",
    "solid-js": "^1.8.7",
    "vinxi": "0.0.59"
  },
  "engines": {
    "node": ">=18"
  }
}`

### Context 🔦

Generate a simple SPA that I can upload as static site. I use SolidStart because of the file based routing.

### Your environment 🌎

```shell
System:
  OS: Linux KDE Neon | Kernel 6.6.1-060601-generic
  Arquitecture: x86_64
Node Version: v18.17.1
SolidStart version: 0.4.2
```

**Comment by u1in** [comment]
I found a similar issue in vinxi, maybe helpful.
["Should be provided by compiler" Error #77](https://github.com/nksaraf/vinxi/issues/77)

**Comment by ivanjoz** [comment]
It is solve using "override" in the package.json to match de vinxi version in the dependencies. In mi case I am using vinxi 0.0.62. 

```json
{
  "dependencies": {
    "@solidjs/meta": "^0.29.2",
    "@solidjs/router": "^0.10.5",
    "@solidjs/start": "^0.4.2",
    "solid-js": "^1.8.7",
    "vinxi": "0.0.62"
  },
  "overrides": {
    "vinxi": "0.0.62"
  },
}
```

**Comment by ryansolid** [comment]
Ok new version of Start now matching ranges in Vinxi should fix this. Try 0.4.3
