### ISSUE TITLE
[Bug?]: Conflicting versions of package 'seroval' are created in output.

### ISSUE THREAD

**Issue by TisLeo** [solidjs/solid-start#1214]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I build my SolidStart app, the output produces two different versions of a package called `seroval` which are conflicting and cause errors when trying to deploy the app.

When running `bun run build` (or `npm`...causes the same output), the following is produced:
<img width="229" alt="image" src="https://github.com/solidjs/solid-start/assets/88405502/58ae0ac6-ff19-4a27-89a1-bfcf7cb96bd1">

I am building for Vercel specifically (with the `--preview vercel` flag on the vinxi build command inside package.json), but the same occurs under the normal `.output/...` if built without this flag.

The following error occurs: `SyntaxError: The requested module 'seroval' does not provide an export named 'createStream'`

When running `npm ls seroval`, I get:
<img width="193" alt="image" src="https://github.com/solidjs/solid-start/assets/88405502/11617c8d-6a2a-45eb-94b1-96c1a1139de6">
I have the current latest version of both solid start and solidjs. Here are the relevant dependencies:
```json
"dependencies": {
       ...
        "@solidjs/meta": "^0.29.3",
        "@solidjs/router": "^0.10.5",
        "@solidjs/start": "^0.4.2",
        "clsx": "^2.1.0",
        "solid-js": "^1.8.7",
        "solid-start": "^0.3.10",
        "vinxi": "0.0.62"
       ...
    },
```

### Expected behavior 🤔

The output to be built correctly without conflicting dependencies.

### Steps to reproduce 🕹

Steps:

1. Create a solid app with the dependencies shown above
2. Build with `npm/bun run build`
3. Try to run or deploy it somewhere (vercel or locally; same error)

### Your environment 🌎

```shell
MacOS Ventura
VSCode
```

**Comment by ryansolid** [comment]
Updated Solid with the lates. All versions of Seroval are the same.
