### ISSUE TITLE
[Bug?]: The Solid Start docs are broken

### ISSUE THREAD

**Issue by ssebastianoo** [solidjs/solid-start#1215]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I open https://start.solidjs.com/ this happens:

![image](https://github.com/solidjs/solid-start/assets/48064277/e3b756be-fafa-49f9-9ab3-abd0060e6e0d)

### Expected behavior 🤔

The site should load normally

### Steps to reproduce 🕹

Steps:

1. Open https://start.solidjs.com/

### Your environment 🌎

```shell
System:
 OS: macOS Sonoma
 Browser: Arc, Safari, Firefox
```

**Comment by StevenStavrakis** [comment]
Can confirm

**Comment by bradley-varol** [comment]
Looks like there might be a Javascript error preventing the stylesheet from loading!

https://start.solidjs.com/core-concepts/assets/ssr-2f166d92.css

**Comment by nksaraf** [comment]
Should be fixed now (bump to vinxi 0.0.64)
