### ISSUE TITLE
[Bug?]: Vite always re-optimises all dependencies when launching dev server

### ISSUE THREAD

**Issue by Brendonovich** [solidjs/solid-start#1233]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Running `vinxi dev` will cause Vite to re-optimise all dependencies, even those that it has previously optimised.

### Expected behavior 🤔

Dependencies that were previously optimised shouldn't be re-optimised

### Steps to reproduce 🕹

Steps:

1. Clone https://github.com/brendonovich/macrograph
2. `pnpm install`
3. `pnpm web dev` and go to `http://localhost:4321`
4.  Kill `pnpm web dev`
5. Repeat steps 3 & 4 a few times
6. Notice that vite re-optimised deps such as `@solid-primitives/*` and `@koblate/core` every time, ignoring caching

### Context 🔦

My project has quite a few dependencies to optimise, so this bug makes the dev server's startup time pretty large.

I think this may be a bug in Vinxi, as there's a couple of places ([1](https://github.com/nksaraf/vinxi/blob/4f793bd2384694d3d4a008fc865f4acee6ef4fb6/packages/vinxi/lib/build.js#L538-L540), [2](https://github.com/nksaraf/vinxi/blob/4f793bd2384694d3d4a008fc865f4acee6ef4fb6/packages/vinxi/lib/build.js#L611-L614)) where `opimtizeDeps` is forced.

**Comment by nksaraf** [comment]
those are applied during build. yeah ill have to see whats happening.

**Comment by FlatMapIO** [comment]
> I think this may be a bug in Vinxi, as there's a couple of places ([1](https://github.com/nksaraf/vinxi/blob/4f793bd2384694d3d4a008fc865f4acee6ef4fb6/packages/vinxi/lib/build.js#L538-L540), [2](https://github.com/nksaraf/vinxi/blob/4f793bd2384694d3d4a008fc865f4acee6ef4fb6/packages/vinxi/lib/build.js#L611-L614)) where opimtizeDeps is forced.

Comments `force: true `Not helpful

**Comment by FlatMapIO** [comment]
@nksaraf Is it possible to raise the priority of this issue?   I'm using ark-ui and every time I change the browser it shows a 30M js file loaded 😅

**Comment by nksaraf** [comment]
Yeah I spent some time looking at this and wasn't at first pass able to find where the optimizeDeps is happening again. Ill look again this weekend

**Comment by FlatMapIO** [comment]
It seems that all solid libraries have this problem, they all haves `source/**/*.jsx` in their dist, and for the time being I can only prebuild packages like lucide-solid into a single file, and set the `resolve.alias` in the vite, otherwise every reload is DDoS'ing the disk! and I have to wait tens of seconds.

**Comment by spaaacetoast** [comment]
> It seems that all solid libraries have this problem, they all haves `source/**/*.jsx` in their dist, and for the time being I can only prebuild packages like lucide-solid into a single file, and set the `resolve.alias` in the vite, otherwise every reload is DDoS'ing the disk! and I have to wait tens of seconds.

Not necessarily related to this issue but the whole package being loaded has more to do with how vite loads kobalte and ark, see [this kobalte issue](https://github.com/kobaltedev/kobalte/issues/35)

**Comment by birkskyum** [comment]
@Brendonovich , the repro is now quite far behind the latest versions of solid-start / vinxi / solid-router. Would you be able to update it?

**Comment by FlatMapIO** [comment]
In my experiments, full overloads are rarely (if ever) triggered in 0.6.0, and have little or no impact on the development experience.

**Comment by Brendonovich** [comment]
@birkskyum I've updated all those deps and I'm not getting the optimize deps log anymore, might be fixed now.

**Comment by birkskyum** [comment]
Excellent, thanks, I'll try the repro again later today and see if I get the same outcome.

**Comment by ryansolid** [comment]
Awesome
