### ISSUE TITLE
[Bug?]: docs: favicon.ico is missing in prod

### ISSUE THREAD

**Issue by glitch-txs** [solidjs/solid-start#1235]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![image](https://github.com/solidjs/solid-start/assets/66949816/399b5bf0-ebd5-4dab-993d-69af517f557c)

### Expected behavior 🤔

icon should show in the browser tab

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by ryansolid** [comment]
It's very odd. I must admit. I see the file in my local builds. I presume it makes it to cloudflare and yet it doesn't get served by the static asset.

**Comment by edivados** [comment]
This is what I could find out.

[kv-asset-handler](https://github.com/cloudflare/kv-asset-handler) tries to determine the type of `/favicon.ico` with [mime](https://github.com/broofa/mime), fails and loads `/favicon.ico/index.html`.

The interessting thing is that `ico` and other extensions which should be there are missing from mime. Why that is I don't know. Tried to force everything to `kv-asset-handler: 0.3.0` and `mime: 3` but no luck. Maybe something else is messing with it.

```js
var Mime_1 = Mime$1;

var standard = {...}

let Mime = Mime_1;
var lite = new Mime(standard); // <=== where is the others map?

var mime_1 = mime$1.exports;
```

**Comment by birkskyum** [comment]
Seems to work alright?

<img width="1048" alt="Screenshot 2024-03-12 at 15 31 38" src="https://github.com/solidjs/solid-start/assets/74932975/aabb9c08-5be3-4ed3-9990-354e34be0c5c">

**Comment by ryansolid** [comment]
I think that is an old saved one. I still see us returning an HTML page on that request. Somehow it isn't there or isn't matching on static assets first.

**Comment by edivados** [comment]
The answer was right there...🤦‍♂️ 

This was [fixed for the pages preset](https://github.com/unjs/nitro/pull/933). There is an open issue for the [cloudflare preset](https://github.com/unjs/nitro/issues/281)  and apperently also applies to cloudflare_module.  

mime/lite seems to be [pulled in by unenv](https://github.com/unjs/unenv/blob/2c5b2662dccdf114f4106df082686b7850c00b5a/src/presets/nodeless.ts#L36-L39). Adding an alias to the full mime db like it was done for pages works around the problem. Gave it a quick try locally and worked.

```js
server: {
    preset: "cloudflare_module",
    alias: {
      "_mime": "mime/index.js"
    }
}
```

**Comment by ryansolid** [comment]
As this is not pages they will probably make it lower priority. I'm going to close it here and we can just track the progress in that nitro issue. I'm glad the workaround exists.
