### ISSUE TITLE
[Bug?]: Wrong server build when using "debug" package

### ISSUE THREAD

**Issue by indeyets** [solidjs/solid-start#1238]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

`import something from "debug"` leads to aliasing of `something` to `console.debug` instead of using actual "debug" package.

### Expected behavior 🤔

"debug" package should not have special treatment and should be built/bundled as any other package.

### Steps to reproduce 🕹

Here's the reproduction repository: https://github.com/indeyets/vinxi-debug-bug
It is created using official procedure for solid-start projects.

I added "debug" to dependencies using regular name and using a "ddbbgg" alias. Used both in app.tsx to show the difference.

1. `npm install`
2. `npm run build`
3. see `.output/server/chunks/nitro/node-server.mjs`, search for ".extend("

on my machine it looks like this: `const It = debug$1(), Bt = It.extend("error"), Ht = nt("debug2:solid:root"), Nt = Ht.extend("error");`

`It` refers to `from "debug"` and is broken, `Ht` refers to `from "ddbbgg"` and works fine

**Comment by indeyets** [comment]
@nksaraf it is probably related to vinxi, but I post here as my reproduction case is in solid-start

**Comment by ryansolid** [comment]
Realistically I'm not likely to debug this one so I moved the issue to Vinxi and backlinked. https://github.com/nksaraf/vinxi/issues/291
