### ISSUE TITLE
[Bug?]: todomvc app doesn't work on vercel

### ISSUE THREAD

**Issue by albertoforni** [solidjs/solid-start#1239]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I cloned the `todomvc` app from the `examples` folder and tried to deploy it to vercel using the preset in `vite.config.ts`

```ts
import { defineConfig } from "@solidjs/start/config";

export default defineConfig({
  start: {
    server: {
      preset: "vercel",
    },
  },
});
```

In Build & Development Settings, I tried to override the different settings and specify `Other` Framework with no luck.
<img width="969" alt="image" src="https://github.com/solidjs/solid-start/assets/2559136/75d48d10-1464-4a45-b549-1ba361dc5807">

When I load the page I get this error in the console
<img width="649" alt="image" src="https://github.com/solidjs/solid-start/assets/2559136/64990441-3bbf-4ea6-99b7-d4b49302adf9">

### Steps to reproduce 🕹

Steps:

1. Clone the repo https://github.com/albertoforni/solidstart-todomvc
2. Deploy to [vercel](https://vercel.com/dashboard)
3. Open the page

### Your environment 🌎

```shell
solid-start: 0.4.6
```

**Comment by lxsmnsyc** [comment]
This seems to be an issue to the app itself rather than the preset

https://github.com/solidjs/solid-start/blob/main/examples/todomvc/src/routes/index.tsx#L50-L56

**Comment by edivados** [comment]
Does that driver work on vercel?

https://github.com/solidjs/solid-start/blob/c8ec9f1e66650dd1f557d6dcc9ed1badd44db45c/examples/todomvc/src/lib/api.ts#L7-L13

**Comment by ryansolid** [comment]
Yeah if I was to bet the problem is with the storage option. It probably isn't finding the todos properly.

**Comment by albertoforni** [comment]
Thanks, I'll try to change that and see if it works.

**Comment by albertoforni** [comment]
I confirm that by replacing
```
const storage = createStorage({
  driver: fsLiteDriver({
    base: "./.data"
  })
});
```
with a simple `Map`, it works.

Thanks everyone for the help and sorry for the noise.
I was trying to debug another project I'm migrating from `v0.3.10` and I wanted to see if a simple example worked. I guess I picked a not-so-simple one... At least now I know that it does work.
