### ISSUE TITLE
[Bug?]: The requested module 'node_modules/h3/dist/index.mjs' does not provide an export named 'createHandler' when running `bun run build`

### ISSUE THREAD

**Issue by andrewnathanco** [solidjs/solid-start#1252]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When running `bun run build` or `pnpm run build` or `npm run build` i get this error.

<img width="1197" alt="image" src="https://github.com/solidjs/solid-start/assets/34322878/e7d7b448-0f42-4000-8327-3ced7d72d38d">

### Expected behavior 🤔

I would expect the project to finish the build.

### Steps to reproduce 🕹

Steps:

1. git clone https://github.com/andrewnathanco/guess
2. cd ./code
3. bun install
4. bun run build

### Context 🔦

I'm trying to build my solid start project. This also happens in Docker.

### Your environment 🌎

in docker

```shell
FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
```

in bun

```
bun --version
1.0.1
```

**Comment by atk** [comment]
You need to update the imports of your server entry.

**Comment by andrewnathanco** [comment]
@atk okay yeah that fixed it thanks.
