### ISSUE TITLE
Set failed, cookie was too large. option to compress data in session?

### ISSUE THREAD

**Issue by nksaraf** [solidjs/solid-start#1260]
```
export async function signin({accessToken, profile}: { accessToken: string, profile: string }) {
    try {
        const session = await getSession();
        await session.update((d: UserSession) => (d.accessToken = accessToken));
        await session.update((d: UserSession) => (d.profile = profile));
    } catch (err) {
        return err as Error;
    }
}
```

And I get response back from api with the error in **Set-Cookie** header:

**Set failed, cookie was too large.**

Actual length of access token is 244, profile is 334. 
Do I have an option to compress data?

_Originally posted by @mikalaikabash in https://github.com/solidjs/solid-start/issues/1192#issuecomment-1890907435_

**Comment by ryansolid** [comment]
That's a good question. Generally we are just exposing H3 APIs and aren't doing any client side cookie handling either. If the cookie is too large, I'm gathering since we aren't handling the decoding beyond what H3 does, then we wouldn't be responsible for handling the encoding either.

**Comment by mikalaikabash** [comment]
I ended up saving only access token in session. 

Please close this issue.
