### ISSUE TITLE
[Bug?]: client router not working with docs site

### ISSUE THREAD

**Issue by babyccino** [solidjs/solid-start#1265]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Moving between pages triggers full page reload

### Expected behavior 🤔

Moving between pages should use the client-side router

### Steps to reproduce 🕹

Steps:

1. go to https://start.solidjs.com/ or start docs dev server
2. click on any page link

### Your environment 🌎

```shell
System:
  OS: OSX 14.2.1
  CPU: Apple M2
Binaries:
  Node: 19.9.0
  pnpm: 8.13.1
npmPackages:
  solid-start: 0.4.10
```

**Comment by ryansolid** [comment]
This is intentional. The docs site is an MPA with Islands and pre-rendering similar to Astro. In a sense this testing our own tech but this apprach reduces the javascript sent and the hydration time for the page load.
