### ISSUE TITLE
[Bug?]: Same plugin instance being passed to multiple routers can cause problems

### ISSUE THREAD

**Issue by edivados** [solidjs/solid-start#1277]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Vite plugins some times use factory functions and keep state inside the function scope to pass it between hooks. Solid-Start passing the same plugin instaces to multiple routers can cause unexpected problems.

Currently this is avoidable by using a function for plugins instead of an array.

### Expected behavior 🤔

Not to pass the same instance to multiple routers.

### Steps to reproduce 🕹

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/solidjs-solid-start-w9seky?file=vite.config.ts)

Steps:

1. pnpm create solid <name>
2. select basic/ts/ssr
3. add the vite.config below
4. pnpm run build

Watch the items count increase between router builds.

```ts
import { defineConfig } from "@solidjs/start/config";

const itemsPlugin = () => {
  const items = [];

  return {
    name: "items-plugin",
    generateBundle() {
      items.push(1);
    },
    closeBundle() {
      console.log("Items: ", items.length);
    }
  }
}

export default defineConfig({
  plugins: [itemsPlugin()]
});
```

### Context 🔦

Came across this on https://github.com/nksaraf/vinxi/issues/108#issuecomment-1902164388 with [unplugin-imagemin](https://github.com/unplugin/unplugin-imagemin) where one problem (3rd point) is caused by this.

**Comment by ryansolid** [comment]
What would you prefer. We always force the function, or have it just be an option?

**Comment by edivados** [comment]
Unless there is a reason not to, I would default to always using a function so I don't have to think about this problem.

**Comment by ryansolid** [comment]
I think 0.6.0 basically solves this now with there being vite as a function. So closing this.
