### ISSUE TITLE
Node version should be checked when starting the script

### ISSUE THREAD

**Issue by DieTapete** [solidjs/solid-start#128]
I just had to deal with some issues like https://github.com/solidjs/solid-start/issues/104 until i figured that the node version I used (12.13.0) was apparently not high enough. There should be a check on startup if the user is running the script with a supported node version and bail if thats not the case.

**Comment by nksaraf** [comment]
Thats a good point, we need to make the DX around this better

**Comment by cstrnt** [comment]
Wouldn't setting the `engine` field in the `package.json` enough for this case?

**Comment by nksaraf** [comment]
I thought we did do that , but I also think we set it incorrectly to `>=14`

**Comment by ryansolid** [comment]
Yeah it's a fun one. I did 14 because we need to support the build chain for Netlify, Vercel, and other AWS Lambda based providers. We use their Edge functions which don't even require Node but it's why we are here.

**Comment by ryansolid** [comment]
Well, updated all the engines to 16 now.
