### ISSUE TITLE
[Bug?]: onig.wasm from shikiji in build output

### ISSUE THREAD

**Issue by edivados** [solidjs/solid-start#1281]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

onig.wasm from [shikiji](https://github.com/antfu/shikiji) is emitted as asset in build.

### Expected behavior 🤔

No onig.wasm in build output.

### Steps to reproduce 🕹

Look at terminal output at the end.

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/solidjs-solid-start-j1qdpn)

Steps:

1. pnpm create solid <name>
2. select basic/ts/ssr
3. pnpm run build
4. go to `.output/public/_build/assets` (there is a .wasm file)

**Comment by ryansolid** [comment]
I see.. good catch. I was so concerned with it tree shaking in the browser (which it does), I didn't see that it made it into the assets. Not sure what we will do here but good to know.

**Comment by edivados** [comment]
Ok. Looks like I can remove it from the bundle for now.

**Comment by ryansolid** [comment]
@lxsmnsyc or @nksaraf any thoughts on this?

**Comment by edivados** [comment]
No wasm file in `0.7.5`. I guess this was fixed in `0.7.3` by https://github.com/solidjs/solid-start/pull/1373
Thanky you.
