### ISSUE TITLE
[Bug?]: Hydration Error Occurs When Adding New Route

### ISSUE THREAD

**Issue by hemanthsaik** [solidjs/solid-start#1286]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The issue with Solid Start is that whenever I add a new route, it causes a hydration error. This means that instead of the new route displaying correctly, the app doesn't load it properly. I have to restart the development environment every time I add a new route to get it working again.
<img width="1680" alt="Screenshot 2024-01-26 at 10 22 26 AM" src="https://github.com/solidjs/solid-start/assets/67971173/4f5ec8f8-dd7c-4021-bf77-e7b9790687e3">

### Expected behavior 🤔

The expected behavior is that when I add a new route to my Solid Start application, it should display correctly without any errors. I should be able to navigate to the new route seamlessly, and the application should continue to function smoothly without needing to restart the development environment.

### Steps to reproduce 🕹

Steps:

1. Start the Solid Start development environment.
2. Navigate to the application.
3. Add a new route to the application.
4. Attempt to access the newly added route.
5. Observe that a hydration error occurs, preventing the route from displaying correctly.
6. Note that the application becomes unresponsive and requires a restart of the development environment to resolve the issue.

**Comment by ryansolid** [comment]
You mean a fresh load of the page on the new route right? Any client-side navigation would not involve hydration. I wonder if there is something up with HMR.

**Comment by hemanthsaik** [comment]
Thanks for your response! Yes, you're correct. I meant a fresh load of the page on the new route.

Regarding your suggestion about the server HMR (Hot Module Replacement), I appreciate your insight. However, I must admit that my understanding of the core functionality is limited, so I'm not certain if there's an issue with the server HMR.

As I'm relatively new to development, I'm still learning and may not be familiar with all aspects of the setup. I'd greatly appreciate any guidance or suggestions for improvement you can offer.

I'd also like to invite you to take a look at my base setup on GitHub. If you have a moment, could you please review it and let me know if there are any mistakes or areas where I can improve? Here's the link: [GitHub Link](https://github.com/hemanthsaik/solid-init)

Thank you for your help!

**Comment by angry-meow** [comment]
I faced the same issue but noticed something.

The recently added route gives the hydration error until you reset the cache (refresh via `Ctrl + Shift + R` or selecting `Disable cache` in the DevTools' Network tab).

So, @hemanthsaik, you fortunately don't have to restart the server every time.

**Comment by hemanthsaik** [comment]
@angry-meow thank you buddy 😀

**Comment by ryansolid** [comment]
So it works but the browser is getting back previously cached versions of the JS and it isn't matching up. This isn't on Solid's side them most likely and on the build/HMR side. Thanks for the info @angry-meow.

**Comment by alexpmac** [comment]
I've been wrangling with this issue attempting to port a small project over from Astro, and refreshing the cache does work.
However in testing I've noticed that it only exhibits the hydration mismatch issue when a couple of things are true:

1. When the 404 route file is named `[...404].tsx`
2. When that file component is importing and using another component within

Renaming the file to `[...NotFound].tsx` while keeping the imported component has no issues, along with keeping the file named `[...404].tsx` but removing any imported components within

**Comment by aellerton** [comment]
This is still the case.

Steps to reproduce:

```
pnpm create solid@latest
# name: solid-bug-minimal
# solid-start: yes
# template: basic
# typescript: yes

cd solid-bug-minimal
pnpm install
code .   # or any editor of your choice
pnpm dev
```

Then:
* load http://localhost:3000 - all works fine
* add file `src/routes/contact.tsx` copying/modifying content from `about.tsx` 
* update `app.tsx` with a link to it the contact page.
* save files in the editor

The new link will appear via HMR, but clicking it will show a 404.

Reloading in the browser will show hyrdation error:
![image](https://github.com/solidjs/solid-start/assets/967842/58a4ea83-7748-400b-ad1f-a61f45fcd570)

It does load the new route if:
* Stop the dev server and restart
* control+shift+F5 (in Chrome Windows) to force clear of cache.

**Comment by klequis** [comment]
I have been experiencing this as well. The only way to reproduce it consistently is to add a new route. It doesn't matter if the dev server is running when the new route is added or not.

Interestingly, after adding the new route and navigating to it I almost always get routed to the catch-all route (page not found). After navigating away and back to the new page a few times I get the hydration error.

If I disable the cash the problem goes away. 

Tried Chromium, Chrome and FireFox. All have the same behavior.

**Comment by klequis** [comment]
I'm writing a tutorial where I and and remove routes, so a good test of this fix. I'm happy to report that since I started using the packages with this fix I haven't had a single problem in the past 2 days :+1:

**Comment by vibhuvV** [comment]
Not sure if it is related to the same thing or not but I am still facing this issue.
These are my dependencies
```json
  "dependencies": {
    "@solidjs/router": "^0.14.1",
    "@solidjs/start": "^1.0.6",
    "solid-js": "^1.8.19",
    "vinxi": "^0.4.1"
  },
```

![Screenshot 2024-07-26 at 11 06 27 PM](https://github.com/user-attachments/assets/33251676-710f-48a9-8052-a884c2d43139)

**Comment by mdynnl** [comment]
@vibhuvV It's more likely to be related to the most recent hydration key optimization. Please open another issue with the code where the hydration mismatch occurs. To track it down, you can try to look for the most similar key in the DOM tree.
