### ISSUE TITLE
Fresh solid-start init with v0.1.0-alpha.83 fails to load router FormError

### ISSUE THREAD

**Issue by katywings** [solidjs/solid-start#129]
IS:
Creating a fresh solid-start instance with v0.1.0-alpha.83, running it and opening http://localhost:3000/ fails with the error: 
`Error: failed to load module for ssr: ../router/FormError
    at instantiateModule (XYZ/start-test/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59253:15)`

SHOULD:
There should be no error :D

EXTRA INFO:
The error goes away by downgrading to v0.1.0-alpha.82.

SCREENSHOTS:
![Init](https://user-images.githubusercontent.com/4012401/172021397-00136987-7bc4-4699-bbad-c8b8ddbc9076.png)
![SolidStartFormErrorFail](https://user-images.githubusercontent.com/4012401/172021407-d8f94338-169b-474a-b6cb-dd30d79f0cff.png)

**Comment by benbender** [comment]
can confirm.

**Comment by ryansolid** [comment]
Sorry I thought I updated all the locations let me see. What I missed.

**Comment by ryansolid** [comment]
Ok it was missing folder in package.json files. It should work in alpha.84.

**Comment by katywings** [comment]
Awesome @ryansolid, thank you for your work!
