### ISSUE TITLE
[Bug?]: During build, getting `[plugin:vite:resolve] Module ??? has been externalized for browser compatibility, imported by ...` errors

### ISSUE THREAD

**Issue by lominming** [solidjs/solid-start#1293]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

During the build process `vinxi build`, getting a lot of `[plugin:vite:resolve] Module ??? has been externalized for browser compatibility, imported by ... ` errors, followed by `"performance" is not exported by "__vite-browser-external", imported by "node_modules/postgres/src/connection.js".` error which I suspect is related.

![image](https://github.com/solidjs/solid-start/assets/742933/1c9be23c-891b-4d86-bbfe-c91d1deeb2b7)

### Expected behavior 🤔

Should not have error.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

There are a bunch of places that I used `getRequestEvent` which I am not sure whether is related based on https://github.com/solidjs/solid-start/issues/1172

Could it be because of lack of configuration that causes Vinxi to bundle the files for browser when some files are meant to be on the server side?

**Comment by nksaraf** [comment]
where is postgres being used (server functions?) coz if the dependencies are not being treeshaken this can cause problems.

**Comment by lominming** [comment]
Found the issue. During the migration to the latest `0.4.0` (beta 2), some previously `server$` did not get converted to `"use server";` and is hence wrongly build to be browser modules which triggered the error.

If all the related modules are properly defined to be "backend" functions, build works.
