### ISSUE TITLE
[Bug?]: Cloudflare presets don't cache assets

### ISSUE THREAD

**Issue by rvlzzr** [solidjs/solid-start#1315]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In solid-start 0.3 using the cloudflare adapters, refreshing the page and looking at the network section of devtools, you see assets all showing (memory cache) as expected.

In the current version, everything hits the server which returns 304 status.

### Expected behavior 🤔

Assets should be cached.

### Steps to reproduce 🕹

Steps:

1. Use one of the cloudflare presets and build/deploy.
2. Open network tab of devtools in your browser.
3. Refresh the page.
4. Note that you never see memory or disk cache for assets.

**Comment by rvlzzr** [comment]
Also `routeRules` as per https://github.com/nksaraf/vinxi/issues/140#issuecomment-1913720882 don't seem to do anything for Cloudflare as far as I can tell -- I don't see any working way to send cache-control headers for assets that works with the cloudflare adapters (and shouldn't this be the default anyway?).

**Comment by ryansolid** [comment]
Hmm.. we might have done something special for our previous adapters but now we follow nitro's preset. So the advice from https://github.com/nksaraf/vinxi/issues/140#issuecomment-1913720882 is the solution. If that doesn't work it is on Nitro/Vinxi side but there isn't anything we can do here.
