### ISSUE TITLE
[Feature?]: [docs] Add a 'edit this page' button on every documentation page

### ISSUE THREAD

**Issue by yaikohi** [solidjs/solid-start#1316]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Add a 'edit this page' button on the documentation website. It would send the user to a location where they can edit the page and then create a PR on github.

### Examples 🌈

- [Elysia documentation](https://elysiajs.com/plugins/overview.html): Has it at the bottom of every page
- [spacedrive documentation](https://www.spacedrive.com/docs/product/getting-started/introduction): Also has it at the bottom of the page.

## Why

- It makes it easier for people to create a PR when they notice that the docs have a mistake in some script or maybe a typo & generally welcomes the community to contribute to the docs. I've done so for the Elysia docs whenever I noticed something was incorrect / out-of-date / or maybe there was a typo. 

Elysia is also a framework that is heavily in development similar to solidstart so I thought that solidstart would also benefit from the community more in this sense. 

## Why not

- Might be more work for people that handle the PR's if too many people make updates to the docs this way. 
- it's already possible if people want to.

**Comment by ryansolid** [comment]
I would love anything that would help with more people writing docs. This sounds like a great idea. Whether I have time to get to it short terms is another thing. But I like it.

**Comment by dyyyl** [comment]
I think this is a really good idea, and I'd be happy to start working on the feature!

**Comment by yaikohi** [comment]
The new docs have this implemented to some degree so this can be closed I think!

https://docs.solidjs.com/solid-start 
> Clicking on 'edit this page' (at the bottom of the page) doesn't seem to work well yet though, but that's something for the repository of that project.
