### ISSUE TITLE
deployment on vercel fails

### ISSUE THREAD

**Issue by verdavaine** [solidjs/solid-start#132]
I get this error 'Could not resolve entry module (node_modules/solid-start/runtime/entries/client.tsx)' when deploying hackernews on vercel.
Locally, it works correctly.

**Comment by ryansolid** [comment]
Interesting it should all be bundled in the build by that point and not be referencing initial source files. I haven't done any deploys to Vercel in the last month but seems strange anything would have changed. Are you using github hooks to deploy or doing so manually by CLI?

**Comment by verdavaine** [comment]
The deployment is done automatically every time I push a new commit on github

**Comment by nksaraf** [comment]
> Could not resolve entry module (node_modules/solid-start/runtime/entries/client.tsx)

This file path is from an old version of solid-start, so it probably is not installing the correct solid-start version, could you confirm this..

**Comment by nksaraf** [comment]
Marking as closed because this is definetely an older version as seen by the path that's being imported. Please upgrade to latest version and if this problem persists you can reopen this issue.
