### ISSUE TITLE
[Bug?]: Docs Build is Broken

### ISSUE THREAD

**Issue by ryansolid** [solidjs/solid-start#1321]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I get the error:
> [vite-server-references] Invalid left-hand side in prefix operation. (1:2)
file: /Users/ryancarniato/Development/solid-start/docs/routes/api/GET.md?pick=getFrontMatter:1:2
> ERROR  Invalid left-hand side in prefix operation. (1:2)                                                             4:15:01 PM
> at constructor (node_modules/.pnpm/@babel+parser@7.23.9/node_modules/@babel/parser/lib/index.js:353:19)

### Expected behavior 🤔

That the docs build

### Steps to reproduce 🕹

pnpm docs:build

works fine in dev

### Context 🔦

As far as I can tell this began when I started doing single flight. But only seems to effect the docs transformation.

**Comment by doeixd** [comment]
I'd try removing the `twoslash` from the code block on the `GET.md` file

**Comment by nksaraf** [comment]
fixed by [f73de3a](https://github.com/solidjs/solid-start/commit/f73de3a61f964748e456f6f714a3c290cd53379b)
