### ISSUE TITLE
[Bug?]: Rejected promises in server fns are not handled correctly

### ISSUE THREAD

**Issue by marvin-j97** [solidjs/solid-start#1323]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

This is similar but not the same as https://github.com/solidjs/solid-start/issues/1222
Here's a simple reproduction:

```tsx
import { cache, createAsync } from "@solidjs/router";

const myFn = cache(async () => {
  "use server";

  await Promise.reject("oh no");

  return "Halló";
}, "myFn");

export default function Home() {
  const msg = createAsync(() => myFn(), {
    deferStream: true
  });

  return (
    <main>
      <h1>{msg()} world!</h1>
    </main>
  );
}
```

On initial SSR, Dev server crashes with `Error: oh no`, but should probably show an error page, and log something in the console, but not die.

When using client-side routing (going from /about to /broken page), an error is printed:

```
Uncaught (in promise) SyntaxError: Unexpected identifier 'no'
    at eval (<anonymous>)
    at deserialize (index.mjs?v=7b36de8d:3200:19)
    at SerovalChunkReader.next (server-runtime.ts?v=7b36de8d:43:14)
    at SerovalChunkReader.next (server-runtime.ts?v=7b36de8d:30:25)
    at async deserializeStream (server-runtime.ts?v=7b36de8d:60:18)
```

Seemingly, rejections are not taken into account correctly. Again, a pop-up telling the user a fatal error in the server function occured would be great.

### Steps to reproduce 🕹

See example

### Context 🔦

Obvious

### Your environment 🌎

- Using latest `basic` solid-cli example as of today
- Chrome
- Ubuntu

**Comment by lxsmnsyc** [comment]
probably has something to do with `cache` 🤔

**Comment by marvin-j97** [comment]
> probably has something to do with `cache` 🤔
> 
> does it work normally without it?

No.

CSR routing:

```
Error: Unknown error
    at castError (chunk-VFKAEII7.js?v=c4b37483:979:10)
    at chunk-VFKAEII7.js?v=c4b37483:364:79
```

SSR, crashes:

```
Error: oh no
```

**Comment by lxsmnsyc** [comment]
Okay thanks! for the _server, can you show me what does the response look like?

**Comment by marvin-j97** [comment]
> Okay thanks! for the _server, can you show me what does the response look like?

```
oh no
```
(literally)

**Comment by marvin-j97** [comment]
@lxsmnsyc Without using cache:

```json
{
  "statusCode": 500,
  "stack": []
}
```

**Comment by lxsmnsyc** [comment]
Just realized that this is the cause of the issue

https://github.com/solidjs/solid-start/blob/f787f2b6d6bea386929db180574e60c321173824/packages/start/config/server-handler.ts#L171

it was not following the expected format for the deserializer. Will fix.
