### ISSUE TITLE
[Bug?]: Hydration error on new project

### ISSUE THREAD

**Issue by gaearon** [solidjs/solid-start#1332]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

```
npm init solid@latest
```

- bare
- SSR: yes
- TS: no

Result:

<img width="1250" alt="Screenshot 2024-02-14 at 11 13 54" src="https://github.com/solidjs/solid-start/assets/810438/5706f01b-48d6-4e52-a4ca-e659eb746a11">

### Expected behavior 🤔

No mismatch in a fresh project

### Steps to reproduce 🕹

See above

### Context 🔦

Creating a project

### Your environment 🌎

```shell
Node 18.19
macOS
```

**Comment by emogua** [comment]
I got the same error

**Comment by zachlankton** [comment]
Ah, yep, this is happening for me with new projects now too.  Something pushed recently? I've tried rolling the version back in package.json, but that didn't work.

However if I copy this https://github.com/zachlankton/playing-with-server-components/blob/main/solidjs/package-lock.json lock file into the project and re-run `npm install` it works.

There are a few older dependencies in that lock file.

**Comment by AlbertSabate** [comment]
I could narrow it down. The issue started from the bump of solid-refresh from v0.6.3 to v0.7.0.

Temporal fix:
```
"pnpm": {
    "overrides": {
      "solid-refresh": "0.6.3"
    }
  }
```

You guys can share if doing this fixes your hydration issue. It will be easier to find the root cause.

**Comment by lxsmnsyc** [comment]
temporary fix for now is to set the resolution for solid-refresh to 0.6.3

I still yet have to test the new refresh in Start, but things got a little unexpected domino effect.

**Comment by ryansolid** [comment]
Vite Plugin Solid did an update that grabbed the latest Solid Refresh that introduces a new granular HMR stragety. The range in Solid Start is only locked to the nearest major in Start and it broke everything. I'm going to set the range to minor in Start and we can test the new Vite plugin. Sorry for the inconvenience.

**Comment by elite174** [comment]
The same thing happens with
```
    "@solidjs/router": "0.12.4",
    "@solidjs/start": "0.5.10",
    "solid-js": "1.8.15",
    "vinxi": "0.3.3"
```

Any updates?

**Comment by elite174** [comment]
UPDATE: fixed this with using `Suspense` in `app.tsx`

**Comment by ryansolid** [comment]
We are still testing the new Refresh plugin I'm going to consider this one closed because we already reverted the broken build. We will worry about the new Refresh plugin when it is ready.
