### ISSUE TITLE
[Bug?]: page content gets duplicated when changing source code

### ISSUE THREAD

**Issue by sina-salahshour** [solidjs/solid-start#1333]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I created a solid project with pnpm create solid, selected the `bare` version with no `ssr`.
launched the dev  mode, when i change `app.tsx`, rendered content gets duplicated without even updating changes.

### Expected behavior 🤔

update the rendered content to match the source code.

### Steps to reproduce 🕹

Steps:

1. pnpm create solid
2. select bare
3. no ssr
4. launch dev mode and open a browser
5. change inside `h1` tag on `app.tsx`

### Your environment 🌎

```shell
System:
  OS: Linux 6.6.5.16.realtime1-3-rt Arch
  CPU: (12) x86_64
Binaries:
  Node: 20.5.1
  pnpm: 8.12.2
npmPackages:
  @solidjs/start: ^0.5.6
  solid-js: ^1.8.14
  vinxi: ^0.2.1
```

**Comment by ryansolid** [comment]
I've locked the Vite plugin to minor version starting in 0.5.7. You can update to that for now until it is properly tested with SolidStart.

**Comment by sina-salahshour** [comment]
Ok, thanks for your time 🙏🏻

**Comment by ryansolid** [comment]
Sorry about the confusion.. I also reverted the Vite plugin. The change impacted too many projects.

**Comment by ryansolid** [comment]
We are still testing the new refresh issue. Since it was reverted and this was "fixed" we will address it when the new one is released if it shows up.
