### ISSUE TITLE
[Bug?]: Can't import createPlugin from seroval when deploying to render.com

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-start#1338]
When deploying to Node 20 on Render.com I get this

```
INFO┌────────────────────────────────────────┐
INFO│ ⚙  Preparing app for node-server...    │
INFO└────────────────────────────────────────┘
INFO[success] [vinxi] Generated public .output/public
INFO[info] [vinxi] Initializing prerenderer
ERROR[error] The requested module 'file:///opt/render/project/src/node_modules/seroval/dist/esm/production/index.mjs' does not provide an export named 'createPlugin'
INFO  import { createPlugin, createStream, fromJSON, crossSerializeStream, getCrossReferenceHeader } from 'node_modules/seroval/dist/esm/production/index.mjs';
INFO  ^^^^^^^^^^^^
INFO  SyntaxError: The requested module 'node_modules/seroval/dist/esm/production/index.mjs' does not provide an export named 'createPlugin'
INFO  at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
INFO  at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
INFO  at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
INFO  at async prerender (node_modules/.pnpm/nitropack@2.8.1/node_modules/nitropack/dist/shared/nitro.0a84349b.mjs:56:26)
INFO  at async createBuild (node_modules/.pnpm/vinxi@0.2.1_preact@10.19.5/node_modules/vinxi/lib/build.js:310:2)
INFO  at async Object.run (node_modules/.pnpm/vinxi@0.2.1_preact@10.19.5/node_modules/vinxi/bin/cli.mjs:206:5)
INFO  at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:316:16)
INFO  at async runCommand (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:307:11)
INFO  at async runMain (node_modules/.pnpm/citty@0.1.6/node_modules/citty/dist/index.mjs:445:7) 
INFO
ERROR[error] The requested module 'file:///opt/render/project/src/node_modules/seroval/dist/esm/production/index.mjs' does not provide an export named 'createPlugin'
INFO
```

Everything works when I build and run locally.

My versions are:

    "@solidjs/meta": "^0.29.3",
    "@solidjs/router": "^0.12.3",
    "@solidjs/start": "^0.5.9",
    "solid-js": "^1.8.15",
    "vinxi": "0.2.1"

in .pnpm, i can see it's also `seroval@1.0.4`

### Steps to reproduce 🕹

It's a bit tricky to repro without a render.com deployment, as it works locally.

**Comment by birkskyum** [comment]
@lxsmnsyc , do you have any idea what might be going on here?

**Comment by lxsmnsyc** [comment]
Only way this could happen is if it's installing a version of seroval<1

**Comment by birkskyum** [comment]
It dawned on me that it's looking for seroval at:

`'file:///opt/render/project/src/node_modules/seroval/dist/esm/production/index.mjs'

and that due to pnpm it exists at

`'file:///opt/render/project/src/node_modules/.pnpm/seroval/dist/esm/production/index.mjs'

So I tried adding it to my package.json and that worked. It's just weird why that would be necessary when on localhost it's able to source seroval from within the `.pnpm` directory

**Comment by birkskyum** [comment]
It would appear to have been a deploy cache. I purged everything and tried again, and things worked without an explicit seroval installation
