### ISSUE TITLE
[Bug?]: Plugin types, typescript issues

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-start#1339]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I get this type of issues when using plugins.

<img width="644" alt="Screenshot 2024-02-18 at 13 09 14" src="https://github.com/solidjs/solid-start/assets/74932975/62b11a29-d710-4390-be2e-fec1483be420">

### Steps to reproduce 🕹

Can be reproduced by installing latest vite pwa and adding an empty VitePWA plugin in vite config.

**Comment by birkskyum** [comment]
The VitePWA returns a standard rollup Plugin:

`interface Plugin<A = any> extends rollup.Plugin<A> `

And the solid start expect a `PluginOption` defined in this convoluted way:

`export declare type PluginOption = Plugin_2 | false | null | undefined | PluginOption[] | Promise<Plugin_2 | false | null | undefined | PluginOption[]>;`

**Comment by ryansolid** [comment]
I think this is just fixed in the next version with the Vite 5 update.. I wasn't able to reproduce it at least on that branch.

I went back to main (Vite 4) and I see the Plugin_2 alias but it also isn't screaming red lines at me. So I don't know.

**Comment by birkskyum** [comment]
just checked, and I also can't repro it now.
