### ISSUE TITLE
[Bug?]: Options are displayed incorrectly when making a new project with CLI

### ISSUE THREAD

**Issue by elite174** [solidjs/solid-start#1345]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![image](https://github.com/solidjs/solid-start/assets/13636224/854a7b56-9e9f-4766-8a10-b1092a2925c4)

### Expected behavior 🤔

Options should be displayed correctly

### Steps to reproduce 🕹

Steps:

Make a new project with `pnpm create solid`

### Your environment 🌎

```shell
OS: Windows
```

**Comment by ryansolid** [comment]
I've went and created and issue in the appropriate repository.

**Comment by elite174** [comment]
Then, I guess, I can close this here.

**Comment by Tommypop2** [comment]
@elite174 I've pushed something that should fix it. If the issue persists, feel free to re-open the issue on the CLI repo.

Thanks for reporting :)
