### ISSUE TITLE
[Bug?]: Plugin typescript issues with UnoCSS

### ISSUE THREAD

**Issue by malekim** [solidjs/solid-start#1351]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

```
import { defineConfig } from "@solidjs/start/config"
import UnoCSS from "unocss/vite"

export default defineConfig({
  plugins: [
    UnoCSS()
  ]
})
```

The error:

```
TS2322: Type  Plugin<any>[]  is not assignable to type  PluginOption 
Type  Plugin<any>[]  is not assignable to type  PluginOption[] 
Type  Plugin<any>  is not assignable to type  PluginOption 
Type  Plugin<any>  is not assignable to type  Plugin_2 
Types of property  apply  are incompatible.
```

Previously, even with that error, UnoCSS was working fine. Currently, I see the error:

```
[vite] Error when evaluating SSR module /src/app.tsx: failed to import "virtual:uno.css"
```

Same error if I try to import just "uno.css".

### Expected behavior 🤔

Just working UnoCSS and VitePlugins.

### Steps to reproduce 🕹

Steps:

1. pnpm create solid
2. pnpm install unocss --save-dev
3. import 'import "virtual:uno.css"' in the .tsx

**Comment by malekim** [comment]
After changing the `vite.config.ts` and `app.config.ts` and updating vinxi to 0.3.6, unocss as a plugin still doesn't work and here is the error:

`TS2345: Argument of type  { plugins: Plugin<any>[][]; }  is not assignable to parameter of type  SolidStartInlineConfig 
Object literal may only specify known properties, and  plugins  does not exist in type  SolidStartInlineConfig`

Vinxi is very unstable, I feel fear with each update.

**Comment by marvin-j97** [comment]
> After changing the `vite.config.ts` and `app.config.ts` and updating vinxi to 0.3.6, unocss as a plugin still doesn't work and here is the error:
> 
> `TS2345: Argument of type  { plugins: Plugin<any>[][]; }  is not assignable to parameter of type  SolidStartInlineConfig  Object literal may only specify known properties, and  plugins  does not exist in type  SolidStartInlineConfig`
> 
> Vinxi is very unstable, I feel fear with each update.

For me, Uno works with 0.3.6.

You have to nest the `plugins` parameter into `vite`, see my config above.

The Typescript error is still there, but it also happens if you use Vite's `defineConfig`, so the types are not matching up. I think it's due to Vite 5 and Uno's types not lining up.

**Comment by malekim** [comment]
You're right, nesting the config worked for me. Thank you.

This is the solution:
`import { defineConfig } from "@solidjs/start/config";
import UnoCSS from "unocss/vite";

export default defineConfig({
  vite: {
    plugins: [UnoCSS()],
  }
});`
