### ISSUE TITLE
[Bug]: Starting a new solidStart application with npm produces an application that can't target Cloudflare Pages

### ISSUE THREAD

**Issue by dario-piotrowicz** [solidjs/solid-start#1357]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I run `npm create-solid@latest` the CLI produces an application that, when using the `cloudflare-pages` preset can't be deployed on Cloudflare Pages.

Trying to run the application via `wrangler pages dev` or deploy it via `wrangler pages deploy` produces the following error:
![Screenshot 2024-03-01 at 17 48 00](https://github.com/solidjs/solid-start/assets/61631103/5af8a13d-5a7f-4474-b863-e6f645e83e22)

PS: this seems to be a regression as this error was present before, fixed and now has come back, see: https://github.com/solidjs/solid-start/issues/1217

### Expected behavior 🤔

The generated application should be deployable to Cloudflare Pages.

### Steps to reproduce 🕹

Steps:

1. run `npx create-solid@latest`
2. choose to create a solid-start project
3. run `cd <your-solid-project>`
4. run `npm install`
5. run `SERVER_PRESET=cloudflare-pages npm run build`
  (instead of using `SERVER_PRESET` you can update the `app.config.(js/ts)` file accordingly)
6. run `npx wrangler pages dev dist/`
7. see the error in the terminal

<details>
<summary>Screenshots of my terminal when running the above steps</summary>

![solid1](https://github.com/solidjs/solid-start/assets/61631103/8ce4975f-3834-415a-923f-3bcf073fb92a)

![solid2](https://github.com/solidjs/solid-start/assets/61631103/a31f26f9-d78e-4d32-b48a-20c06434f96d)

![solid3](https://github.com/solidjs/solid-start/assets/61631103/b9b99e50-171c-4fb5-95cd-6b689248b05a)

</details>

### Context 🔦

> [!NOTE]
> this seems to only happen with `npm`, I did try `pnpm` and it didn't present the same issue

### Your environment 🌎

```shell
macOs Sonoma 14.3.1
npm: 9.5.1
node: 18.16.0
```

**Comment by ryansolid** [comment]
Yeah this has to do with package resolution I think. I locked the vinxi in the examples to fix a bug but not in start itself and it must not match up properly causing the issue. Now that I've unlocked again I'm hoping this is fixed..

**Comment by dario-piotrowicz** [comment]
@ryansolid I just tried creating a brand new solidStart app and the issue seems to be gone!

Thanks a bunch! ❤️ 

I'm closing the issue then 🙂👍
