### ISSUE TITLE
[Bug?]: I'm curious that the routesDir configuration has been lost for months. Don't maintainers use this framework?

### ISSUE THREAD

**Issue by 6643** [solidjs/solid-start#1359]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by lxsmnsyc** [comment]
Are you referring to this? https://github.com/solidjs/solid-start/blob/main/docs/routes/api/app-config.md#solidjsstartconfig

**Comment by 6643** [comment]
@lxsmnsyc 
The new project does not have this configuration option

**Comment by ryansolid** [comment]
Docs are a bit out of date. When we did the rewrite that option didn't survive. We could add it back if it makes sense. Although I guess this is an indicator that not many people use this option.

**Comment by ryansolid** [comment]
`routesDir` is back in 0.7.0
