### ISSUE TITLE
[Bug?]: `"use server"` doesn't always work

### ISSUE THREAD

**Issue by samualtnorman** [solidjs/solid-start#1360]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

`"use server"` has no effect under certain conditions

### Expected behavior 🤔

`"use server"` does what it's supposed to do

### Steps to reproduce 🕹

make a route with this
```js
import { createResource } from "solid-js"
import { isServer } from "solid-js/web"

const data = () => createResource(() => {
	"use server"
	console.log(isServer)
	return Math.random()
})

export default function Home() {
	const [ , { refetch } ] = data()

	setTimeout(() => refetch(), 1000)
	
	return ``
}
```
then open the route in a browser with the console open and after 1 second you'll see that `false` is logged in the browser console even though that's supposed to be server code

### Context 🔦

use `"use server"`

### Your environment 🌎

```shell
System:
	OS: NixOS 23.11.4516.e0da498ad77a (Tapir) x86_64
	CPU: 12th Gen Intel(R) Core(TM) i5-12500 (12) @ 5.90 GHz
Binaries:
	Node: 20.9.0 - /etc/profiles/per-user/samual/bin/node
	pnpm: 8.15.4 - /home/samual/.local/share/pnpm/pnpm
npmPackages:
	@solidjs/meta: 0.29.3
	@solidjs/router: 0.12.4
	@solidjs/start: 0.6.0
	solid-js: 1.8.15
	vinxi: 0.3.9
```

**Comment by lxsmnsyc** [comment]
I'm surprised that even worked given that `createResource` cannot be declared at module-level in SSR.

**Comment by samualtnorman** [comment]
it doesn't make a difference since it's not run until the component is run

**Comment by ryansolid** [comment]
Yeah it doesn't look like it handles double closures properly. First closure is fine but function in a function doesn't seem to transform.
