### ISSUE TITLE
[Bug?]: Unable to use HMR with docker local setup

### ISSUE THREAD

**Issue by jake-a-wood** [solidjs/solid-start#1364]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Pages load in dev mode fine. However, when I save changes, there is no hot reloading occurring. When I look in the log, it appears that an attempt to connect to `ws://localhost:<some-random-port-number>` and then when that fails, it attempts to continuously poll `http://localhost:<another-random-port-number>`. 

### Expected behavior 🤔

I should be able to configure a port for hot module reloading to use so I can resolve this issue. 

### Steps to reproduce 🕹

Steps:

1. Run `docker run --rm -it -v $PWD:/usr/src/app -w /usr/src/app  'oven/bun:latest' bunx create-solid` (you'll need docker) to start up a solid-start project.
2. Go with all the default values (solid-project, yes, basic, yes)
3. `cd` into the solid-project folder
4. Run `docker run --rm -it -v $PWD:/usr/src/app -w /usr/src/app 'oven/bun:latest' install`
5. Run `docker run --rm -it -v $PWD:/usr/src/app -w /usr/src/app -p 3000:3000  'oven/bun:latest' run dev`
6. View http://localhost:3000 and see the working application.
7. Change a value in `src/routes/index.tsx` (such as "Hello World!" to "Hello There!") and save.
8. See that the page does not update automatically and that a refresh is required to view.

### Context 🔦

I frequently utilize docker to handle my technical stack dependencies. I'm sure the dev command normally works fine if you're working on your host machine with the dependency installed locally, but in this situation I would like to keep my node runtime separate so I can swap out bun for something else should I see a reason to. 

I don't know if there's a way to configure the hot module reload port so that I can expose it to my host machine. If not, it'd be ideal to be able to so I can rely on hmr during development. Perhaps I've missed it in the documentation? 

### Your environment 🌎

```shell
System:
	OS: Windows 10 Pro within WSL
	CPU: Intel(R) Core(TM) i9-10850K
Binaries:
	Bun: 1.0.30
Packages:
	@solidjs/meta => ^0.29.2
	@solidjs/router => ^0.12.5
	@solidjs/start => ^0.6.1
	solid-js => ^1.8.15
	vinxi => ^0.3.9
```

**Comment by jake-a-wood** [comment]
Just adding on some of my troubleshooting research here. It looks like you can establish the port for HMR by editing the app.config.ts to look like so:

```ts
import { defineConfig } from "@solidjs/start/config"

export default defineConfig({
	vite: {
		// @ts-ignore
		server: {
			hmr: {
				clientPort: 4000
			}
		},
	}
})
```

I added the `@ts-ignore` because I'm being told by the typescript server here that the server property doesn't exist; part of the reason I wasn't able to find this up front. 

I've also added a port forward for 4000 in my docker command when running dev mode. 

This hasn't quite fixed my issue yet, however. The request is made to the expected port for HMR, but no response is getting returned for some reason.

**Comment by edivados** [comment]
The [type definition](https://github.com/nksaraf/vinxi/blob/618149b312423742b8fe592869181ce2aef77744/packages/vinxi/lib/vite-dev.d.ts#L40) in vinxi omits the server prop. `server.hmr` could be added back.

[`clientPort`](https://vitejs.dev/config/server-options#server-hmr) tells the client what port to connect to but doesn't change the port the hmr server is running on. 
Try this.

```ts
import { defineConfig } from '@solidjs/start/config';

export default defineConfig({
  vite({ router }) {
    if (router === 'client') {
      return {
        server: {
          hmr: {
            port: 4000,
          },
        },
      };
    }
    return {};
  },
});
```

**Comment by jake-a-wood** [comment]
> The [type definition](https://github.com/nksaraf/vinxi/blob/618149b312423742b8fe592869181ce2aef77744/packages/vinxi/lib/vite-dev.d.ts#L40) in vinxi omits the server prop. `server.hmr` could be added back.
> 
> [`clientPort`](https://vitejs.dev/config/server-options#server-hmr) tells the client what port to connect to but doesn't change the port the hmr server is running on. Try this.
> 
> ```ts
> import { defineConfig } from '@solidjs/start/config';
> 
> export default defineConfig({
>   vite({ router }) {
>     if (router === 'client') {
>       return {
>         server: {
>           hmr: {
>             port: 4000,
>           },
>         },
>       };
>     }
>     return {};
>   },
> });
> ```
> 
> Also don't forget to map the hmr port when creating the container.
> 
> ```
> -p 3000:3000 -p 4000:4000
> ```

This worked perfectly! Though I got a type error with the vite function, it worked nonetheless. 

I think you're right about not omitting the server property in the type definition if indeed we're meant to be able to override it like I am doing so here. 

I'll leave this open for discussion, but ultimately I'm good to go at the moment.

**Comment by ryansolid** [comment]
Awesome. These types come from Vinxi. It's hard to know all the settings to allow in `server` I imagine since some of them won't work. But I've received questions all week. I will add these back in the next release at least until this can be sorted.

**Comment by petercorrea** [comment]
@ryansolid Was this fixed? I had issues and the above solution worked.
