### ISSUE TITLE
[Bug?]: 0.7.0 - Could not resolve "#start/app"

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-start#1370]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Tried upgrading 0.7.0 and get this:

```sh
vinxi v0.3.10
vinxi starting dev server

  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

✘ [ERROR] Could not resolve "#start/app"

    node_modules/.pnpm/@solidjs+start@0.7.0_rollup@2.79.1_solid-js@1.8.15_vinxi@0.3.10_vite@5.1.5/node_modules/@solidjs/start/client/StartClient.tsx:3:16:
      3 │ import App from "#start/app";
        ╵                 ~~~~~~~~~~~~

  You can mark the path "#start/app" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle.
```

### Expected behavior 🤔

No error

### Steps to reproduce 🕹

I must admit that I don't see this when I run the examples, so i will debug more, but deleting node-modules etc. didn't solve it in my app.

**Comment by ryansolid** [comment]
When you say it works on the examples... do you mean in the repo? Or separately installed. I just installed the update in another project and seemed fine but the change might be that I have a dynamic import to `#start/app` now. Which fixes an issue, I hope it doesn't cause another.

**Comment by birkskyum** [comment]
The `create solid` didn't get the latest versions, so I ran the examples in the solid-start repo.

**Comment by edivados** [comment]
https://stackblitz.com/edit/solidjs-solid-start-bgpxtc?file=package.json

**Comment by birkskyum** [comment]
Thanks @edivados !

**Comment by ryansolid** [comment]
I think I figured it out.. but it is a bit weird. It has to do with SolidStart's client and server entries. They need to be .tsx/.jsx. I guess it is consistent with like the router.. otherwise Vite won't do downstream JSX transforms I guess.

**Comment by birkskyum** [comment]
Excellent, that did the trick!
