### ISSUE TITLE
[Bug?]: Properties set on `event.locals` in `middleware.ts` are missing from `getRequestEvent()!.locals`

### ISSUE THREAD

**Issue by asterikx** [solidjs/solid-start#1377]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Properties set on `event.locals` in `middleware.ts` are missing from `getRequestEvent()!.locals`.

### Expected behavior 🤔

Properties set on `event.locals` in `middleware.ts` are present on `getRequestEvent()!.locals`.

### Steps to reproduce 🕹

Reproduction link: https://stackblitz.com/edit/vitejs-vite-hgzy8d?file=src%2Froutes%2Findex.tsx

### Your environment 🌎

```shell
@solidjs/start@0.7.3
@solidjs/router@0.13.0
```

**Comment by ryansolid** [comment]
Thanks for reporting. We attempted to make a TS build and somehow that has been breaking a bunch of stuff.

**Comment by ryansolid** [comment]
And yet again this seems to be something that works perfectly fine in the repo but breaks outside of it.

**Comment by ryansolid** [comment]
Should be fixed in 0.7.4
