### ISSUE TITLE
how to use https on localhost

### ISSUE THREAD

**Issue by harxki** [solidjs/solid-start#139]
I want to use https on local, so i create key and cert with using mkcert. 
I rewrite vite.config.js as follows to use https on the local host, but an error occurred.

```tsx
export default defineConfig({
  plugins: [solid()],
  server: {
    https: {
      key: fs.readFileSync("./scripts/key.pem"),
      cert: fs.readFileSync("./scripts/cert.pem"),
    },
  },
});

// error
ERROR TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token [":method"]
```

Is it possible to develop using https in solid-start?

**Comment by holubond** [comment]
I solved a similar issue (in production, I didn't care about https for development) by using Nginx as a reverse proxy, which took care of https in cooperation with Certbot. It was for SvelteKit and NextJs apps tho, but I see no reason why it shouldn't work with SolidStart.

**Comment by AlexErrant** [comment]
I'm using https on localhost with solid-start: https://github.com/AlexErrant/Pentive/blob/main/hub/vite.config.ts

To be clear - I'm using `pentive.local` in my mkcert and modified my hosts file to have that point to `127.0.0.1`: https://github.com/AlexErrant/Pentive/blob/main/design-decisions/run-locally.md#2-update-your-hosts-file

**Comment by shareable-vision** [comment]
Use 'vite-plugin-mkcert' in vite.config.js:

```js
import { defineConfig } from "vite";
import mkcert from 'vite-plugin-mkcert'
const secureLocalhost = true
export default defineConfig({
   server: {
      https: secureLocalhost
   },
   plugins: [
      secureLocalhost && mkcert(),
      //... other plugins
   ]
})
```

**Comment by apatrida** [comment]
Note, this is likely no longer valid for Solid-Start 0.4.x or newer, and would require something different when in dev mode.
