### ISSUE TITLE
[Bug?]:  Creating a new Solid Start using Bun throws an error

### ISSUE THREAD

**Issue by ubmit** [solidjs/solid-start#1391]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Running `bunx create solid` throws the following error:

`error: could not determine executable to run for package create`

Using `pnpm dlx` works just fine.

### Expected behavior 🤔

Expected the project to be created.

### Steps to reproduce 🕹

Steps:

1. Run `bunx create solid`

### Your environment 🌎

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 308.13 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - ~/.asdf/installs/nodejs/20.8.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.10.2 - /opt/homebrew/bin/pnpm
    bun: 1.0.15 - /opt/homebrew/bin/bun
  Managers:
    Cargo: 1.72.1 - /opt/homebrew/bin/cargo
    Homebrew: 4.2.12 - /opt/homebrew/bin/brew
    pip3: 22.2.2 - ~/.pyenv/shims/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
```

**Comment by ryansolid** [comment]
My understanding is there is a difference between `bunx create solid` and `bun create solid`. That the latter is what should be run. But I admit I don't know enough about this. 

The CLI is maintained here: https://github.com/solidjs-community/solid-cli. I'd transfer the issue but it is outside of our immediate org.

**Comment by ryansolid** [comment]
Ok got the answer:

<img width="734" alt="Screenshot 2024-03-15 at 10 33 17 AM" src="https://github.com/solidjs/solid-start/assets/2768267/8040263b-4eee-47a1-b748-71131010ef71">

**Comment by ubmit** [comment]
Thanks @ryansolid!
