### ISSUE TITLE
[Bug?]: Hydration Mismatch when using `children`

### ISSUE THREAD

**Issue by doeixd** [solidjs/solid-start#1392]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hello, I am getting a hydration mismatch error when attempting the following in ssr mode :

```tsx
import { children } from "solid-js";

export default function App() {
  return (
    <Holder>
      <h2> Wont show </h2>
    </Holder>
  );
}

function Holder(props) {
  const _kids = children(() => props.children);
  return <h2> Will Show </h2>;
}

```

This could entirely be my misunderstanding. Please let me know 

here is the error: 

![image](https://github.com/solidjs/solid-start/assets/13461122/b7123fc5-aa28-4767-9268-f820c2d33e2b)

### Expected behavior 🤔

I would expect the return value of `Holder` to render as normal

### Steps to reproduce 🕹

[Reproduction Link](https://codesandbox.io/p/devbox/peaceful-browser-k2frpy?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt5rte0d00063j6ozaygsf23%2522%252C%2522sizes%2522%253A%255B64.09253425907242%252C35.90746574092758%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt5rte0d00023j6o4d82d84g%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt5rte0d00043j6okhwlml0i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt5rte0d00053j6o0ucgm672%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt5rte0d00023j6o4d82d84g%2522%253A%257B%2522id%2522%253A%2522clt5rte0d00023j6o4d82d84g%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clt5rte0d00053j6o0ucgm672%2522%253A%257B%2522id%2522%253A%2522clt5rte0d00053j6o0ucgm672%2522%252C%2522activeTabId%2522%253A%2522cltrkio9a01ry3j6pos5k5wck%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cltrkh07301dt3j6pbvlgexe8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cltrkio9a01ry3j6pos5k5wck%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clt5rte0d00043j6okhwlml0i%2522%253A%257B%2522id%2522%253A%2522clt5rte0d00043j6okhwlml0i%2522%252C%2522activeTabId%2522%253A%2522cltrklvzu01ye3j6pd0b8fmgw%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cltrkgut6018p3j6pl3xhoqb1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522cltrklvzu01ye3j6pd0b8fmgw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltrklw47001bdci0aua46dts%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Context 🔦

I am attempting to have the children of a component add values to a context item, then render the result with that context.

Similar to:
```tsx

function List () {
  let context = createMutable({
    items: []
  })

  let _renderedChildren = children(() => ( 
    <ListContext.Provider value={context}>
      {localProps.children}
    </ListContext.Provider>
   ))

  return (
    <For each={context.items}>
      {(item) => <div>{item.name}</div>}
    </For>
  )
}
```

**Comment by ryansolid** [comment]
There is an existing issue in Solid related to this. It has to do with the eager resolution of computeds. https://github.com/solidjs/solid/issues/1977

**Comment by doeixd** [comment]
Thanks for letting me know about the issue. I probably should've checked the Solid repo first.

Thanks for the feedback! Maybe there is a better way to accomplish my goals?

[Here is an example of what I'm trying to do](https://codesandbox.io/p/devbox/solid-context-virtual-lffk2l?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltrqc21q00083d6k3xln1prl%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltrqc21o00023d6kl9kpym2l%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltrqc21p00053d6kdbiif3xx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltrqc21p00073d6k9sqnb0oq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltrqc21o00023d6kl9kpym2l%2522%253A%257B%2522id%2522%253A%2522cltrqc21o00023d6kl9kpym2l%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltrqc21p00073d6k9sqnb0oq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltrqc21p00063d6kgkrfnic5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltrqc21p00073d6k9sqnb0oq%2522%252C%2522activeTabId%2522%253A%2522cltrqc21p00063d6kgkrfnic5%2522%257D%252C%2522cltrqc21p00053d6kdbiif3xx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltrqc21p00033d6knrxi8g7b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522cltrqc21p00043d6kosf4zd8g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltomd0r30013dch79mou3twi%2522%257D%255D%252C%2522id%2522%253A%2522cltrqc21p00053d6kdbiif3xx%2522%252C%2522activeTabId%2522%253A%2522cltrqc21p00033d6knrxi8g7b%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

_renderChildren is not used, it is just there to access the `props.children`, and allow those children to have access to the list context. context.items would be set by the children who use that context.

**Comment by ryansolid** [comment]
If `_renderedChildren` is never read then this is quite a different scenario than I was thinking. You just want to run those components in that context and have them write to your context. This sort of a synchronous effect. It probably could just be run top level without a wrapper. That being said I imagine the problem is probably downstream. Ie real DOM elements are getting rendered during that pass whereas really you want to pass back configuration. It's hard for me to see all the layers.

**Comment by ryansolid** [comment]
I don't know what to do with this one, as the behavior is by design but I don't have enough information to offer a better solution. If you want to chat about this more maybe flag me in a discussion or on discord.
