### ISSUE TITLE
Enable typescript strict mode

### ISSUE THREAD

**Issue by modderme123** [solidjs/solid-start#140]
There are a couple of types that have an optional undefined, enabling strict mode will help with handling them (also it will make sure that users of solid-start with strict mode enabled don't get those errors in their project)

**Comment by nksaraf** [comment]
Could you point out the specific ones so we could deal with them? Or make a PR?

**Comment by modderme123** [comment]
Sure, I'll make a PR to use Typescript's `?.` operator

**Comment by ryansolid** [comment]
I guess we are in good versions of node to do that. I have been avoiding `?.` and `??` as it tends to break some tooling.

**Comment by modderme123** [comment]
Update: when I enable strict mode [here](https://github.com/solidjs/solid-start/blob/main/packages/start/tsconfig.json], I get ~300 errors from `tsc --noEmit`. I've cut that down to about 56 that I'm manually working through

**Comment by davycoe** [comment]
the following also produces errors in my tsconfig:
```
"strictNullChecks": true,
"noImplicitAny": true,
"noImplicitReturns": true,
"noUnusedLocals": true,
"noUnusedParameters": true,
"strict": true
```

**Comment by nksaraf** [comment]
@modderme123 could you make a PR for what you have! I can work on top to get it to completion for strict mode

**Comment by modderme123** [comment]
Just got back to this and after rebasing, it looks like you've got most of the initial errors. Only 2 files had any changes that still were valid for the current codebase and they'd be trivial to recreate
