### ISSUE TITLE
SSR with `<Suspense/>` doesn't work anymore as it used to

### ISSUE THREAD

**Issue by BierDav** [solidjs/solid-start#1402]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The current behavior when using Suspense in ssr in `0.7.6` is that it renders the content in a `<template/>`

Let's look at this example I provided: [https://codesandbox.io/p/github/BierDav/solid-start-ssr-bug/master](https://codesandbox.io/p/github/BierDav/solid-start-ssr-bug/master)

When we look at the working example at the network tab and preview the initial html provided we see everything looks fine:
![image](https://github.com/solidjs/solid-start/assets/46626041/325b0fad-0b55-4b8c-971b-604f98bc265e)
The list is rendered and the style is applied

But on the `not-working` page, which uses a `createResource`, everything in the suspense is seamingly missing:
![image](https://github.com/solidjs/solid-start/assets/46626041/73be4fcb-27c3-41c5-8e0f-5d43c37437bd)

If we look closely than we see that the content of the Suspense can be found in the initial html, but it is contained in a template which makes it invisible in the preview and also in the initial view the user gets:
![image](https://github.com/solidjs/solid-start/assets/46626041/0f3ad38f-08fe-469b-a2dc-eb230a4ddeaa)

This is a different behaviour than in `0.3.10` from which I recently upgraded. Because in this version the result of Suspense is directly rendered in the body and this is what I expect because doing it the **new** way has two major disadvatages:
1. The user again has to wait till the javascript kicks in, which kills all the advantage of ssr
2. There are issues with methods like `useAssets` which makes libraries that heavily rely on this as for example `suid` unusable

**Note:**
I can be that the issue with `useAssets` in a `<For/>` is unrelated, but I was not sure and didn't want to make a second example. As you can see in the example, all the coffee entries are full width, because the css applied using `useAssets` which should make them 200px wide doesn't work in a `<For/>`

### Expected behavior 🤔

I want that ssr works again as it already was, that it renders directly into the body and that `useAssets` does work even when used in a `<For/>`

### Context 🔦

I want to point out that everything worked fine in `0.3.10`, but they broke in the recent versions. I would really love a quick fix for that, because I have already ploughed up our whole codebase.

**Comment by BierDav** [comment]
But when it is a streaming resource why is the result directly in the initial response?

**Comment by lxsmnsyc** [comment]
> Thanks for your answer, I understand that useAssets is only server-only, but that's quite inconvenient when useAssets doesn't work for ssr that is streamed. Is there a solution to this?

Like I mentioned, you add `deferStream: true` to the resource that you want to "await" before sending the initial HTML.

> Btw. what is actually streamed, the hydratable html or only the data?
SSR sends first the initial HTML. If any Suspense boundary is triggered and the resource that triggered it is a stremaing resource, the initial HTML only includes the `fallback` UI. When the resource resolves, the data is streamed to the client, alongside the "success" UI of the Suspense (this is the `template` element you are seeing).

**Comment by BierDav** [comment]
> When the resource resolves, the data is streamed to the client, alongside the "success" UI of the Suspense (this is the template element you are seeing).

Uhh ok that makes sense

> If you're referring to the snippet combined with createResource, it still won't work,

No I am referring to the snippet without createResource, which should in theory work, but it doesn't

**Comment by lxsmnsyc** [comment]
> Additionally what I don't understand is why not already inline the template when the "success" page is already available?

The thing is, it isn't. The same concept applies to how this doesn't work:

```js
let example = 'Loading';

Promise.resolve().then(() => {
  example = 'Success';
});

console.log(example); // Loading
```

> I mean I can clearly see that in the template that is contained in the initial html the data is already filled in. I don't know if that was excatly the behaviour, but I would love to see a hybrid solution

Browsers can batch chunks but the server doesn't know this and cannot make this kind of assumption.

> I don't know if that was excatly the behaviour, but I would love to see a hybrid solution. So that all data that is responed before the initial html is sent is instantly inlined so that the user never sees the loading fallback and if the data fetching takes longer than ssr than we dynamically switch to streaming.

Which is what I recommended: `deferStream: true`

**Comment by lxsmnsyc** [comment]
> But why does the browser even render the html page before it even has the whole picture, elements on the end of the document could change the whole page?

The whole concept of streaming is so that the browser can immediately show the page as soon as possible. Streaming utilizes that fact and then sends the lazier chunks after it. Solid's async SSR is the complete opposite of this: it waits for everything before sending the entire HTML.

**Comment by BierDav** [comment]
Thanks for your detailed explanation. But what about `useAssets` in streaming mode?

**Comment by ryansolid** [comment]
If you want the 0.3.10 async default you can just pass it in to createHandler. We default to streaming now but you can have the previous behavior.

```js
createHandler(() => <StartServer />, { mode: "async" })
```

**Comment by BierDav** [comment]
Ahh thanks for your info, the thing with the `async` mode I have also already found out, but thanks for making it clear.

I will close the issue now, because everything is clear now and this has been more a discussion than an issue.

Have a nice day, @lxsmnsyc and @ryansolid
