### ISSUE TITLE
[Bug?]: HMR briefly updates before reverting in docker container with windows host.

### ISSUE THREAD

**Issue by NathanSMB** [solidjs/solid-start#1407]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I make a change to my source code, the web page updates briefly to reflect my changes before reverting.

### Expected behavior 🤔

When I make a change to my source code, I expect the web page to update and be persistent.

### Steps to reproduce 🕹

I've created a minimal setup to reproduce this bug. 

https://github.com/NathanSMB/devcontainer-bug

Steps:

1. Have a windows machine with docker setup and the dev containers extension in VS Code
2. Clone the repo above and open it from the container using the extension
3. Got to localhost:3000 in your browser
4. Make a change to the source code and observe the browser.

Note: There is a gif in the above repo that shows the bug in action.

### Context 🔦

I'm trying to setup a devcontainer environment that allows for quick onboarding. I want it to be as simple as building and connecting to the containerized environment and then changes happen automatically. I feel like I'm this 🤏 close to getting it working.

### Your environment 🌎

```shell
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3296

Docker Desktop Version: 4.28.0 (139021)
Docker Engine Version: 25.0.3
Docker Compose Version: Compose: v2.24.6-desktop.1

Docker desktop is using the WSL2 based engine.

Note: I have confirmed this does not happen from my m2 Macbook so it seems to be Windows specific.
```

**Comment by edivados** [comment]
Adding `usePolling` to all routers should fix this. 

The page reload (ssr) returns stale data. Looks like the ssr router never gets the fs event but the client build is updated correctly. When navigating between routes it shows the changes.

```js
import { defineConfig } from "@solidjs/start/config";

export default defineConfig({
    vite ({ router }) {
        if (router === "client") {
            return {
                server: {
                    hmr: {
                        port: 4000,
                    },
                    watch: {
                        usePolling: true,
                    }
                },
            };
        }
        return {
            server: {
                watch: {
                    usePolling: true,
                }
            }
        };
    }
});
```

**Comment by NathanSMB** [comment]
Thank you! I tried that and it worked.
