### ISSUE TITLE
[Bug?] The response ignores multi-valued headers

### ISSUE THREAD

**Issue by FlatMapIO** [solidjs/solid-start#1415]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Regardless of the form used to set a multi-value header in the response, the client ultimately receives only a single-valued header. Currently, the issue can only be circumvented by using vinxi/http's setCookie(event.nativeEvent) method. 

### Steps to reproduce 🕹

Steps:
```tsx
// invalid

h = new Headers()
h.append('Set-Cookie', 'k1=v1')
h.append('Set-Cookie', 'k2=v2')
return json({}, {headers: h})

// invalid
return json({}, { headers: [ ['Set-Cookie', 'k1=v1'],  ['Set-Cookie', 'k2=v2'] ] })


// valid
setCookie(event.nativeEvent,'k1', 'v1')
setCookie(event.nativeEvent,'k2', 'v2')
```

**Comment by ryansolid** [comment]
Thanks. I was hoping merging into the H3Event would just work but we need logic it seems.
