### ISSUE TITLE
[Bug?]: Erroneous 404s when rapidly switching routes

### ISSUE THREAD

**Issue by nordfjord** [solidjs/solid-start#1419]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When rapidly clicking links on the solid start docs they sometimes 404

### Expected behavior 🤔

They should not 404

### Steps to reproduce 🕹

https://github.com/solidjs/solid-start/assets/3721521/2726b88d-e20d-45cc-a451-806c169878aa

### Context 🔦

Not sure if this is the right repo to report this to, but found this issue by accident on the docs and am assuming they're a solid start app

### Your environment 🌎

```shell
- Firefox
- Linux
```

**Comment by hardywu** [comment]
better try with all chrome plugins disabled and check if any ouputs in the DevTool console

**Comment by heilwood** [comment]
I have similar issues with routing on my app, just randomly not working

https://github.com/solidjs/solid-start/assets/27227165/d240b592-3cc1-42d7-a8f5-5140bb3cd642

![image](https://github.com/solidjs/solid-start/assets/27227165/2643ea5a-c8ec-4c1f-8f7a-76b39b39587a)
![image](https://github.com/solidjs/solid-start/assets/27227165/e74cbb96-4b68-456b-9406-e48177163ad1)
![image](https://github.com/solidjs/solid-start/assets/27227165/cdbee84d-afb5-42d5-b0f7-bf4a5ea7f966)

**Comment by hardywu** [comment]
@heilwood  check the console logs. If it's similar to #1408, try the new merged PR #1418 .

**Comment by heilwood** [comment]
for me looks like fixed

**Comment by ryansolid** [comment]
@heilwood thanks for the update. I wasn't able to get this on the docs site so closing for now. But if it surfaces again would appreciate the issue.
