### ISSUE TITLE
with-auth example not working

### ISSUE THREAD

**Issue by rishi-raj-jain** [solidjs/solid-start#142]
Steps to reproduce
- Clone the with-auth example
- `yarn install`
- `yarn run dev`
- The version I chose for solid-start was "0.1.0-y.0"
<img width="1141" alt="Screenshot 2022-06-21 at 8 08 00 AM" src="https://user-images.githubusercontent.com/46300090/174704573-53624e9d-3bfb-40a4-9a4b-a31ffa010d37.png">

**Comment by ghalle** [comment]
That version is from over a year ago, the latest version right now is `0.1.0-alpha.89`

**Comment by rishi-raj-jain** [comment]
Ah okay, thanks for the quick response. I'll try that right away.

**Comment by rishi-raj-jain** [comment]
Still this doesn't work.
Steps to reproduce remain the same, the version I chose these time were 0.1.0-alpha.89 for solid-start and 0.1.0-alpha.82 for solid-start-node (didn't see 0.1.0-alpha.89 for solid-start-node).

As soon as I visit localhost:3000, facing the following error:
<img width="1440" alt="Screenshot 2022-06-21 at 9 01 36 AM" src="https://user-images.githubusercontent.com/46300090/174710468-2582feb8-bd92-4b38-822a-fc4ab2b57605.png">

**Comment by ghalle** [comment]
You'll want to also clone the `withAuth` example at the same version
https://github.com/solidjs/solid-start/tree/v0.1.0-alpha.89/examples/with-auth

There's some unpublished changes in the main branch.

**Comment by rishi-raj-jain** [comment]
Thanks, trying this.

**Comment by rishi-raj-jain** [comment]
Yup, that worked!
