### ISSUE TITLE
How to create a SSG site?

### ISSUE THREAD

**Issue by andares** [solidjs/solid-start#1425]
I noticed on the homepage documentation that it mentions support for creating an SSG site. As I understand it, this feature allows a project to be compiled into a purely static website. May I ask how to use this feature currently? I was unable to find relevant information in the documentation.

**Comment by birkskyum** [comment]
That is true. You can use the `static` preset. There is more information on the options here: https://nitro.unjs.io/config#prerender

For a production example of such a site, I've built one here that you can use as a reference for config: [live site](https://maplibre.org/maplibre-style-spec/) , [code](https://github.com/maplibre/maplibre-style-spec/tree/main/docs)

**Comment by birkskyum** [comment]
We use GitHub mainly for talking about bugs / changes to the libraries, but feel free to reach out in the SolidJS discord, where there is a helpful community, if you have more questions on usage.

**Comment by andares** [comment]
> That is true, you can build SSG and deploy to a static server. You can use the `static` preset. There is more information on the options here: https://nitro.unjs.io/config#prerender
> 
> For a production example of such a site, I've built one here that you can use as a reference for config: [live site](https://maplibre.org/maplibre-style-spec/) , [code](https://github.com/maplibre/maplibre-style-spec/tree/main/docs)

Thank you very much! I will check out the solution you provided. 😄

**Comment by andares** [comment]
Got it, it's work!

**Comment by arnfaldur** [comment]
I encountered the same issue. I was confused by this mentioned reference as it isn't a SSG solid start project.
https://github.com/maplibre/maplibre-style-spec/tree/85a63c49c471c534cbd1af3c02e075feb1e94f69/docs
Here is a link to the relevant code/commit, as they seem to have migrated away from a solid start SSG subproject.

**Comment by arnfaldur** [comment]
I have been a bit stumped on how to achieve this while migrating an older solid-start 0.3 project to the new API.
https://docs.solidjs.com/solid-start/reference/config/define-config#configuring-nitro
https://docs.solidjs.com/solid-start/building-your-application/route-prerendering
It took me longer than I'd hoped to find these two links but here they are. I'm posting them here in case anyone finds themselves in my wake.

**Comment by oddpxl** [comment]
Very useful - thank you - this got my SSG build going !
