### ISSUE TITLE
[Bug?]: No value attribute on CSR, but present in SSR

### ISSUE THREAD

**Issue by filipw01** [solidjs/solid-start#1453]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using number (any number, both 0 and 1 result in the same behavior) on client side navigation no value for `value` attribute is rendered, but on SSR it is working as expected resulting in "0" and "1" for the value

### Expected behavior 🤔

I expected both to work the same turning the number into string

### Steps to reproduce 🕹

[github link](https://github.com/filipw01/fiszki/tree/solid-bug-reproduction)
[stackblitz link](https://stackblitz.com/~/github.com/filipw01/fiszki)
<img width="433" alt="Screenshot 2024-04-20 at 22 50 12" src="https://github.com/solidjs/solid-start/assets/22986859/ca7d3269-2df6-4bf5-8dbf-ef1b526a5428">

1. open `solid-bug-reproduction` branch
2. open preview on localhost:3000
3. click on orange 0/0 (if you inspect the input element you will see value="0")
4. you should see nothing here page
5. navigate back
6. Inspect the element - orange 0/0 - input element will have value attribute with no value set

### Context 🔦

I'm writing an app and it was unexpected to fail because TS was alright with it

### Your environment 🌎

```shell
Darwin 23.4.0 Darwin Kernel Version 23.4.0: root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64


node 20.12.1
npm 10.5.0

 "@solidjs/start": "0.7.7",
```

**Comment by AirBorne04** [comment]
Hi @filipw01 ,
when opening your project, there are some issues due to your database usage, can you create a reproduction that is isolating the issue, maybe with mock data instead of live db?

**Comment by filipw01** [comment]
Are you sure you checked out the correct branch? Sadly I think there's no way to create a link directly to the branch with reproduction so you need to do that manually. 

Interestingly stackblitz doesn't show my branch with reproduction now 🤔 

Can you in stackblitz terminal do 
`git pull && git checkout solid-bug-reproduction && npm run dev` I think that should do it (checked just now)

**Comment by filipw01** [comment]
So this sounds more like solid bug, not solid-start, right? Let me open an issue there
