### ISSUE TITLE
[Bug?]: Typescript error in tsconfig.json for new projects created with pnpm.

### ISSUE THREAD

**Issue by HansT01** [solidjs/solid-start#1454]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![image](https://github.com/solidjs/solid-start/assets/73771314/78be00b7-6093-4f2a-b71a-3eadb4fc6df1)
```
Cannot find type definition file for 'vite/client'.
  The file is in the program because:
    Entry point of type library 'vite/client' specified in compilerOptions
```

### Expected behavior 🤔

No Typescript errors

### Steps to reproduce 🕹

Steps:

1. `pnpm create solid`
2. choose any template
3. navigate to project and `pnpm install`
4. restart TS server

### Context 🔦

This issue seems to have an easy fix, and it is to change the line in the tsconfig from:
`"types": ["vinxi/client", "vite/client"],`
to this:
`"types": ["vinxi/types/client"],`

This issue seems to only occur when using pnpm and not npm. I have not tested this on other machines.
I am rather new to the ecosystem. Please take the change with a grain of salt. 
I found the type from vinxi's documentation: https://vinxi.vercel.app/guide/aliases.html

**Comment by ryansolid** [comment]
fixed by #1455
