### ISSUE TITLE
[Bug?]: Frequently generate  app.config.timestamp_.js  files when i change app.config.js file

### ISSUE THREAD

**Issue by solid-component** [solidjs/solid-start#1460]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

1. pnpm dev
2. change app.config.js file
3. The app.config.timestamp_x.js file is generated frequently in the root directory

### Expected behavior 🤔

1. pnpm dev
2. change app.config.js file
3. Do not generate app.config files frequently in the root directory

**Comment by LiMao00** [comment]
> Hmm.. this has got to be a Vinxi/Vite thing. Most likely Vite. Not sure why it is happening but thanks for reporting.

The number is now 533, just a few times.
![Image](https://github.com/user-attachments/assets/fe908754-6af7-465e-abc4-fb8aaff53c23)
