### ISSUE TITLE
[Bug?]: Dev server fails to start when installing with new pnpm lockfiles

### ISSUE THREAD

**Issue by HansT01** [solidjs/solid-start#1465]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Dev server fails with the following error:
```
vinxi v0.3.11
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '<PROJECT_PATH>\node_modules\.pnpm\@solidjs+start@1.0.0-rc.0_rollup@4.17.2_solid-js@1.8.17_vinxi@0.3.11_@types+node@20.12.8_iore_xyc5haahokuf7onqczdjnghlzm\node_modules\@vinxi\server-functions\plugin' imported from <PROJECT_PATH>\node_modules\.pnpm\@solidjs+start@1.0.0-rc.0_rollup@4.17.2_solid-js@1.8.17_vinxi@0.3.11_@types+node@20.12.8_iore_xyc5haahokuf7onqczdjnghlzm\node_modules\@solidjs\start\config\index.js
Did you mean to import "@vinxi/server-functions/plugin.js"?
    at finalizeResolution (node:internal/modules/esm/resolve:263:11)
    at moduleResolve (node:internal/modules/esm/resolve:908:10)
    at defaultResolve (node:internal/modules/esm/resolve:1131:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: '<PROJECT_PATH>/node_modules/.pnpm/@solidjs+start@1.0.0-rc.0_rollup@4.17.2_solid-js@1.8.17_vinxi@0.3.11_@types+node@20.12.8_iore_xyc5haahokuf7onqczdjnghlzm/node_modules/@vinxi/server-functions/plugin'
}
vinxi starting dev server
Terminate batch job (Y/N)?
```

An `app.config.timestamp_<TIMESTAMP>.js` file is created as a side effect.

![image](https://github.com/solidjs/solid-start/assets/73771314/cce76f49-40c5-4f68-a227-1faaa982b027)

### Expected behavior 🤔

No errors 

### Steps to reproduce 🕹

Steps:

1. `pnpm add -g pnpm@latest`
2. `pnpm create solid`
3. choose any template
4. navigate to project
5. `pnpm install`
6. `pnpm dev`

### Context 🔦

I had a repository with an older lockfile that got updated when I installed anything. The newer lockfile errors while the older one does not. In this example I've just updated the solidjs package from `1.8.16` to `1.8.17`. See the lockfile diff here:

https://github.com/HansT01/stock-evaluator/commit/7f459ebb6d250efff5d1c8996729dddacb98648d#r141586858

Issue could be related https://github.com/solidjs/solid-start/issues/1460

### Your environment 🌎

```shell
Windows 10 OS
pnpm 9.0.6
node 21.7.3
```

**Comment by ryansolid** [comment]
Hmm... I wonder if it is windows related. I used this an opportunity to upgrade to node 20 and update to the latest pnpm. And I did not hit the same issues. I removed the lockfile and the node_modules and tried again and still good.

I might need help from others to reproduce this.

**Comment by HansT01** [comment]
Upgrading from node v21.7.3 to 22 seemed to have fix the issue for me. Downgrading to node 20 also seems to fix the issue.

**Comment by HansT01** [comment]
Issue probably isn't worth investigating further.
