### ISSUE TITLE
[Bug?]: RouteDefinition throw redirect not working

### ISSUE THREAD

**Issue by 0-don** [solidjs/solid-start#1471]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

the load method doesnt redirect to the thrown page
https://stackblitz.com/~/github.com/0-don/solid-project?file=src/routes/index.tsx

```tsx
import { Title } from "@solidjs/meta";
import { RouteDefinition, redirect } from "@solidjs/router";
import Counter from "~/components/Counter";

export const route = {
  load() {
    throw redirect("/about");
  },
} satisfies RouteDefinition;

export default function Home() {
  return (
    <main>
      <Title>Hello World</Title>
      <h1>Hello world!</h1>
      <Counter />
      <p>
        Visit{" "}
        <a href="https://start.solidjs.com" target="_blank">
          start.solidjs.com
        </a>{" "}
        to learn how to build SolidStart apps.
      </p>
    </main>
  );
}
```

**Comment by ryansolid** [comment]
This isn't the API. `redirect` works within `cache` and `action` functions which are wrappers around Solid Router's data APIs. If you want to navigate inside the load function `useNavigate`.

It would be interesting to try to marry these together I suppose. `load` could have additional logic in it. But generally it isn't the load function doing the redirect as much as where the data is being used on the page.
