### ISSUE TITLE
[Bug?]:Error: Hydration Mismatch. Unable to find DOM nodes for hydration key: 0-0-0-0-0-0-0-0-1-0-0-0-1-0-0-0-0-0-1

### ISSUE THREAD

**Issue by KunalSin9h** [solidjs/solid-start#1473]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Whenever i create a route with folders like `routes/admin/dash.tsx` this error happens when accessing that page. 

### Expected behavior 🤔

The page should render as normal.

### Steps to reproduce 🕹

Steps:

1. Create a route with folder

**Comment by KunalSin9h** [comment]
![image](https://github.com/solidjs/solid-start/assets/82411321/5fa4f179-df6f-4b5e-b7d5-9a86250b64d9)

**Comment by ryansolid** [comment]
Does this happen after restarting the dev server. There is a known bug: https://github.com/solidjs/solid-start/issues/1286

**Comment by KunalSin9h** [comment]
@ryansolid tested also with v1, when adding new route this error happens, but after shutting down vite and restart is working.

**Comment by FlatMapIO** [comment]
Based on my experience, encountering such issues is usually due to:
- Adding/removing routes
- A component that might be a client-only component not being wrapped with the `clientOnly` wrapper, which might require an elimination process to identify it 😭

Generally, restarting the development server resolves the issue. Sometimes, it's also necessary to delete the `node_modules/.vinxi` directory.

**Comment by KunalSin9h** [comment]
working only when removing `node_modules/.vinxi` package.

**Comment by sckoorp** [comment]
same issue happened to me when creating `routes/product/[id].tsx`, even after restarting the dev server, the problem persists, but deleting `node_modules/.vinxi` resolves it.

**Comment by anurag-roy** [comment]
A hard reload on the browser (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>) seems to solve it for me

**Comment by klequis** [comment]
I have had this problem as well. The problem goes away when I disable the browser cache.

**Comment by juanUrdaneta** [comment]
removing node_modules/.vinxi or doing a hard reload `cmd + shift + R` solves the issue as well.

**Comment by cs-clarence** [comment]
same problem

**Comment by Suman196pokhrel** [comment]
I am facing the same issue. 

**Temporary Solution:**
Rather than deleting the .vixin from node_modules, I disabled caching from the developer tools -> Network tab. But it is pretty offputting when trying out a new framework.

**Comment by mdynnl** [comment]
This can be closed after vixi minor version is released.

**Comment by Sleepful** [comment]
Weirdest error message, but I got this for nesting <a> tags in the JSX 🤦

**Comment by klequis** [comment]
If you are still struggling with this I suggest you open a new issue with a reproduction of the problem
