### ISSUE TITLE
[Bug?]:  Streaming/ async generator doesn't work

### ISSUE THREAD

**Issue by ducan-ne** [solidjs/solid-start#1477]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

It shows a error when I consume data from a server function		

### Expected behavior 🤔

Should work as it was implemented in seroval

### Steps to reproduce 🕹

Steps:

I've made the reproduction here 
https://github.com/ducan-ne/solid-async-generator-reproduction/blob/main/src/actions.tsx
https://github.com/ducan-ne/solid-async-generator-reproduction/blob/main/src/components/Counter.tsx	

### Context 🔦

In case it's needed: node 20, macos

### Your environment 🌎

```shell
node 20, macos
```

**Comment by ducan-ne** [comment]
It's not bug from sevoral, I've confirmed it here https://github.com/lxsmnsyc/seroval/issues/31

**Comment by lxsmnsyc** [comment]
I've re-tested this over again, seems like a seroval thing, but let's just keep the tracking issue here for better visibility.

**Comment by ryansolid** [comment]
> I've re-tested this over again, seems like a seroval thing specifically the runtime for the async iterator, but let's just keep the tracking issue here for better visibility.

Not quite following. Is it on the seroval side?

**Comment by lxsmnsyc** [comment]
@ryansolid Yep, it was a one character mistake on the stream constructor. It is fixed now in 1.0.7.

This didn't really impact anything as the issue only happens when there's an immediate, single-push on the stream (stream thinks that the the value is the only thing in the buffer and ends immediately). For any other kind of delayed pushes, or immediate set of push-and-close, the stream normally works.

**Comment by ducan-ne** [comment]
Confirmed, the issue is now fixed.
![CleanShot 2024-05-16 at 15 33 22@2x](https://github.com/solidjs/solid-start/assets/16853175/74f18f3b-7403-419c-b3ab-9d45496ebd2d)

```
export const getABC = async function* () {
  "use server"
  yield { abc: true }

  await new Promise((resolve) => setTimeout(resolve, 5000))
  yield { xyz: true }
}
```

**Comment by ryansolid** [comment]
Thanks.
