### ISSUE TITLE
[Bug?]: Something went wrong

### ISSUE THREAD

**Issue by LiMao00** [solidjs/solid-start#1494]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![image](https://github.com/solidjs/solid-start/assets/99939885/74a40cfe-139c-4cbb-8695-5bb83e2c2098)
maybe a bug

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by blkcor** [comment]
I encounter the error too, and I am located in china mainland.Maybe the network issue like nuxt... ☹️
