### ISSUE TITLE
Support Nested Routing and Manifests

### ISSUE THREAD

**Issue by ryansolid** [solidjs/solid-start#15]
Solid App Router supports nested routing. They do so by naming a file the same name as the folder. In so it acts as the parent. I haven't added that yet.

In addition we need to make sure that manifest lookup for preload works as well.

**Comment by jceb** [comment]
To improve the status quo, this line https://github.com/solidjs/solid-start/blob/main/packages/start/components/Outlet.tsx#L22 could be extended to `let temp = list.find(o => o._id !== '/' && o._id && id.startsWith(o._id));`. This would make it possible to support this kind of file structure:

```
/account/registration.jsx
/account/registration/index.jsx
/account/registration/otherpage.jsx
```

That generates this route structure:

```
      <Routes>
        <Route path="/account/registration" element=..>
          <Route path="/" element=.. >
            <Route path="/" />
            <Route path="/otherpage" element=.. />
          </Route>
        </Route>
      </Routes>
```

Compared to the previous route structure that doesn't work at all:

```
      <Routes>
        <Route path="/account/registration" element=..>
          <Route path="/" element=.. >
            <Route path="/">
              <Route path="/otherpage" element=.. />
            </Route>
          </Route>
        </Route>
      </Routes>
```
