### ISSUE TITLE
[Bug?]: resolve type fail on `moduleResolution: "Bundler"`

### ISSUE THREAD

**Issue by Gehbt** [solidjs/solid-start#1505]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Expected behavior 🤔

Since #1476 set `moduleResolution: "Bundler"`, package.json don't export `env.d.ts` in `exports`. 

![image](https://github.com/solidjs/solid-start/assets/74761884/bca81aad-2d5d-4297-803f-7683be3307bf)

In addition, in `defineConfig` at `@solidjs/start/config`, option `vite` has same problem.

![image](https://github.com/solidjs/solid-start/assets/74761884/b18289cb-293c-4e60-83f0-5473b924887e)

**Comment by ryansolid** [comment]
@GiyoMoon Seems to be related to the PR around moduleResolution

**Comment by Brendonovich** [comment]
Looks like #1506 has fixed the `env` part of this issue, the `vite` problem should be fixed by [this Vinxi PR](https://github.com/nksaraf/vinxi/pull/309)
