### ISSUE TITLE
[Bug?]: 404 page doesn't work in cloudflare pages

### ISSUE THREAD

**Issue by huseeiin** [solidjs/solid-start#1527]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

going to a page that doesn't exist in cloudflare pages shows a blank page with a `Uncaught (in promise) Error: Context is not available` error in the browser console

### Expected behavior 🤔

for `[...404].tsx` to render correctly

### Steps to reproduce 🕹

Steps:

1.create a solid start project
2.wrangler pages deploy dist
3.go to /page-that-doesnt-exist
4.empty page

**Comment by Brendonovich** [comment]
Add `unenv` as a dependency and put this in your config:
```ts
import { defineConfig } from "@solidjs/start/config";
import { cloudflare } from "unenv";

export default defineConfig({
  server: {
    preset: "cloudflare-pages",
    unenv: cloudflare,
  },
});
```

I think this will be done as part of the cloudflare preset at some point: https://github.com/unjs/nitro/issues/1943

**Comment by huseeiin** [comment]
> `nodejs_compat`

worked! thanks!

**Comment by huseeiin** [comment]
> Add `unenv` as a dependency, add the `nodejs_compat` compatability flag to your pages project, and put this in your config:
> 
> ```ts
> import { defineConfig } from "@solidjs/start/config";
> import { cloudflare } from "unenv";
> 
> export default defineConfig({
>   server: {
>     preset: "cloudflare-pages",
>     unenv: cloudflare,
>   },
> });
> ```
> 
> I think this will be done as part of the cloudflare preset at some point: [unjs/nitro#1943](https://github.com/unjs/nitro/issues/1943)

but, without the 404 status code?
