### ISSUE TITLE
[Feature?]: Allow `init` of projects with both `vitest` and `tailwindcss`

### ISSUE THREAD

**Issue by hamirmahal** [solidjs/solid-start#1528]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Users should have the option to include both `vitest` and `tailwindcss` in a new project created with `npm init solid@latest`.

### Examples 🌈

`npx create-next-app@latest` has something similar, where users can add TypeScript, and Eslint, and Tailwind CSS to a new project. It'd be nice if `npm init solid@latest` let users add all of the above, plus `vitest`.

```
$ npx create-next-app@latest
✔ What is your project named? … my-app
✔ Would you like to use TypeScript? … No / Yes
✔ Would you like to use ESLint? … No / Yes
✔ Would you like to use Tailwind CSS? … No / Yes
```

### Motivation 🔦

This reduces boilerplate and saves time for people who want to create a new `solid` project with `vitest` and `tailwindcss`.

**Comment by atk** [comment]
You can use `solid-cli add vitest` to your solid-start app with tailwind.

**Comment by brenelz** [comment]
Oh wow that CLI is super cool going to remember that next time. I think we can close this issue?
