### ISSUE TITLE
[Bug?]: Deno downloading error - npm package 'uWebSockets.js' does not exist

### ISSUE THREAD

**Issue by ben-laird** [solidjs/solid-start#1530]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using the basic Solid Start template with Typescript, running `deno task dev` will error with the following message:

```sh
error: npm package 'uWebSockets.js' does not exist.
```

### Expected behavior 🤔

Deno should be able to download all dependencies listed in `package.json` and should start the development server

### Steps to reproduce 🕹

Steps:

1. run `pnpm create solid` and use any name
2. select "Yes" when prompted for whether this is a Solid Start project
3. select the "basic" template
4. select "Yes" when prompted for whether to use TypeScript
5. run `deno task dev` in the root directory of the new project
6. observe error

### Context 🔦

I'm playing around with Solid Start in personal web apps and wanted to know if it would work with Deno in development and not just in production. I can't assume it does even though Vite works with Deno because framework authors can still break that compatibility; I've found that to be the case with Astro, regrettably.

Potentially related issues:

- #1177, specifically [this comment](https://github.com/solidjs/solid-start/issues/1177#issuecomment-1869473359) where a contributor points out that Deno is affected by a similar problem
- this [issue in Deno](https://github.com/denoland/deno/issues/20607) that the contributor mentioned

There's a chance this bug is upstream, possibly with Vinxi, Nitro, or even with Deno. I just figured I'd start here since I can't exactly pinpoint where the bug actually happens; there's no stack trace or indication of what caused `uWebSockets.js` to even be included in the downloads.

`package.json`:
```json
{
  "name": "example-basic",
  "type": "module",
  "scripts": {
    "dev": "vinxi dev",
    "build": "vinxi build",
    "start": "vinxi start",
    "version": "vinxi version"
  },
  "dependencies": {
    "@solidjs/meta": "^0.29.4",
    "@solidjs/router": "^0.13.3",
    "@solidjs/start": "^1.0.1",
    "solid-js": "^1.8.17",
    "vinxi": "^0.3.11"
  },
  "engines": {
    "node": ">=18"
  }
}
```

### Your environment 🌎

```shell
$ system_profiler SPSoftwareDataType SPHardwareDataType: (partial)
Software:

    System Software Overview:

      System Version: macOS 14.3 (23D56)
      Kernel Version: Darwin 23.3.0

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Chip: Apple M3 Max
      Total Number of Cores: 14 (10 performance and 4 efficiency)
      Memory: 36 GB
      System Firmware Version: 10151.81.1

$ deno --version:
deno 1.44.0 (release, aarch64-apple-darwin)
v8 12.6.228.3
typescript 5.4.5

$ node --version:
v22.2.0

$ pnpm --version:
9.1.4
```

**Comment by Brendonovich** [comment]
`uWebSockets.js` is included by [crossws](https://crossws.unjs.io/). You can replicate this error outside of start by running `deno repl` and entering `import "npm:crossws"`.
Maybe Deno's `npm:` resolver doesn't take into account packages that have `github:` dependencies, since it seems to look for `uWebSockets.js` on npm?

**Comment by brenelz** [comment]
yeah good call @Brendonovich. Maybe need to file a bug on the deno repo?

**Comment by vincentfretin** [comment]
https://github.com/denoland/deno/issues/20339#issuecomment-1967957257
 -> https://github.com/denoland/deno/issues/22606#issuecomment-2134637706

**Comment by birkskyum** [comment]
@ben-laird , run `DENO_FUTURE=1 deno task dev`

**Comment by ben-laird** [comment]
Running `DENO_FUTURE=1 deno task dev` works as expected. I'll close this issue as completed if you'd like @birkskyum, since this is an upstream issue that's fixed in a future version of Deno.
