### ISSUE TITLE
[Bug?]: `compressPublicAssets` nitro config does not work

### ISSUE THREAD

**Issue by huseeiin** [solidjs/solid-start#1569]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

when i enabled brotli it errors `[5:22:22 PM]  ERROR  Cannot find module "/home/hussein/Desktop/solid-project/.output/server/index.mjs" from "/home/hussein/Desktop/solid-project/node_modules/vinxi/bin/cli.mjs"`

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by mdynnl** [comment]
did you forget to include steps? anyway, can't seem to reproduce this.
1. both `brotli` and `gzip` are enabled by default and working.
2. `compressPublicAssets: false` disables both.
3. `compressPublicAssets: { gzip: false, brotli: false }` disables each respectively.

tested with solid-start/basic template
```
├── @solidjs/meta@0.29.4
├── @solidjs/router@0.13.6
├── @solidjs/start@1.0.2
├── solid-js@1.8.18
└── vinxi@0.3.12
```

**Comment by huseeiin** [comment]
> did you forget to include steps? anyway, can't seem to reproduce this.
> 
>     1. both `brotli` and `gzip` are enabled by default and working.
> 
>     2. `compressPublicAssets: false` disables both.
> 
>     3. `compressPublicAssets: { gzip: false, brotli: false }` disables each respectively.
> 
> 
> tested with solid-start/basic template
> 
> ```
> ├── @solidjs/meta@0.29.4
> ├── @solidjs/router@0.13.6
> ├── @solidjs/start@1.0.2
> ├── solid-js@1.8.18
> └── vinxi@0.3.12
> ```

with the `basic` example i'm only seeing gzip in the network tab 
![image](https://github.com/solidjs/solid-start/assets/122984423/54c49fb1-8f53-4394-8104-a801278435fc)

**Comment by mdynnl** [comment]
i believe this is expected because the response can only be served in one of a few encoding formats specified by `Accept-Encoding` request header. you probably should see what you're expecting if you modified the request headers somehow to accept `brotli`.

<img width="569" alt="Screenshot 2024-07-03 at 20 03 31" src="https://github.com/solidjs/solid-start/assets/53917354/5890fac8-1c49-42db-8647-a5a24cc8372f">


some info that might be useful https://nitro.unjs.io/config#compresspublicassets

> If enabled, Nitro will generate a pre-compressed (gzip and/or brotli) version of supported types of public assets and prerendered routes larger than 1024 bytes into the public directory. The best compression level is used. Using this option you can support zero overhead asset compression without using a CDN.
