### ISSUE TITLE
[Bug?]: "Zero-config" Netlify provider does not load a Netlify preset automatically

### ISSUE THREAD

**Issue by serhalp** [solidjs/solid-start#1576]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When deploying to Netlify and when using the Netlify CLI, the `node-server` Nitro preset is used by default.

### Expected behavior 🤔

The `netlify` (or `netlify_edge`) preset should be loaded by default, when not otherwise specified.

### Steps to reproduce 🕹

Steps:

1. `pnpm create solid`
2. `pnpm add --global netlify-cli`
3. `netlify dev` or `netlify serve` or [deploy to Netlify](https://docs.solidjs.com/guides/deployment-options/netlify)

### Context 🔦

[Netlify is a Nitro "zero-config provider"](https://nitro.unjs.io/deploy#zero-config-providers).

Also, a Netlify preset is required to use any server-side functionality (SSR, etc.) at runtime.

My best guess is that [this vinxi logic](https://github.com/nksaraf/vinxi/blob/8600f15330416da37a75ca9799f3c9db102feba0/packages/vinxi/lib/build.js#L70-L79) results in always explicitly passing a preset to Nitro, so [all its preset resolution logic](https://github.com/unjs/nitro/blob/63526f24b03e5e5de65934c697c92dd00f1e1ab1/src/core/config/loader.ts) ends up being useless as it is overridden by the explicit preset passed in? I don't know if that's quite right though.

If that's true, it would mean all the other zero-config providers aren't zero config either. I haven't verified that.

### Your environment 🌎

```shell
macOS 14.5, node@20.11.1, pnpm@8.15.5, @solidjs/start@1.0.2
```

**Comment by ryansolid** [comment]
I think you are right.. I noticed there was a bug here but hadn't had the chance to dig into it. Thank you.

**Comment by serhalp** [comment]
👋🏼 Hey Ryan, do you think I should open an issue over in the vinxi repo?

**Comment by ryansolid** [comment]
I actually already got on it: https://github.com/nksaraf/vinxi/pull/325

**Comment by ryansolid** [comment]
Ok fix is in. Just going to test it now.
