### ISSUE TITLE
[Bug?]: Using layouts with route groups at root level causes hydration errors

### ISSUE THREAD

**Issue by HansT01** [solidjs/solid-start#1582]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm trying to create a layout `(base).tsx` at the root level for the route group `(base)` with the following structure:

```
|-- routes/
    |-- (base).tsx   <-- layout
    |-- (base)/
        |-- index.tsx
        |-- about-us.tsx
    |-- admin.tsx    <-- layout
    |-- admin/
        |-- dashboard.tsx
```

Doing so causes a hydration error when rendering one of the pages in the `(base)` route group.

![image](https://github.com/user-attachments/assets/6e0ac0f5-0435-46fe-8c99-3ed799ab5800)

### Expected behavior 🤔

No hydration errors, and everything renders as expected.

### Steps to reproduce 🕹

Steps:

1. Start a new solid start project
2. Create a route group with a layout at the root level, similar to the one in the "current behavior" section
3. Navigate to one of the pages in the route group
4. Hydration error

### Context 🔦

I want to create two different layouts for admin and non-admin pages. I want non-admin pages to be at the root-level, with admin pages under the `/admin` route.

I've read through the documentation for SolidStart routing, but it doesn't seem to address this caveat, so I am unsure if this is a technical limitation or just an oversight.

Here are route structures I've tested:

Hydration error:
```
|-- routes/
    |-- (base).tsx   <-- layout
    |-- (base)/
        |-- index.tsx
        |-- about-us.tsx
    |-- admin.tsx    <-- layout
    |-- admin/
        |-- dashboard.tsx
```

No hydration error, but no layout:
```
|-- routes/
    |-- (base)/
        |-- index.tsx
        |-- about-us.tsx
    |-- admin.tsx    <-- layout
    |-- admin/
        |-- dashboard.tsx
```

No hydration error with layout, but not root level:
```
|-- routes/
    |-- test/
        |-- (base).tsx   <-- layout
        |-- (base)/
            |-- index.tsx
            |-- about-us.tsx
    |-- admin.tsx        <-- layout
    |-- admin/
        |-- dashboard.tsx
```

### Your environment 🌎

```shell
OS: Windows
node: v20.15.1
@solidjs/router: ^0.13.3
@solidjs/start: ^1.0.1
solid-js: ^1.8.17
vinxi: ^0.3.11
```

**Comment by HansT01** [comment]
Oops it looks like I hadn't tested on the latest versions. After updating everything, this now works as expected. Sorry!

**Comment by mrlectus** [comment]
> Oops it looks like I hadn't tested on the latest versions. After updating everything, this now works as expected. Sorry!

which example worked?

**Comment by HansT01** [comment]
> > Oops it looks like I hadn't tested on the latest versions. After updating everything, this now works as expected. Sorry!
> 
> which example worked?

Example provided under context
