### ISSUE TITLE
[Feature?]: Compile error when using `"use server";` in a non Async/Promise function

### ISSUE THREAD

**Issue by nbrugger-tgm** [solidjs/solid-start#1623]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

i can write typescript code like this

```tsx
function loadEnvVar() : string {
	"use server";
	return REQUIRED_ENV.BASE_URL;
}
```
Which will always lead to problems on the client since instead of a string a promise will be returned. Which makes sense, the method call is a RPC call so its async by nature. Maybe this can come in form of a compiler check or a ESlint rule?

### Examples 🌈

```tsx
function loadEnvVar() : string {
//      \/ "use server" functions must return a Promise<?> type  [COMPILER MESSAGE]
	"use server";
	return REQUIRED_ENV.BASE_URL;
}
```

### Motivation 🔦

Making it easier and more obvious that you write invalid non typesave code

**Comment by gamertike** [comment]
Oh wait this example is the compiler error you would like to be implemented???

**Comment by lxsmnsyc** [comment]
there's pretty much nothing that can be done here (at least in Start) so yeah, closest you'll get should be a linter error.

**Comment by nbrugger-tgm** [comment]
Yes sorry I was not entirely clear in the example.

I would like to get the commented line as linting or compilation error (when you create the automatically RPC calls)

**Comment by nbrugger-tgm** [comment]
At the very least I would want this restriction be made very clear in the docs

WARNING: only async/Promise<> returning methods can use "use server".

Or something like that

**Comment by lxsmnsyc** [comment]
well tbf I don't think it's restricted to async functions, but as long as the function returns a Promise

**Comment by nbrugger-tgm** [comment]
That's what I said tho

> only async/Promise<> returning methods

**Comment by ryansolid** [comment]
Yeah basically this cannot be done via compiler analysis nor enforced purely by types. You need a TypeScript plugin or some type aware analysis to do this. Or basically it be a lint rule. I guess this is a documentation issue.

**Comment by ryansolid** [comment]
Ok opened: https://github.com/solidjs/solid-docs/issues/891
