### ISSUE TITLE
[Bug?]:SyntaxError: Unexpected token 'N', "Not Found" is not valid JSON

### ISSUE THREAD

**Issue by ZacRenis** [solidjs/solid-start#1627]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1.npm create jd-app@latest
2.What is the name of the app? apri
3.Will you deploy this project to vercel? If so, how None
4.Copied template files to D:\path\to\create-jd-app\project
5. What should we use for this app? AuthJS, Prisma, TailwindCSS, pRPC
6. cd project
7. npm run push
8. npm run dev

it was caused by AuthJS, but i do not know how to fix it.

**Comment by ZacRenis** [comment]
/

**Comment by lxsmnsyc** [comment]
Do you have any `.json()` calls anywhere? seems like it's trying to decode a non-existent json.

**Comment by blopker** [comment]
I just ran into this via an `npm update`. No code changes, just updating `@solid-mediakit/auth` from 2.1.2 to 2.1.3 ([this commit](https://github.com/solidjs-community/mediakit/commit/fd8def1c0aed31f45f6541a7b4a0e2453810e92e)). I'm not sure what's wrong though, the stack trace is not easy to understand.

**Comment by ZacRenis** [comment]
> I just ran into this via an `npm update`. No code changes, just updating `@solid-mediakit/auth` from 2.1.2 to 2.1.3 ([this commit](https://github.com/solidjs-community/mediakit/commit/fd8def1c0aed31f45f6541a7b4a0e2453810e92e)). I'm not sure what's wrong though, the stack trace is not easy to understand.

Not really, I just run those command to initial the project, I suppose it was caused by none-config of `AuthJS`, because it goes correctly when I start a new project without selected AuthJS.

**Comment by ZacRenis** [comment]
> Not really, I just run those command to initial the project

Not really, I just run those command to initial the project without changing any code.

**Comment by levma** [comment]
Downgrading `@solid-mediakit/auth` to `v2.1.2` solved the issue for me.

**Comment by levma** [comment]
This solved the problem for me:
I've set `config.basePath` to `'/api/auth'` in src/server/auth.ts
(I've created an issue in mediakit as it is related to their package and not solid-start directly: https://github.com/solidjs-community/mediakit/issues/103)

**Comment by ryansolid** [comment]
A new version of create-jd-app was released the other day might be worth double checking. In either case I'd consider opening the issue there or in mediakit as this seems specific to those libraries.
