### ISSUE TITLE
[Bug?]:Error: Hydration Mismatch. Unable to find DOM nodes for hydration key: 0000000010000<a href="/">Index</a>

### ISSUE THREAD

**Issue by vincehi** [solidjs/solid-start#1638]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I've noticed that with the latest version of solidStart@1.0.7 there's a hydration problem on the first load.

### Expected behavior 🤔

I'd like a real Changelog for SolidStart

### Steps to reproduce 🕹

Steps:

1. `npm create solid`
2. SolidStart: yes, template: with-prisma, Typescript: yes
3. npm run dev
4. go to localhost:3000
Hydration problem on first load.

### Your environment 🌎

```shell
System:
    OS: macOS 13.7
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 77.46 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.volta/tools/image/node/20.11.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.2.4 - ~/.volta/tools/image/node/20.11.0/bin/npm
    pnpm: 7.13.4 - /usr/local/bin/pnpm
    bun: 1.1.29 - /usr/local/bin/bun
  npmPackages:
    @prisma/client: ^5.12.1 => 5.20.0 
    @solidjs/router: ^0.14.7 => 0.14.7 
    @solidjs/start: ^1.0.7 => 1.0.7 
    @types/node: ^20.12.7 => 20.16.9 
    prisma: ^5.12.1 => 5.20.0 
    solid-js: ^1.9.1 => 1.9.1 
    vinxi: ^0.4.3 => 0.4.3 
  npmGlobalPackages:
    corepack: 0.23.0
    npm: 10.2.4
```

**Comment by katywings** [comment]
Can confirm this. The first ssr after startup seems to come with no hydration ids on the elements.

**Comment by vincehi** [comment]
> Can confirm this. The first ssr after startup seems to come with no hydration ids on the elements.

Use solidStart@1.0.7 while you wait

**Comment by katywings** [comment]
Okay the problem was introduced with #1635 - undoing it fixes the problem.
