### ISSUE TITLE
createServerData not being compiled in non-route files

### ISSUE THREAD

**Issue by nksaraf** [solidjs/solid-start#164]
Should add test for this
Requires us to add serverResource babel plugin to non-route files as well

**Comment by ryansolid** [comment]
This is interesting. At first I'm thinking, so what.. But `routeData` is the only piece actually tied to the route I think.. What's interesting is having stuff like redirects happen somewhere nested in the component tree, but then again maybe that flexibility is a good thing. `server` is generic for sure.. but the extent of Actions and Data are interesting to consider. It might be enough to show best practices and keep things really flexible, but I do think the consequences are worth thinking on.

**Comment by nksaraf** [comment]
This applies for both `createServerAction` and `createServerData`..but also people need to be able to abstract a `createServerData` function in a different function, and import that and use it in `routeData`. Can't break that composability. 

Server actions by default can be used anywhere obviously coz thats inside components.
