### ISSUE TITLE
[Bug?]: No valid compatibility date is specified.  

### ISSUE THREAD

**Issue by OrJDev** [solidjs/solid-start#1670]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Seems like some commit broke something, using

```
    "@solidjs/router": "^0.15.0",
    "@solidjs/start": "^1.0.10",
    "autoprefixer": "^10.4.19",
    "postcss": "^8.4.38",
    "solid-js": "^1.9.2",
    "tailwindcss": "^3.4.3",
    "vinxi": "^0.4.3"
```

when running `pnpm dev` you get this warning:

```
 WARN  No valid compatibility date is specified.                                                                             nitro 1:12:01 AM

ℹ Using 2024-04-03 as fallback.                                                                                             nitro 1:12:01 AM
  Please specify compatibility date to avoid unwanted behavior changes:
     - Add compatibilityDate: '2024-11-03' to the config file.
     - Or set COMPATIBILITY_DATE=2024-11-03 environment variable.
```

this is a warning i got in a brand new SolidStart app + Tailwind using the Solid cli to create this app.

<img width="823" alt="Screenshot 2024-11-03 at 1 13 34" src="https://github.com/user-attachments/assets/b38b84df-b477-4c18-8561-074458b7a916">

### Steps to reproduce 🕹

Steps:

1. Create New SolidStart + Tailwind App
2. Install Deps
3. Run the dev server

**Comment by notKamui** [comment]
This seems like a vinxi issue as it is happening to me too with tanstack-start, which uses vinxi

**Comment by karimmaassen** [comment]
I have the same issue. 

```
    "@solidjs/start": "^1.0.10",
    "firebase-admin": "^12.7.0",
    "firebase-functions": "^6.1.0",
    "firebase-functions-test": "^3.3.0",
    "solid-js": "^1.9.2",
    "vinxi": "^0.4.3"
```

**Comment by OrJDev** [comment]
> I have the same issue. 
> 
> 
> 
> ```
> 
>     "@solidjs/start": "^1.0.10",
> 
>     "firebase-admin": "^12.7.0",
> 
>     "firebase-functions": "^6.1.0",
> 
>     "firebase-functions-test": "^3.3.0",
> 
>     "solid-js": "^1.9.2",
> 
>     "vinxi": "^0.4.3"
> 
> ```

Yes its just a vinxi (nitro) issues @nksaraf

**Comment by ocombe** [comment]
Got the same error but I'm not using solidjs or vinxi, just nitropack (which I guess is used by vinxi)

**Comment by OrJDev** [comment]
> Got the same error but I'm not using solidjs or vinxi, just nitropack (which I guess is used by vinxi)

Ye looks like a nitro issues

**Comment by yurisich** [comment]
Workaround:

```diff
   "name": "example-basic",
   "type": "module",
   "scripts": {
-    "dev": "vinxi dev",
+    "dev": "COMPATIBILITY_DATE=2024-11-24 vinxi dev",
     "build": "vinxi build",
     "start": "vinxi start",
     "version": "vinxi version"
```

**Comment by birkskyum** [comment]
In the app config, the date can be added like this:

```ts
export default defineConfig({
	server: {
		compatibilityDate: "2024-11-24"
	},
});
```

**Comment by atilafassina** [comment]
This issue has been solved upstream as vinxi now provides a `compatilbilityDate` out-of-the-box.
