### ISSUE TITLE
[Bug?]: `createAsync()` or `query()` not working properly when using reactive params?

### ISSUE THREAD

**Issue by michaelhaar** [solidjs/solid-start#1691]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

(see Stackblitz example in repro section)

<img width="721" alt="Screenshot 2024-12-19 at 20 18 43" src="https://github.com/user-attachments/assets/918c16c3-394a-4b12-8ef7-045bcdb15e3a" />

```
import { createAsync, query } from '@solidjs/router';
import { createSignal, For, Suspense } from 'solid-js';

export function Users() {
  const [isActive, setIsActive] = createSignal(true);
  const users = createAsync(() => getUsers(isActive()));

  const handleClick = () => {
    setIsActive((prev) => !prev);
  };

  return (
    <div>
      <div class="flex gap-2 items-center justify-center mb-4">
        <div>Filter Users:</div>
        <button
          onClick={handleClick}
          class="px-2 border-2 border-solid border-black bg-white"
        >
          {isActive() ? 'inactive' : 'active'}
        </button>
      </div>

      <Suspense fallback={<div> loading ...</div>}>
        <For each={users()}>{(user) => <li>{user}</li>}</For>
      </Suspense>
    </div>
  );
}

const getUsers = query(async (isActive: boolean) => {
  'use server';

  console.log("Warning: Should not be called once it's cached?");

  // Simulate a slow response
  await new Promise((resolve) => setTimeout(resolve, 500));

  return isActive
    ? ['activeUser1', 'activeUser2']
    : ['inactiveUser1', 'inactiveUser2'];
}, 'users');

```

- update the `active`/`inactive` filter by clicking the button multiple times with 5+ seconds breaks between clicks 
- Server function gets called multiple times. (see terminal logs)
- (Server function is not called when clicking faster => Cache seems to be working)

### Expected behavior 🤔

(see Stackblitz example in repro section)

- Server function is called exactly 2 times regardless of the clicking speed?
- Server function call is cached properly.

### Steps to reproduce 🕹

[Stackblitz Demo](https://stackblitz.com/edit/github-hz6dv3hk?file=src%2Froutes%2Findex.tsx)

### Context 🔦

(I'm new to Solidjs and Solid-Start.)

I was following the data loading example from the latest (Beta) docs, which works fine:
https://docs.solidjs.com/solid-start/building-your-application/data-loading#data-loading-always-on-the-server

I tried adding some reactive parameters to the server function. Unfortunately the caching of the `query()` function isn't working as expected. Please find the Stackblitz example in the reproduction section! 

(I was also able to reproduce this on my local machine in another project using the latest solid-start package 1.0.10)

Am I doing something wrong? 

It would be great if you could also add a `data loading with reactive params` example to the docs?

Notes: 
I think this issue caused by using a combination of `createAsync`+`query`+`signals`?

As far as I can tell this code is causing the issue:
https://github.com/solidjs/solid-router/blob/main/src/data/query.ts#L100-L112

(For some reason the function inside `onCleanup(() => cached[4].count--);` is called causing count to be zero and `Date.now() - cached[0] < PRELOAD_TIMEOUT` is causing this weird 5 second working caching behaviour)

PS: 

@ryansolid and team: Thanks for creating this framework. Keep up the great work! I'll keep watching your streams on youtube.

### Your environment 🌎

```shell
System:
  OS: macOS Ventura Version 13.5
  CPU: Apple M2 Pro
Binaries:
  Node: v20.11.0
  npm: 10.2.4
npmPackages:
  solid-start: 1.0.10
```

**Comment by michaelhaar** [comment]
@brenelz Thank you for the explanation!

As a new user of the solid-router/solid-start framework I read the solid-router [query docs](https://docs.solidjs.com/solid-router/reference/data-apis/query) page and I figured that the main purpose of the query function is caching (=deduping?) requests. (As explained in the first paragraph on the docs page)

> When this newly created function is called for the first time with a specific set of arguments, the original function is run, and its return value is stored in a cache and returned to the caller of the created function. The next time the created function is called with the same arguments (as long as the cache is still valid), it will return the cached value instead of re-executing the original function.

The key thing seems to be the "as long as the cache is still valid" part.  IMHO The docs are not clear on how long this is. 

> The return value is a CachedFunction, a function that has the same signature as the function you passed to cache. This cached function stores the return value using the cache key. Under most circumstances, this temporarily prevents the passed function from running with the same arguments, even if the created function is called repeatedly.

<img width="1126" alt="Screenshot 2024-12-19 at 20 44 01" src="https://github.com/user-attachments/assets/4ce59b95-9876-4ff1-8cee-c93785ada994" />

I assumed the solid `query` function behaves similar to other frameworks/libraries. e.g. react query which seems to have a 5 minute cacheTime by default. (see: [Important defaults](https://tanstack.com/query/v4/docs/framework/react/guides/important-defaults))

**Comment by michaelhaar** [comment]
From what I'm understanding providing an option argument for the `cacheTime` would be very useful for use cases like this?

e.g.:

```
query(fn: (...args: any) => any, name: string, options: { cacheTime?: number } = {})
```

**Comment by atilafassina** [comment]
> From what I'm understanding providing an option argument for the `cacheTime` would be very useful for use cases like this?
> 
> e.g.:
> 
> ```
> function query<T extends (...args: any) => any>(
>   fn: T,
>   name: string,
>   { cacheTime = 5000 }: { cacheTime?: number } = {}
> )
> ```
> 
> Implementation could look like this? [michaelhaar/solid-router@39ec5b4](https://github.com/michaelhaar/solid-router/commit/39ec5b4876598b499551d315967d1114ffe0bd1c)

This seems to be a common confusion between the way Tanstack Query works with queries and cache.
In SolidStart they are very very different.

I believe the cache you're wanting to is a "stale-while-revalidate" cache, which you can accomplish by adding that header to your resource response. The cache that we have within SolidStart (provided by the `query()` helper) is first and foremost a deduplication cache. It won't prevent the request from re-firing between your client and the server. It will, though, prevent the ServerFunction from re-executing if called multiple times (during the same roundtrip).

As your tests showed, that roundtrip cache is valid for 5 seconds. So, subsequent calls within that timeframe will not re-execute the function (this means for both outbound requests or resource serialization/responses). Unless somewhere in your code you used `reload()` or `revalidate()` (you can also revalidate other queries with your response object, e.g.: if you call a `logout()` server function, you can revalidate the `getUser()` query.

So, if I understood your issue corrected, your code is working as you should expect. SolidStart doesn't provide any cache primitive for the client, we recommend our users to leverage the platform for that.

**Comment by michaelhaar** [comment]
@atilafassina 

> So, if I understood your issue corrected, your code is working as you should expect. SolidStart doesn't provide any cache primitive for the client ...

That's unfortunate! Thank you for the clarification! 🙏 📈 

----

Regarding this option:
> I believe the cache you're wanting to is a "stale-while-revalidate" cache, which you can accomplish by adding that header to your resource response

I tried something like this, but unfortunately the browser isn't caching the request/response at all
```ts
const getUsers = query(async (isActive: boolean) => {
  'use server';

  console.log("Warning: Should not be called once it's cached?");

  // Simulate a slow response
  await new Promise((resolve) => setTimeout(resolve, 500));

  const data = isActive
    ? ['activeUser1', 'activeUser2']
    : ['inactiveUser1', 'inactiveUser2'];

  return json(data, {
    headers: {
      'cache-Control': 'public, max-age=3600',
    },
  });
}, 'users');
```

I used the `json` function and tried various cache-control headers but I couldn't  get this working with server functions. [Modified Stackblitz Example](https://stackblitz.com/edit/github-hz6dv3hk-3wtq3yzl?file=src%2Fcomponents%2FUsers.tsx). 

I assume it's because of the query params which are automatically set by the server function or maybe because of `Content-Type: text/javascript` 🤔
