### ISSUE TITLE
server functions errors being sent to the client during prod

### ISSUE THREAD

**Issue by ghalle** [solidjs/solid-start#170]
Right now it seems like the errors are fully sent to the client, including message and stack traces, even in production.

[Example](https://stackblitz.com/edit/solid-start-server-func-error?file=src%2Froutes%2Findex.tsx)

The obvious solution would be to substitute the error with a generic 500 error during production.

But should the error still be sent to the client during dev or should they be printed on the server?
Sending them to the client would introduce different behavior between dev and prod build and should be well documented.

Also should it be possible for the users to opt-in to have certain errors sent to the client (no stacktraces)?
```typescript
import { ServerError } from "solid-start/server"
server(() => {
  throw new ServerError("Will be sent to the client")
})()
```

**Comment by nksaraf** [comment]
Fixed using this API, should be part of the latest releases (0.1.0-alpha.99)
