### ISSUE TITLE
nit: relative redirects have different behavior with and without javascript

### ISSUE THREAD

**Issue by boehs** [solidjs/solid-start#187]
Tiny problem, I think this has more to do with solid-start than app router but unsure.

Forms sent to the browser have the following signature:

```html
<form method="post" action="/_m/src/routes/index.tsx/0/routeData">
```

When javascript loads, the form's behavior is changed to do the fetching without navigating. The discrepancy happens when an action issues a redirect with a relative path (`./solidJs`).

- **When there is javascript** the path is relative to the URL of the page the user submitted from (say `/`), because it is handled by javascript instead of navigating away
- **When there is not javascript** the browser navigates to `/_m/src/routes/index.tsx/0/routeData` and *then* it handles the redirect, so the user finds herself at `/_m/src/routes/index.tsx/0/routeData/solidjs` instead of `/solidjs`

I'm not sure how to fix this?

1.  preprocess relative paths to be absolute? In this scenario the server always issues absolute redirects SPECIFICALLY for action responses (because then the location the user is coming from is almost always predictable based on the route signature), BUT this is flawed because of wildcard routes (user could be coming from `/i/love` or `/i/love/solid` and as such absolute is impossible))
2. Dynamic absolute redirect based on `Referer` header. Just merge the referrer and relative path together! BUT the Referrer header is not guarantied.

Both 1 & 2 together can account for 99.99% of cases but fail if all three conditions are met

1. The user has not loaded javascript
2. The path the action was created on is a wildcard
3. There is no referrer header

And this would be very hard to debug if someone had the misfortune of encountering it.

To fix this we could encode the referrer in the formdata, and that would account for every case (and without need for the preprossessing)! I think this is the best solution, but it's not elegant.

This leaves one last option (unless you have other ideas), banning relative routes! Horrible idea. I don't like that one.

**Comment by nksaraf** [comment]
I actually think that banning relative redirects is actually the best idea. Here's why? 
While redirecting from an action, an action can be in a component anywhere in the tree, its not associated with a route.. so its actually bad to rely on knowing the current route for the action, an action should almost never assume that it'll know the route the action is coming from.  we currently have this behaviour where we try to redirect to the original page if an action doesn't return anything, but this is also flaky.

**Comment by boehs** [comment]
> its not associated with a route.

oops that's right, forgot! I can see there being some rare use cases though where relative paths are desirable, like wildcards. Maybe in the error it's wise to suggest an escape hatch, like a hidden form value?

**Comment by nksaraf** [comment]
Yeah hidden form value or a parameter value is the best place to send the current url down..

**Comment by boehs** [comment]
@rturnq any thoughts on disallowing relative paths in navigate? I expect the best place for this change would be in app router itself.

**Comment by nksaraf** [comment]
I don't think `navigate` needs to disallow relative routes because its mainly the client side navigation method where we want to allow it. `Response` with redirect is a more server side navigate where relative navigation is tricky because we can't reliable have the client URL, so we can be reliable about the behaviour

**Comment by boehs** [comment]
Oops, right, full of mistakes today

**Comment by nksaraf** [comment]
Added warning in https://github.com/solidjs/solid-start/commit/c0b2e91d2771be6d21b1dbe57945605884ad53a8
