### ISSUE TITLE
Disabling the client side router

### ISSUE THREAD

**Issue by boehs** [solidjs/solid-start#190]
From discord

> in solid-start can you do a full page refresh instead of client side routing?
> i prefer mpa style but with client side interactivity

**Comment by boehs** [comment]
> **nk**: Yeah we are thinking of a fresh style mode for this with islands architecture. just experimenting
> > **me**: Could it be as simple as not including the client side router?
> right now that's our best bet.. but we also don't need the whole routes config and can probably reduce the size quite a bit

**Comment by nksaraf** [comment]
We do have an exterimental `islands` mode and `islandsRouter` mode for this, but this is being explored currently.

**Comment by mb21** [comment]
I don't understand the following sentence from https://start.solidjs.com/api/A:

> The `<A>` component is [...] progressive enhance-able and can work with client-side routing even when not hydrated bridging the gap between Single Page applications and Islands.

So the new `islands` mode and router still have some kind of js-client-side-routing? Looking at the network-tab when checking out the movies template and navigating confirms this.

But isn't there a way to do an website with SolidStart with an Astro-like architecture: a MPA where links are plain HTML `<a>` tags and the browser handles back/forward navigation, but where we still can have client-side-hydrated islands?

(See [The balance has shifted away from SPAs](https://nolanlawson.com/2022/05/21/the-balance-has-shifted-away-from-spas/) for a motivation, or [Building a Modern Website? SSG vs. SSR, SPA vs. MPA, Svelte vs. Solid](https://mb21.github.io/blog/2023/09/18/building-a-modern-website-ssg-vs-ssr-spa-vs-mpa-svelte-vs-solid.html) for my personal rumblings.)
