### ISSUE TITLE
Server functions defined outside of routes not initialized on the server when called inside of event handler

### ISSUE THREAD

**Issue by ghalle** [solidjs/solid-start#196]
Repro: https://stackblitz.com/edit/solid-start-sf-not-init?file=src%2Fserver.ts,src%2Froutes%2Findex.tsx

Happens because during the solid SSR transform all the interactive stuff like event handlers are deleted. Which then causes the import to be deleted as there are no more references and therefore the server function is never initialized server side.

Here's what the code looks like right before the import is deleted:
```typescript
import { ssr as _$ssr } from "solid-js/web";
import { escape as _$escape } from "solid-js/web";
import { ssrHydrationKey as _$ssrHydrationKey } from "solid-js/web";
const _tmpl$ = ["<main", "><h1>Hello world!</h1><button>Greet</button><p>", "</p></main>"];
import { createSignal } from "solid-js";
import { greet } from "~/server";
export default function Home() {
  const [message, setMessage] = createSignal("");
  return _$ssr(_tmpl$, _$ssrHydrationKey(), _$escape(message));
}
```

This can be worked around by defining a function outside of the JSX and calling the server function from there instead.

**Comment by nksaraf** [comment]
fixed in https://github.com/solidjs/solid-start/commit/33b66d2f8b6687f1552b574cd05a4804029ed579
