### ISSUE TITLE
Inconsistent use of imports from @solidjs/meta or solid-start

### ISSUE THREAD

**Issue by boehs** [solidjs/solid-start#217]
Just saw in bare, not sure if elsewhere also

https://github.com/solidjs/solid-start/blob/554cfa9fdcbdbb480ebd71ef11f66d471fa534bd/examples/bare/src/routes/index.tsx#L1

https://github.com/solidjs/solid-start/blob/554cfa9fdcbdbb480ebd71ef11f66d471fa534bd/examples/bare/src/routes/%5B...404%5D.tsx#L1

Come think of it, does @solidjs/meta need to be an explicit dep anymore?

**Comment by nksaraf** [comment]
I think I would prefer it not being needed to be imported separately.. but I wonder what happens if `@solidjs/meta` bumps versions.. how do people use that.. is there a simple way for users to do that.. I feel like there is and im being dumb..

**Comment by boehs** [comment]
Couldn't it just be a dependency of solid-start and it gets bumped when everything is ready?

**Comment by nksaraf** [comment]
Yeah I am not sure why people have these as peerDependencies, now Im wondering.. is it to give users control of what version they use?

**Comment by boehs** [comment]
I'm explicitly using `solidjs/@meta` because it was a dependency in the bare starter.

If it is removed from dependencies and users want to use their own version of meta, they can just update their imports from `solid-start`'s reexport to their `solidjs/@meta` dependency, so no harm.

Lots of advantage to it *not* being an explicit dep though

- We get to make sure it's safe before upgrading, our users might not do so
- If we need to modify some router behaviors, it's easy because the ball is in our court as users are importing from `solid-start` instead of directly from `@solidjs/router`
- No confusing duplicate intelisense imports

**Comment by nksaraf** [comment]
I do like these things.. they are all really helpful.. its not like u are free to change the version to anything and it'll work with us.. maybe thats true for solid-js.. but not those other dependencies.. @ryansolid any thoughts?

**Comment by ryansolid** [comment]
Yeah maybe these 2 things are actually firm dependencies. They sort of aren't if we break apart the vite plugins more but then trying to reconcile that might be unneeded complexity. This is like the bare minimum needed for isomorphic routing I guess. I'm fine making them hard dependencies. Although I'm sure someone will have some other case where they don't want that, but SolidStart components depend on them so hard to break them out completely. You could choose not to use those SolidStart components as well, but maybe not enough of a concern to merit not having them fixed.

**Comment by nksaraf** [comment]
I think it makes sense for our examples and docs to show everything imported from `solid-start`. It might still make sense for `@solidjs/meta` to be a explicit dependency because as @ryansolid mentioned, it will allow people to import from `@solidjs/meta` if they want, but they loose this if they dont install it explicitly. But then maybe if they want to use it separately they can install it separately?
