### ISSUE TITLE
An SSR example with fetching API

### ISSUE THREAD

**Issue by theowenyoung** [solidjs/solid-start#22]
Hi, thanks for your great work, I love solid, I want to give it a try in my new project.

After `npm init solid@next`, it inited a simple template without feching any API, I can't find any documents about this, is there anything I missed?

**Comment by ryansolid** [comment]
Still working on opinionated pieces here. Generally speaking the docs on `createResource` on the solidjs.com and the data functions for the solid-app-router are what you are looking and will automatically take care of data serialization. This project is still in alpha. The best example I can give you right now is: https://github.com/solidjs/solid-hackernews/tree/vite-ssr

**Comment by theowenyoung** [comment]
Thanks, that helps a lot!

**Comment by nksaraf** [comment]
Checkout what we are doing with `server` functions now. Its an easy way to add server-side data fetching. Documentation is still incoming.
