### ISSUE TITLE
`durable-objects-websocket` example doesn't have tailwindcss/windicss 

### ISSUE THREAD

**Issue by lightyaer** [solidjs/solid-start#223]
The example `durable-objects-websocket` doesn't have tailwind/windicss deps installed, but it does use classes and styles from it.

**Comment by lightyaer** [comment]
I can put up a PR if given a preference tailwindcss or windicss?

**Comment by nksaraf** [comment]
Heyy really thanks for this PR.. but i think what we might do, and you can update your PR for this.. is just styling our examples with root.css files so people can move off them easily. We will have a windicss starter, but putting it in a websocket example makes it tough to make the examples flexible. Does that make sense?
