### ISSUE TITLE
`durable-objects-websocket` doesn't login when SSR is false

### ISSUE THREAD

**Issue by lightyaer** [solidjs/solid-start#224]
[durable-objects-websocket](https://github.com/solidjs/solid-start/tree/main/examples/durable-objects-websocket) doesn't work as expected when SSR is false.

Steps to Reproduce:
- Set up project using `npm init solid@next`
- Say `NO` to SSR
- `npm i` on project
- `npm run dev` on project

Open browser and then devtools -> Console
Seeing errors
<img width="1728" alt="Screenshot 2022-08-06 at 8 27 14 AM" src="https://user-images.githubusercontent.com/5101454/183230767-8983449e-b0d2-4a84-adab-767668b2ed41.png">

Login with username and password mentioned in placeholders
`kody` & `twixrox`, it redirects to login page

**Comment by nksaraf** [comment]
Right now that example had not been migrated to some latest APIs for SPA mode yet. That's in the works. In the meanwhile you can try the SSR mode since you need the server stuff for the web-sockets anyway.

**Comment by nksaraf** [comment]
This should work in the next release. Earlier our SPA mode had no support for server functions or API routes, recently fixed that so this should work soon.
