### ISSUE TITLE
Exit with errors when pnpm run dev

### ISSUE THREAD

**Issue by harshmangalam** [solidjs/solid-start#226]
After initialising new project and   `pnpm run dev`  i got error 
![solid-start-error](https://user-images.githubusercontent.com/57381638/183243408-5033a308-76a1-40fd-82e8-60e27ffe6fe5.png)

**Comment by harshmangalam** [comment]
It work well without errors when i remove Counter.css import from Counter.tsx

**Comment by nksaraf** [comment]
Fixed by #218
