### ISSUE TITLE
dev and build behave inconsistently

### ISSUE THREAD

**Issue by zoy-l** [solidjs/solid-start#229]
Hi,👋 I am working on a css in js tool, it works fine in development mode, but after build it reports an error `Cannot read properties of undefined (reading 'cloneNode')`

did i miss something？

```
entry-client.4de8017e.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'cloneNode')
    at ke (entry-client.4de8017e.js:1:14608)
    at Object.fn (entry-client.4de8017e.js:1:20732)
    at L (entry-client.4de8017e.js:1:3369)
    at j (entry-client.4de8017e.js:1:3169)
    at x (entry-client.4de8017e.js:1:923)
    at qe (entry-client.4de8017e.js:1:20616)
    at entry-client.4de8017e.js:1:43305
    at createExtracts (entry-client.4de8017e.js:1:41612)
    at gn (entry-client.4de8017e.js:1:43730)
    at entry-client.4de8017e.js:1:6983
```

createExtracts
```js
() => [
    Dynamic({
      component: 'meta',
      id: metaSelectorCacheId,
      name: 'styils-cache',
      mode: metaMode,
      content: selectorCacheString
    }),
    Dynamic({
      component: 'style',
      id: globalStyleSSRId,
      children: ssrGlobalData
    }),
    Dynamic({
      component: 'style',
      id: styleSSRId,
      children: ssrData
    })
  ]
```

<img width="666" alt="image" src="https://user-images.githubusercontent.com/15136058/183248931-620150c1-4a12-4beb-a5eb-acc688fd3c7b.png">

**Comment by nksaraf** [comment]
I would suggest using the title case versions of these components.. eg. `Meta`, `Style` even in the Dynamic.. that should make it work..

**Comment by zoy-l** [comment]
... I retested not to use it here, using `Dynamic` to create a `tag` in page, and an error will also appear after packaging
<img width="498" alt="image" src="https://user-images.githubusercontent.com/15136058/183297834-06fb49e7-074b-483b-9b59-e4b87a9dfa5c.png">
It seems to be related to the attribute `data-hk`

**Comment by nksaraf** [comment]
Can you make a reproduction of this issue somewhere so I could also take a look.. Difficult to debug without that

**Comment by zoy-l** [comment]
https://github.com/zoy-l/solid-start 👋

**Comment by zoy-l** [comment]
https://github.com/zoy-l/solid-vite-ssr The same exists
maybe the problem with 'solid' itself?

**Comment by nksaraf** [comment]
Are you passing all the props down to the Dynamic component?

**Comment by nksaraf** [comment]
I see that you are calling dynamic yourself.. is there a reason for that.. its not the correct way to use component.. though its nothing too different.. but I think the hydration might get affected

**Comment by zoy-l** [comment]
I use it as a render function, like `react.createElement` I am not sure if this is correct...
<img width="472" alt="image" src="https://user-images.githubusercontent.com/15136058/183399453-3a1a1d22-2bfb-498d-83b0-b3f2aad1b027.png">
This is the code I wrote,

**Comment by zoy-l** [comment]
https://github.com/solidjs/solid/issues/1145 here
