### ISSUE TITLE
Type error when using renderStream (or renderSync) function

### ISSUE THREAD

**Issue by clemvnt** [solidjs/solid-start#240]
### Describe the bug

When I use the `renderStream` (or `renderSync`) function, I get a type error that I do not get when I use the `renderAsync` function. 
![image](https://user-images.githubusercontent.com/19864578/183995500-e54c9c9d-25ee-445d-9acf-ca78a3604361.png)

There are no issues at runtime.

### Reproduction

https://github.com/clemvnt/solid-stack/blob/main/src/entry-server.tsx

**Comment by nksaraf** [comment]
Ahh thanks for catching this .. might have been a recent change.. will fix!
