### ISSUE TITLE
Error when running tests with Vitest

### ISSUE THREAD

**Issue by clemvnt** [solidjs/solid-start#241]
### Describe the bug

When I run the tests with Vitest, I get the following error:

![image](https://user-images.githubusercontent.com/19864578/183997338-7aa890c1-80a8-4849-a797-0819053b0942.png)

I guess adding the `vitest.setup.ts` to the `exports` list (and in the `files` list because this file is not published) of the `package.json` file of the `solid-start` package should solve the problem. But looking at this file, I wonder if it is really required as you can do tests without needing `@testing-library/jest-dom`.

To fix this issue on my side, I added a custom vite plugin that override the config and more precisely the `test.setupFiles` option :

![image](https://user-images.githubusercontent.com/19864578/184007187-6d87a891-ca81-4112-9d9d-f679c612a143.png)

Then, I got another error :

![image](https://user-images.githubusercontent.com/19864578/184007251-d3805bbf-a78a-4d96-b222-ebaf3fd66adf.png)

To fix this error, I setted the `test.deps.registerNodeLoader` option to `true` (like in the [solid example of the vitest repo](https://github.com/vitest-dev/vitest/blob/155943c5b6792a4c75ed5108d39ab052255bae19/examples/solid/vite.config.mjs)) :
![image](https://user-images.githubusercontent.com/19864578/184007674-63a6c220-0ac2-4aca-a2ec-739a0b3e4da0.png)

This option seems to be required since v0.21.0 (https://github.com/vitest-dev/vitest/pull/1778).

And now, tests are working :

![image](https://user-images.githubusercontent.com/19864578/184015374-b15d75e7-163d-4c97-9aa2-4c6a90522ac6.png)

### Reproduction

https://github.com/clemvnt/solid-stack

To reproduce the error, you must comment [the custom vite plugin](https://github.com/clemvnt/solid-stack/blob/main/vite.config.ts#L9-L17) that override the config.

### Alternative

I wonder if it is really necessary for the `solid-start` vite plugin to completely define the vitest configuration because it seems that we cannot add our own configuration such as :
![image](https://user-images.githubusercontent.com/19864578/184010002-1f324fc6-40ab-45ce-90e7-50ef7575cd35.png)

Is it possible that the configuration could be overwritten on our side? The `solid-start` vite plugin could still set the required options (`test.transformMode.web` and `test.deps.registerNodeLoader`) and leave the possibility to add or override options.

Moreover, the `test.globals`, `test.setupFiles`, `test.threads`, `test.isolate` options do not seem to be required for the tests to work. Wouldn't it be better not to set these options to use the default vitest behavior and let the user choose?

I suppose that this alternative would require a change in the [following lines](https://github.com/solidjs/solid-start/blob/a756f1696ad9372d1e2079fa27f15f42da4196b8/packages/start/vite/plugin.js#L380-L396) :
```diff
- test: {
+ test: mergeConfig({
   environment: "jsdom",
   transformMode: {
     web: [/\.[tj]sx?$/]
   },
+  deps: {
+    registerNodeLoader: true
+  },
+ }, conf.test),
-  globals: true,
-  setupFiles: "node_modules/solid-start/vitest.setup.ts"
-  threads: false
-  isolate: false
- },
```

Depending on which solution you choose, fixing the missing import or the proposed alternative, I could make a pull request.

**Comment by nksaraf** [comment]
Thanks for this! I have been reconsidering this approach since I added it and basically was waiting for some feedback. This is very helpful, and im gonna think about a good solution.. the idea is I wanted for people to be the install `vitest`, `jsdom`, `@testing-library/jest-dom`, etc. and start testing without configuring

**Comment by atk** [comment]
I have already an idea on how to do that. We can test in the running config which environment is available and adapt the config correspondingly; also we can set/augment the testing config in the plugin. I'm currently a bit low on time, but if nobody else will, I can prepare a PR.

**Comment by clemvnt** [comment]
Also, leaving the choice of environment will be even more relevant when [@vitest/browser](https://github.com/vitest-dev/vitest/tree/main/packages/browser) is ready.

Some people will want to run their tests directly in the browser, others will want to use `jsdom` (or `happy-dom` but not right away because there are blocking issues: https://github.com/capricorn86/happy-dom/issues/544, https://github.com/capricorn86/happy-dom/issues/343).

**Comment by atk** [comment]
The happy-dom issue is supposedly resolved.

**Comment by cnava9389** [comment]
The hydration error can also be fixed if you add solid-js as an inline dependency in vite.config.

test: {
    environment: 'happy-dom',
    includeSource: ['src/**/*.{js,ts,jsx,tsx}'],
    globals: true,
    isolate: true,
    deps: {
      inline: [/solid-js/],
    },
    transformMode: {
      web: [/.[jt]sx?$/],
    }
  }

**Comment by ryansolid** [comment]
Is this issue resolved now?

**Comment by atk** [comment]
The happy-dom issues are fixed by now. Instead of deps.inline = [/solid-js/], the new proposed configuration is deps.registerNodeLoader = true.

**Comment by orenelbaum** [comment]
It seems like the issue can be closed?
The Vitest template seems to be working fine.

**Comment by atk** [comment]
I agree. This can be closed.

**Comment by clemvnt** [comment]
The issue is solved. Thank you all !
