### ISSUE TITLE
What is the right way to initialize DB connection pool on the server and access it inside createServerData/createServerAction?

### ISSUE THREAD

**Issue by zelid** [solidjs/solid-start#254]
Both `createServerData` and `createServerAction` run on the server.

I need to call DB queries from inside `createServerData` / `createServerAction`.

Where should I configure server to initialize DB connection and how to pass the server-context with DB connection to  `createServerData` and `createServerAction`?

**Comment by nksaraf** [comment]
normally you can just create a file called `db.ts` .. initialize a connection there for the server.. and then import that and use it in inside ur createServerData/Action call.. we will keep the code out of the client bundle

**Comment by frenzzy** [comment]
Sorry for rising this question again, but what is the right way of opening and closing db connections on app startup and before hot reload or as a graceful shutdown?

For example in case of TypeORM they do not allow to use models/entities until `AppDataSource.initialize()` is finished (EntityMetadataNotFoundError: No metadata for "User" was found).

Also in case of any code changes in development mode, it opens more and more database connections without closing the old ones.
