### ISSUE TITLE
Actions are sent to client

### ISSUE THREAD

**Issue by mhyfritz** [solidjs/solid-start#26]
This is more of a question, but I was assuming actions are server-only and are not sent to the client. Currently they are, however, and I am getting errors as I am importing Node-only modules.

Is this a bug?

![Screenshot from 2021-10-18 05-48-57](https://user-images.githubusercontent.com/718983/137666541-d389e6ef-e4f0-4e45-bad5-40d6135a94da.png)

**Comment by ryansolid** [comment]
We are replacing actions currently with something more pluggable. I'm going to close this as these are no longer around.
