### ISSUE TITLE
Import error with base project templates

### ISSUE THREAD

**Issue by msherer95** [solidjs/solid-start#260]
I created a new bare project using TypeScript. Clicking the counter buttons does not increment the counter, with the following error in the console:

```
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/solid-js_web.js?v=f66acebf' does not provide an export named 'use' (at Form.tsx:9:10)
```

There seems to be some issue with a ref in `node_modules/solid-start/data/Form.tsx`. If I delete the ref below, the counter button and other signals start working normally:

```
<form
      ref={f => {
        form = f;
        if (typeof props.ref === "function") props.ref(f);
      }}
  ```

**Comment by cperez87** [comment]
Hi @msherer95,
I was getting the same issue. 
I resolved this by changing vite.config.ts
```
export default defineConfig({
  plugins: [solid({ ssr: false })],
});
```
To
```
export default defineConfig({
  plugins: [solid()],
});
```

I had selected "No SSR" during init.

**Comment by EthanStandel** [comment]
Just to add: this makes hydration entirely fail on an example with MDX. The existance of a `<Link />` component in the base template makes the page 500, and if I remove that the `<Counter />` component never actually hydrates. This one is pretty critical and I think makes Solid Start unusable as a whole from the current template.

**Comment by msherer95** [comment]
@cperez87 I was also able to fix this by upgrading to `solid-js@1.5.1`, good call.

**Comment by EthanStandel** [comment]
@msherer95 confirmed, which means this is only a problem with the template, though it very well could scare people away

**Comment by nksaraf** [comment]
yeah we should fix immediately
