### ISSUE TITLE
Cannot deploy to cloudflare due to use of setTimeout outside of request

### ISSUE THREAD

**Issue by patdx** [solidjs/solid-start#261]
Maybe I missed something, but I couldn't find any discussion on this error and could reproduce it easily so I will post here.

I tried to create a fresh project and install the cloudflare adapter based on the example in the repository. It got stuck on this error:

```sh
pnpm wrangler dev --no-bundle

# ...

✘ [ERROR] Error on remote worker: ParseError: A request to the Cloudflare API (/accounts/{{accountId}}/workers/scripts/my-worker/edge-preview) failed.

      at throwFetchError
  (/home/pm/dev/solid-start-test/node_modules/.pnpm/wrangler@2.0.28/node_modules/wrangler/wrangler-dist/cli.js:141293:17)
      at fetchResult
  (/home/pm/dev/solid-start-test/node_modules/.pnpm/wrangler@2.0.28/node_modules/wrangler/wrangler-dist/cli.js:141262:5)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async createPreviewToken
  (/home/pm/dev/solid-start-test/node_modules/.pnpm/wrangler@2.0.28/node_modules/wrangler/wrangler-dist/cli.js:141555:29)
      at async createWorkerPreview
  (/home/pm/dev/solid-start-test/node_modules/.pnpm/wrangler@2.0.28/node_modules/wrangler/wrangler-dist/cli.js:141575:17)
      at async start
  (/home/pm/dev/solid-start-test/node_modules/.pnpm/wrangler@2.0.28/node_modules/wrangler/wrangler-dist/cli.js:142271:34)
  {
    text: 'A request to the Cloudflare API
  (/accounts/aa64ec8db8fac880566631c5c791719d/workers/scripts/workers-websocket-durable-objects/edge-preview)
  failed.',
    notes: [
      {
        text: 'Uncaught Error: Some functionality, such as asynchronous I/O, timeouts, and
  generating random values, can only be performed while handling a request.\n' +
          '  at server.js:706:3 in lazy\n' +
          '  at server.js:2346:16\n' +
          ' [code: 10021]'
      }
    ],
    location: undefined,
    kind: 'error',
    code: 10021
  }
```

(Note: `pnpm wrangler publish, pnpm wrangler dev` also get the same error, but the version above gives a stack trace with line numbers in the compiled server.js, so I use that version for demonstration purposes)

It seems to be throwing the error when setTimeout is called inside of lazy():

https://github.com/patdx/solid-start-cloudflare-test/blob/main/dist/server.js#L706
https://github.com/patdx/solid-start-cloudflare-test/blob/main/dist/server.js#L2346

```
function lazy(fn) {
  // ...
  setTimeout(load); // <-- HERE!
  // ...
```

You can check the compiled code here: https://github.com/patdx/solid-start-cloudflare-test

Possible fixes:

1. skip setTimeout in workers mode:
   ```ts
   // setTimeout(load);
   ```
2. wrap setTimeout in a try catch
   ```ts
   try {
     setTimeout(load);
   } catch (err) {
     console.log(`WARN: ${err}`);
   }
   ```

3. call load without setTimeout
   ```ts
   load();
   ```

4. wrap in promise
   ```ts
     console.log("calling load");
     Promise.resolve().then(() => {
       console.log("beginning preload");
       load();
     });
   ```

Strategies 1~4 seemed to work when I tried modifying the server.js file but I'm not sure which one is correct. I guess this line is preloading the route code? For node or other non-restricted runtimes, especially with multiple files, I think it makes sense to preload when the CPU is free. For cloudflare workers, I guess the script is restricted to be in one file. Also, workers are limited on compute time with only 10ms for the free plan. So I don't know that trying to "preload" it would give any special advantage for cloudlfare. Therefore, (2) may be a good option (though, allowing an error to be thrown and caught for each lazy route on script init feels kind of wrong,,,)

**Comment by ryansolid** [comment]
Yeah.. this is on me, and good to know. We were trying to loosen up lazy loading for dev, but Solid server has no dev mode so I was trying to get something that wouldn't negatively impact production either. I will change the strategy here.  This is part of Solid core and probably won't fly in other environments as well.

**Comment by patdx** [comment]
Thanks, I tried the new solid-js v1.5.3 and it seems to work now :)
