### ISSUE TITLE
Setting a class based on a signal on the Body component fails to update

### ISSUE THREAD

**Issue by EthanStandel** [solidjs/solid-start#262]
The updates from the signal don't seem to fire, and in fact it appears that the JSX-breakout doesn't run at all on the client.

e.g. the log never fires here even initially on hydration

```tsx
<Body class={console.log("hello") || bodyClass() /* <- bodyClass is a signal accessor */} />
```

but it fires here, by just using the native body element

```tsx
<body class={console.log("hello") || bodyClass() /* <- bodyClass is a signal accessor */} />
```

**Comment by nksaraf** [comment]
This should work with the latest release.. alpha.102

**Comment by EthanStandel** [comment]
Confirmed, thank you!
