### ISSUE TITLE
Vercel adapter doesn't seem to work

### ISSUE THREAD

**Issue by OrJDev** [solidjs/solid-start#266]
Basically vercel adapter doesn't seem to work on newer versions of SolidStart, at first i thought it was an error on vercel side but after hours of debugging it seems like it doesn't create the .output dir correctly, here is the response I received from vercel:

Hi there, 

It does look like there's a specific issue with that build, however as this works on an older version of solidstart (our example) then it seems like a specific SolidStart issue which causes the builder to never finish.

I've also tested this using "npm init solid@next" and loading the hackernews template and then running on Vercel, which builds successfully - although the .output files aren't created correctly via the adapter.

I would suggest reverting back your packages to try and identify where your issue lies, try to build from our template and slowly upgrade to identify where the issues lies or asking for assistance on their Github discussions or issues: https://github.com/solidjs/solid-start/discussions

**Comment by ryansolid** [comment]
Hmm.. Vercel engineers updated the plugin themselves and my projects work from manual deploy (ie build locally). So I'd be surprised if the output was wrong unless they changed something again. The template on their site is definitely dated though. Will be updating it soon.

It is possible there is a build issue under their environment though as that is not what I have setup to test. Last time I hit this was someone trying to use node libraries on the edge and it otherwise worked.

**Comment by OrJDev** [comment]
Here is my repo, I don't use anything special. 

https://github.com/OrJDev/solidstart-trpc


Perhaps i did something wrong, i don't know i just followed the adapter docs

**Comment by ryansolid** [comment]
I intend to make a non-edge version of the adapter quicky here.

**Comment by OrJDev** [comment]
Aight let me know (;

**Comment by ryansolid** [comment]
Yeah alpha.101 now defaults to non-edge and edge needs to specify an argument to the options.

**Comment by OrJDev** [comment]
Awesome thanks

**Comment by nksaraf** [comment]
Is this resolved now? @ryansolid

**Comment by ryansolid** [comment]
Well we default to non-edge so I imagine.

**Comment by OrJDev** [comment]
it does work when you build and deploy locally but not via a github repo.
ig it is resolved.
