### ISSUE TITLE
[solid-start-mdx]: allow to pass additional `rehypePlugins ` and `remarkPlugins `

### ISSUE THREAD

**Issue by fabien-ml** [solidjs/solid-start#267]
Hi, 

Currently `soild-start-mdx` doesn't accept params so it's not possible to extends the mdx configuration with additional plugins.

**Comment by ryansolid** [comment]
We should decide the future of this project. We use it for docs. But it isn't really something I believe I"m interested in maintaining as part of SolidStart.. feels outside of it. So we need to decide where this goes.

**Comment by nksaraf** [comment]
probably better outside or private. private is preferred from my side. but if we want to conventionalize some of the mdx infra for solid-start mdx usage, we should split it out.

**Comment by ryansolid** [comment]
I made it private and now there are basically no downloads so.. I'm just going to close this as a won't fix.
