### ISSUE TITLE
ERROR ReferenceError: localStorage is not define, also window

### ISSUE THREAD

**Issue by sdykae** [solidjs/solid-start#269]
I think the function is been created when cliendside - serverside root is been defined so, it does not know browser apis, how can i use this on cliend-side rendering since, i'm not using ssr.

This happens in nextjs also https://github.com/vercel/next.js/discussions/19911
and they say to used `useEffect()` to somehow know its already in the client, but I don't know how to do it with solid-start

https://stackoverflow.com/questions/59540321/in-react-and-next-js-constructor-i-am-getting-reference-error-localstorage-is

```typescript
import { createEffect } from 'solid-js';
import { createStore, SetStoreFunction, Store } from 'solid-js/store';

export const createLocalStore: <T>(
  initState: T & object,
  storeName: string,
) => [Store<T>, SetStoreFunction<T>] = (initState, storeName) => {
  const [state, setState] = createStore(initState);
  // localStorage.getItem
  if (localStorage && localStorage.getItem(storeName)) {
    try {
      setState(JSON.parse(localStorage.getItem(storeName) as string));
    } catch (error) {
      setState(() => initState);
    }
  }
  createEffect(() => {
    localStorage.setItem(storeName, JSON.stringify(state));
  });
  return [state, setState];
};

```
![image](https://user-images.githubusercontent.com/50224521/188411618-2eabf2b5-b40e-49e5-93a1-b078724cd584.png)

**Comment by ryansolid** [comment]
Ideally you'd just initialize the store with the correct data instead of calling setStore immediately. The trickiest part is that the server and client must match for hydration. So generally you probably want to do all the state setting in a `createEffect` that runs after hydration. In this case maybe wrap that first block between the comment and createEffect in an `onMount`.

**Comment by sdykae** [comment]
Updated my implementation, but I think It's ok what you said, need to match.

```typescript
import { createEffect } from 'solid-js';
import { createStore, SetStoreFunction, Store } from 'solid-js/store';

export function createLocalStore<T extends object>(
  storeName: string,
  initStateWhenLocalStorageNull: T,
): [Store<T>, SetStoreFunction<T>] {
  // GET LOCALSTORATE STATE or FallBack
  let initState: T;
  try {
    initState = JSON.parse(localStorage.getItem(storeName));
  } catch (error) {
    initState = initStateWhenLocalStorageNull;
  }

  const [state, setState] = createStore(initState);
  createEffect(() => {

    // SAVE INCOMMING STATE
    const incommingState = { ...state } as T & object;

    // UPDATE STORE FROM LOCAL STORAGE

    localStorage.setItem(storeName, JSON.stringify(incommingState));

  });
  return [state, setState];
}

```
