### ISSUE TITLE
During hydration, `<!DOCTYPE html>` is deleted, which leads to an error in lighthouse

### ISSUE THREAD

**Issue by russelgal** [solidjs/solid-start#27]
![image](https://user-images.githubusercontent.com/3201077/143660108-4185e5ef-29d8-4365-bcf0-4d9b2cd6edc8.png)
lighthouse

![image](https://user-images.githubusercontent.com/3201077/143660284-6caf7c8b-036f-40ba-a37e-d18430ed4704.png)
![image](https://user-images.githubusercontent.com/3201077/143660477-c284ea70-de47-4093-b6ae-e2868c5e709e.png)

**Comment by russelgal** [comment]
it works fine
``` js 
export default function Root({ Start }) {
  return (
    <Start>
//
     {"<!DOCTYPE html>"}
//
      <html lang="en">
        <head>
          <meta charset="utf-8" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1,minimum-scale=1"
          />
          <Meta />
          <Links />
        </head>
        <body>
          <Outlet />
          <Scripts />
        </body>
      </html>
    </Start>
  );
}
```
by deleting here of course

https://github.com/solidjs/solid-start/blob/e493fcb96e85a8064e69a574936ee36c34f8d4d9/packages/start/runtime/entries/stringAsync.tsx#L23

https://github.com/solidjs/solid-start/blob/e493fcb96e85a8064e69a574936ee36c34f8d4d9/packages/start/runtime/entries/nodeStream.tsx#L24

**Comment by LXSMNSYC** [comment]
This seems to be a hydration issue. The doctype markup was removed after page hydration.

**Comment by ryansolid** [comment]
This is fixed now.
