### ISSUE TITLE
CSS modules are not working in development

### ISSUE THREAD

**Issue by dertieran** [solidjs/solid-start#271]
Just upgraded from `alpha.99` to `alpha.101` and noticed that the styles from the css modules did not work anymore.

The elements still had the right classes, but after looking deeper into it I noticed that the `<style>` in the head looked weird. 😄 

```html
<style data-sm="0-0-0-0-0-0-0-0-0-1-1-2-1-0-0-0-0">
	  /* /src/components/Button/Button.module.css */
	  [object Object]
	  /* /src/root.css */
	  body {
		  font-family: -apple-system, BlinkMacSystemFont, “Segoe UI”, Roboto, Helvetica, Arial, sans-serif;
	  }
</style>
```

**FYI:** This is also broken in `alpha.100`

**Edit:** This is only in `dev` mode, when I `build` and `start` the app everything works as expected.

**Comment by dertieran** [comment]
Just tested this again and the `[object Object]` issue was also there in `alpha.99`.
The issue seems to be that now some `<style>` elements are missing.

The styles in the `<head>` looked like this in `alpha.99`

```html
<style>
	  /* /src/components/Button/Button.module.css */
	  [object Object]
	  /* /src/root.css */
	  body {
		  font-family: -apple-system, BlinkMacSystemFont, “Segoe UI”, Roboto, Helvetica, Arial, sans-serif;
	  }
</style>
<style type="text/css">
	  body {
		  font-family: -apple-system, BlinkMacSystemFont, “Segoe UI”, Roboto, Helvetica, Arial, sans-serif;
	  }
</style>
<style type="text/css">
	  ._Button_ynxiq_1 {
		  text-transform: uppercase;
	  }
</style>
```

And after upgrading to `alpha.100` the `<style type="text/css">` are gone and only the first `<style>` element is left *(and it now has a `data-sm` attribute)*.

**Comment by dertieran** [comment]
Hmm in a minimal example I can only reproduce it when I start my classes with uppercase.
So maybe the default for `localsConvention` the changed to `camelCaseOnly` somehow 🤔 
Changing it back to `camelCase` fixed the issue
```js
import solid from 'solid-start/vite';
import {defineConfig} from 'vite';
export default defineConfig({
	plugins: [solid()],
	css: {modules: {localsConvention: 'camelCase'}},
});
```

But this doesn't fix it in my project, but maybe it helps for others.

**Comment by nksaraf** [comment]
This should be fixed in next release https://github.com/solidjs/solid-start/commit/75f40dbe0aa7f1dccd639830dc7289772daf9e05
