### ISSUE TITLE
ssr: html open < is escaped with &lt;

### ISSUE THREAD

**Issue by btakita** [solidjs/solid-start#275]
The following is rendered...Looks like components returning a raw html string will be escaped.

```
&lt;html>
  &lt;head>
...
  &lt;/head>
&lt;/html>
```

**Comment by btakita** [comment]
https://github.com/solidjs/solid-start/issues/273

**Comment by nksaraf** [comment]
Should be fixed by https://github.com/solidjs/solid-start/commit/a0a1c63b1a4adaa1e0a92d0aaa4ba81d03d555ed
