### ISSUE TITLE
createResource not working properly when server-rendered

### ISSUE THREAD

**Issue by jazoom** [solidjs/solid-start#277]
Using SolidJS (with Astro) it was working as expected but with Solid Start it has some strange behaviours.

Take this code for example:
```
export default function Details({ id }: props) {
  const [data] = createResource(id, fetchData);

  return (
    <>
      <Switch fallback={<p>Loading...</p>}>
        <Match when={data.state === "ready"}>
          <div>Something</div>
        </Match>
        <Match when={data.state === "errored"}>
          <p>Error loading</p>
        </Match>
      </Switch>
    </>
  );
}
```

The first problem is the UI is never loaded. It seems `data.state === "resolved"`. TypeScript doesn't like that because it's considered not a valid state and is not documented in SolidJS. Unfortunately checking for `data.state === "ready" || data.state === "resolved"` also doesn't seem to work (I have no idea why not). It *does* work when checking for `data().thingThatWasFetched`.

The second problem is when `fetchData` throws an error I get something like this in the UI:
```
error text

Clear errors and retry
Error: error text
    at C (http://localhost:3000/assets/_id_.ab736406.js:1:1049)
    ...
```

So the `<Match when={data.state === "errored"}>` condition can never be true and I can't figure out how one would avoid showing this ugly error screen to a user.

One other thing I noticed. `fallback={<p>Loading...</p>` is also never shown, even when adding in a delay for the fetch. It's just a blank page until the promise returns.

I suspect this goes beyond just `createResource`.

**Comment by ryansolid** [comment]
Yeah we need to document the usage better. In general you need to read a resource for it to suspend which is why I was hesitant to add all these state things. You should rely on Error Boundaries and Suspense to handle loading and error states. We haven't written good guides. But essentially using these state reads to prevent reading directly means that Suspense never happens. The whole Switch/Match thing won't work as you expect. Nor could it.

**Comment by jazoom** [comment]
Thanks heaps for the response, Ryan. Now that you've pointed that out to me I had another look at the docs for Suspense and you do say something about it: https://www.solidjs.com/tutorial/async_suspense

> It's important to note that it's the read of an async derived value that triggers Suspense, not the async fetching itself. If a resource signal (including lazy components) is not read under the Suspense boundary, it will not suspend.

> Suspense in many ways is just a Show component that renders both branches. While Suspense is vital for asynchronous Server rendering, do not feel the need to jump immediately to using it for client-rendered code. Solid's fine-grained rendering has no additional cost for splitting things manually.

I've been using Svelte for some time, and Vue before that, and React before that, and the term "Suspense" is something I'm unfamiliar with. `createResource` with its states seemed so simple and seemed to work so well I just used that. The thing that draws me to SolidJS is its simplicity and relative lack of magic. I didn't realise I had no choice but to use Suspense when going to server-side rendering.

I think initially I was put off trying out Suspense because I didn't understand it in the docs. That would be mostly because this statement seems backwards to me:

> "If a resource signal (including lazy components) is not read under the Suspense boundary, it will not suspend."

Suspend means to stop something. I would have thought that "suspension" is what happens while awaiting the data, not after it arrives. Indeed, rendering does appear to suspend when I don't use Suspense. But when I use Suspense it completes. Even the way you refer to suspense in your comment above seems strange to me. It might help if it's documented somewhere why it's actually called "suspense", because I just can't wrap my head around why it's called that.

React has this page (https://17.reactjs.org/docs/concurrent-mode-suspense.html) that talks about what appears to be the same concept, but it doesn't seem to use the word "suspense" in the backwards way. For example, this makes sense to me:

> React tries to render <ProfileDetails>. It calls resource.user.read(). None of the data is fetched yet, so this component “suspends”. React skips over it, and tries rendering other components in the tree.

I know worrying about the semantics sounds silly in retrospect, but it might be useful feeback for you to know that because it didn't make sense to me as I was reading the docs I avoided using it.

Regarding the error message, it seems changing `<ErrorBoundary>` to  `<ErrorBoundary fallback={(error) => <p>Some error: {error.toString()}</p>}>` in `root.tsx` clarified what's going on here. That UI I couldn't get rid of seems to be a default UI for an ErrorBoundary that doesn't have a fallback (as is default in Solid Start's template).

Using Suspense and ErrorBoundary makes the JSX less like HTML, which I generally try to avoid. I guess I have no choice but to use them when doing SSR with SolidJS.

Anyway, SolidJS is just amazing. Thanks for making it. I look forward to seeing what you do with Solid Start.

**Comment by jazoom** [comment]
Actually I must still be misunderstanding something. It's not working when I convert this

```
export default function Details({ id }: props) {
  const [data] = createResource(id, fetchData);

  return (
    <>
      <Switch fallback={<p>Loading...</p>}>
        <Match when={data()?.thing}>
          <div>{data().thing}</div>
        </Match>
        <Match when={data.state === "errored"}>
          <p>Error loading</p>
        </Match>
      </Switch>
    </>
  );
}
```

to this

```
export default function Details({ id }: props) {
  const [data] = createResource(id, fetchData);

  return (
    <>
      <Suspense fallback={<p>Loading...</p>}>
        <ErrorBoundary
          fallback={(error) => <p>Error loading</p>}
        >
          <div>{data().thing}</div>
        </ErrorBoundary>
      </Suspense>
    </>
  );
}
```

`data().thing` doesn't exist in the second example. What is missing?

**Comment by jazoom** [comment]
I've done some playing around and adding `Show` makes it work.

```
export default function Details({ id }: props) {
  const [data] = createResource(id, fetchData);

  return (
    <>
      <Suspense fallback={<p>Loading...</p>}>
        <ErrorBoundary
          fallback={(error) => <p>Error loading</p>}
        >
          <Show when={data()?.thing}>
            <div>{data().thing}</div>
          </Show>
        </ErrorBoundary>
      </Suspense>
    </>
  );
}
```

From what I can tell, this shouldn't be necessary, though? Becuase removing `Suspense` in this case also works the same.

**Comment by ryansolid** [comment]
Yeah Solid works differently than React. Suspense holds effects/rendering but it doesn't interrupt or throw promises. It builds up incrementally instead of throwing away and re-rendering. Which means it doesn't change the necessity to null check.
