### ISSUE TITLE
Fails to render on fresh install

### ISSUE THREAD

**Issue by thednp** [solidjs/solid-start#278]
I wanted to give solid-start a try on my Windows machine. Here's all I did
* `npm init solid@next`
* Choose Bare (but any actually)
* Use SSR - YES
* Use TypeScript - YES
* `npm install`
* `npm run dev`

This is what I get
![image](https://user-images.githubusercontent.com/6761246/190902726-c3eb3098-165b-4618-9e5b-dc9e55b12cff.png)

The console shows this error:
![image](https://user-images.githubusercontent.com/6761246/190902904-27983823-6189-4e7d-8454-eeead6687926.png)

What's up?

**Comment by fabianlanzerath** [comment]
I also have this problem! :/

**Comment by davycoe** [comment]
for now make sure you pin the following dependencies in your package.json:
- `"solid-js": "1.5.4"`
- `"vite": "3.0.9"`

should now work, future patches are coming to address the above

**Comment by fabianlanzerath** [comment]
Works, thank you!

**Comment by thednp** [comment]
Confirmed. Thank you
