### ISSUE TITLE
TailwindCSS Example is Broken on MacOS

### ISSUE THREAD

**Issue by osilkin98** [solidjs/solid-start#279]
Hi, I created a new TailwindCSS project from the solid-start list of templates using `pnpm create solid@next` and then installing . After trying with both `pnpm run build; pnpm run start` as well as `pnpm run dev`, I'm seeing the following broken page on every page:

<img width="1040" alt="Screen Shot 2022-09-18 at 3 10 45 PM" src="https://user-images.githubusercontent.com/16809287/190924527-ea5fe1ca-7d80-4ece-9db3-9510ea3af169.png">

solid-start version: `0.1.0-alpha.100`

**Comment by ghalle** [comment]
We are aware of this issue and there is a [commit](https://github.com/solidjs/solid-start/commit/a0a1c63b1a4adaa1e0a92d0aaa4ba81d03d555ed) addressing it.

This should be fixed whenever the next alpha version is released (alpha.104).

In the meantime you can use an older version of solid-js:
```json
"solid-js": "1.5.4"
```

**Comment by osilkin98** [comment]
Okay, great! I’ll rollback to that version for the time being

**Comment by nksaraf** [comment]
Should be fixed in latest solid 1.5.5 and solid-start v0.1.0-alpha.105

**Comment by osilkin98** [comment]
Awesome, I’ll check it out later today!
