### ISSUE TITLE
Don't default to Terser

### ISSUE THREAD

**Issue by CoolOppo** [solidjs/solid-start#283]
Defaulting to Terser breaks code which depends on newer ES features, for example top-level await. I can't compile my code because of this.

https://github.com/solidjs/solid-start/blob/03e94207c9864505ac4aaf2bb015e3d5108881ea/packages/start/bin.cjs#L169

It should probably just match whatever Vite's default is in this regard (esbuild), and the Solid Vite plugin could allow for specifying Terser if that's wanted. This issue makes a lot of my website's code completely break and is stopping me from giving solid-start a good try.

**Comment by ryansolid** [comment]
Good to know. We can change this. I saw this change of default add about 8% to the bundle size so I immediately went back. I wasn't sure the reasoning..

**Comment by CoolOppo** [comment]
Thanks for the quick fix @ryansolid!
