### ISSUE TITLE
`solid-start-vercel` uses edge middleware instead of edge functions.

### ISSUE THREAD

**Issue by soorria** [solidjs/solid-start#287]
The main issue with middleware is that it sits in front of the CDN, so any responses with shared cache headers (e.g. `s-max-age`) don't get cached in the CDN.

Astro had, and [resolved](https://github.com/withastro/astro/pull/4713/files) the same issue and it seems to be a pretty simple update.

**Comment by ryansolid** [comment]
Fixed in 0.1.1
