### ISSUE TITLE
`npm run dev` is broken with solid-js@1.2.6 (Windows)

### ISSUE THREAD

**Issue by bgoscinski** [solidjs/solid-start#29]
**Describe the bug**
I bootstrapped new project using solid-start but when trying to start it I get the error originating from solid-js/dist/server.cjs

**To Reproduce**
Provide a code snippet and steps to reproduce the behavior:

1. `mkdir my-app`
2. `cd my-app`
3. `npm init solid@next`
4. `npm install`
5. make sure that only version 1.2.6 of solid-js is intalled: `npm ls solid-js`
6. `npm run dev -- --open`

**Expected behavior**
No error, example app runs correctly.

**Actual behavior**
```
$ npm run dev -- --open

> dev
> solid-start dev "--open"

Pre-bundling dependencies:
  solid-js
  solid-js/web
  solid-js/store
  solid-js/html
  solid-js/h
(this will be run only when your dependencies or config have changed)
http://localhost:3000
TypeError: Cannot read properties of undefined (reading 'id')
    at wrap (C:\dev\my-app\node_modules\solid-js\dist\server.cjs:385:37)
    at Proxy.createComponent (C:\dev\my-app\node_modules\solid-js\dist\server.cjs:229:10)
    at Object.element.component.element.element [as outlet] (/node_modules/solid-app-router/dist/routing.js:59:35)
    at Object.get children [as children] (c:/dev/my-app/node_modules/solid-app-router/dist/components.jsx:56:57)
    at C:\dev\my-app\node_modules\solid-js\dist\server.cjs:138:35
    at C:\dev\my-app\node_modules\solid-js\dist\server.cjs:106:43
    at createMemo (C:\dev\my-app\node_modules\solid-js\dist\server.cjs:54:13)
    at children (C:\dev\my-app\node_modules\solid-js\dist\server.cjs:106:10)
    at C:\dev\my-app\node_modules\solid-js\dist\server.cjs:138:14
    at createMemo (C:\dev\my-app\node_modules\solid-js\dist\server.cjs:54:13)
```

**Additional context**
Downgrading solid-js to 1.2.5 fixes the issue:
1. Make sure you're using npm that supports overrides: `npm i -g npm@^8.3.0`
2. Apply this change:
    ```diff
    diff --git a/package.json b/package.json
    index b7bd862..21928be 100644
    --- a/package.json
    +++ b/package.json
    @@ -8,7 +8,7 @@
       "type": "module",
       "devDependencies": {
         "solid-app-router": "^0.1.14",
    -    "solid-js": "^1.2.6",
    +    "solid-js": "1.2.5",
         "solid-meta": "^0.27.2",
         "solid-start": "next",
         "solid-start-node": "next",
    @@ -16,5 +16,8 @@
       },
       "engines": {
         "node": ">=12"
    +  },
    +  "overrides": {
    +    "solid-js": "1.2.5"
       }
     }
    ```
3. `rm -rf package-lock.json node_modules`
4. `npm install`
5. make sure that only version 1.2.5 of solid-js is intalled: `npm ls solid-js`
6. `npm run dev -- --open`
```
$ npm run dev -- --open

> dev
> solid-start dev "--open"

Pre-bundling dependencies:
  solid-js
  solid-js/web
  solid-js/store
  solid-js/html
  solid-js/h
(this will be run only when your dependencies or config have changed)
http://localhost:3000
You appear to have multiple instances of Solid. This can lead to unexpected behavior.
computations created outside a `createRoot` or `render` will never be disposed
computations created outside a `createRoot` or `render` will never be disposed
computations created outside a `createRoot` or `render` will never be disposed
computations created outside a `createRoot` or `render` will never be disposed
computations created outside a `createRoot` or `render` will never be disposed
computations created outside a `createRoot` or `render` will never be disposed
computations created outside a `createRoot` or `render` will never be disposed
```

**Comment by fictitious** [comment]
I found that adding this to vite config

```
    ssr: { noExternal: ['solid-js'] },
```

avoids the issue in vite (after deleting `node_modules/.vite` cache)

For solid-start 0.50, you also need these two PRs https://github.com/solidjs/solid-start/pull/39  https://github.com/solidjs/solid-start/pull/40   to fix some other stuff

**Comment by Brendan-csel** [comment]
> I found that adding this to vite config
> 
> ```
>     ssr: { noExternal: ['solid-js'] },
> ```
> 
> avoids the issue in vite (after deleting `node_modules/.vite` cache)

@ryansolid this does seem to resolve building on WIndows.  

So two questions:
- Is this the complete fix so I should close that issue I opened with [vite](https://github.com/vitejs/vite/issues/6080)?
- should this be added to the default `npm init solid@next` templates?

**Comment by fictitious** [comment]
> Is this the complete fix so I should close that issue I opened with vite?

No this just makes vite to use different code path which does not hit that particular bug. 

As I understand, when a lib is in `ssr.noExternals`, vite uses esm export from the lib and bundles it in the usual way (which works). Without `noExternals`, there's [an optimization](https://vitejs.dev/guide/ssr.html#ssr-externals) in vite that uses cjs export from the lib, assuming that it's pre-bundled already (btw esm export from `solid-js` is also pre-bundled, but anyway). The next thing I need to understand to have more progress on that vite issue is how `solid-js` ends up being loaded by `dynamicImport` in vite's `ssrModuleLoaders`, and how it's related to the ssr-externals optimization.

> should this be added to the default npm init solid@next templates?

Only as a temporary workaround I suppose.

**Comment by fictitious** [comment]
I've created a PR for vite: https://github.com/vitejs/vite/pull/6470

**Comment by fictitious** [comment]
PR has been merged and released in vite 2.7.13, so this can be closed I suppose

**Comment by bgoscinski** [comment]
I wanted to retest this but I'll need to wait for https://github.com/solidjs/solid-start/commit/45f3a165489849026e13feeea820cc2000c6ec9a to be released first. Thanks @fictitious!

**Comment by ryansolid** [comment]
try alpha 55

**Comment by bgoscinski** [comment]
Thanks! It works :)
