### ISSUE TITLE
routeData with more than 3 createServerData$ will not call all 3 consistantly

### ISSUE THREAD

**Issue by Tanner-Scadden** [solidjs/solid-start#305]
When you have a routeData with more than 3 createServerData$ inside of it, it won't call all 3 of them consistently. I can create a reproducible environment if needed. Logs of the app:

![image](https://user-images.githubusercontent.com/44242867/195462845-0632e445-7737-4bc4-8dfb-babf6e32b6ad.png)

**Comment by nksaraf** [comment]
A reproduction would be awesome to figure out the issue better

**Comment by nksaraf** [comment]
Any updates on that reproduction? @Tanner-Scadden

**Comment by Tanner-Scadden** [comment]
This was an issue of not directly accessing the data inside of JSX for the categories call. Resources need to be used in a reactive matter during SSR to wait for the data to load before rendering. This does not include createEffects or onMount, since those are not ran on the server. Thanks for the help @nksaraf, closing.
