### ISSUE TITLE
Support pathless route group.

### ISSUE THREAD

**Issue by izznatsir** [solidjs/solid-start#316]
Support route group convention to apply layout for route group members without adding a path segment.

Prior arts:
- [Remix Pathless Layout Routes](https://remix.run/docs/en/v1/api/conventions#pathless-layout-routes)
- [SvelteKit Layout Groups](https://kit.svelte.dev/docs/advanced-routing#advanced-layouts-group)

**Comment by patdx** [comment]
It appears to be in the works here: https://github.com/solidjs/solid-start/commit/977e4518afdb5fe32f6532345fff91d2836cdcb1

**Comment by izznatsir** [comment]
Ahh, the documentation is missing, so I thought it is not yet being implemented. Thanks @patdx for letting me know!
