### ISSUE TITLE
Routing not working correctly

### ISSUE THREAD

**Issue by mosheduminer** [solidjs/solid-start#32]
If you create two files in the pages folder, `Pagination` and `PaginationNav`, navigating to either one will show an empty page, and not render the appropriate route. Removing one of the files causes the remaining page to render properly. You can easily repro by using `npm init solid@next` and adding two pages with a simple function to each.

I just did the above, but using solid-js 1.2.5 (as I am on windows, as per https://github.com/solidjs/solid-start/issues/29), and solid-start `0.1.0-alpha.44` due to solid-js dependency resolution.

**Comment by ryansolid** [comment]
Should be fixed now.
