### ISSUE TITLE
Scroll restoration issues in solid-start docs

### ISSUE THREAD

**Issue by harshmangalam** [solidjs/solid-start#339]
When i visit [What is SolidStart?](https://start.solidjs.com/getting-started/what-is-solidstart)  and scroll to middle of page and after that when i move to [Project setup](https://start.solidjs.com/getting-started/project-setup)  the scroll position is at same place where previous link scroll was. This is happening with all links in docs.

**Comment by reggi** [comment]
I just noticed this as well, it makes me think that I'm being taken to a specific part of the page for a reason, like an fragment, but It's just maintaining the scroll from the previous page.

**Comment by nksaraf** [comment]
Yeah with our new server routing, this is still a problem, that we haven't solved. It wont be in your apps, but our docs are using our experimental stuff.. We are working on fixing this

**Comment by orenelbaum** [comment]
if you turn off the islands router or even switch to csr it still has the same problem

**Comment by ryansolid** [comment]
Now that we are using MPA islands here it doesn't happen. This issue is largely the way the site is designed. We will look at changing that in the future. But for now the issue isn't present.
