### ISSUE TITLE
Cannot read properties of null (reading '$type')

### ISSUE THREAD

**Issue by Tanner-Scadden** [solidjs/solid-start#352]
Getting this error in my app after upgrading to 0.2.0 and 1.6. Originates from this file, line 95. Might be user error, if it is let me know. 

https://github.com/solidjs/solid-start/blob/b720ae2b5dffcbb2cef39217b849ee0b8cbb16c6/packages/start/server/server-functions/browser.ts

**Comment by ghalle** [comment]
We need to add a check to make sure `value` is not null on this line:
https://github.com/solidjs/solid-start/blob/b720ae2b5dffcbb2cef39217b849ee0b8cbb16c6/packages/start/server/server-functions/browser.ts#L95
