### ISSUE TITLE
Docs page responds with invalid HTML

### ISSUE THREAD

**Issue by Olian04** [solidjs/solid-start#354]
I was browsing the docs and got distracted by something else and changed tab. While I was reading the other tab the docs got unloaded by chrome. After a while when I navigated back to the docs tab it reloaded as invalid HMTL. Reloading the page, or letting chrome unload the tab again, solves the issue.

![image](https://user-images.githubusercontent.com/5493406/197344932-ba528af0-48bb-4b26-a604-c1382fc0b4ad.png)

| Name           | Version              |
|:--------------:|:-----------------:|
| Chrome        | 106.0.5249.119 |
| Windows 10 | 19043.2130       |

**Comment by mattmoos** [comment]
Can confirm this. I found out to get it consistently when closing the page and then using "Re-open Closed Tab".
I'm on macOS (Big Sur) and get it in Chrome and Firefox, but not Safari.

**Comment by nksaraf** [comment]
Should be fixed by https://github.com/solidjs/solid-start/commit/46c0fbbf8ac6db85dc6fed40c7b05ccb581cb04b
