### ISSUE TITLE
PnP (Yarn) support

### ISSUE THREAD

**Issue by JonahLund** [solidjs/solid-start#356]
Currently solid-start doesn't work with yarn PnP. More specifically the solid-start _**bin.cjs**_ seems to be incompatible with PnP, the spawned processes that contains paths like `[..."node_modules/vite/bin/vite.js"]` can't be properly resolved.

Thanks!

**Comment by boehs** [comment]
Internally we use PNPM, I don't know if anyone has enough familiarity with yarn to research this

**Comment by JonahLund** [comment]
So yarn PnP removes the node_modules directory and uses a file called .pnp.cjs for dependencies instead, which makes it extremely fast and efficient. However since there is no node_modules directory, binaries cannot be run with ./node_modules/[name]/bin.., So the way to run scripts or programs with PnP is to use _**yarn [binary] ...args**_. I managed to get it to work quite easily by replacing the occurrences where the binaries are ran by directly referencing the node_modules path

So replacing 
```js
spawn(
  "node",
  [
    "--experimental-vm-modules",
    "node_modules/vite/bin/vite.js",
    "dev",
    "--mode",
    "production",
    ...(config ? ["--config", config.configFile] : []),
    ...(port ? ["--port", port] : [])
  ])
```
with
```js
spawn(
  "yarn",
  [
    "run",
    "vite",
    "dev",
    "--mode",
    "production",
    ...(config ? ["--config", config.configFile] : []),
    ...(port ? ["--port", port] : [])
  ])
```

Im guessing the easiest fix is to check if PnP is used and running it similarily to the example above if that's the case.

**Comment by patdx** [comment]
This would also help for monorepos where vite or whatever binary, for example [wrangler](https://github.com/solidjs/solid-start/blob/ca67de6caa0bb350387fd59b6d7a1fc4fea9ab01/packages/start-cloudflare-workers/index.js#L115) is installed in a different dir than solid-start.

Actually according to Yarn's docs, they recommend to just call the binary directly: https://yarnpkg.com/advanced/rulebook#user-scripts-shouldnt-hardcode-the-node_modulesbin-folder, eg:

```js
spawn(
  "vite",
  [
    inspect ? "--inspect" : undefined,
    "dev",
    ...(config ? ["--config", config.configFile] : []),
    ...(port ? ["--port", port] : []),
    ...(host ? ["--host"] : []),
  ].filter(Boolean),
  {
    shell: true,
    stdio: "inherit",
    env: {
      ...process.env,
      NODE_OPTIONS: "--experimental-vm-modules",
    },
  }
);
```

Since it is in the yarn docs, it probably works fine for PnP mode too? Also I believe it could be used for any package manager, no need to check which one first.

**Comment by JonahLund** [comment]
> This would also help for monorepos where vite or whatever binary, for example [wrangler](https://github.com/solidjs/solid-start/blob/ca67de6caa0bb350387fd59b6d7a1fc4fea9ab01/packages/start-cloudflare-workers/index.js#L115) is installed in a different dir than solid-start.
> 
> Actually according to Yarn's docs, they recommend to just call the binary directly: https://yarnpkg.com/advanced/rulebook#user-scripts-shouldnt-hardcode-the-node_modulesbin-folder, eg:
> 
> ```js
> spawn(
>   "vite",
>   [
>     inspect ? "--inspect" : undefined,
>     "dev",
>     ...(config ? ["--config", config.configFile] : []),
>     ...(port ? ["--port", port] : []),
>     ...(host ? ["--host"] : []),
>   ].filter(Boolean),
>   {
>     shell: true,
>     stdio: "inherit",
>     env: {
>       ...process.env,
>       NODE_OPTIONS: "--experimental-vm-modules",
>     },
>   }
> );
> ```
> 
> Since it is in the yarn docs, it probably works fine for PnP mode too? Also I believe it could be used for any package manager, no need to check which one first.

Im pretty sure that in order to run the binaries 'as is' you need to have them globally installed, which is not the case for binaries ran by dependencies such as solid-start

**Comment by JonahLund** [comment]
Well might not be the case atleast, which is why you would run them using ./node_modules/vite directly in the first place

**Comment by nksaraf** [comment]
Ohh if this `NODE_OPTIONS` env variable works, yeah Ill absolutely do this. The reason I switched earlier was to have the `--experimental-vm-modules` stuff
