### ISSUE TITLE
`createResource` (ssrLoadFrom: "initial") with `useParams` doesn't fetch on client-side

### ISSUE THREAD

**Issue by JonahLund** [solidjs/solid-start#370]
When using `createResource` with **ssrLoadFrom: "initial"** to only fetch a resource client side together with `useParams`, it doesn't fetch anything unless you create a reactive value and then set it using `onMount`, which feels like a hacky way of doing it

```js 
// This doesn't work
const param = useParams();

const [data] = createResource(
  () => param.token,
  async (token: string) =>
    await fetch(`http://localhost:8080/${token}`, {
      method: "POST",
      credentials: "include",
    }),
  {
    ssrLoadFrom: "initial",
  }
);
```

```js
// This works
const param = useParams();
const [token, setToken] = createSignal<string>();

onMount(() => setToken(param.token));

const [data] = createResource(
  token,
  async (token: string) =>
    await fetch(`http://localhost:8080/${token}`, {
      method: "POST",
      credentials: "include",
    }),
  {
    ssrLoadFrom: "initial",
  }
);
```

**Comment by ryansolid** [comment]
I think there may be a misunderstanding what the intention is of the feature.

As of right now we don't have a client fetch option for `ssrLoadFrom`. What happens is either we use `initial` and it loads the value from `initialValue` option for both client and server and only updates on source change after the fact. This is for if the data is say coming in from somewhere else. I wouldn't expect anyone to use this with SolidStart. It's mostly for things like Astro or Vite Fastify where the data is resolved before rendering in Solid. These handle serialization so we just need to make sure the resource loads with the right data.

If the data fetching is happening in SolidStart then the expectation would be to just use it without the option and pass the promise in that is fetched on the server. In this case we fetch on the server, serialize the data, and restore it on the client. Any future changes will trigger on the client.

Now if the desire is to not fetch on the server and only in the client. Yeah I'd use null version on both sides, so it hydrates the same and then set it in `onMount` like you did. There may be a client option in the future for `ssrLoadFrom` but it'd basically be doing that as we need SSR and hydration to match so we can't client fetch anything until after hydration is done.

**Comment by JonahLund** [comment]
> ou create a reactive value and then set it using `onMount`, which feels like a hacky way of doing it
> 
> ```js
> // This doesn't work
> ```

Alright. got it. Yeah i didn't think too much about what `ssrLoadFrom` actually did, my intentions were to only fetch data from the client using `createResource`, and i found that `ssrLoadFrom` somewhat did something with that haha
