### ISSUE TITLE
Spelling issue in the template project.

### ISSUE THREAD

**Issue by MAST1999** [solidjs/solid-start#379]
I built a new project using `pnpm create solid`, and selected tailwindcss template with server rendering and typescript.

Need to change optimise to optimize in the `README.md`.

![2022-10-29_01-36](https://user-images.githubusercontent.com/48868969/198740709-0da51cb3-f8ba-42b2-9639-9306db8ac914.png)

**Comment by mattbdc** [comment]
Optimise is the correct spelling, perhaps something got lost when we exported the language. I love your colo**u**r scheme though...

**Comment by MAST1999** [comment]
Oh right... my spell checkers (I checked with two) was screaming at me.

Didn't know "optimise" can be written like this as well.

P.S. the color scheme is onedark.
