### ISSUE TITLE
Solid start build sometimes stalls (with ssr: false)

### ISSUE THREAD

**Issue by OrJDev** [solidjs/solid-start#383]
(Sometimes) Log stucks on vercel when trying to build & deploy, no error or anything it just freezes.
It does work when trying to build locally but it is pretty annoying having to wait for it to build before running 
```bash
vercel deploy --prebuilt.
```

Any idea what causes that?

**Comment by OrJDev** [comment]
(here)
![Screenshot_1](https://user-images.githubusercontent.com/91349014/198890037-94e61108-67ad-453e-addb-85f763920750.png)

**Comment by nksaraf** [comment]
I think this might be a bug with our SPA mode build. We start a vite dev server to ask for the index.html but we should probably figure out a different solution. I have some ideas. You can keep ssr: true for now? That should be more reliable

**Comment by OrJDev** [comment]
Based on my stack I really prefer not to, but if that's the only solution I'll do that.

**Comment by nksaraf** [comment]
Just a workaround for vercel until we fix this.. or you can build locally and deploy using `vercel deploy --prebuilt`

**Comment by OrJDev** [comment]
> Just a workaround for vercel until we fix this.. or you can build locally and deploy using `vercel deploy --prebuilt`
> 
> 

Bulding it locally will not work when using prisma, requires additional configuration which i need to dig into a little bit more and since all of my projects use prisma this is not a solution for me

**Comment by nksaraf** [comment]
Ahh okay makes sense. Is there a repo I can look at and try.. Have been meaning to figure out is prisma works properly.. I can debug the issues better than way

**Comment by OrJDev** [comment]
Ye its a private repo so i will add you as a contributor

**Comment by nksaraf** [comment]
Ahh okay so it works when deployed from vercel website but not locally ?

**Comment by OrJDev** [comment]
Ye i mean you could try any repo that uses prisma, not mine specifically. If you build it locally and deploy it using the cli it will throw some ssl xxx weird error, therefore it needs to be built on vercel environment instead.

**Comment by aidanaden** [comment]
hi! i ran into the same issue when using `pnpm` as my package manager, solved this issue by using `yarn` instead! issue might have something to do with `pnpm` maybe?

**Comment by atzzCokeK** [comment]
The same thing happens to me. Suddenly It can't be deployed. I tried to use `yarn` instead of pnpm, but never solved.
I add source code about <Context>, that might cause this failed?
![image](https://user-images.githubusercontent.com/25091548/202617582-6dbcd634-2153-4fb5-829a-147339da277b.png)

**Comment by atzzCokeK** [comment]
When I change ssr mode, the error is updated!
![image](https://user-images.githubusercontent.com/25091548/202618307-fd48129b-4eb9-49f4-9e5d-8a73bbdd1416.png)

**Comment by OrJDev** [comment]
Currently developing my company's app using solid start, planing on hosting on Vercel. Any update on that?

**Comment by rshov** [comment]
Same problem here

**Comment by OrJDev** [comment]
edit:

this doesn't seem like a vercel only issue, just tried cloudfare and i get the exact same issue:
```
> build
> solid-start build

 solid-start build 
 version  0.2.7
(node:2979) ExperimentalWarning: The Ed25519 Web Crypto API algorithm is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 adapter  cloudflare-workers

solid-start building client...
solid-start rendering index.html...
```

**Comment by ryansolid** [comment]
Please retry again 0.2.19. I've made some big improvements to `ssr: false`. I can't reproduce the issue locally at least by messing with imports.

**Comment by OrJDev** [comment]
> Please retry again 0.2.19. I've made some big improvements to `ssr: false`. I can't reproduce the issue locally at least by messing with imports.

Yes this seems to work with the exact same project that failed with older versions:

```


solid-start building client...
--
10:13:47.448 | solid-start rendering index.html...
10:13:49.696 | solid-start index.html rendered in: 2.248s
10:13:49.736 | vite v3.2.5 building for production...
10:13:49.763 | transforming...
10:13:53.533 | ✓ 212 modules transformed.
10:13:53.602 | Inspect report generated at /vercel/path0/.solid/inspect


```

closing this
