### ISSUE TITLE
Failed to import entry-server

### ISSUE THREAD

**Issue by ddPn08** [solidjs/solid-start#385]
When I try to build with solid-start@0.2.2 I get the following error:
![image](https://user-images.githubusercontent.com/71378929/198992478-e51a9373-a53b-402c-b61a-80cf3185f9d6.png)
I understood that [this commit](https://github.com/solidjs/solid-start/commit/766737e4799afca7deae05b2f96cc5a4c38e70c3) had an effect, but I didn't know how to fix it, so I created an issue.

**Comment by nksaraf** [comment]
Yeah my bad this was a slip up: can u bump to 0.2.3, it should be fixed
