### ISSUE TITLE
[Bug] Whitespace Around JSX Expressions in Native DOM Elements Errs on Load

### ISSUE THREAD

**Issue by tcardlab** [solidjs/solid-start#389]
<details>
  <summary> <h3> Spaces around {props.title} [line 10] generates error on page load: </h3>  </summary>
  <img width="841" alt="Screen Shot 2022-10-31 at 10 18 30 PM" src="https://user-images.githubusercontent.com/35203441/199144548-c72f8866-0bdb-49c7-8fea-5f326a914f8a.png">
</details>

<details>
  <summary> <h3> Removing spaces around {props.title} [line 10] fixes error: </h3>  </summary>
<img width="839" alt="Screen Shot 2022-10-31 at 10 18 52 PM" src="https://user-images.githubusercontent.com/35203441/199144525-471faa31-fc79-4a6d-bc3d-5aad20be97bd.png">
</details>

<details>
  <summary> <h3> Console Error: </h3>  </summary>
  <img width="679" alt="Screen Shot 2022-10-31 at 10 34 38 PM" src="https://user-images.githubusercontent.com/35203441/199146622-b097e24d-7b58-4631-aea1-1dc56ef19862.png">
</details>

<br/>

Discovery:
https://stackblitz.com/edit/github-7nvpqz-6bopea?file=src/components/Page.tsx

Minimum reproduction (with bumped versions):
https://stackblitz.com/edit/github-7nvpqz-z7feez?file=src/components/Page.tsx

*Note: custom elements not affected by bug*

**Comment by ryansolid** [comment]
I believe this is fixed with a new package lock. Re-open if still having an issue.
