### ISSUE TITLE
Support a base path prefix for links and scripts

### ISSUE THREAD

**Issue by jculvey** [solidjs/solid-start#391]
The `<Scripts>` and `<Links>` components don't currently allow for a base path to be specified. This makes it difficult to support use cases where requests for assets contained in the manifest are proxied through another service that assumes a different path for the assets.

**Comment by atk** [comment]
You can specify a base property in the vite configuration. I already fixed the issue that this did not work previously.

**Comment by jculvey** [comment]
Awesome, thanks!
