### ISSUE TITLE
Optional entry-client and entry-server

### ISSUE THREAD

**Issue by QuentinDutot** [solidjs/solid-start#392]
Suggestion: **make entry-client and entry-server files optional**

In most cases these files will stay unchanged and only add unnecessary boilerplate.
For comparison, in NextJs the _app/ _document files are optional and can be added if any code is required in it.

_I haven't checked the code, I have no idea about the complexity behind._

**Comment by nksaraf** [comment]
Secret is that this should already work! Try it.. But we don't want to promote that too much. its better to have visibility into what the entry point is doing just in case you want to customize
