### ISSUE TITLE
vite behavior is optional: "When you use imports, Vite will create a hashed filename"

### ISSUE THREAD

**Issue by milahu** [solidjs/solid-start#396]
https://github.com/solidjs/solid-start/blob/996f2b72878cf753e4ac8a4dedbea791643ad74d/docs/core-concepts/static-assets.md?plain=1#L58

this can be disabled for pretty asset paths

example vite.config.js ([source](https://github.com/milahu/nix-eval-js/blob/main/demo/vite.config.js)) based on https://github.com/vitejs/vite/issues/378

```js
import { defineConfig } from 'vite';
import solidPlugin from 'vite-plugin-solid';

const assetsDir = '';
//const assetsDir = 'assets/';

const outputDefaults = {
  //format: 'iife', // default

  // remove hashes from filenames
  entryFileNames: `${assetsDir}[name].js`,
  chunkFileNames: `${assetsDir}[name].js`,
  assetFileNames: `${assetsDir}[name].[ext]`,
}

export default defineConfig({
  base: "./", // generate relative paths in html
  plugins: [
    solidPlugin(),
  ],
  build: {
    target: 'esnext',
    //polyfillDynamicImport: false,
    //sourcemap: true,
    minify: false, // smaller git diffs
    // example sizes for solidjs app with monaco-editor
    // false: 5396.78 KiB // smaller git diffs
    // 'esbuild': 2027.36 KiB // default
    // 'terser': 2002.37 KiB
    rollupOptions: {
      output: {
        ...outputDefaults,
      }
    },
  },
  esbuild: {
    // keep names of functions an classes
    keepNames: true,
  },
  worker: {
    rollupOptions: {
      output: {
        ...outputDefaults,
      }
    },
  },
});
```

limitation: files generated by `@vitejs/plugin-legacy` still have a hash https://github.com/vitejs/vite/issues/378#issuecomment-841779745

**Comment by nksaraf** [comment]
Yeah sounds fair. thanks to this issue people will find this workaround. But we don't want to get people too much into the weeds with vite configs. So simply wanted to explain the various use cases in which these techniques might be helpful.
