### ISSUE TITLE
"__dirname is not defined in ES module scope" when running "solid-start start"

### ISSUE THREAD

**Issue by viridia** [solidjs/solid-start#398]
When I attempt to run "npm start" in my solid-start project, I get the following error:

```
file:///Users/talin/Projects/solid/colloquy/dist/server.js:36542
	import_path.default.join(__dirname, "../query-engine-darwin");
	                         ^

ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Users/talin/Projects/solid/colloquy/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/talin/Projects/solid/colloquy/dist/server.js:36542:27
    at file:///Users/talin/Projects/solid/colloquy/dist/server.js:48573:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)

Node.js v18.10.0
```

**Comment by JonahLund** [comment]
Make sure to add the `.cjs` extension to any javascript file you add instead of just `.js`

**Comment by pawelblaszczyk5** [comment]
Actually it's caused by Prisma being a CJS dependency. You can solve it by externalizing it, like this: https://github.com/pawelblaszczyk5/planotes/blob/4b24f1d74735856bc438ba72c4ac036e9d198a73/apps/web/vite.config.ts#L8

**Comment by huzaifahj** [comment]
@pawelblaszczyk5 what if our Prisma client is in another folder in a monorepo? This is only what worked for me:

```ts
import { createRequire } from "module"
const require = createRequire(import.meta.url)
const { PrismaClient } = require("../../../prisma/prisma-client/index.js")
```

**Comment by mkreuzmayr** [comment]
@huzaifahj @pawelblaszczyk5 Here is the type-safe solution I came up with.

https://github.com/prisma/prisma/issues/5030#issuecomment-1398076317
> 
> ```typescript
> import type { PrismaClient as ImportedPrismaClient } from '@prisma/client';
> import { createRequire } from 'module';
> 
> const require = createRequire(import.meta.url ?? __filename);
> 
> const { PrismaClient: RequiredPrismaClient } = require('@prisma/client');
> 
> const _PrismaClient: typeof ImportedPrismaClient = RequiredPrismaClient;
> 
> export class PrismaClient extends _PrismaClient {}
> ```
