### ISSUE TITLE
solid-start build output missing routes when run in monorepo structure

### ISSUE THREAD

**Issue by dallastjames** [solidjs/solid-start#403]
I've been playing with (and absolutely loving) solid/solid start for the last week. One of the oddities that I've come across is that building the project in a monorepo structure seems to throw off the build outputs and cause the resulting build to be missing all of the routes.

In my example below, I've taken the solid-hackernews app and built it in a non-monorepo structure (left) and in a simple pnpm workspace (right). In the latter, the `index.html` and any other relevant "page" files are missing from the build output. This example is using the vercel adapter, but I also get the same behavior using the default `node` adapter.

![image](https://user-images.githubusercontent.com/16655763/200359789-65c4cf4e-a9d2-4319-b845-6f78d9d416f5.png)

In my testing, i'm using PNPM, which shouldn't be affected by the monorepo support information on the readme to my understanding. 

A repo showing this behavior can be found here:

[monorepo](https://github.com/dallastjames/solid-start-hackernews-pnpm-workspace-invalid-generation)  
[not monorepo](https://github.com/dallastjames/solid-start-hackernews-pnpm-workspace-invalid-generation/tree/not-monorepo)

Reproduction steps:

* Clone repo
* `pnpm i`
* `pnpm --filter hackernews build`
* OR `pnpm build` for non-monorepo
* compare the contents of the built `dist/public` directory

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
