### ISSUE TITLE
build problem in docker

### ISSUE THREAD

**Issue by baravak** [solidjs/solid-start#406]
A lot of time passes but nothing happens
![image](https://user-images.githubusercontent.com/953471/200414497-3bdacef5-2b7a-4b9a-b5dd-218285982059.png)

**Comment by ryansolid** [comment]
This looks related to ssr: false. Using the root to render the index.html seems to have issues on certain platforms.

What version of Node are you on?

**Comment by mantysalo** [comment]
Faced the same issue with `ssr: false` on Node v16.1.0

Node v16.19.0 works normally and v18.11.0 works fine as well.

Is there something that can be done to enable some debugging logs?

**Comment by ryansolid** [comment]
I think we need v16.8 or higher. I can look at potential for logging more.

**Comment by ryansolid** [comment]
I'm going to close this one and consider the logging question part of #383.
