### ISSUE TITLE
Invalid JavaScript produced when route data has null prototypes

### ISSUE THREAD

**Issue by viridia** [solidjs/solid-start#422]
The `graphql` package generates objects with `null` prototypes. When these objects are returned from `createServerData$`, they get serialized as `Object.assign(Object.create(null), { ...props... }))`. Unfortunately, it looks like the code generator is adding an extra right parens ')' after the call to `Object.assign()`, so this generates a syntax error in the browser.

This only affects the initial HTML; subsequent fetches work fine.

**Comment by viridia** [comment]
I eventually worked around this problem by post-processing the object to covert all the objects in the response to have normal prototypes.

**Comment by viridia** [comment]
Based on the Discord chat from a few weeks ago, I think Ryan might have added a fix for this but I am not sure.

**Comment by ryansolid** [comment]
I exposed our SolidJS serializer so now we can change how stuff is serialized but I haven't wired it up.

**Comment by ryansolid** [comment]
NVM.. I did fix this: https://github.com/ryansolid/dom-expressions/commit/23464e548436e0a59a2fba2113f3877ee2af7b4e
