### ISSUE TITLE
An unhandler error occured: print stack trace to stderr

### ISSUE THREAD

**Issue by btakita** [solidjs/solid-start#450]
It is very difficult to locate the error without a stack trace.

https://github.com/solidjs/solid-start/blob/main/packages/start/dev/server.js#L26

**Comment by AshSimmonds** [comment]
Oh gosh there it is! There's only 2 places on the indexed internet where `An unhandler error occured` occurs - and they're from eons ago. Was driving me nuts with an untraceable error.

**Comment by btakita** [comment]
I pulled out all but 2 strands of hair on my head
