### ISSUE TITLE
Vite config server port ignored

### ISSUE THREAD

**Issue by tomexx** [solidjs/solid-start#456]
Hi all,

I found out that Solid Start ignores configuration from `vite.config.ts`

I tried to run the app on a different port than `3000`:

```
export default defineConfig({
	plugins: [solid()],
	server: {
		port: 3005,
	},
})
```

I run the dev mode with:

```
solid-start dev --config vite.config.ts
```

But the server port from config file is ignored and the app runs on default port `3000`

**Comment by ryansolid** [comment]
Yeah I got that --port thing from SvelteKit but I guess Vite has its own way to of doing this and we should align with that more probably.

**Comment by beans42** [comment]
Found a fix for this, remove the default --port 3000 argument from the cli.
https://github.com/solidjs/solid-start/blob/0566cf57e02a75c189884ddd235f26b595efe965/packages/start/bin.cjs#L41
