### ISSUE TITLE
Error creating dinamyc route - MDX template

### ISSUE THREAD

**Issue by carlostobon** [solidjs/solid-start#457]
[vite] connecting... client.ts:19:8
[vite] connected. client.ts:134:14
import.meta.env.DEV = true mount.tsx:19:9
import.meta.env.PROD = false mount.tsx:20:9
import.meta.env.START_SSR = true mount.tsx:21:9
import.meta.env.START_ISLANDS = false mount.tsx:22:9
import.meta.env.START_ISLANDS_ROUTER = false mount.tsx:23:9
import.meta.env.SSR = false mount.tsx:24:9
Unable to find DOM nodes for hydration key: 0-0-0-0-0-0-0-0-0-1-0-0-2-0-1-1-0-0-0-0-0 dev.js:249:38
Unable to find DOM nodes for hydration key: 0-0-0-0-0-0-0-0-0-1-0-0-2-0-1-1-0-0-1-0-0 dev.js:249:38
Unable to find DOM nodes for hydration key: 0-0-0-0-0-0-0-0-0-1-0-0-2-0-1-1-0-0-2-0-0 dev.js:249:38

Error: Unrecoverable Hydration Mismatch. No template for key: 0-0-0-0-0-0-0-0-0-1-0-0-2-0-1-1-0-0-1-0-0

    getNextElement dev.js:250
    Dynamic dev.js:583
    runComputation dev.js:694
    updateComputation dev.js:677
    createMemo dev.js:238
    Dynamic dev.js:573
    c dev.js:516
    untrack dev.js:421
    c dev.js:512
    runComputation dev.js:694
    updateComputation dev.js:677
    devComponent dev.js:523
    createComponent dev.js:1220
    o index.mjs:1
    c dev.js:516
    untrack dev.js:421
    c dev.js:512
    runComputation dev.js:694
    updateComputation dev.js:677
    devComponent dev.js:523
    createComponent dev.js:1220
    _createMdxContent [...404].mdx:3
    MDXContent [...404].mdx:36
    hmrCompWrapper @solid-refresh:10
    untrack dev.js:421
    hmrCompWrapper @solid-refresh:10
    runComputation dev.js:694
    updateComputation dev.js:677
    createMemo dev.js:238
    hmrCompWrapper @solid-refresh:7
    wrap dev.js:1365
    untrack dev.js:421
    wrap dev.js:1358
    runComputation dev.js:694
    updateComputation dev.js:677
    runTop dev.js:770
    runQueue dev.js:840
    completeUpdates dev.js:796
    runUpdates dev.js:787
    writeSignal dev.js:649
    setter dev.js:195
    wrap dev.js:1346
ErrorBoundary.tsx:27:29

**Comment by SufianBabri** [comment]
I am seeing this error as well. Hasn't this been fixed yet?

**Comment by SufianBabri** [comment]
I have resolved it by downgrading to vite 3.1.2.

Thanks to [Ryan's comment](https://github.com/solidjs/solid-start/issues/532#issuecomment-1477357308):
> Yeah this hydration issue seems to be related to the Vite 4.0 update. Downgrading to Vite 3.1.2 seems to fix it. HMR I can't speak to yet.
