### ISSUE TITLE
Confused About Nested Routes

### ISSUE THREAD

**Issue by knpwrs** [solidjs/solid-start#463]
With the following file structure:

```
routes
├── [...404].tsx
├── foo
│   └── index.tsx
└── index.tsx

1 directory, 3 files
```

And the following contents for `routes/index.tsx`:

```tsx
import { Outlet } from "solid-start";

export default function Home() {
  return (
    <main>
      <p>Root</p>
      <Outlet />
    </main>
  );
}
```

and `routes/foo/index.tsx`:

```tsx
import { Outlet } from "solid-start";

export default function Home() {
  return (
    <main>
      <p>Foo</p>
      <Outlet />
    </main>
  );
}
```

I was expecting visiting `http://localhost:3000/foo` to have two paragraphs, one saying `root` followed by another saying `foo`. What I'm finding, however, is that `/` only shows `root` (expected) and `/foo` only shows `foo` (not expected).

After reading the nested routes documentation I tried the following file structure:

```tsx
src/routes
├── [...404].tsx
├── index
│   ├── auth
│   │   └── login.tsx
│   └── auth.tsx
└── index.tsx

2 directories, 4 files
```

Both `index.tsx` and `auth.tsx` are essentially:

```tsx
import { Outlet } from 'sold-start';

export default function ComponentName() { // Either Index or Auth
  return <Outlet />
}
```

And `login.tsx` is simply:

```tsx
export default function Login() {
  return <h2>Login!</h2>
}
```

I've tried other various file and folder layouts but I can't seem to get nested routing to work, and all of the example projects only go one route deep as far as I can tell.

I also commented on this older issue: https://github.com/solidjs/solid-start/issues/107#issuecomment-1313086232

**Comment by knpwrs** [comment]
Ultimately what I was trying to achieve is a series of routes like `/`, `/foo`, and `/foo/bar`, and have the route at `/` act as the layout for `/foo`, `/foo/bar`, and everything else under `/`. After playing around with it a bit more, I managed to achieve this with the following file structure:

```
src/routes
├── [...index]
│   ├── foo
│   │   └── bar.tsx
│   └── foo.tsx
└── [...index].tsx

2 directories, 3 files
```

Is that the idiomatic way to accomplish what I'm describing?

**Comment by knpwrs** [comment]
I can also see some new docs that have been pushed to the repo but not published to the website yet. The following also seems to achieve what I'm after:

```
src/routes
├── (home)
│   ├── foo
│   │   └── bar
│   │       └── (bar).tsx
│   └── foo.tsx
└── (home).tsx

3 directories, 3 files
```

**Comment by roalmeida** [comment]
You have to declare the route that is used as the layout in the Root.tsx file. In my tests it didn't work using just the route file structure

``` js
<Route path='/home' compoment={<HomeLayout />}>  // home.tsx
  <Route path='/home/foo' compoment={<Foo/> }/> // home/foo.tsx
</Route>
```

**Comment by emilbonnek** [comment]
> I can also see some new docs that have been pushed to the repo but not published to the website yet. The following also seems to achieve what I'm after:
> 
> ```
> src/routes
> ├── (home)
> │   ├── foo
> │   │   └── bar
> │   │       └── (bar).tsx
> │   └── foo.tsx
> └── (home).tsx
> 
> 3 directories, 3 files
> ```

@knpwrs yep, this is also what I was trying to say above too actually. I just do the same with `(app).tsx` and an `(app)` folder.. I consider this to be the most idiomatic way of doing it. The `(home).tsx` file becomes a 'layout' component for everything inside the `(home)` directory.

**Comment by knpwrs** [comment]
Ah, okay! Thank you! I think I grok the way rooting with now.

**Comment by JohnCido** [comment]
Rename my index.tsx and index folder to (app) did solve the problem. But I think this should be added to the document site too? Since many websites do have a shared layout across all pages (e.g. shared header and footer).
