### ISSUE TITLE
cannot find package 'stream' imported from node_modules/solid-start/node_modules/solid-start/node/globals.js

### ISSUE THREAD

**Issue by DivyanshuBhoyar** [solidjs/solid-start#464]
Project created with pnpm create solid.
With typescript and without typescript.

Using node v16.3.0 on linux/pop-os

![Screenshot from 2022-11-20 10-23-49](https://user-images.githubusercontent.com/64900631/202886514-0fec3fd4-18ae-4afc-854f-90c79570d500.png)

**Comment by patreeceeo** [comment]
I'm able to work around this by upgrading Nodejs to the 18.12.1 LTS release, fwiw.

**Comment by ryansolid** [comment]
Hmm.. I am pretty sure newer 16's should be fine too. We using `undici` and it uses some node internals that came in later 16 releases.
