### ISSUE TITLE
degit error when setting up a project

### ISSUE THREAD

**Issue by jakelazaroff** [solidjs/solid-start#465]
Hi! Just tried out Solid Start and had trouble setting up the project because of a `degit`-related zlib error. I dug around and found [an open bug report in the `degit` repo](https://github.com/Rich-Harris/degit/issues/313).

The fix in that issue (clearing the cached files in `~/.degit`) cleared it up for me, but I figured I'd let y'all know in case you wanted to investigate (or switch to `tiged` as another commenter suggests).

**Comment by ryansolid** [comment]
Yeah I imagine we won't do too much and just rely on the downstream issue. Looks like other issues linked are all closed. Thanks for making the issue. So people can find it if they hit it.
