### ISSUE TITLE
Solid Start not working with Vercel

### ISSUE THREAD

**Issue by CrispyBacon1999** [solidjs/solid-start#471]
I'm trying to deploy my site with Vercel, but it gives a 404 no matter what I have it configured with. I have SolidStart selected in the project settings, with the `dist` folder set as the output. It seems like the SSR server isn't starting up and Vercel is trying to just serve from the folders directly. Going to https://rainbowrumble.org/server.js, it just gives the server directly. Any ideas on how to fix this?

**Comment by poohcom1** [comment]
You'll have to use the vercel adapter: https://github.com/solidjs/solid-start/tree/main/packages/start-vercel. The setup is pretty simple, but it's pretty experimental so you might run into some issues that you'll have to find a workaround (I had issues with front-end libraries breaking serverless functions).

**Comment by CrispyBacon1999** [comment]
That did it, thanks! Never would have thought to do that.
