### ISSUE TITLE
server env variables require additonal configuration / packages

### ISSUE THREAD

**Issue by OrJDev** [solidjs/solid-start#480]
Currently enviroment variables that are not prefixed with `VITE_` will not be loaded,
variables that are prefixed with `VITE_` will be exposed to the client (`import.meta.env`),
what causing it so there is no such thing as `server env variable` in SolidStart.

this could easily be fixed using dotenv:
```ts
import solid from "solid-start/vite";
import dotenv from "dotenv";
import UnoCSS from "unocss/vite";
import { defineConfig } from "vite";
// @ts-expect-error no typing
import vercel from "solid-start-vercel";
  
export default defineConfig(() => {
  dotenv.config();
  return {
    plugins: [
          solid({ ssr: false, adapter: vercel({ edge: false }) }),
          UnoCSS(),
        ],
  };
});
```
but I think that it should not be handled in our end as SolidStart is a meta framework, and should be loading server variables by default.

**Comment by ryansolid** [comment]
I agree. I imagine you have an idea of what this should look like. Is it just adding dotenv? Open to following your lead here as I've never really looked at this part in other meta frameworks. I've heard that SvelteKit does well here but that's about it.

**Comment by OrJDev** [comment]
Ye you just have to add dotenv, and call the config function. As you can see in the example above it is that simple.

**Comment by OrJDev** [comment]
Check out how nuxt does it

https://github.com/nuxt/nuxt.js/blob/dev/packages/config/src/load.js

**Comment by OrJDev** [comment]
just make sure to merge and test: examples/bare is where i tested it

https://github.com/solidjs/solid-start/pull/585

**Comment by OrJDev** [comment]
Reopened, close when my pr gets merged please

**Comment by apatrida** [comment]
Are these build-time or runtime variables?  i.e. if you do a production build and have not yet defined `VITE_SOMETHING` then will `VITE_SOMETHING` be available on the client if it is only defined before running the build?

SveltKit supports both static (build time) and dynamic (runtime) variables and docker containers, k8s will want to use runtime and not build time since secrets maybe are not baked into the container and are provided later.

**Comment by JakkuSakura** [comment]
A note here:
app.config.ts requires dotenv yourself
