### ISSUE TITLE
`createServerData$`'s are running on the client in certain circumstances

### ISSUE THREAD

**Issue by oscartbeaumont** [solidjs/solid-start#487]
If my understanding is correct under no circumstance `createServerData$` should be executed on the client but under a few conditions, I have been able to make it do that. I have been able to isolate the problems and have put them into this demonstration repository [here](https://github.com/oscartbeaumont/solidstart-bug).

It seems to be coming down to having a `createServerData$` being defined in a utility file outside of the current page but I don't know enough about the internals of SolidJS to draw any conclusion or know how to help fix this.

Thanks for your time, I have been loving SolidStart!

**Comment by ryansolid** [comment]
I think we are only transforming .jsx/.tsx files right now which is the issue here.

**Comment by oscartbeaumont** [comment]
Renaming the file to `tsx` fixed it, thanks.

I definitely think `ts` and `js` should be added given I think that is going to catch out new users.

It's also a pretty confusing default behavior to just run it on the hook on the client so I also recon an error should be thrown instead.

**Comment by ryansolid** [comment]
I'm already tracking this issue. So closing.
