### ISSUE TITLE
[Bug] Routes are not resolved correctly because of an incorrect regex

### ISSUE THREAD

**Issue by emme1444** [solidjs/solid-start#49]
Some files in the `pages` directory are incorrectly resolved as routes.

For example:

`src/pages/rockets.tsx` --> `/rock.tsx`

This is because the periods (`.`) in the below regex are not escaped.

https://github.com/solidjs/solid-start/blob/596bc2e8c290cb5dc02f9b994a16836e0554ad69/packages/start/routes.js#L22-L24

**Comment by nksaraf** [comment]
Thanks for pointing this out. I observed this myself. Thanks for fix too in the PR.
