### ISSUE TITLE
Build succeeds despite transformations failed

### ISSUE THREAD

**Issue by pawelblaszczyk5** [solidjs/solid-start#494]
It looks like the build is succeeding even if Solid Start specific transformations using esbuild fails. I would expect it to exit with non-0 code so it would properly fail e.g. GitHub actions. 

Reproduction: https://stackblitz.com/edit/vitejs-vite-mktcwb?file=package.json 

Steps: 
- Go to reproduction
- Run `npm run build`
- Build succeeds despite errors and broken output

Note: I know what's the solution to the fail in reproduction (usage of unsupported by Solid Start's esbuild version TypeScript syntax) 😛

**Comment by ryansolid** [comment]
I see what you are saying. I just tried adding an ESBuild plugin that just throws, and it was the same. So it seems like Vite doesn't care if ESBuild fails. I don't know how important this is to fix, but it doesn't appear to be within our control. Could be worth taking up with Vite.
