### ISSUE TITLE
Move the docs website to a separate repo

### ISSUE THREAD

**Issue by orenelbaum** [solidjs/solid-start#501]
I think that it would probably be a good idea to move the website to a separate repo in order to reduce the noise in this repo.
This repo also has a lot of open issues at the moment and a bunch of pull requests and opening issues and creating pull requests for the website will create a big mess.

**Comment by marshallswain** [comment]
While the repo issues may seem more challenging to navigate, the benefits you get from keeping the docs in the same repo tend to make it easier to make high-quality contributions that stay in sync with the docs.  Having managed FeathersJS docs using both ways, I've come to prefer keeping everything together.  When you treat docs like a separate product, they tend to get treated like a second-rate product.  Not having to coordinate and jump between repos for a PR is really lovely.

**Comment by orenelbaum** [comment]
Apparently the plan is to create a new website at some point, this website is temporary. So I'm going to close this issue.
