### ISSUE TITLE
Remove hardcoded `node_modules`

### ISSUE THREAD

**Issue by rtritto** [solidjs/solid-start#506]
Not all package managers use `node_modules` as target folder to save modules.
An example is _yarn Berry_, with Plug'n'Play enabled (pnp loader), that use `./yarn/cache` or global cache folder instead of `node_modules` one.

All absolute imports to relative imports:
Example for [packages/start/vite/index.d.ts](https://github.com/solidjs/solid-start/blob/main/packages/start/vite/index.d.ts):
```diff
- import { Plugin } from "node_modules/vite";
+ import { Plugin } from "vite";
```

**Comment by ryansolid** [comment]
Yeah this is super strange. Maybe it was an auto code import? @nksaraf

**Comment by rtritto** [comment]
@ryansolid node_modules comes back [packages/start/vite/index.d.ts](https://github.com/solidjs/solid-start/blob/main/packages/start/vite/index.d.ts)

**Comment by rtritto** [comment]
@ryansolid can this issue be reopened?
