### ISSUE TITLE
How to programmatically create element during SSR

### ISSUE THREAD

**Issue by charkour** [solidjs/solid-start#507]
I'm trying to create a `<Typography />` component with an `as` prop. The `as` prop allows the user of the component to change the HTML element rendered (`'h1'`, `'h2'`, etc). 

With client-side Solid.js, I'm able to use `document.createElement(as)`, but with SolidStart, `document` is undefined on the server which throws an error. Is there a workaround for this? I'm looking for a way to create an element based on props passed to the component. Perhaps using VDOM libraries has tainted the way I think about components. Potentially, I could use a `<Switch />` from `'solid-js'` to render different components. `createComponent` from Solid doesn't work because `as` is not a function but a string. 

This is the code in question: 

```tsx
export const Typography: Component<Props> = ({ as = "h1", ...rest }) => {
  const element = document.createElement(as);
  spread(element, rest);
  typeof rest.children === "string" &&
    setAttribute(element, "id", rest.children);

  return element;
};

function App() {
  return (
    <div>
      <Typography>H1</Typography>
      <Typography as="h2">H2</Typography>
    </div>
  );
}
```

Here's a [playground](https://playground.solidjs.com/anonymous/c9373890-4236-49a7-a800-4d1023675fef) that works with Solid.js, but not on the when server-rendered. 

The ideal solution would be to import `createElement` from `'solid-start'` which works isomorphically.

```tsx
import { createElement } from 'solid-start';

export const Typography: Component<Props> = ({ as = "h1", ...rest }) => {
  const element = createElement(as);
  spread(element, rest);
  typeof rest.children === "string" &&
    setAttribute(element, "id", rest.children);

  return element;
};

function App() {
  return (
    <div>
      <Typography>H1</Typography>
      <Typography as="h2">H2</Typography>
    </div>
  );
}
```

**Comment by pawelblaszczyk5** [comment]
Solid has a built-in Dynamic component made for that 😀 https://www.solidjs.com/docs/latest/api#dynamic 

You can pass strings like "h1" to dynamically create arbitrary tags

**Comment by charkour** [comment]
Hey @pawelblaszczyk5,

That works wonderfully. When searching for a solution, my search terms must have been wrong. 

Thanks for the quick response!
