### ISSUE TITLE
 DOMException: Failed to execute 'querySelector' on 'Element': 'style[s:id="67a5277a-0-1"]' is not a valid 

### ISSUE THREAD

**Issue by Ladvace** [solidjs/solid-start#508]
Template: **with-solid-styled**

When clicking on the anchor link "about" (which doesn't exist) I got the following error:

` DOMException: Failed to execute 'querySelector' on 'Element': 'style[s:id="67a5277a-0-1"]' is not a valid `

after that you are not able to update the counter clicking on the counter button

**Comment by orenelbaum** [comment]
This is a bug in solid-styled.
I opened an issue there:
https://github.com/lxsmnsyc/solid-styled/issues/12
So you can close this issue.
