### ISSUE TITLE
[enhancement] Add dark mode to the docs website

### ISSUE THREAD

**Issue by orenelbaum** [solidjs/solid-start#512]

**Comment by dayvster** [comment]
I'm game for taking this on as well if it's cool?

**Comment by hamirmahal** [comment]
It looks like https://start.solidjs.com/ supports theme switching.

**Comment by hamirmahal** [comment]
![image](https://github.com/solidjs/solid-start/assets/43425812/3707205b-900c-4896-b05a-7d4b6e25abef)

**Comment by hamirmahal** [comment]
And https://docs.solidjs.com/solid-start does, too.

**Comment by hamirmahal** [comment]
![image](https://github.com/solidjs/solid-start/assets/43425812/8a6d0944-e24a-4dc7-82af-910da637e5fb)

**Comment by hamirmahal** [comment]
@ryansolid do you want to close this?

**Comment by brenelz** [comment]
Yeah i think this can be closed
