### ISSUE TITLE
CSR mode not working with index.html in dev mode 

### ISSUE THREAD

**Issue by Vexcited** [solidjs/solid-start#518]
Hello, when we use the `index.html` method for CSR, the rendered HTML in dev mode is completely different and omits everything defined in the index.html

It just uses a default root.tsx if it doesn't exist and don't take what I have in my index.html file.

Hope someone can help me- Thanks!

**Comment by ryansolid** [comment]
Yeah we don't use index.html. THe idea was to use all the same mechanisms. So the root gets built at build time into index.html. I don't know if this is the best, but that was the intention.

**Comment by Vexcited** [comment]
Oh okay, didn't knew that. Even though, at production build time it uses the `index.html` if it exists so that's a little confusing I guess.

By the way, when using `root.tsx` without ant `index.html`, the built `index.html` doesn't put scripts in the body at all even if we put `<Scripts />` in `<Body>`.

In result, I had to add a DOM load event listener in the `entry-client.tsx` of one of my projects to fix a "`document.body` is `undefined`" error.

**Comment by Vexcited** [comment]
Also, I opened this issue because of a problem with `vite-plugin-pwa` which doesn't add the built `index.html` in the service-worker.

Results to the PWA not working offline because of `index.html` not cached.

I fixed this problem by using both `index.html` and `root.tsx` but don't know if that's good practice.

**Comment by ryansolid** [comment]
Hmm.. I've been playing a bunch with ssr: false and I see script/style insertion and the body tag. Is the problem with vite-plugin-pwa it doesn't recognize where index.html is located?

**Comment by Vexcited** [comment]
> Is the problem with vite-plugin-pwa it doesn't recognize where index.html is located?

Yeah pretty much since with an index.html it works by default.

**Comment by lhjt** [comment]
> I fixed this problem by using both `index.html` and `root.tsx` but don't know if that's good practice.

I'm also trying to use this plugin, but I have SSR enabled. Would you be able to provide an example/link to the docs where you found how to add `index.html`? (I have been searching but been unable to find)

**Comment by Vexcited** [comment]
> workbox: {
>   additionalManifestEntries: [{ url: "/index.html", revision: null }],

I also tried this before but the issue with `revision: null` is that your HTML file will never be updated! I came up with a solution to provider the hash of the generated HTML and put it in that revision object but it didn't worked well and each updates didn't worked properly.

**Comment by Vexcited** [comment]
> I'm also trying to use this plugin, but I have SSR enabled. Would you be able to provide an example/link to the docs where you found how to add `index.html`? (I have been searching but I have been unable to find it - running into the same `index.html` has not been precached error)

I don't know if it's in the docs but I would recommend looking directly at the unit tests for SPA so you get the latest examples.

Here it is for the `index.html` file, <https://github.com/solidjs/solid-start/blob/c9c3e5524a3e363f9745fb5ca037a4436ae61eea/test/spa-test.ts#L51-L63>

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
