### ISSUE TITLE
[create-solid] Allow mixing-and-matching settings

### ISSUE THREAD

**Issue by thislooksfun** [solidjs/solid-start#524]
The starter examples are good, but it would be nice if there was a way to mix-and-match the features, rather than picking just one at a time. For example, say I want auth + tailwind + websocket, unless I'm missing something there's currently no way to get just that set of features. It's not a requirement, but it would be a really nice QoL feature for getting new devs up-and-running quickly.

**Comment by orenelbaum** [comment]
duplicate of https://github.com/solidjs/solid-start/issues/496

**Comment by thislooksfun** [comment]
So it is!
