### ISSUE TITLE
bug: build is not esm compatible

### ISSUE THREAD

**Issue by apollo79** [solidjs/solid-start#529]
I am using `solid-start` with the `node` adapter and `Prisma`. The `dev` mode works completely fine, however, when I build the application and try to run it with `pnpm start`, I get this error:

```
file:///<path_to_project>/dist/server.js:36641
        import_path2.default.join(__dirname, "../query-engine-darwin");
                                  ^

ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/<path_to_project>/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///<path_to_project>/dist/server.js:36641:28
    at file:///<path_to_project>/dist/server.js:52455:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)

Node.js v18.12.1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by apollo79** [comment]
This seems to be a well-known issue with `prisma`, which isn't fully `esm` compatible: https://github.com/prisma/prisma/issues/5030. The issues / comments I found matching exactly this problem with `__dirname`, are: 
- https://github.com/prisma/prisma/issues/15614
- https://github.com/prisma/prisma/issues/5030#issuecomment-1258275202
- https://github.com/prisma/prisma/pull/4920#issuecomment-1261174902

I tried a few of the workarounds, but nothing seems to work for `solid-start`

**Comment by pawelblaszczyk5** [comment]
You should externalize Prisma, you can look here for an example 😀

https://github.com/solidjs/solid-start/issues/398

**Comment by binajmen** [comment]
> You should externalize Prisma, you can look here for an example 😀
> 
> #398

It seems to solve it indeed. Do you know what is the impact when doing this magic?

**Comment by Hubro** [comment]
> It seems to solve it indeed. Do you know what is the impact when doing this magic?

My assumption is that Prisma won't be bundled with the server, which means you'll actually have to install it as a dependency wherever you end up deploying your server.
