### ISSUE TITLE
`redirect()` doesn't work when called after await boundary using `renderAsync`/`renderStream`

### ISSUE THREAD

**Issue by thislooksfun** [solidjs/solid-start#533]
When using `renderAsync` or `renderStream` mode the `redirect()` call inside of a `createServerData$` block does absolutely nothing.

Example:

```tsx
// entry-server.ts
import {
  createHandler,
  renderAsync,
  StartServer,
} from "solid-start/entry-server";

export default createHandler(
  renderAsync(event => <StartServer event={event} />)
);
```

```tsx
// src/routes/secret.tsx
import { createServerData$, redirect } from "solid-start/server";

export default () => <h1>How did you get here??</h1>;

export const routeData = () => {
  return createServerData$(async () => {
    // Delay execution until the next async frame.
    await new Promise(resolve => setTimeout(resolve, 0));
    return redirect("/");
  });
};
```

Navigating to `/secret` _should_ redirect you to `/`, but it doesn't. If you comment out the `await new Promise` line however, it _does_ redirect properly.

When using `renderSync` the redirect works as expected, but for performance reasons I would rather use `renderAsync`/`renderStream`.

---

I am using `solid-start@0.2.7`, `solid-js@1.6.4`, `vite@3.2.5`, and `node@18`.

**Comment by nksaraf** [comment]
This is happening because you are not using routeData in your component. So it actually doesnt wait for the `createServerData$` to finish on the server (since it presumes you dont need it). If you use the `useRouteData` in your component, in the JSX , you will get the redirect happening on the server.

**Comment by thislooksfun** [comment]
@nksaraf It seems I over-simplified my example in the search of an MRE, but it still happens even when I have `useRouteData`:

```tsx
import { Show } from "solid-js";
import { useRouteData } from "solid-start";
import { createServerData$, redirect } from "solid-start/server";

export function routeData() {
  return createServerData$(async (_, { request }) => {
    const url = new URL(request.url);
    const token = url.searchParams.get("token");

    // Arbitrary delay to simulate doing something actually async.
    await new Promise(resolve => setTimeout(resolve, 0));
    if (token !== process.env.SECRET_TOKEN) throw redirect("/");

    return process.env.SECRET_DATA;
  });
}

export default function Page() {
  const data = useRouteData<typeof routeData>();
  return (
    <Show when={!data.loading} fallback={<h1>Loading...</h1>}>
      <h1>The secret data is: {data()}</h1>
    </Show>
  );
}
```

**Comment by thislooksfun** [comment]
Hmm. Actually it appears that I can fix that example by changing it to `when={!data.loading || data() instanceof Response}`, but my actual code is still not working even with that check...

**Comment by thislooksfun** [comment]
Ah, I think I figured it out. If you call `data()`, then it works. If you only check `data.loading`, then `data()` is never called, and thus the redirect is never executed.

**Comment by thislooksfun** [comment]
I both do and don't agree. I would expect that if you call `useRouteData` that it would process any redirects, whether you call the resulting signal or not (like the example of just checking `data.loading`). However if I don't call `useRouteData` I would actually expect the `routeData` function _not_ to be called. Perhaps with a separate magic export (like `routeAccess`) that will be called when the route is trying to load, but doesn't actually return any data to the client side.

However, both of those are separate discussions to the bug described in this issue, so should be reported in new issues instead.

**Comment by binajmen** [comment]
You're probably right.

I created a new issue to better explain the inconsistencies I noticed: https://github.com/solidjs/solid-start/issues/574
