### ISSUE TITLE
Enhanced anchor tags changing search params doesn't trigger reload of routeData

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-start#538]
Moving from /test to /test?param=4 doesn't trigger an update in the routeData despite it being a different route.

**Comment by ryansolid** [comment]
This might be poor naming of the field so it isn't obvious where to find the reactive version. We have a reactive query object based off location which might be what is necessary here. You'd access it like `location.query.test`.

This works with the router. See users page in this example: https://codesandbox.io/s/solid-app-router-example-nr288?file=/pages/users.js

If there is still an issue, post some code and I can look at it.

**Comment by arsaizdihar** [comment]
I have the same issue. I used location.query as key of createServerData in routeData but when navigate to different url query doesn't refetch the routeData
```ts
export function routeData({ location }: RouteDataArgs) {
  return createServerData$(
    ([_, _dif]) => {
      const level = [28, 37, 45, 58];
      let dif = Number(_dif);
      // ...
    },
    { key: ["game", location.query.dif] }
  );
}
```

**Comment by ryansolid** [comment]
Key should be a function for it to be reactive. We need better documentation.

**Comment by birkskyum** [comment]
Here is some code - My expectation was that triggering "A" would change the url, rerun the createRoute similar to what happens at the end of a createRouteAction, and that both "url data" and "route data" would update accordingly. This works when using the "a" tag as it just reloads the page (repo [here](https://github.com/birkskyum/anchor-test-solid-start)) - I've tried adding location as a key function in createRouteData, but maybe I wired it up wrong.

```tsx
import { Show } from "solid-js";
import { A, createRouteData, useLocation, useRouteData, useSearchParams } from "solid-start";

export function routeData(){

  const location = useLocation();

  return createRouteData<number>(()=>{
    return parseFloat(location.query.test) * Math.round(Math.random()*10)
  })
}

export default function Home() {
  const data = useRouteData<typeof routeData>()

  const location = useLocation();
  return (
    <>
      <p>Url data: {location.query.test}</p>
      <Show when={data()}>
        <p>Route data: {data()}</p>
      </Show>

      <A href={`/?test=${Math.random()}`}>Change query parameter</A>
    </>
  );
}
```

**Comment by ryansolid** [comment]
The whole point is not to rerender. If the route doesn't change we don't run `routeData` again. We just update the reactive parameters. This allows the most minimal work to be done. Only resources that listen to those params will update.

**Comment by ryansolid** [comment]
Similar to #562. Just added more docs for this thanks to #567.
