### ISSUE TITLE
Elements are not being placed under the right parent.

### ISSUE THREAD

**Issue by ItzDerock** [solidjs/solid-start#560]
When you try to insert children into a component like this:
```jsx
<p style={'color: red;'}>
  {children}
</p>
```
solid-start will instead render it like this:
```jsx
<p style={'color: red;'}></p> {children}
```

See this example: 
code: https://replit.com/@derock/some-solid-testing
demo: https://some-solid-testing.derock.repl.co
(codesandbox doesn't have a solid-start template, so I used replit instead)

This example is a simple plain `npm init solid` app with a new Test component defined like this:
```tsx
import { JSX } from "solid-js";

export default function TestComponent({ children }: {
  children: JSX.Element
}) {
  return (
    <div>
      text before child
      
      <p style={{ color: "red" }}>
        {children}
      </p>

      text after child
    </div>
  )
}
```

and when used like this:
```tsx
<Test>
   <pre>testing</pre> a b c
   <em>this</em> should be red text
 </Test>
```
the children get placed outside of the `<p>` component:
![example](https://derock.media/r/28sc6H.png)

I tested this out too on the solid.js sandbox, and it works fine there, so it seems like an issue with solid-start's ssr.

**Comment by russelgal** [comment]
https://github.com/solidjs/solid/discussions/287#discussioncomment-240864

**Comment by ItzDerock** [comment]
> [solidjs/solid#287 (comment)](https://github.com/solidjs/solid/discussions/287#discussioncomment-240864)

Tried the same example, but without deconstructing props, and the issue persists.
https://replit.com/@derock/some-solid-testing-pt2

Tried passing in children like this: `<p children={props.children} />` to no avail.

**Comment by ryansolid** [comment]
This is the browser automatically "fixing" badly formed HTML. `<pre>` appears to not be allowed in`<p>` and browser self closes it.
