### ISSUE TITLE
Have createServerAction$ default to redirecting to the calling page?

### ISSUE THREAD

**Issue by thislooksfun** [solidjs/solid-start#568]
Currently you need to return/throw a `redirect()` from `createServerAction$`, even you just want to use it for an on-page event (like adding something to a to-do list, for example). Returning a redirect isn't the end of the world, but it is confusing for the default behavior to be navigating to a page with the return value of the server action. it's especially annoying because it means that pages with server actions now need to know their own paths, which I would rather not do, if possible, as it means that if I ever move/rename the route, then I need to remember to update the `redirect()` in that file.

Ideally `createServerAction$` would be able to generate a default `return (await actionFn()) ?? redirect(__source_route__);` pattern, where `__source_route__` is, obviously, the path to the route file. That way it behaves sensibly in the default case (reloading the same page we started on), but if we _want_ the action to redirect somewhere else (for a login form, for example), then we still can.

I don't see any benefit for being able to direct to the JSON response page, as if you want to render a nice page on form success you should `redirect()` to a results route, and if you want an API you shouldn't be using `createServerAction$` for it anyway.

**Comment by ryansolid** [comment]
Yeah this is actually hard to guarantee. It was the first thing I saw when making the Todo example but with JS turned off we don't have the easiest way to ensure we get the data. The referrer of the request may not be there. And we can't add custom stuff on the request without JS.

All that we could think of was rendering it into the form like an automatic hidden field so maybe that's the way to go.

**Comment by thislooksfun** [comment]
An automatic hidden field would definitely work, but only if you're using the `Form` style of action. Calling it directly still wouldn't work... Maybe make it so that if you don't have the hidden field then it errors if you don't return/throw a Response? Or even just override the default action page renderer to show a more useful error? At least that way we could tell devs "hey, you _need_ to return a redirect here or else things won't work as expected", rather than the current confusing "here's a JSON blob!"

**Comment by thislooksfun** [comment]
> An automatic hidden field would definitely work, but only if you're using the `Form` style of action. Calling it directly still wouldn't work...

...except that if you are able to call it directly, then JS is working and we can inject custom data no problem. 🤦

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
