### ISSUE TITLE
`createServerData$` only being transpiled in .jsx/.tsx files

### ISSUE THREAD

**Issue by thislooksfun** [solidjs/solid-start#572]
I don't know whether this is intentional, or even fixable, but if you call `createServerData$` outside of a `.tsx` file, it does not get properly transpiled. I noticed this when I tried to make some helper functions that, since none of them use JSX directly, I put in a `.ts` file. When looking at the output, however, I noticed that it did not transpire that code correctly. Inside of `.tsx` files it transpires just fine, as expected, but I would expect that it would work the same in all source files, since they all get lumped into the bundle.

**Comment by ryansolid** [comment]
Duplicated #408
