### ISSUE TITLE
`createServerData$` not properly tree shaking if declared outside of route

### ISSUE THREAD

**Issue by thislooksfun** [solidjs/solid-start#573]
I'm trying to make a helper for fetching some commonly-accessed data in my app using `createServerData$`. When I define the getter inside the route itself, everything works fine. But as soon as I try to move that helper out to a different file, it starts bringing server-only code into the client bundle, which then breaks the app.

Example: (`ensureSession` depends on server-only code, and should not be included in the client bundle)

```tsx
// src/routes/working-fine.tsx
import { type Component } from "solid-js";
import { Title, useRouteData } from "solid-start";
import { createServerData$ } from "solid-start/server";

import { ensureSession } from "~/util/auth";

export const routeData = () => {
  return {
    session: createServerData$((_, { request }) => ensureSession(request)),
  };
};

const Page: Component = () => {
  const { session } = useRouteData<typeof routeData>();
  return (
    <>
      <Title>Working as expected!</Title>
      <div class="flex flex-col items-center gap-2">
        <pre>{JSON.stringify(session(), undefined, 2)}</pre>
      </div>
    </>
  );
};

export default Page;
```

```tsx
// src/util/auth.tsx
export const ensureSession = async (req: Request) => {
  /* <snip> */
};

export const ensureSessionData = () => {
  return createServerData$((_, { request }) => ensureSession(request));
}
```

```tsx
// src/routes/broken.tsx
import { type Component } from "solid-js";
import { Title, useRouteData } from "solid-start";
import { createServerData$ } from "solid-start/server";

import { ensureSessionData } from "~/util/auth";

export const routeData = () => {
  return {
    session: ensureSessionData(),
  };
};

const Page: Component = () => {
  const { session } = useRouteData<typeof routeData>();
  return (
    <>
      <Title>I Am Broken :(</Title>
      <div class="flex flex-col items-center gap-2">
        <pre>{JSON.stringify(session(), undefined, 2)}</pre>
      </div>
    </>
  );
};

export default Page;
```

The first route, `working-fine.tsx`, works as expected. Everything loads with no errors. The second route, on the other hand, throws an error because it's trying to initialize server-only code on the client side.

If this is not enough information, let me know and I can put together an MRE repository.

**Comment by xluk9** [comment]
Is that a typo? In `auth.tsx` you don't export `ensureSession` but only `ensureSessionData`, while in `working-fine.tsx` you import `ensureSession` from `auth`.

**Comment by thislooksfun** [comment]
Ah, whoops. Yeah that was a typo from when I tried to simplify after I copy-pasted. It has been fixed.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
