### ISSUE TITLE
Inconsistencies between GET and POST on the same route?

### ISSUE THREAD

**Issue by binajmen** [solidjs/solid-start#574]
When hitting a route directly (typing the url + enter and/or refresh -> both leading to a GET) or indirectly (following a `<A>` link -> leading to a POST), the behaviour are not the same.

Here a code snippet:
```ts
export function routeData() {
  return createServerData$(async (_, { request }) => isAdmin(request));
}

export default function Admin() {
  return (
      <AdminLayout>
        <Outlet />
      </AdminLayout>
  );
}

export async function isUser(request: Request) {
  const { id } = await authenticator.isAuthenticated(request, {
    failureRedirect: "/",
  });

  const user = await prisma.user.findUniqueOrThrow({ where: { id } });

  return user;
}

export async function isAdmin(request: Request) {
  const user = await isUser(request);

  if (!user.isAdmin) {
    throw redirect("/en/login");
  }

  return user;
}
```
With the above code snippet, if I'm not an admin but I access the route directly, no redirection will happen. I have the same behaviour with this variant (still not consuming the `data()`):
```ts
export default function Admin() {
  const data = useRouteData<typeof routeData>();

  return (
      <AdminLayout>
        <Outlet />
      </AdminLayout>
  );
}
```

It's only when I consume the data that the redirection happen:
```ts
export default function Admin() {
  const data = useRouteData<typeof routeData>();

  return (
    <Show when={data()}>
      <AdminLayout>
        <Outlet />
      </AdminLayout>
    </Show>
  );
}
```

I understand this is perhaps the expected behaviour: "if you don't consume the useRouteData, why bothering calling it?". As a newcomer, it was not clear for me.

But:

1. If I put some `console.log` here and there, I clearly see them in the server console, only the redirect is not catched/processed in snippet 1 and 2.

2. The redirection is not working in snippet 1 and 2 when hitting directly the route. In the server log, it is a `GET http://localhost:3000/admin/organisations`

3. The redirection do work however with snippet 1 and 2 when following a link `<A>`. In the server log, the call is different: `POST http://localhost:3000/_m/src/routes/admin/organisations.tsx/0/routeData`

The inconsistencies between 2 and 3 seems suspicious: depending the way we used to reach the page, the behaviour is different. I believe it should not.

Besides the fact that this kind of "blank" operation could (should?) be done in a middleware (but I did not find any examples yet), I'm wondering what is the current approach to perform such things?

**Comment by ryansolid** [comment]
Yeah.. this is a bit of fun. Resource reads are what trigger Suspense so without reading it the page has already responded before redirecting so it is a no-op. However on subsequent route navigation it is hitting the server function URLs directly and just getting the data. The client would still need to read to suspend, but it at worst means premature navigation.

**Comment by binajmen** [comment]
I understand the logic way better day after day. Is it correct to "force" things by having `<Show when={data()}>` at the root of the JSX?

Thank you for the clarification, I'll close this issue to not pollute the real ones.
