### ISSUE TITLE
[Docs] CSR / SSR / SSG

### ISSUE THREAD

**Issue by vchirikov** [solidjs/solid-start#589]
Hi, first of all - thanks for your work, awesome.

I have read the documentation and didn't find the information about how to switch between rendering strategies per page for example, is it possible to enable SSG only for certain route parameters and so on.

Could you add this to the docs?

**Comment by leoj3n** [comment]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/990216/209452798-341c751e-6697-449c-9aca-0c2b427d9699.png">

**Comment by leoj3n** [comment]
https://youtu.be/O2kFXlNSdn0?t=3363

**Comment by leoj3n** [comment]
I'm trying to understand what people are wanting to do here... If we imagine a website that, for instance, allows users to anonymously edit/publish custom movie poster ideas (plus a blurb for the backstory) and then browse other published submissions... Such a website may have the following parts:

- Marketing Landing Page <sub>(Static page that links to the blog, editing app, and explorer)</sub>
- Paginated List of Blog Posts <sub>(List of blog posts with next/prev links and current page number)</sub>
- Blog Page w/ Expandable Comments <sub>(Blog post content and comments with expandable replies)</sub>
- Movie Poster Editing App <sub>(An app that is heavy along the lines of Figma/Photoshop)</sub>
- Published Movie Posters Explorer <sub>(Search functionality and data pulled from an API)</sub>

If I understand correctly, people are thinking depending on the vertical route vector the user is hitting, you may want to employ different strategies, perhaps like:

| Marketing Landing Page | Paginated List of Blog Posts | Blog Page w/ Expandable Comments | Movie Poster Editing App | Published Movie Posters Explorer |
| :--: | :--: | :--: | :--: | :--: |
| SSG | SSR | SSR | CSR | Islands? |
| Default Example | Hackernews Demo | Hackernews Demo | Figma / Photoshop Equivalent | Solid Start Movie App |

There are some questions which this raises that may not have clear answers such as:

- First and foremost, have I understood what people are wanting to do here?
- What if the user comes in via one vector (let's say the static marketing page) and then navigates to another vector (let's say any of the other pages)... Will this be a seamless transition, or will this force some suboptimal refresh that is actually a deoptimization on the whole?
- Would this add sufficient complexity to make for a bad development tradeoff, or would it be a simple convention?

**Comment by leoj3n** [comment]
@vchirikov https://astro.build/ has a generator written in Go which is probably the fastest option if you are trying to pre-generate a huge number of routes and it also provides plugins for most JS frameworks hydration scripts that can optionally be deferred until client interaction. It also has an SSR mode, where Astro uses HTML streaming to send each component to the browser as it renders them. While the components you write for Astro look like typical JS it is actually parsed in Go and just HTML is what's delivered... They use WASM at some point in the process perhaps for the "frontmatter" which is JS code that can be executed for any given component during build/ssr.

**Comment by leoj3n** [comment]
@vchirikov I think it's not too hard to get SPA router into the MPA... Astro docs:

> SPAs can also offer more powerful transitions across page navigation because they control so much about page rendering. To match this support, MPAs leverage tools like Hotwire’s [Turbo](https://turbo.hotwired.dev/) that mimic client routing by also controlling navigation in the browser. The HTML is still rendered on the server, but Turbo can now display a seamless transition between pages similar to client routing in an SPA.

- https://docs.astro.build/en/concepts/mpa-vs-spa/
- https://turbo.hotwired.dev/
- https://github.com/Charca/astro-movies/blob/main/src/scripts/spa-navigation.js
- https://github.com/natemoo-re/micromorph
- https://www.youtube.com/watch?v=yLmD7BZCY4Q

**Comment by leoj3n** [comment]
@vchirikov You linked the Svelte docs which sounds like they have implemented exactly what you are wanting to do right now... Question for you is why not just use SvelteKit in that case?

As far as I can deduce, currently SolidStart supports many of the same modes but they are not integrated, and instead work on a whole-project basis...

> SPA, SSR, Islands, Island Routing or any of SolidStart's other capabilities.

> https://start.solidjs.com/api/vite#solid-startvite
> The vite plugin exposes the following options:
> - prerenderRoutes (string[], default []): list of route paths to prerender (currently only works with static adapter).
> - ssr (boolean, default true): toggles between client rendering and server rendering (ssr) mode.
> - islands (boolean, default false): experimental toggles on "islands" mode.
> - islandsRouter (boolean, default false): experimental toggles on hybrid "islands" routing.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Comment by leoj3n** [comment]
@ryansolid Can you give a quick update on where things stand in regards to what was discussed here? Haven't had a chance to keep up with Solid to know if things have changed and am just curious what your thoughts are. If you have a moment to clarify/debunk any assumptions made here, that would be great!

**Comment by ryansolid** [comment]
Yeah we are in a much better state now. You can basically make any adapter static by putting:

```
export default defineConfig({
  server: {
    static: true
    prerender: {
      routes: [] // array of routes
      crawlLinks: true // automatic route detection based on urls
    }
  }
})
```
This stuff is all documented on Nitro site. And there is some documentation on the start docs: https://start.solidjs.com/core-concepts/route-prerendering

**Comment by juji** [comment]
> Yeah we are in a much better state now. You can basically make any adapter static by putting:
> 
> ```
> export default defineConfig({
>   server: {
>     static: true
>     prerender: {
>       routes: [] // array of routes
>       crawlLinks: true // automatic route detection based on urls
>     }
>   }
> })
> ```
> 
> This stuff is all documented on Nitro site. And there is some documentation on the start docs: https://start.solidjs.com/core-concepts/route-prerendering

The link is now https://docs.solidjs.com/solid-start/building-your-application/route-prerendering 

for whoever searching..

thanks @ryansolid
