### ISSUE TITLE
client env is not strict

### ISSUE THREAD

**Issue by OrJDev** [solidjs/solid-start#590]
related https://github.com/solidjs/solid-start/pull/585

currently you can try using server env in import.meta.env, which ofc is not valid and will result in nothing.
server env is any variable that doesn't start with VITE_,
meaning that typescript will not scream at you if you try doing something like:
```ts
import.meta.env.HELLO
```
that is because the current type simply accept any string.

this could easily be fixed using this type instead
```ts
interface ImportMetaEnv extends Record<`VITE_${string}`,any>{
  BASE_URL: string
  MODE: string
  DEV: boolean
  PROD: boolean
  SSR: boolean
}
```

```ts
  console.log("not valid", import.meta.env.SERVER_TEST); // Property 'SERVER_TEST' does not exist on type 'ImportMetaEnv'.ts(2339)
  console.log("valid", import.meta.env.VITE_TEST); 
 ```
 
can make a pr if needed.

**Comment by atk** [comment]
A PR would be nice. However, can we re-use any type exposed by vite in order to be future-proof if this is changed in the future?

**Comment by OrJDev** [comment]
I really am not sure because vite's import meta env type accepts [key: string] by default along with all of the other properties, so we have to redeclare the entire import meta env type,
they won't change it anytime soon I believe but ofc if they do it will not be hard to update.
