### ISSUE TITLE
Local build fails to starup after adding "solid-start-vercel" adapter.

### ISSUE THREAD

**Issue by calirails** [solidjs/solid-start#591]
I've been learning solid-start through the HackerNews generated project. I am wallking through code and want to ensure that I am able to deploy solid-start apps through the Github and Vercel CICD integration. 

Upon the initial build and deployment, I encountered an error that Vercel could not locate the build output directory and that I needed to adjust the Project Settings. To work around this, I've added an override of the Vercel Project to designate an Output Directory of "dist" but clicking on the deployed site still fails with 404 page. 

To troubleshoot the error locally, I decided to do a local production build to test startup but then came across this error which led me to this Github issue that suggests I needed to add the [vercel adapter](https://github.com/solidjs/solid-start/tree/cbafb3108b79533f6492719af74842df1c7fe26e/packages/start-vercel). After doing so, I got this following error when attempting `npm run build` followed by `npm run start`

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/942698/209736195-c30f3e07-49ca-465d-a609-60b70d7bac9e.png">

My environment: MAC OSX, Node v16.16.0, NPM v8.11.0 with the following package.json.
```
{
  "name": "hackernews",
  "scripts": {
    "dev": "solid-start dev",
    "build": "solid-start build",
    "start": "solid-start start"
  },
  "type": "module",
  "main": "./dist/index.js",
  "devDependencies": {
    "solid-start-node": "^0.2.0",
    "typescript": "^4.8.4",
    "vite": "^3.1.8"
  },
  "dependencies": {
    "@solidjs/meta": "^0.28.0",
    "@solidjs/router": "^0.6.0",
    "solid-js": "^1.6.2",
    "solid-start": "^0.2.0",
    "solid-start-vercel": "^0.2.8",
    "undici": "^5.11.0"
  },
  "engines": {
    "node": "^16.16.0"
  }
}
```

To reproduce:
1. Pull head of 'main' branch at this public repository: https://github.com/calirails/solidjs-starter-hackernews
2. Install dependencies via `npm install` at the root. At this point the project runs fine via `npm run dev`
3. Build for production via `npm run build`
4. Start production build via `npm run start` and observe the ``Error: spawn ENOTDIR`.
**NOTE**: if I remove the solid-start-server package via `npm uinstall solid-start-vercel` then the production build starts fine but fails when navigating to the root of deployed site from vercel deployment.

I've tried both the standard as well as the "edge: true" option within the vercel adapter via:
```
export default defineConfig({
  plugins: [solid({ adapter: vercel() })]
  //also tried this -> plugins: [solid({ adapter: vercel({ edge: true }) })]
});
```
I'll continue to troubleshoot; however, I would very much appreciate guidance on what I've done wrong and can do differently to complete a deployment of a build that starts up on Vercel's hosted platform. 
Thanks in advance.

**Comment by calirails** [comment]
An update: with the use of the `vercel` adapter and the edge option added as follows fixes the 404 Error on the deployed Vercel web site.
```
file: vite.config.js
export default defineConfig({
    plugins: [solid({ adapter: vercel({ edge: true }) })]
});
```

The error locally via `npm run start` following the build remains.

**Comment by ryansolid** [comment]
Do you have the vercel cli installed? Just double checking the spawn command seems to be complaining about something in the file system so that is the obvious place to start.

**Comment by calirails** [comment]
Yes, I do have `vercel` cli installed; v.28.10.1.
```
vercel -v
vercel -v
Vercel CLI 28.10.1
28.10.1
```

I appreciate the feedback.

**Comment by ryansolid** [comment]
There is no local environment to vercel to my knowledge so the start command just calls vercel cli it looks like. That's why I wanted to check if it was present because its complaining about some directory not found or something like that. I wonder if like the build output is bad and it can't find the `.output` folder or something like that. I haven't sat down and tried this is a few weeks so might be something there. I was just trying to give any quick advice before I dug in.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
