### ISSUE TITLE
windows: route path mismatch with manifest

### ISSUE THREAD

**Issue by fictitious** [solidjs/solid-start#60]
this is what manifest looks like on windows in `getAssetsFromManifest` :

```
getAssetsFromManifest: route= [ { originalPath: '/', pattern: '', path: '/', params: {} } ]
manifest:  {
  '/C:/Users/me/src/test-solid-start/2022-01-23/src': [
    { type: 'script', href: '/assets/index.1ce99872.js' },
    { type: 'script', href: '/assets/client.99f63873.js' },
    { type: 'style', href: '/assets/index.adcc5497.css' }
  ],
  '*': [ { type: 'script', href: '/assets/client.99f63873.js' } ]
}
```

that `C:/Users/..` path is just '/' on linux

as a result, on windows, no script and style tags are added to the `<head>`

**Comment by ryansolid** [comment]
I see sweet.. (sarcasm).. I'm open to suggestions. These sort of inconsistencies are going to be the real challenge for people building tooling around this. We might need to handle it ourselves. But for now I'm open to suggestions.

**Comment by fictitious** [comment]
on linux, `rollup-route-manifest` is happy to convert absolute file path to the route relative to routes root: on [this line](https://github.com/lukeed/rollup-route-manifest/blob/master/src/index.js#L74) after calling `toRoute()` with 

```
console.log(`bundle key ${key} fid=${fid} route=${route}`);
```
we have
```
bundle key assets/index.0503c002.js fid=/.../solid-start-tests/with-mdx-ts/src/pages/index.mdx route=/
```

on windows, not so much, the absolute path prefix remains:

```
bundle key assets/index.1ce99872.js fid=C:/.../test-solid-start/2022-01-23/src/pages/index.tsx route=/C:/.../test-solid-start/2022-01-23/src
```

now looking where it gets those routes from...

**Comment by fictitious** [comment]
... sigh. Vite made their choice, they [always normalize paths to posix-style](https://github.com/vitejs/vite/issues/1487#issuecomment-758140585):

> Vite's resolve plugin and most official Rollup plugins normalize windows paths this way,

hard to blame them.

as long as this part continues to be vite/rollup plugin, I think it's ok to just reuse [`normalizePath`](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/utils.ts#L145) from vite when necessary, to avoid mismatches with their path resolution.
