### ISSUE TITLE
Using "@kubernetes/client-node" completely breaks "solid-start start" (also build gives warnings about circular dependencies)

### ISSUE THREAD

**Issue by Hubro** [solidjs/solid-start#600]
Adding `@kubernetes/client-node` to the project immediately breaks running the application using `solid-start start`.

Building the project seems to work fine, although it pumps out a lot of warnings about circular dependencies:

<pre>
➜ npm run build

> build
> solid-start build

 solid-start build 
 version  0.2.9
 adapter  node

solid-start building client...
vite v3.2.5 building for production...
✓ 57 modules transformed.
dist/public/manifest.json                      0.77 KiB
dist/public/ssr-manifest.json                  1.56 KiB
dist/public/assets/_...404_.1061ea00.js        0.55 KiB / gzip: 0.37 KiB
dist/public/assets/index.6ce7460b.js           0.53 KiB / gzip: 0.36 KiB
dist/public/assets/entry-client.d870915a.css   0.37 KiB / gzip: 0.26 KiB
dist/public/assets/entry-client.35470192.js    42.79 KiB / gzip: 16.20 KiB
solid-start client built in: 853.834ms

solid-start building server...
vite v3.2.5 building SSR bundle for production...
✓ 60 modules transformed.
.solid/server/manifest.json     0.18 KiB
.solid/server/entry-server.js   56.83 KiB
solid-start server built in: 450.811ms

Circular dependency: node_modules/glob/glob.js -> node_modules/glob/sync.js -> node_modules/glob/glob.js
Circular dependency: node_modules/shelljs/shell.js -> node_modules/shelljs/src/common.js -> node_modules/shelljs/shell.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/fingerprint.js
Circular dependency: node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/signature.js -> node_modules/sshpk/lib/utils.js -> node_modules/sshpk/lib/private-key.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/signature.js -> node_modules/sshpk/lib/utils.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/dhe.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/dhe.js -> node_modules/sshpk/lib/private-key.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/private-key.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/pem.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/pem.js -> node_modules/sshpk/lib/private-key.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/pem.js -> node_modules/sshpk/lib/formats/pkcs1.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/pem.js -> node_modules/sshpk/lib/formats/pkcs1.js -> node_modules/sshpk/lib/private-key.js
Circular dependency: node_modules/sshpk/lib/formats/pem.js -> node_modules/sshpk/lib/formats/pkcs1.js -> node_modules/sshpk/lib/formats/pem.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/pem.js -> node_modules/sshpk/lib/formats/pkcs1.js -> node_modules/sshpk/lib/formats/pkcs8.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/pem.js -> node_modules/sshpk/lib/formats/pkcs1.js -> node_modules/sshpk/lib/formats/pkcs8.js -> node_modules/sshpk/lib/private-key.js
Circular dependency: node_modules/sshpk/lib/formats/pem.js -> node_modules/sshpk/lib/formats/pkcs1.js -> node_modules/sshpk/lib/formats/pkcs8.js -> node_modules/sshpk/lib/formats/pem.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/pem.js -> node_modules/sshpk/lib/formats/ssh-private.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/pem.js -> node_modules/sshpk/lib/formats/ssh-private.js -> node_modules/sshpk/lib/private-key.js
Circular dependency: node_modules/sshpk/lib/formats/pem.js -> node_modules/sshpk/lib/formats/ssh-private.js -> node_modules/sshpk/lib/formats/pem.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/pem.js -> node_modules/sshpk/lib/formats/ssh-private.js -> node_modules/sshpk/lib/formats/rfc4253.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/pem.js -> node_modules/sshpk/lib/formats/ssh-private.js -> node_modules/sshpk/lib/formats/rfc4253.js -> node_modules/sshpk/lib/private-key.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/ssh.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/ssh.js -> node_modules/sshpk/lib/private-key.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/dnssec.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/dnssec.js -> node_modules/sshpk/lib/private-key.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/putty.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/private-key.js -> node_modules/sshpk/lib/formats/auto.js -> node_modules/sshpk/lib/formats/putty.js -> node_modules/sshpk/lib/private-key.js
Circular dependency: node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/certificate.js -> node_modules/sshpk/lib/fingerprint.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/certificate.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/certificate.js -> node_modules/sshpk/lib/identity.js -> node_modules/sshpk/lib/fingerprint.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/certificate.js -> node_modules/sshpk/lib/formats/openssh-cert.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/certificate.js -> node_modules/sshpk/lib/formats/openssh-cert.js -> node_modules/sshpk/lib/certificate.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/certificate.js -> node_modules/sshpk/lib/formats/x509.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/certificate.js -> node_modules/sshpk/lib/formats/x509.js -> node_modules/sshpk/lib/certificate.js
Circular dependency: node_modules/sshpk/lib/key.js -> node_modules/sshpk/lib/fingerprint.js -> node_modules/sshpk/lib/certificate.js -> node_modules/sshpk/lib/formats/x509-pem.js -> node_modules/sshpk/lib/key.js
Circular dependency: node_modules/sshpk/lib/certificate.js -> node_modules/sshpk/lib/formats/x509-pem.js -> node_modules/sshpk/lib/certificate.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/admissionregistrationApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/admissionregistrationV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/apiextensionsApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/apiextensionsV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/apiregistrationApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/apiregistrationV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/apisApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/appsApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/appsV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/authenticationApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/authenticationV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/authorizationApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/authorizationV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/autoscalingApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/autoscalingV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/autoscalingV2Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/autoscalingV2beta2Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/batchApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/batchV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/certificatesApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/certificatesV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/coordinationApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/coordinationV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/coreApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/customObjectsApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/discoveryApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/discoveryV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/eventsApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/eventsV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/flowcontrolApiserverApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/flowcontrolApiserverV1beta1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/flowcontrolApiserverV1beta2Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/internalApiserverApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/internalApiserverV1alpha1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/logsApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/networkingApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/networkingV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/networkingV1alpha1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/nodeApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/nodeV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/openidApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/policyApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/policyV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/rbacAuthorizationApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/rbacAuthorizationV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/schedulingApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/schedulingV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/storageApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/storageV1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/storageV1beta1Api.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/versionApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/gen/api/apis.js -> node_modules/@kubernetes/client-node/dist/gen/api/wellKnownApi.js -> node_modules/@kubernetes/client-node/dist/gen/api/apis.js
Circular dependency: node_modules/@kubernetes/client-node/dist/cache.js -> node_modules/@kubernetes/client-node/dist/informer.js -> node_modules/@kubernetes/client-node/dist/cache.js
</pre>

When I attempt to start the server afterwards, it crashes with this error:

<pre>
➜ npm run start

> start
> solid-start start

 solid-start start 
 version  0.2.9
 adapter  node

  ➜  Page Routes:
     ┌─ http://localhost:3000/*404
     └─ http://localhost:3000/

  ➜  API Routes:
     None! 👻

file:///tmp/solid-start-bare/dist/server.js:23256
	throw new Error('Could not dynamically require "' + path + '". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.');
	     ^

Error: Could not dynamically require "./src/cat". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
    at commonjsRequire (file:///tmp/solid-start-bare/dist/server.js:23256:8)
    at file:///tmp/solid-start-bare/dist/server.js:27245:4
    at Array.forEach (<anonymous>)
    at requireShell (file:///tmp/solid-start-bare/dist/server.js:27244:20)
    at requireConfig (file:///tmp/solid-start-bare/dist/server.js:177718:18)
    at file:///tmp/solid-start-bare/dist/server.js:193811:23
    at file:///tmp/solid-start-bare/dist/server.js:193828:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
</pre>

Running `solid-start dev` works fine.

## How to reproduce

I created a minimal repo to reproduce the problem here:

https://github.com/Hubro/solid-start-bare/tree/kubernetes-client-breaks-build

(I tried making a StackBlitz example but I wasn't even able to run `solid-start build` there...)

After cloning the above repo:

```bash
git checkout kubernetes-client-breaks-build
npm install
npm run build
npm run start
```

**Comment by ruler501** [comment]
Is this fixed by https://github.com/solidjs/solid-start/pull/626

**Comment by Hubro** [comment]
If anybody has any ideas, I would love any suggestions on how to work around this error.

**Comment by Hubro** [comment]
After some assistance from Razboy20 on the SolidJS Discord, I got this issue resolved with the following Vite config:

```typescript
import solid from "solid-start/vite";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [solid()],
  build: {
    commonjsOptions: {
      dynamicRequireTargets: [
        "node_modules/.pnpm/*/node_modules/shelljs/src/*.js"
      ]
    }
  },
});
```

So as far as I can tell, this is an issue with Rollup + `@kubernetes/client-node`, it has nothing to do with Solid Start.
