### ISSUE TITLE
Rewriting URLs breaks hydration

### ISSUE THREAD

**Issue by jchatard** [solidjs/solid-start#604]
## Summary

Rewriting URLs breaks hydration. Probably because hydration is based on the current URL.

## Steps to reproduce

1. Get repro `git clone https://github.com/Breek/solid-stat-rewrite-middleware`
2. Get into dir `cd solid-stat-rewrite-middleware`
3. Start app `pnpm install && pnpm dev`
4. Navigate to http://localhost:3000/
5. Open browser console.
6. Click `About Company`
7. On the new page, click the `<Counter />` component.

## Expected behavior

When I navigate to `/about` this should happen:

- The route page `about-company.tsx` should be rendered by the server.
- The route page `about-company.tsx` should be hydrated.
- The `<Counter />` component should work.

## Actual behavior

When I navigate to `/about` this should happen:

- The route page `about-company.tsx` should be rendered by the server: **OK**
- The route page `about-company.tsx` should be hydrated: **KO**
- The `<Counter />` component should work: **KO**
- Errors shown in the browser’s console shows that the hydration process of the `[…404]` page route is triggered.

## Additional context

**MPA:** the application should be a Multi Page App - [related commit](https://github.com/Breek/solid-stat-rewrite-middleware/commit/3accadb08fc95c7536f18093aaf72213e3574af1). I’m using `<a>` instead of `<A>`.

**My understanding:** hydration happens based on the browser current URL. I don’t really know, nor understand, the internals of Solid Start, but I guess this happens thanks to the manifest.

I think that for this kind of use cases, hydration should be fired based on `rendered route` as opposed to `current browser URL`.

**Rewrite:** some months ago, I had a chat with @nksaraf where he suggested me this kind of approach to do URL rewriting ([Discord chat with Nikhil](https://discord.com/channels/722131463138705510/910635844119982080/1032526465885024297)).

I’ve seen the `internal-fetch` [branch](https://github.com/solidjs/solid-start/commits/internal-fetch) of Solid Start. And especially this [commit](https://github.com/solidjs/solid-start/commit/848ad00b267e4433aa6b328268a8d31c79ed3b4b#diff-1a2d11025da308cfdc63ac0ee074ad163b5b3def72afb2c4beb7fa9ee2f801b5) seems to deal with rewrite:

```ts
test("should rewrite", async ({ page }) => {
  let app = new PlaywrightFixture(appFixture, page);
  await app.goto("/api/rewrite", true);
  await page.waitForSelector("[data-testid='redirected']");
});
```

But I don’t know if this is related to my issue 🧐.

Would love some help on this.

Cheers,
Jérémy

**Comment by nksaraf** [comment]
Thanks for the really detailed exploration. Had been away for the holidays. Will explore this week.

**Comment by jchatard** [comment]
Hi @nksaraf!

I was wondering if you've had a chance to take a look at this issue? If you have any advice or could point me in the right direction to investigate, I would really appreciate it.

Thank you,
Jérémy

**Comment by jchatard** [comment]
I finally could implement full URL rewriting by patching Solid Router. But I’m pretty sure this is the ugly way — but hey, it works!

First I created a middleware which gets the Solid Start `route` for a given URL (this is done server-side):

```tsx
if (pathname === "/about") {
      console.debug("🛫 We want to rewrite `/about` to `/about-company`");
      // Let's create a new URL
      const url = new URL(`/about-company`, "http://internal");
      const request = new Request(url.href);

      for (const [key, value] of event.request.headers) {
        request.headers.set(key, value);
      }

      const prevPath = event.request.headers.get("x-solid-referrer");
      //...
}
```

Second I declare a global variable to be able to catch it on the client side, so I add this in `root.tsx` (this is also server-side):

```tsx
import { useLocation } from "@solidjs/router";

export default function Root() {
  const location = useLocation(); // ⬅️ Get location
  return (
    <Html lang="en">
      <Head>
        <Title>SolidStart - Bare</Title>
        <Meta charset="utf-8" />
        <Meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- ⬇️ Populate "matchedRoute" with the rewritten URL -->
        <script>{`matchedRoute = "${location.pathname}";`}</script>
      </Head>
      <Body>
      <!-- Stuff here -->
      </Body>
  </Html>);
}
```

Third I patched Solid Router to assign the matched route instead of getting it from the current browser URL:

```diff
diff --git a/dist/components.jsx b/dist/components.jsx
index 1ffb7f8d13879724b708c3dc3c3da871462a9e23..7c9572657b03f03ea50dd07325cfe23be1f29106 100644
--- a/dist/components.jsx
+++ b/dist/components.jsx
@@ -15,7 +15,7 @@ export const Routes = (props) => {
     const parentRoute = useRoute();
     const routeDefs = children(() => props.children);
     const branches = createMemo(() => createBranches(routeDefs(), joinPaths(parentRoute.pattern, props.base || ""), Outlet));
-    const matches = createMemo(() => getRouteMatches(branches(), router.location.pathname));
+    const matches = createMemo(() => getRouteMatches(branches(), globalThis.matchedRoute ? globalThis.matchedRoute : router.location.pathname));
     const params = createMemoObject(() => {
         const m = matches();
         const params = {};
```

And tadadada 🥳 hydravion works!

I would love to have this included in a less hacky way.

Do you have thoughts on this?

Working repro: https://github.com/Breek/solid-stat-rewrite-middleware/tree/patched_router

Cheers,
Jérémy

**Comment by CanRau** [comment]
Yea URL rewriting would be really helpful for multi tenancy where React Router fails basically.

Currently evaluating all options 🤓

Any news on first class support?

**Comment by ryansolid** [comment]
Honestly not sure where this belongs after the refactor:

In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
