### ISSUE TITLE
Dev mode ignores custom adapter

### ISSUE THREAD

**Issue by AFatNiBBa** [solidjs/solid-start#632]
I don't know if it is my fault, but it seems that when I start my project in dev mode, the build process I specified in the adapter gets completely ignored. 
Do I need to create a specific build process for the dev mode?
Is there a way to create one build process for both dev and "start" mode?
(The adapter I'm using is `solid-start-express` on npm)

**Comment by ryansolid** [comment]
Yeah. Dev mode uses the default dev node environment for most adapters. Cloudflare Adapters use Miniflare though so that might be where I'd start. You can expose a dev option:

https://github.com/solidjs/solid-start/blob/main/packages/start-cloudflare-workers/index.js#L17

**Comment by nksaraf** [comment]
Yeah we don't build in dev mode
