### ISSUE TITLE
Prod run error: Cannot read properties of undefined (resolve.length === 1)

### ISSUE THREAD

**Issue by Tanner-Scadden** [solidjs/solid-start#635]
## Summary
Bringing the package `@neo4j/graphql-ogm` into scope of a project causes the app to not run in production. Not sure if this is related to vite or solid-start's build process. I am building & running in node 18. Package does not have these issues in other environments. 

## Steps to reproduce
1. Get repo `git clone https://github.com/Tanner-Scadden/length-undefined`
2. cd length-undefined
3. pnpm install && pnpm dev
4. Navigate to http://localhost:3000. App runs
5. pnpm build
6. pnpm start
7. Navigate to http://localhost:3000. App crashes with error the ErrorStack:
```
file:///home/tannerscadden/neddaxs/internal/ponderly/apps/internal/dist/server.js:293825
    if (resolve.length === 1 || process.env.PRETTIER_FALLBACK_RESOLVE) {
                ^

TypeError: Cannot read properties of undefined (reading 'length')
    at src/common/resolve.js (file:///home/tannerscadden/neddaxs/internal/ponderly/apps/internal/dist/server.js:293825:17)
    at __require (file:///home/tannerscadden/neddaxs/internal/ponderly/apps/internal/dist/server.js:279773:51)
    at src/config/resolve-config.js (file:///home/tannerscadden/neddaxs/internal/ponderly/apps/internal/dist/server.js:296282:19)
    at __require (file:///home/tannerscadden/neddaxs/internal/ponderly/apps/internal/dist/server.js:279773:51)
    at src/common/get-file-info.js (file:///home/tannerscadden/neddaxs/internal/ponderly/apps/internal/dist/server.js:296664:19)
    at __require (file:///home/tannerscadden/neddaxs/internal/ponderly/apps/internal/dist/server.js:279773:51)
    at file:///home/tannerscadden/neddaxs/internal/ponderly/apps/internal/dist/server.js:315805:19
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
```

## Expected behavior
For the build to be able to run. 

## Actual behavior
Error is thrown when the module is loaded. If we moved the module to a global import, it would crash on production start. 

## Additional context
Uncertain who is responsible for this bug.

If I go to the source of the bug in the build:
```
var require_resolve2 = __commonJS2({
  "src/common/resolve.js"(exports2, module2) {
    var {
      resolve
    } = commonjsRequire;
    if (resolve.length === 1 || process.env.PRETTIER_FALLBACK_RESOLVE) {
      resolve = (id, options) => {
        let basedir;
        if (options && options.paths && options.paths.length === 1) {
          basedir = options.paths[0];
        }
        return require_resolve().sync(id, {
          basedir
        });
      };
    }
    module2.exports = resolve;
  }
});
```

I am able to check for resolve to be truthy, and then the app's build runs perfect. Any assistance would be great!

**Comment by ryansolid** [comment]
Interesting. Yeah, this is not in SolidStart's code. But what part of the build process would cause this to happen will take a little bit of tracking down.

**Comment by Tanner-Scadden** [comment]
@ryansolid Let me know what I can do to help! Not sure what steps I can take next.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
