### ISSUE TITLE
SSR: `TypeError: Cannot read properties of null (reading 'nextSibling')`

### ISSUE THREAD

**Issue by nirtamir2** [solidjs/solid-start#639]
Hi
I'm using solid-start and I have a problem with hydration.
I created a minimal reproduction from solid-start official bare example.
https://github.com/nirtamir2/solid-start-ssr-error-reproduction/blob/main/src/routes/index.tsx

```tsx
import type { Component, JSX, JSXElement} from "solid-js";
import { createContext } from "solid-js";

const MyContext = createContext<boolean>(false);
export const MyProvider: Component<{
    children?: JSX.Element;
}> = (props) => {
    return <MyContext.Provider value>{props.children}</MyContext.Provider>;
};

export function MyComponent(props: { children: JSXElement }) {
    return <div>{props.children}</div>;
}

function Comparison(props: { a: JSX.Element; b: JSX.Element }) {
    return (
        <div>
            <div>{props.a}</div>
            <div>{props.b}</div>
        </div>
    );
}

export default function Home() {
    return (
        <MyProvider>
            <div>
                <p class="headline">
                    <MyComponent>MyComponent Children</MyComponent>
                </p>
                <Comparison a={<h2 class="item">a</h2>} b={<h2 class="item">a</h2>} />
                <p>End</p>
            </div>
        </MyProvider>
    );
}

```

I get the error (in SSR) of 
```
    ErrorBoundary.tsx:27 TypeError: Cannot read properties of null (reading 'nextSibling')
    at get children [as children] (index.tsx:26:20)
    at get children [as children] (index.tsx:8:45)
    at Object.fn (dev.js:990:35)
    at runComputation (dev.js:705:22)
    at updateComputation (dev.js:688:3)
    at createMemo (dev.js:244:10)
    at children (dev.js:586:20)
    at dev.js:990:14
    at untrack (dev.js:427:12)
    at Object.fn (dev.js:986:36)
```

**Comment by ryansolid** [comment]
I'm pretty sure I know what the issue is but it's been hard for us to detect over component boundaries. You can't put a `<div>` in a `<p>` the browser will correct this for us and screw everything up.

**Comment by nirtamir2** [comment]
You right! Changing the `p` to a `div` fixes the issue :)
Is there a way we can identify this problem ahead of time? Maybe a better error message? Because its hard to identify it from the context of `Cannot read properties of null (reading 'nextSibling')`

**Comment by ryansolid** [comment]
That's what I'm saying.. compiler can't find it. Isolated runtime checks can't find it. We can only really validate this as the string is about to be sent over the wire. So never take that cost in prod but maybe in dev. Streaming makes this challenging though again because things get broken up and technically all our async rendering is like streams under the hood.

**Comment by nirtamir2** [comment]
> We can only really validate this as the string is about to be sent over the wire. So never take that cost in prod but maybe in dev.

This sounds great. I would be happy to see as many checks as we could do as you suggested - so we will have better DX.
Thank you for your kind help Ryan! I'm closing this issue.
