### ISSUE TITLE
Get Client's IP Address

### ISSUE THREAD

**Issue by ryansolid** [solidjs/solid-start#641]
We need this feature for more than a few reasons but it isn't part of the Request model. I think we should just jam it on Server Context probably as `clientAddress`. Luckily others have gone through this: https://github.com/withastro/astro/issues/3708

So we should add this.

**Comment by indeyets** [comment]
@ryansolid this commit breaks types. see https://github.com/solidjs/solid-start/actions/runs/3917523573/jobs/6697359050

previous commit was green
