### ISSUE TITLE
Global `context` Data for Server Functions

### ISSUE THREAD

**Issue by ITenthusiasm** [solidjs/solid-start#642]
Both [`Remix`](https://remix.run/docs/en/v1/route/loader#context) and [`Svelte Kit`](https://kit.svelte.dev/docs/load#shared-state) have a concept of "global context data" that is accessible to all server functions (i.e., loaders, actions, etc.). One of the use cases where this is especially helpful is when we want each of the loaders to know the current user id (if one is needed), and to perform actions based on that information.

It'd be great if we had something similar in `SolidStart`. 🙏🏾 I imagine it could be set in `entry.server.tsx` through the `middleware`? Unless another place seemed like a more appropriate candidate.

**Comment by ryansolid** [comment]
Technically we have our PageEvents or ServerContext which serves this purpose. In server functions it is hung off `this`. I like the idea of adding a `.locals` object to it where you can add arbitrary things.
