### ISSUE TITLE
Can't access items in PocketBase list in the client

### ISSUE THREAD

**Issue by L-Mario564** [solidjs/solid-start#643]
I want to pass an array of records from the PocketBase database to the client but once it's there I can't acces the `items` property. Here's my code:

```ts
import PocketBase, { ListResult } from 'pocketbase';
import { createRouteData, useRouteData } from 'solid-start';
import { Todo } from '~/types';
import { createEffect } from 'solid-js';

export function routeData() {
  const todos = createRouteData(async (): Promise<ListResult<Todo>> => {
    const pb = new PocketBase('http://127.0.0.1:8090');

    let todos = await pb.collection('todos').getList<Todo>(1, 25, {
      sort: '-created'
    });
    
    // items property works fine here
    console.log(todos.items)

    return { ... todos };
  }, { key: 'todos' });
  
  return { todos };
}

export default function Home() {
  const { todos } = useRouteData<typeof routeData>();

  createEffect(() => {
    if (todos()) {
      // Can't access items here
      console.log(todos()?.items);
    }
  });

  return <>
    // ...
  </>;
}
```

On the second console log, I get this:

![Screenshot (2258)](https://user-images.githubusercontent.com/75393279/212415810-8e486535-572e-45cb-8345-872846ec2a9b.png)

It also says it has a length of 1 despite having more records in the DB (which again, works fine inside the `createRouteData` function). First time trying out this framework so is this a bug or am I doing something wrong?

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
