### ISSUE TITLE
Vite 4 / Rollup 3 support

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-start#660]
The work towards this touches multiple PR's, so this is a tracking issue.

**Comment by huijiewei** [comment]
Is there any plan to upgrade to vite4, because of the problem of the last / in the subdirectory, vite4 is very important

**Comment by birkskyum** [comment]
I believe the last issue remaining before there is Vite 4 compatibility is the open issue wrt the spa-test referenced here

**Comment by huijiewei** [comment]
Because the resolveConfig behavior of vite has changed, the defaultModeEnv parameter has been added, which needs to be set as soon as possible。 so solid-start not set this parameter. vite use default development env.
