### ISSUE TITLE
spa-test breaks in Vite 4 due to hydration (data-hk)

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-start#674]
Part of #660 

In spa-test, the combination of 'with index.html' and app.goto('/about') leads to this data-hk inconsistency in Vite 4:

<img width="713" alt="Screenshot 2023-01-20 at 14 43 00" src="https://user-images.githubusercontent.com/74932975/213709869-bc820993-b53d-4f53-94a1-627da7c4d9f8.png">

**Comment by ryansolid** [comment]
Hmm.. that suggests it is getting the server rendered code instead of client rendered. Some configuration issue only present in Vite 4. Maybe the way some setting is merged? Hmm..

**Comment by birkskyum** [comment]
Is there an issue made for the dev mode issue anywhere? Where are these reports?

**Comment by birkskyum** [comment]
@ryansolid  It could very well be that the prod/dev issue emerged as a result of this breaking change in vite 4 where the way to set prod/dev flags was being reworked: https://github.com/vitejs/vite/pull/10996

**Comment by huijiewei** [comment]
#753
