### ISSUE TITLE
start-aws: public files are not being served

### ISSUE THREAD

**Issue by btakita** [solidjs/solid-start#689]
To get around this issue, I added the following into `entry-server.ts`

```ts
const static_file_dir = resolve(join(
	dirname(new URL(import.meta.url).pathname),
	...(process.env.AWS_LAMBDA_RUNTIME_API ? ['..', 'client'] : ['..', '..', 'public'])))
export default createHandler(()=>handleRequest)
async function handleRequest(event:FetchEvent) {
	if (process.env.AWS_LAMBDA_RUNTIME_API) {
		try {
			const url = event.request.url
			const handle = await open(join(static_file_dir, new URL(url).pathname))
			const stats = await stat(fs_path)
			if (stats.isFile()) {
				const handle = await open(fs_path)
				return new Response(Readable.toWeb(handle.createReadStream()), {
					status: 200,
					headers: new Headers({
						'Content-Type': ext_r_mime[extname(url)]
					})
				})
			}
		} catch (err) {}
	}
	// ...
	return renderAsync(/*...*/)
}
```

**Comment by thdxr** [comment]
Hey when you say public files are not being served do you mean once you deploy?  And how are you deploying?

**Comment by btakita** [comment]
@thdxr I'm using `aws-cdk-lib` to build & deploy the stack.

**Comment by thdxr** [comment]
this was really made to be used with SST and a certain architecture

https://github.com/serverless-stack/sst/blob/sst2/packages/sst/src/constructs/SolidStartSite.ts

**Comment by btakita** [comment]
That's interesting. I never even heard about SST, so thank you for pointing it out to me. I'm just using raw `aws-cdk-lib`, so it's interesting to see the differences with the static file serving & the `requestContext` usage in the handler. Are static files served from the lambda in the SST stack?

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
