### ISSUE TITLE
`renderStream` acting like `renderAsync` after build

### ISSUE THREAD

**Issue by Torsten85** [solidjs/solid-start#691]
Hello,
maybe I'm missing something here, but in my use case, `renderStream` only works in dev mode.

Assume the following page ( of course with `renderStream` in **entry-server.tsx**) :

```jsx
import { Suspense } from "solid-js";
import { useRouteData } from "solid-start";
import { createServerData$ } from "solid-start/server";

const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export function routeData() {
  const letters = createServerData$(async () => {
    await wait(1000);
    return "a-b-c";
  });
  const numbers = createServerData$(async () => {
    await wait(2000);
    return "1-2-3";
  });

  return { letters, numbers };
}

export default function Home() {
  const { letters, numbers } = useRouteData<typeof routeData>();
  return (
    <>
      <p>
        <Suspense fallback="Loading Letters">{letters}</Suspense>
      </p>
      <p>
        <Suspense fallback="Loading Numbers">{numbers}</Suspense>
      </p>
    </>
  );
}
```

Running this in dev mode shows the Suspense Boundary "Loading Letters" for 1s until the Letters are loaded and the outher boundary shows "Loading Numbers" for 2s. Everything as expected.

Running `pnpm build && pnpm start`, the result is quite different:
The whole page keeps loading for 2s and then renders the full content. No Loading States / Error Boundaries gets rendered.
So this acts like `renderAsync`.

What am I missing?

**Comment by bondehagen** [comment]
Seems like a bug, I have experienced the same.

**Comment by colexbruhn** [comment]
My best guess is that `deferStream` is getting set to `true` at some point in the build step, but I'm sure the true answer is a little more nuanced than that.

Although it's not ideal, I've been using `renderSync` to force an immediate server response. From my understanding, this results in an extra call to the server once the client is loaded as opposed to the server asynchronously sending over the data from the initial request as in `renderStream`, but it results in the desired client suspense behavior. This method results in some particularly bad FOUC in development, but this issue goes away after build.

Hopefully someone more knowledgeable than me can chime in and shed some more light as to what's going on, but hopefully this workaround will suffice for now!

**Comment by bondehagen** [comment]
When running in dev, the webserver is from vite and when running in production on node, it's using Polka as the server, so it could be it's just not hooked up correctly there.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
