### ISSUE TITLE
`http://localhost:undefined` on Windows 10 when using `--open` flag

### ISSUE THREAD

**Issue by max-programming** [solidjs/solid-start#695]
Just getting into Solid Start for the first time. I bootstrapped an app and when I followed the docs to start the dev server with the `--open` flag, Windows gave me this error.

However the app works fine and the terminal shows the port properly, it just can't open it directly
![image](https://user-images.githubusercontent.com/51731966/215306299-a41f7a0f-cab8-4f22-b002-45f72907fe32.png)

**Comment by ryansolid** [comment]
Yeah probably when I removed hardcoding the default port. We probably need to make a decision here as Vite can set the port.

**Comment by ryansolid** [comment]
Yeah this should be fixed in the latest
