### ISSUE TITLE
When will the SSR CLI be ready for production

### ISSUE THREAD

**Issue by J-env** [solidjs/solid-start#7]
The mobile terminal rating requirements are very high.
I'm going to migrate from NextJS to SolidJS.

**Comment by ryansolid** [comment]
If SvelteKit taking close to a year and not being ready is an indication it's too early for me to set a date. When we get past this alpha stage we should have a better idea. But right now we are still understanding the solution and scope.

**Comment by nksaraf** [comment]
We are working hard towards a beta but ours APIs are stabilizing, you can start playing with the alpha if you are ready for some breaking changes in the future. Closing this for now..
