### ISSUE TITLE
could not resolve entry module

### ISSUE THREAD

**Issue by ZeAmanuel28** [solidjs/solid-start#70]
I am just trying solid start to port my solid.js client side renderded app to solid start (although solid start is in active development) & It works really while dev build (solid-start dev). I tried it with graphql (urql), fetch to an api & its really cool! 

but when i tried to run a production build (solid-start build) it fails saying can't find an entry module! why is this happening? I see that it needs unavailable files, how can i fix this?

![151749148-cdda8603-79d9-40bf-9b2f-26c469e5be79.png](https://user-images.githubusercontent.com/96905008/151944043-d5b93452-67ac-4a77-9f72-1ecae91b4392.png)

**Comment by nksaraf** [comment]
The file thats its trying to access... solid-start\runtime\server\nodeStream\app.jsx is not part of the what we ship in our latest @next releases. So that's why the suggestion is that you are probably on an older version. Maybe tell us the version of solid-start u see in your `package.json`

**Comment by ZeAmanuel28** [comment]
thanks! This is because when I generate solid start app (npm init solid@next), it gives me a root.tsx in the src folder & when I try it many times & get the latest packages, I realized that it needs entry-server & entry-client files! I have get this files from solid start examples hacker news demo! Please in included this files with the npx command!

**Comment by ryansolid** [comment]
I mean they should be there in the latest. Can you confirm?

**Comment by ZeAmanuel28** [comment]
its alpha 58 - 59! i will try to use the latest! give you my feedback!

thanks ryan! that you are helping us to move forward as the web & users expectations involves!

streaming is really cool in both data & HTML (may be will come to css later)! I recently tried streaming in cloudflare workers, its awesome!
