### ISSUE TITLE
Handle un-bundleable dependencies

### ISSUE THREAD

**Issue by arbassett** [solidjs/solid-start#725]
# Summary

Solid start in general can collect all required dependencies at build time and bundle them into a single handler. but when encountering a dependency that can't be bundle like `.node` files or prisma's `schema.prisma` we have to be able to copy them into the final output. This issue has to be handled on a per adapter base ex. Vercel expects you to run `@vercel/nft` on your project and build the folder structure your self while Netlify does this for you using their deployment pipeline. 

# Solution

## Adapters

By default each adapter should include a `include` option to glob files (started in #644). but for deployments that have CI/CD we should have the adapters do as much automatically as possible

- Vercel has already been fixed in (#702)
  - Note: we might be able to not do the `@vercel/nft` bundling for edge runtime same reason as Cloudflare
- Netlify handles this already
- Cloudflare workers & Pages should only need `include` as it can't use native node apis
- Deno for the same reasons as Cloudflare
- Node will need the same treatment as Vercel. currently (if you have un-bundleable dependencies) you can't just take the output of the dist folder and run you have to install node_modules that are already bundled in the output to run
- Aws has the same problems as Vercel & Node but I'm not sure on if we should handle it ourselves automatically.. its possible that someone using the aws adapter will be using a framework. these frameworks might want to handle zipping the result themselves. [sst does this for next](https://github.com/serverless-nextjs/serverless-next.js/blob/ca7f7f72e3b1e5fcb49ffc4a3f6d6f629e644b20/packages/libs/lambda-at-edge/src/build.ts#L267-L280). instead we could provide a `zip` option to [zip it with the same tool netlify uses](https://github.com/netlify/zip-it-and-ship-it)

## Documentaion

Besides the standard adapter options documentation when its stable we should have some documentation in source to keep track that this issue is handled in any rewrites or new adapters... tests would help but that would require checking folder structures so im not sure if just tests are enough

**Comment by arbassett** [comment]
With the announcement that solid-start is going to use astro as a base. Im going to pause any work i have on this until after the migration has happened and confirm that this issue has been fixed or requires further work upstream

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
