### ISSUE TITLE
Broken Context usage with setter 

### ISSUE THREAD

**Issue by damienld22** [solidjs/solid-start#729]
Hello,

### Context and problem

I want to use the `Context API` but I think there is a bug when I use a setter inside the context (or maybe I miss something).
In the playground of SolidJS, everything work well. But when I generate a "bare" Solid Start project for a minimal reproduction, the bug appear.

### My use case (simplified) :

- Create a `Context` that contains a counter (the state is in a `Signal`).
- Update the value of the counter using the setter of the Signal in the `onMount` method

Result : The `onMount` method is called, but the setter is not considered.

### How to reproduce :

- Create a new Solid Start project with `npm init solid` (with `bare`, `TypeScript` and `SSR`)
- Add the following `CounterContext.tsx` file in "src"

```
import { onMount, createSignal, createContext, useContext, Accessor}  from "solid-js";

type CounterStore = [Accessor<number>];
const CounterContext = createContext<CounterStore>();

export function CounterContextProvider(props) {
  const [count, setCount] = createSignal(0);

  onMount(() => {
    setCount(12); // This call is not considered
  });

  const store: CounterStore = [count];

  return (
    <CounterContext.Provider value={store}>
      {props.children}
    </CounterContext.Provider>
  );
}

export function useCounter() {
  return useContext(CounterContext);
}
```

- Add `CounterContextProvider` in `root.tsx`

```
export default function Root() {
  return (
    <Html lang="en">
      <Head>
        <Title>SolidStart - Bare</Title>
        <Meta charset="utf-8" />
        <Meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Body>
        <CounterContextProvider>
          <Suspense>
            <ErrorBoundary>
              <A href="/">Index</A>
              <A href="/about">About</A>
              <Routes>
                <FileRoutes />
              </Routes>
            </ErrorBoundary>
          </Suspense>
        </CounterContextProvider>
        <Scripts />
      </Body>
    </Html>
  );
}
```

- Replace `Counter.tsx` content with the following (to use the context) :

```
export default function Counter() {
  const [count] = useCounter();
  return (
    <>
      <div>{count()}</div>
    </>
  );
}
```

I expect to see **12** as displayed result, but I still **0**.
Maybe I misunderstanding something.

Thanks

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
