### ISSUE TITLE
DOCTYPE not set when ssr is disabled

### ISSUE THREAD

**Issue by milesj** [solidjs/solid-start#731]
We have to disable `ssr` because of hydration issues and problems with Apollo.

We noticed that our website is now in quirks mode and is missing the `DOCTYPE`.

<img width="772" alt="Screenshot 2023-02-08 at 5 03 07 PM" src="https://user-images.githubusercontent.com/143744/217688051-88a65aa7-75c2-4212-8cce-1f466e409f7b.png">

**Comment by seeplusplus** [comment]
just came here to see if someone else had already opened an issue for this. I'm working on putting together a PR for this now.
