### ISSUE TITLE
Don't process clientOnly imports in SSR

### ISSUE THREAD

**Issue by arbassett** [solidjs/solid-start#739]
[initial discord discussion](https://discord.com/channels/722131463138705510/1073754430664626176)

# Summary
Currently the way solid-start builds its apps its impossible to not process that are strictly client only .. meaning they can't be bundled for the server ex monaco-editor.. this causes the build to crash after the vite builds the server when rollup is used for the final result.

this is caused by changings [vites default behavior](https://github.com/solidjs/solid-start/blob/be97acfae1718cf2b5cc4156e747d9b64c4b292e/packages/start/bin.cjs#L310) to not inline dynamically imported files this prevents tools like rollup from doing dead code elimination. changing this to a false allows packages like monaco to be stripped out when behind a clientOnly. 

But the package will still be processed.. this is where vite's ssr.external config comes into play.. currently the [node adapter](https://github.com/solidjs/solid-start/blob/be97acfae1718cf2b5cc4156e747d9b64c4b292e/packages/start-node/index.js#L53) passes this value along to rollup and can build and not include the clientOnly boundary in the result.. but the other adapters currently don't do this.. if we patch the vercel adapter to do the same as node we can get it to build and start.

- [No patch Example](https://stackblitz.com/edit/solid-ssr-vite-becir2?file=src/components/Editor/index.tsx)
- [With Patch](https://stackblitz.com/edit/solid-ssr-vite-bkw6w8?file=vite.config.ts)

Patch files for reference
- [solid-start-vercel@0.2.20.patch](https://github.com/solidjs/solid-start/files/10712537/solid-start-vercel%400.2.20.patch)
- [solid-start@0.2.20.patch](https://github.com/solidjs/solid-start/files/10712538/solid-start%400.2.20.patch)

# Solution

While im fairly certain that allowing vite to split dynamic imports into multiple files by default is fine as they will get processed by the adpaters into a single file.. im uncertain if every adapter can currently respect the ssr.external config.. this issue relates to #725. you may want to flag something as being external to not process it, you may still want to be available at runtime. this works fine in vercel with #702 fixed but still has to be decided on how its handled for other adapters.

- [x] #744
- [ ] PRs to forward ssr.external to adapter rollup build
  - [x] #745
  - These require #725 to progress first to possibly include the external module but not process it
  - [ ] Deno? (need to research how deno handles npm packages)
  - [ ] Cloudflare-workers
  - [ ] Cloudflare-pages
  - [ ] Aws

**Comment by arbassett** [comment]
The core of this issue has been solved by allowing vite to code split rollup can do some dead code elimination and not bundle clientOnly. But with sold-start moving its base to astro core i'm going to pause work on this as the extra work relates to adapter changes and #725. by using astro adapters it may fix the adapter portion of this issue..

One the migration has happened ill take a look into if this is still a issue. if anyone is running into this as a blocker ill see if its something that can be fixed in the meantime

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
