### ISSUE TITLE
Are there any guidelines on how to use local storage as a Store?

### ISSUE THREAD

**Issue by superbull** [solidjs/solid-start#748]
Hi, are there any guidelines or examples on how to use local storage/session storage as a Store in the solid-start project?

There is a "state-management" chapter in the documents: https://start.solidjs.com/core-concepts/state-management, but it seems like a placeholder.

**Comment by superbull** [comment]
I have created a function `createLocalStore` based on the example (https://www.solidjs.com/examples/todos):

```typescript
export function createLocalStore<T extends object>(
  name: string,
  init: T
): [Store<T>, SetStoreFunction<T>] {
  const localState = typeof localStorage === 'undefined' ? undefined : localStorage.getItem(name);
  const [state, setState] = createStore<T>(
    localState ? JSON.parse(localState) : init
  );
  createEffect(() => {
    console.log("effect run:", state)
    localStorage.setItem(name, JSON.stringify(state))
  });
  return [state, setState];
}
```

When I replace the normal `createStore` with this `createLocalStore`, there will be some warnings:

![image](https://user-images.githubusercontent.com/455630/218750669-5d3213d7-191b-407f-94b7-777d96122e08.png)

And the application will have some strange behavior, some parts of the UI will not be updated reactively.

**Comment by boehs** [comment]
We provide https://github.com/solidjs-community/solid-primitives/tree/main/packages/storage#readme

**Comment by superbull** [comment]
@boehs Thanks for providing this library.
I tried it in my solid-start  project, it still has ***computations created outside a 'createRoot' ...*** warning.
May be I didn't do it right. There are not so many document about this library.

I solved this issue by:
1. using a normal `createStore`
2. read the data from localStorage when the application first render using an `onMount`.
3. after `setState`, always call `localStorage.setItem` to update the data in local storage

This is a little cumbersome, but works well.

**Comment by boehs** [comment]
> computations created outside a 'createRoot'

This is not related, as far as I'm aware, to the library itself, rather a general misunderstanding of solid reactivity. These reactive structures should always be made in the component tree (using context) or in a root (see https://www.solidjs.com/tutorial/stores_nocontext)

**Comment by ryansolid** [comment]
It's tricky because if client and server don't match hydration fails. Which makes it almost impossible for localStorage to work properly with data needed to render the page. You have to apply it afterwards like in an `onMount` as suggested above. But then it isn't available at hydration time.
