### ISSUE TITLE
Unintuitive ergonomics of data loading state (in combination with searchParams?)

### ISSUE THREAD

**Issue by emdede** [solidjs/solid-start#754]
To show a loading message can be quite a bit challenging. Especially for the case of loading data relying on Query Parameters.

Assume we have `routeData` that returns something based on `useSearchParams`.
Edit: Forgot to mention a crucial point. Somewhere in the template there's a button that calls `setSearchParams` with some random param.

```tsx
export function MyRoute() {
  const data = useRouteData()
  
  return (
    <Show when={data()} fallback={"Loading"} keyed>
      {(result) => <p>{result}</p>}
    </Show>
  )
  ```
  
Loading state will not show when searchParams change. I am not sure why exactly that is, but I am assuming it has something to do with how page state changes on navigation. Both `data.state` and `data.loading` do not update.

```tsx
export function MyRoute() {
  const data = useRouteData()
  
  return (
    <Show when={data.loading} fallback={<p>{data()</p>}>
      Loading
    </Show>
  )
  ```
  
Loading state will show indefinitely because the read access is never actually executed.

The only way I got it to work is to use the above example and actually insert a random read access to `data()`.

```tsx
export function MyRoute() {
  const data = useRouteData()
  console.log(data())
  
  return (
    <Show when={data.loading} fallback={<p>{data()</p>}>
      Loading
    </Show>
  )
```
Apart from the fact that I am forced to add a read access that I never intended, it's also a bit weird to have to put my main content inside a `fallback`. But that's of minor importance I guess.

Any thoughts on this? Am I doing something utterly wrong here?

"Repro" here: https://stackblitz.com/edit/github-rtwzkq-fni4gq?file=src/routes/index.tsx
This is the broken one. Uncomment the console.log and it works.

As a sidenote: I've initially tried not using `routeData` but `createResource` + `Suspense` in the component itself, which unfortunately broke because `setSearchParams` does not use the current page but routes you to a new one. Something that imo could be pointed out in the docs.

Cheers!

Edit: I have played around a bit more and I have no idea what's going on here. Most of the assumptions I have made are definitely incorrect. But could someone more knowledgeable shed some light on this matter?

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
