### ISSUE TITLE
Layout page is not co-located with folder

### ISSUE THREAD

**Issue by mmrath** [solidjs/solid-start#755]
This is probably not big of an issue but I anyway wanted to know if there are options for improvement. If I have multiple directories each with their own layout, current convention keeps the layout files a little way from the directory. So in the example below - six directories/paths with own layout, the layout file is quite far from thee directory in IDE.

So what could improve it? if there is anyway to keep the layout directly under path. 

A possible alternative I have thought of is create a `(layout)` directory and `(layout).tsx` in each of the paths. That way, they can stay in the parent folder.

Just to mention, I think qwik's convention is quite good in this area.

```
routes
      ├── a/   ---> directory for a here
      ├── b/
      ├── c/
      ├── d/
      ├── e/
      ├── f/
      ├── a.tsx  ---> here is the layout
      ├── b.tsx
      ├── c.tsx
      ├── d.tsx
      ├── e.tsx
      └── f.tsx
```

**Comment by ryansolid** [comment]
This whole area is one that is rife with opinions and honestly no great solutions. 

The ordering is annoying for sure. A lot SolidStart's direction came from how you'd define them without file system routing. Layout's aren't a concept. Only the fact that routes can have children. Ie.. you'd first build a a.tsx.. and at some point later you decided it had children you'd add `a` folder.

In Folder based I gather you `a/index.tsx` and then to add children, you rename `a/index.tsx` to `a/layout.tsx` and then add additional folders. It is verbose by default. I've never like named to purpose files like `page.tsx` or `layout.tsx`. Having a project full of files with the same name gives me terrible old MVC flashbacks.

Flat routes like Remix are interesting but if you end up mixing files and folders the same problem still exists.

Admittedly reviewed many different variations all of these sorts of approaches (except flat routes) before landing where we have. I'm still hoping there are other options but I haven't seen one that doesn't fall into these issues.

**Comment by boehs** [comment]
FWIW you're welcome to do your own implementation, IIRC there's nothing particularally special in start, just the `<FileRoutes/>` component

**Comment by mmocny** [comment]
Related: Is it possible to have a shared layout for the root folder (`routes/`) today?

I tried to just create a `routes.tsx` but that didn't work.  I suspect that means you'll need a special layout file for the root folder, at the root.

At that point, perhaps it suggests you should define routes within the folder for all routes...

**Comment by juniorforlife** [comment]
@ryansolid so currently there's no way to colocate related components/utils/files under a route folder without making them a route?

**Comment by emmanuelchucks** [comment]
> A possible alternative I have thought of is create a `(layout)` directory and `(layout).tsx` in each of the paths. That way, they can stay in the parent folder.

I really like this idea since it's consistent with how you create a 'root' layout in solid start anyway.

**Comment by AzrizHaziq** [comment]
HI @juniorforlife , have you found any work around to do that? i was wondering the same idea.

**Comment by juniorforlife** [comment]
> HI @juniorforlife , have you found any work around to do that? i was wondering the same idea.

Unfortunately I got frustrated with SolidStart and Solid in general so I switched to SvelteKit

**Comment by chaoky** [comment]
just don't use the file router(?), it's optional, with a simple routes files with 10 lines you can organize your code however you want

**Comment by chaoky** [comment]
you can also write your own file router, that's part of beauty of how SolidStart is doing things

**Comment by russelgal** [comment]
@rich_harris
He said that the sveltekit would be ready within weeks, not months )))
the result is known to everyone
sorry I can't find the tweet

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
