### ISSUE TITLE
HMR break string inside <pre>

### ISSUE THREAD

**Issue by iacore** [solidjs/solid-start#760]
![image](https://user-images.githubusercontent.com/74560659/220222176-a1f23e4f-6f21-479e-af79-c3a6d0b0f090.png)

## How to reproduce

1. `pnpm create solid`, choose `bare`, default everything
2. Modify `src/routes/index.tsx` 

```tsx
import { Title } from "solid-start";
import Counter from "~/components/Counter";

const asciiart = `
/-----\\
|     |
+_____+
`

export default function Home() {
  return (
    <main>
      <Title>Hello World</Title>
      <h1>Hello world!</h1>
      <Counter />
      <pre>{asciiart}</pre>
      <p>
        Visit{" "}
        <a href="https://start.solidjs.com" target="_blank">
          start.solidjs.com
        </a>{" "}
        to learn how to build SolidStart apps.
      </p>
    </main>
  );
}
```

3. `pnpm i && pnpm dev` (after this the ACSII art "house" should look right)
4. `touch src/routes/index.tsx` (now the "house" looks wrong like my screenshot)

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Comment by iacore** [comment]
@ryansolid  Still reproducible.




this time replace `src/app.tsx`


```
// @refresh reload
import { createSignal } from "solid-js";

const asciiart = `
/-----\\
|     |
+_____+
`

export default function App() {
  const [count, setCount] = createSignal(0);
  return (
    <main>
      <h1>Hello world!</h1>
      <pre>{asciiart}</pre>
      <button class="increment" onClick={() => setCount(count() + 1)}>
        Clicks: {count()}
      </button>
      <p>
        Visit{" "}
        <a href="https://start.solidjs.com" target="_blank">
          start.solidjs.com
        </a>{" "}
        to learn how to build SolidStart apps.
      </p>
    </main>
  );
}
```

![image](https://github.com/solidjs/solid-start/assets/74560659/c209f1cf-450c-44c8-b44f-644c0002c8ad)
