### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by superbull** [solidjs/solid-start#765]
If there is a input filed named `host` in the Form component, when click one of the input field, there will be an error:
```
Uncaught RangeError: Maximum call stack size exceeded
```

Reproduce steps:
1. init a project based on the template `with-auth`
2. install dependencies and start the dev server
3. in the file `src/routes/login.tsx`, replace all the `username` with `host`, and save
4. click the input field

Below is the screenshot:
![solidstart_form_host](https://user-images.githubusercontent.com/455630/220508064-35ad274a-a9f8-4f70-9103-ce7985a2b1f4.gif)

**Comment by LiQuidProQuo** [comment]
was a bug in solid
https://github.com/solidjs/solid/issues/1380

**Comment by superbull** [comment]
@LiQuidProQuo @ryansolid 
Are you sure it is solved in https://github.com/solidjs/solid/commit/c874b32973d0134ccb1afaa6cb639e091463e67d ?
I have this problem with below version
```
"dependencies": {
    "@solidjs/meta": "^0.28.2",
    "@solidjs/router": "^0.7.0",
    "solid-js": "^1.6.11",
    "solid-start": "^0.2.21",
  },
```
