### ISSUE TITLE
Date type mismatch between Client and Server causing Runtime "TypeError"

### ISSUE THREAD

**Issue by FlorianPallas** [solidjs/solid-start#768]
### Describe the bug
When using `createServerData$(...)` for example, any date objects transferred from the server to the client will be serialized into strings and remain that way on the client, causing a type mismatch between the client and server version of the affected component.

This can cause visual differences or even errors when the client needs to rerender the component (Navigation, Hot Reload, ...) because the client expects a `Date` object to be present.

### Steps to Reproduce the Bug or Issue
Using the minimal example with SSR (and TypeScript), make the following changes to the index page:

```tsx
...
  export default function Home() {
+   const date = createServerData$(() => new Date());
  
    return (
      <main>
+       <p>{date()?.toLocaleDateString()}</p>
...
```

The initial render is as expected. But when switching to the about page and switching back, an error occurs. The client fails to call `toLocaleDateString()`, as the function only exists on `Date` objects, not strings.

### Expected behavior
The client should turn the date string back into a `Date` object, preventing type issues like this.

### Screenshots or Videos

![Screenshot from 2023-02-23 21-18-05](https://user-images.githubusercontent.com/24498189/221020678-56627e07-da9d-4fe8-8212-ac6c113e627f.png)

### Platform
- OS: Linux
- Browser: Chrome
- Version: v0.2.21

**Comment by boehs** [comment]
Fascinating problem, the complexity for a fix seems astronomical. Obviously, the workaround is to just to that serialization client side

**Comment by arbassett** [comment]
So the behaver that the server is doing is kind of funky as really you should get a error on the server as well but it appears on the server the data is not getting serialized but passed directly. This is the exact same issue trpc ran into where the return types would not get changed properly for typescript and blindly say it can send none json serializable types over the wire (Date, Set, Map). what you should do is instead user something like `superjson` to send these values over the wire.

**Comment by lxsmnsyc** [comment]
tbf SolidJS's serialization supports JS values like Date, but this seems to be more of an issue with the serializer itself.

**Comment by lxsmnsyc** [comment]
ah right, server$ did use a different form of serializer than what Solid is currently using.

**Comment by arbassett** [comment]
i stared work in #792 but ryan noted that its now being extracted to Bling so will be moving work to there.
 
tracking issue: https://github.com/TanStack/bling/issues/9

**Comment by lxsmnsyc** [comment]
@arbassett you can probably expand on the fact that Bling currently only supports JSON values

**Comment by lxsmnsyc** [comment]
@antmoux we have a [new serializer](https://github.com/lxsmnsyc/seroval) being used in SolidJS. It's most likely sooner or later we'll get to address this issue

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
