### ISSUE TITLE
initial render of a Route with text only is not properly removed when navigating away.

### ISSUE THREAD

**Issue by LiQuidProQuo** [solidjs/solid-start#776]
when the initial render of the route is a text node only 
navigation to a different route, will not remove the node.

https://stackblitz.com/edit/github-htdqaw
![image](https://user-images.githubusercontent.com/105608035/221796311-9b1dad23-3de2-4aa8-94b7-7d675ad22c83.png)

# `/`  -> `/about` -> `/`
![image](https://user-images.githubusercontent.com/105608035/221796224-e2741170-e583-4f25-9794-e3dddb5c62ad.png)

## expectations 
1. navigation should be consistent for when the initial route render from ssr is a text only result
**keep in mind** that if we refresh the `/about` page, and force initial render on that route
then navigation is correct and there is not left overs of nodes when toggling routes.

**Comment by LiQuidProQuo** [comment]
This issue is not exclusive to text only routes, but also for the case that the route 
returns a fragment, with top level text nodes
```jsx
<>
I am top level node
<div>no problem here</div>
again problem I am at top level
</>
```
it is possible that solid can't properly  or easily track  text nodes in a top level of the fragment
in the current implementation. 

and this is not a top priority, but it will be nice to properly communicate to the users why things are not working as expected.

**Comment by lxsmnsyc** [comment]
iirc this is an issue with text nodes + fragments, there's a similar issue in the SolidJS repo.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
