### ISSUE TITLE
Request from ServerContext doesn't have host/hostname in case of http2 requests

### ISSUE THREAD

**Issue by indeyets** [solidjs/solid-start#777]
This is tested for local development. HTTPS enabled.

HTTP/1 works fine.
HTTP/2 is broken in the following way (host/hostname equal to `"undefined"` string):

I literally had to implement the following workaround. I think it's quite descriptive:

```js
  const serverContext = useServerContext();

  // …

  if (isServer) {
    currentURL = new URL(serverContext.request.url);

    // solid-start has a bug with http/2 requests. try to "fix" it
    if (currentURL.host === "undefined") {
      const authority = serverContext.request.headers.get(":authority");
      if (!authority) {
        throw new Error("Can't find hostname in request");
      }

      currentURL.host = authority;
    }
  }
```

**Comment by indeyets** [comment]
Is it this place? https://github.com/solidjs/solid-start/blob/main/packages/start/node/fetch.js#L140-L152

**Comment by indeyets** [comment]
I also see this warning. Must be related: `(node:90487) UnsupportedWarning: Status message is not supported by HTTP/2 (RFC7540 8.1.2.4)`

**Comment by pekkah** [comment]
Hitting the same issue after I switched to https. The request.url in APIEvent has
```js
url: URL {
      href: 'http://undefined/api/auth/csrf',
      origin: 'http://undefined',
      protocol: 'http:',
      username: '',
      password: '',
      host: 'undefined',
      hostname: 'undefined',
      port: '',
      pathname: '/api/auth/csrf',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    }
```
It also seems to use `http` even though I'm using the full url with https for the fetch.

This is my Vite configuration
```ts
import solid from "solid-start/vite";
import { defineConfig } from "vite";
import mkcert from "vite-plugin-mkcert";

export default defineConfig(() => {
  return {
    server: {
      https: true,
    },
    optimizeDeps: {
      include: ["@auth/core"],
    },
    plugins: [mkcert(), solid({ ssr: true })],
  };
});
```

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
