### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND] when attempting to run any of the templates

### ISSUE THREAD

**Issue by Jcanotorr06** [solidjs/solid-start#781]
I keep getting this error when trying to run the local dev server with any of the templates. I've tried `pnpm`, `yarn` and `npm` in both Windows and WSL to no avail.
![image](https://user-images.githubusercontent.com/59259618/222331138-ca16bc10-b61f-4ff0-a6db-9a435acfffaf.png)

Here's the `package.json` that was created:
```json
{
  "name": "slug",
  "scripts": {
    "dev": "solid-start dev",
    "build": "solid-start build",
    "start": "solid-start start"
  },
  "type": "module",
  "devDependencies": {
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.21",
    "solid-start-node": "^0.2.19",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.9.4",
    "vite": "^3.1.8"
  },
  "dependencies": {
    "@solidjs/meta": "^0.28.2",
    "@solidjs/router": "^0.7.0",
    "solid-js": "^1.6.11",
    "solid-start": "0.2.21",
    "undici": "^5.15.1"
  },
  "engines": {
    "node": ">=16"
  }
}
```

**Comment by boehs** [comment]
Known issue, and already resolved, we are just waiting for a new version. Add ```ts
  "pnpm": {
    "overrides": {
      "solid-refresh": "0.5.0"
    }
  },
``` to package.json

**Comment by lxsmnsyc** [comment]
This should be fixed now, either through re-install solid-start, vite-plugin-solid or solid-refresh
