### ISSUE TITLE
How to use cloudflare adapter?

### ISSUE THREAD

**Issue by ZeAmanuel28** [solidjs/solid-start#79]
I have build a simple site with solid start & need to deploy it in to cloudflare workers! 
I have installed the solid-start-cloudflare-workers packages & set it as an adapter in vite.config.js as an adapter! When I try to build the project, it fails with these error.

![Screenshot (263).png](https://user-images.githubusercontent.com/96905008/152760222-e657540b-f72d-4fc7-9854-e5dae21a9126.png)

How can I fix these problem?

**Comment by atk** [comment]
Did you (p)npm install the adapter in question? Please show us your `vite.config.js`.

**Comment by ZeAmanuel28** [comment]
```import { defineConfig } from "vite"; import solid from "solid-start"; 
import cloudflare from "solid-start-cloudflare-workers"; 

export default defineConfig({ plugins: [solid({ adapter: cloudflare() })] });```

When I use the first configuration it says it says it there is no default export from  solid-start-cloudflare-workers package!

When I make the adapter a string ("solid-start-cloudflare-workers") it will throw the error that is in the image above.

```export default defineConfig({ plugins: [solid({ adapter: "solid-start-cloudflare-workers" })] });```

**Comment by atk** [comment]
The first one should be all right.

**Comment by ZeAmanuel28** [comment]
No! it says there is no default export of solid start cloudflare package!

**Comment by atk** [comment]
It's right there: https://github.com/solidjs/solid-start/blob/main/packages/start-cloudflare-workers/index.js - maybe you have a stale installation, courtesy of the "next" tag, try (p)npm updating `solid-start-cloudflare-workers`.

**Comment by ZeAmanuel28** [comment]
Thanks! I have installed the @next packages & it works!

What do you think about a getting started documentation, videos, articles that I can't find these kind of things! I know that Ryan has made some videos but they are not efficient & detailed (they are some what show cases) , also there is some documentation on solid start repo, but please make work on them!

**Comment by ZeAmanuel28** [comment]
Thanks! I have installed the @next packages & it works!

What do you think about a getting started documentation, videos, articles that I can't find these kind of things! I know that Ryan has made some videos but they are not efficient & detailed (they are some what show cases) , also there is some documentation on solid start repo, but please make work on them!

**Comment by ZeAmanuel28** [comment]
One question that I have is do I need to wrap the outlet in the root.tsx with suspense to make data fetching work in the routes?

**Comment by ryansolid** [comment]
Yes Suspense is how it knows when it's done. That is how it registers the promises and knows when they are all resolved. The same is true for any of the async server mechanisms.

**Comment by ZeAmanuel28** [comment]
Thanks! that I have rewrited some parts of my client side rendered solid.js app with solid start & I have seen some cool 100 performance scores, although my graphql api is not so fast, I get 100% performance score! Thanks! you are making some cool tools that people can use & happy about it!
