### ISSUE TITLE
`<Title>` does not work with children with expression

### ISSUE THREAD

**Issue by leader22** [solidjs/solid-start#797]
Expect `<title>Hello world</title>`, but this code renders only `<title>Hello</title>`.

```jsx
import { Title } from "solid-start";
const PRE = "Hello";

export const Page = () => {
  return (
    <>
      <Title>{PRE} world</Title>
      {/* ... */}
    </>
  );
};
```

SSR outputs HTML has correct title, but update happens on client causes this problem.

It seems only first expression is rendered.

```jsx
<Title>World of {A}</Title> // -> <title>World of </title>
```

Inlining also does not work.

```jsx
<Title>{"DUMMY"} | XXX</Title> // -> <title>DUMMY</title>
```

### How to reproduce

- `npm init solid@latest`
```
✔ Which template do you want to use? › bare
✔ Server Side Rendering? … yes
✔ Use TypeScript? … no
```
- `npm run dev`
- Update `src/routes/index.jsx` like above
- Reload page

### Versions

```json
  "dependencies": {
    "@solidjs/meta": "^0.28.2",
    "@solidjs/router": "^0.8.0",
    "solid-js": "^1.6.14",
    "solid-start": "^0.2.23",
    "undici": "^5.21.0"
  },
```

### Workaround

Ensuring only 1 expression make it works.

```jsx
<Title>{`${PRE} world`}</Title> // -> <title>Hello world</title>
```

**Comment by arbassett** [comment]
@leader22 i can't reproduce this issue https://stackblitz.com/edit/node-ixjsgr?file=src/routes/about.tsx .. click Open in new tab (top right) and click between index and about.

if you still see it could you provide some information like OS and browser

**Comment by leader22** [comment]
Thanks for the confirmation.

It works as expected during page transitions, but the problem occurs on initial load and reload.

Here is the reproduced environment.

- macOS 12.6.3
- Chrome 112 & Firefox 110
- repro: https://github.com/leader22/solidstart-title-repro/

After `npm i && npm run dev`, 👇🏻 

https://user-images.githubusercontent.com/6259812/225780775-c8ff980a-2111-4b25-8566-afe7f626b260.mov

**Comment by arbassett** [comment]
I tried to recreate it with your example. but i wasn't able to

Env
- Windows 11 
- Chrome 111
- repro: https://github.com/leader22/solidstart-title-repro/


https://user-images.githubusercontent.com/32745766/226042552-9fb0ffce-da50-487c-8317-0c0523ee68a3.mp4

Slow 3G

https://user-images.githubusercontent.com/32745766/226042236-7a0b20fb-7d3e-4e09-a7cd-ac5961239489.mp4

**Comment by leader22** [comment]
Thanks again.

Just to be sure, I uploaded the `dist` directory as it is to the repro repo. (`node ./dist/server.js` reproduces as well, at least for me 😅 )

**Comment by arbassett** [comment]
> Thanks again.
> 
> Just to be sure, I uploaded the `dist` directory as it is to the repro repo. (`node ./dist/server.js` reproduces as well, at least for me 😅 )

Okay progress with the dist you uploaded i can reproduce the error... but if delete `node_modules` and reinstall with pnpm it works perfectly fine..

**Comment by leader22** [comment]
As you said, a clean install of everything finally got it working as expected.
I don't know why this happened, but I hope it's not a potential problem.

Thanks again, for your courteous support. 😉
