### ISSUE TITLE
HTTPHeader Component gets cleaned up too soon

### ISSUE THREAD

**Issue by petercorrea** [solidjs/solid-start#801]
When trying to utilize a `HTTPHeader` component from `solid-js`, the headers are not being passed on to the server response, and thus reach the client without the specified headers.

"solid-start": "^0.2.23"
 "solid-js": "^1.6.11"

**Comment by ryansolid** [comment]
I think I fixed this in Solid 1.7. So 0.2.25 should no longer have this issue.
