### ISSUE TITLE
Unable to resolve api routes in root path with a sibling parameterize route

### ISSUE THREAD

**Issue by arbassett** [solidjs/solid-start#806]
# Summary
Any route in the root of routes folder that is a api route or a component route that exports api fns is unable to call them if you have a sibling route with a paramater and index route ex `[id]/index.tsx`

[Stackblitz reproduction](https://stackblitz.com/edit/github-fd2bu6?file=src%2Froutes%2Findex.tsx%3AL12-L12) contains GET and POST examples

Thanks @dested for reporting this issue in [discord](https://discord.com/channels/722131463138705510/910635844119982080/1086763074066858106)

given these paths
```
/[id]/index.tsx
/get.ts
```
and the contents being
```tsx
// get.ts
import { json } from 'solid-start';

export const GET = () => {
  return json({ path: '/get.ts' });
};

// [id]/index.tsx
export default function IdIndex() {
  const location = useLocation();
  return (
    <main>
      <h1>[id]/index.tsx</h1>
      <Show when={location.pathname === '/get'}>
        <div>
          If you see this then your at the path /get but are showing
          [id]/index.tsx
        </div>
      </Show>
    </main>
  );
}
```

if you were to navigate or fetch `/get` instead of getting a json response back you would instead get the renderer result for the file `[id]/index.tsx`
# Details
for the next section i will be using this route structure object and this [router code](https://github.com/solidjs/solid-start/blob/d5bc201778e173db7bcd49d62aa0ef938b5828d9/packages/start/api/router.ts#L3-L43)

```js
 [
  {
    GET: 'skip',
    path: '/:id/',
    score: 7,
    params: [ [Object] ],
    matchSegments: [ null ],
    wildcard: false
  },
  {
    GET: [Function: GET],
    path: '/get',
    score: 4,
    params: [],
    matchSegments: [ 'get' ],
    wildcard: false
  }
]
```

What seems to be happening is the `[id]/index` (/:id/) has a higher score than get while normally this is fine as the match would fail on the checking the segments 
https://github.com/solidjs/solid-start/blob/d5bc201778e173db7bcd49d62aa0ef938b5828d9/packages/start/api/router.ts#L22-L23

But the `[id[/index` route contains a `[ null ]` matchSegment. so when the router runs its check to skip over matchSegments it will imminently exit that loop as it contains a single `null` and continue on the happy path. but if it hit the next check it would of tried the next route
https://github.com/solidjs/solid-start/blob/d5bc201778e173db7bcd49d62aa0ef938b5828d9/packages/start/api/router.ts#L16-L25

This issue has been in since `v0.1.6`

**Comment by arbassett** [comment]
For anyone wanting to tackle this here is a simple test patch [api-routes.patch](https://github.com/solidjs/solid-start/files/11012110/api-routes.patch)
```patch
diff --git a/test/api-routes-test.ts b/test/api-routes-test.ts
index d0aaa6e5..e36be1cf 100644
--- a/test/api-routes-test.ts
+++ b/test/api-routes-test.ts
@@ -42,6 +42,13 @@ test.describe("api routes", () => {
               </>
             )
           `,
+          "src/routes/[:id]/index.jsx": js`
+              export default () => <div>Should never see this</div>
+          `,
+          "src/routes/root-path.js": js`
+            import { json } from "solid-start/server";
+            export let GET = () => json({hello: "world"});
+          `,
           "src/routes/redirected.jsx": js`
             export default () => <div data-testid="redirected">You were redirected</div>;
           `,
@@ -254,5 +261,10 @@ test.describe("api routes", () => {
       expect(res.headers.get("content-type")).toEqual("application/json");
       expect(await res.json()).toEqual({ message: "Hello from Hogwarts" });
     });
+    test("should match root api path with sibling parameterized route", async () => {
+      let res = await fixture.requestDocument("/root-path");
+      expect(res.headers.get("content-type")).toEqual("application/json; charset=utf-8");
+      expect(await res.json()).toEqual({ hello: "world" });
+    });
   }
 });

```

**Comment by arbassett** [comment]
Found another thing where if you any of the internal fetch helpers and try to fetch you will get a 500 error from the server saying that there is no handler for get. 

this is happens as for the same reason as above but since `/:id/` doesn't have a explicit get handler but `skip` it fails

**Comment by dested** [comment]
This bug is really painful. 

I have noticed that changing this to a continue resolves the bug but I can't begin to imagine the implications...
```typescript
 const handler = route[method];
    if (handler === 'skip' || handler === undefined) {
      return;
    }
```
