### ISSUE TITLE
Exporting routeData function from index.tsx (or any other route) causes index.tsx to run twice

### ISSUE THREAD

**Issue by moonymax** [solidjs/solid-start#816]
# Bug Description

When exporting a routeData function from a route file (eg. index.tsx), the file is run twice. Additionally, if another component has a mutual import with index.tsx (eg. about.tsx), that route will also run index.tsx. This behavior appears with full page navigation, and occurs in both production and development (with default adapter). It is also not affected by server-side rendering or the browser being used. It is slightly different with client side navigation, for example when navigating to /about directly index.tsx is run and its run again when navigating to Home from the navbar. Client side navigation following that does not cause the files to be rerun as expected. Interestingly, in production the second run seems to be a different file, or at least the origin of the duplicate console.log is from a different file.

## Steps to Reproduce

1. Run pnpm create solid@latest
2. Choose options (with-tailwindcss, ssr true, ts true in my case).
3. run pnpm install
4. Add the following code to src/routes/index.tsx in the top level scope of the file:
```
export function routeData() {};
console.log("this is being run from index.tsx");
```
5. Create the file src/lib/mutualimport.ts with the following code:
`export function doSomething() {console.log("mutualimport.ts");};`
6. Import the doSomething function from mutualimport.ts in both index.tsx and about.tsx and call it in the component functions.
7. Run pnpm dev or pnpm build and pnpm start.
8. Visit localhost:3000 "this is being run from index.tsx" is logged twice.
9. Visit localhost:3000/about "this is being run from index.tsx" is logged once.
10. For client side navigation behavior visit localhost:3000/about and then click Home. "this is being run from index.tsx" will be logged once on the initial load and then again when navigating to Home (clicking on Home) through the web app navbar.

### Expected Result

index.tsx should only be run once, and the "this is being run from index.tsx" message should only be logged once when visiting /. Additionally, visiting /about should not run index.tsx.
#### Console output for / with pnpm build, pnpm start:
```
this is being run from index.tsx                                          index-4be73194.js:1
mutualimport.ts                                                    mutualimport-1c3d9cbb.js:1
```
#### Console output for /about with pnpm build, pnpm start:
```
mutualimport.ts                                                    mutualimport-1c3d9cbb.js:1
```

### Actual Result

index.tsx is run twice, and the "this is being run from index.tsx" message is logged twice when visiting /. Additionally, the /about route causes index.tsx to be run, resulting in the message "this is being run from index.tsx" being logged.
#### Console output for / with pnpm build, pnpm start:
```
this is being run from index.tsx                                   entry-client-2eb2b743.js:4
this is being run from index.tsx                                          index-4be73194.js:1
mutualimport.ts                                                    mutualimport-1c3d9cbb.js:1
```
#### Console output for /about with pnpm build, pnpm start:
```
this is being run from index.tsx                                   entry-client-2eb2b743.js:4
mutualimport.ts                                                    mutualimport-1c3d9cbb.js:1
```

#### Package.json:
```
{
  "name": "with-tailwind",
  "scripts": {
    "dev": "solid-start dev",
    "build": "solid-start build",
    "start": "solid-start start"
  },
  "type": "module",
  "devDependencies": {
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.21",
    "solid-start-node": "^0.2.19",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.9.4",
    "vite": "^4.1.4"
  },
  "dependencies": {
    "@solidjs/meta": "^0.28.2",
    "@solidjs/router": "^0.8.2",
    "solid-js": "^1.6.16",
    "solid-start": "^0.2.24",
    "undici": "^5.15.1"
  },
  "engines": {
    "node": ">=16"
  }
}
```

#### vite.config.ts:
```
import solid from "solid-start/vite";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [solid()],
});

```

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
