### ISSUE TITLE
Pnpm version can't update button

### ISSUE THREAD

**Issue by LuizzAugusto** [solidjs/solid-start#818]
I can't make button update in pnpm version (Hello World - Bare Template). An error message appear on inspect `Uncaught The browser resolved template HTML does not match JSX input:
<solid-children></solid-children>

<solid-children>. Is your HTML properly formed? `

This error not occur on npm version.

**Comment by LuizzAugusto** [comment]
Actually the problem is not in create the templates with pnpm, but install the libraries with it.

**Comment by dayblox** [comment]
Full error message:
```
Uncaught The browser resolved template HTML does not match JSX input:
<solid-children></solid-children>

<solid-children>. Is your HTML properly formed?
```

**Comment by ryansolid** [comment]
This is the result of 1.6.x version of Solid, and 1.7.x version of our build plugins. If you update Solid to 1.7 it should be fine.

**Comment by dayblox** [comment]
You are right, upgrading everything (including solid) to latest did the job
`pnpm up -L`
