### ISSUE TITLE
Closing Tag bug

### ISSUE THREAD

**Issue by romanobro56** [solidjs/solid-start#823]
After trying many times to reproduce this bug in stackblitz, I am stumped. The packages are up to date, and I even made it so that the stackblitz project is identical to my local one. But somehow it is not erroring. The best I can do is a zipped folder of my project, attached below.

Explanation:
The bug (error message: Cannot read properties of null (reading 'nextSibling')) occurs when a regular html element is followed by a custom component with a prop. This happens when switching pages, and the error message goes away after reloading. This occurs in production as well as dev mode. I am not sure if the prop destructuring is necessary because I have gotten the error message without it, but that might have been a vite hmr issue because I could not reliably reproduce that same error without it. The source code is pretty simple, as shown below.
`~/src/components/Bottom.tsx` (a component that would go on the bottom of each page)
<img width="824" alt="Screen Shot 2023-04-02 at 10 15 16 PM" src="https://user-images.githubusercontent.com/95649099/229396517-55efd7b3-e14e-415e-8e38-44553cd6e8fe.png">
`~/src/routes/index.tsx`
<img width="572" alt="Screen Shot 2023-04-02 at 10 15 32 PM" src="https://user-images.githubusercontent.com/95649099/229396612-b99ff68d-469f-4a0b-8f11-2f60f5219497.png">
`/src/routes/philosophy.tsx` (same issue)
<img width="594" alt="Screen Shot 2023-04-02 at 10 15 37 PM" src="https://user-images.githubusercontent.com/95649099/229396698-12bbf268-7804-4f5a-9ead-27683d1cec45.png">

full error message:

<img width="926" alt="Screen Shot 2023-04-02 at 4 12 05 PM" src="https://user-images.githubusercontent.com/95649099/229397334-6842be48-4b58-4fca-8792-fd7069951b89.png">

zipped project: 
[closing-tag-bug 3.zip](https://github.com/solidjs/solid-start/files/11134177/closing-tag-bug.3.zip)

steps to reproduce(from zip): npm i && npm run dev

**Comment by ryansolid** [comment]
I remove the lock file and node modules and install and I don't get the error.

**Comment by ryansolid** [comment]
I've released 0.2.25 which hopefully forces everything to the right version. We had some older libraries that had locked to earlier versions.

**Comment by romanobro56** [comment]
Okay, thank you.

**Comment by ryansolid** [comment]
I believe these are all closed now. So closing them.
