### ISSUE TITLE
`solid-start@latest` + `solid-js@1.7.1` = broken Node16/18 tests

### ISSUE THREAD

**Issue by AlexErrant** [solidjs/solid-start#827]
Changing all the solid-js references in this repo to v1.7.1 causes Node16/18 tests to fail as seen [in this draft PR](https://github.com/solidjs/solid-start/pull/826).

To be clear, [this is the guilty commit](https://github.com/solidjs/solid-start/pull/826/commits/c1adb9d3e43521ad0d86e353e3c6c32c849d7401), which implicates `package.json`, `packages/start/package.json`, or `test/template/package.json`. [This PR](https://github.com/solidjs/solid-start/pull/825), which is the predecessor of the above PR, has passing Node16/18 tests.

I've no idea what's wrong or how to fix 😊

**Comment by ryansolid** [comment]
Ok I will try to move everything today

**Comment by ryansolid** [comment]
Ok it should be fixed now minus the weird cloudflare tests that were failing in node 18 already.
