### ISSUE TITLE
Weird hydration issue

### ISSUE THREAD

**Issue by OrJDev** [solidjs/solid-start#830]
Using createEffect to print a signal seems to get the signal correctly, but when trying to render it im facing some weird behavior

The code for this page is:

```tsx

const AuthShowcase: VoidComponent = () => {
  const sessionData = createSession();
  createEffect(() => console.log("sess", sessionData()));
  return (
    <div class="flex flex-col items-center justify-center gap-4">
      <p class="text-center text-2xl text-white">
        <Show when={sessionData().data?.user} keyed>
          {(user) => <span>Logged in as {user.name}</span>}
        </Show>
      </p>
      <button
        class="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={() => {
          if (sessionData().data) {
            void signOut();
          } else {
            void signIn("github");
          }
        }}
      >
        {sessionData().data ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
````

<img width="1440" alt="Screenshot 2023-04-05 at 15 05 06" src="https://user-images.githubusercontent.com/91349014/230075272-5735a51d-ab69-4ffc-9076-e707fe5a638f.png">

It does say `logged in as` but the name is not being rendered even tho it is defined, it says sign in even tho sessionData().data is defined (an object) so we expect it to say `sign out` - last: getting some weird hydration error on the console as you can see

```
Unable to find DOM nodes for hydration key: 0-0-0-0-0-0-0-0-0-1-0-0-0-0-0-0-0-0-0-0-1-0-0-4-0-0-1-0
```

**Comment by nksaraf** [comment]
Maybe some suspense issue? Not sure how this would happen

**Comment by OrJDev** [comment]
> Maybe some suspense issue? Not sure how this would happen

I don't use any resource so suspense can't be triggered,

The code for createSession is here:

https://github.com/OrJDev/solid-auth/blob/main/src/client.tsx#L50

**Comment by OrJDev** [comment]
> > Maybe some suspense issue? Not sure how this would happen
> 
> I don't use any resource so suspense can't be triggered,
> 
> The code for createSession is here:
> 
> https://github.com/OrJDev/solid-auth/blob/main/src/client.tsx#L50

Update the session context here:

https://github.com/OrJDev/solid-auth/blob/main/src/client.tsx#L137

**Comment by OrJDev** [comment]
managed to solve it
