### ISSUE TITLE
`pnpm` interactivity bug

### ISSUE THREAD

**Issue by afonsojramos** [solidjs/solid-start#833]
Heyo! 😊

I've came up with a weird bug that I'm not 100% sure how to fix. I've switched to pnpm in a solid-start small project I was starting and cape up to this.

<img width="185" alt="image" src="https://user-images.githubusercontent.com/19473034/230447371-e3c376c1-6546-4571-9e14-09b30b36e9fe.png">

Clicking on the button does nothing and I can find this in the console.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/19473034/230447528-293ca6b0-f487-4130-af31-ae5fb333d25d.png">

### Steps to reproduce

1. Run [npm create jd-app@latest](https://github.com/OrJDev/create-jd-app) (created with Tailwind and tRPC)
2. Create a Counter component, see it working fine
3. Switch to `pnpm`
4. Counter component no longer works

PS: Noticed that there are no issue templates, but that you do have them on https://github.com/solidjs/solid. I'm open to helping with these, just got a question, do you want to have these on all repos or just on some? Because if you want them to be on all repos, we could move the issue templates into https://github.com/solidjs/.github

**Comment by AlexErrant** [comment]
Update your deps. [Related issue](https://github.com/solidjs/solid-start/issues/818).

**Comment by afonsojramos** [comment]
Can confirm that it fixed it, thanks @AlexErrant!
