### ISSUE TITLE
Root data loading

### ISSUE THREAD

**Issue by MWGuy** [solidjs/solid-start#836]
Hi. I'm looking for some way of loading initial data from server (with session access) in application Root, but i can't find any solution.

For example in remix i can define loader function in Root component and use response in any page.

**Comment by AlexErrant** [comment]
[This example gets session data for the index page](https://github.com/solidjs/solid-start/blob/main/examples/with-auth/src/routes/index.tsx#L5)... unless you're looking for [context](https://www.solidjs.com/tutorial/stores_context)? IDK my experience with Remix is minimal.

**Comment by Bersaelor** [comment]
I'm also looking for the same, I can't use `routeData` because I have set my whole app hierarchy to render in the client, and I need the data for the `tags` on the server, before the client renders:

```jsx
[root.tsx]

  const serverData = `?`;
  
  return <Html lang="en">
      <Head>
        <OGHeaders data={serverData} />
      </Head>
      <Body>
              <ClientOnly>
                <AuthContextProvider>
                  <AppContextProvider>
                    <Routes>
                      <FileRoutes />
                    </Routes>
                  </AppContextProvider>
                </AuthContextProvider>
              </ClientOnly>
      </Body>
    </Html>
```

**Comment by hardywu** [comment]
@MWGuy   @Bersaelor You can refer to #647 to set up the init "root.data.ts" file

**Comment by Bersaelor** [comment]
So, what I ended up doing is:

```jsx
[root.tsx]

  return (
    <Html lang="en">
      <Suspense>
        <SSRContextProvider>
             //...
             
```
and load the server side content in `SSRContextProvider`.
This way the code structure is cleaner too and the SSRContextProvider can call routeData successfully

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
