### ISSUE TITLE
DEV is undefined with Solid 1.7.x

### ISSUE THREAD

**Issue by jchatard** [solidjs/solid-start#842]
Since migrating to Solid 1.7.x in my Solid Start project, the `DEV`is always `undefined`.

I rolledback to 1.6.16 and it's working again.

I so few commits about Skypack and DEV export which could be related:

https://github.com/solidjs/solid/commit/705820c0d82b2e4585379abe78eab61e1a9c28d5
https://github.com/solidjs/solid/commit/27994dc93c65db1888a9258b896f5f0115242970

Simple reproduction:
https://stackblitz.com/github/jchatard/solid-dev?file=src%2Froutes%2Findex.tsx

Thanks,
Jérémy

**Comment by jchatard** [comment]
I should add, that up to 1.7.3 this is still occuring.

**Comment by ryansolid** [comment]
Given that it is there in the code, I wonder if somehow the wrong version of Solid is getting bundled in dev mode. Although I'd expect other bad side effects.

**Comment by ryansolid** [comment]
Oh.. it's because there is no DEV mode on the server builds only client so the server is thinking it is Prod and then hydration is basically breaking or rather not updating the nodes. Console.log shows me DEV is defined in the browser.

**Comment by jchatard** [comment]
Yes, that's right, I'm seeing this as well!

**Comment by edivados** [comment]
> Oh.. it's because there is no DEV mode on the server builds only client so the server is thinking it is Prod and then hydration is basically breaking or rather not updating the nodes. Console.log shows me DEV is defined in the browser.

@ryansolid  I hit a related problem I think where `isDev` from `solid-js/web` is always false on the server. Took a look and there is no dev build for `web/server` that gets `_SOLID_DEV_` replaced. It's just hardcoded to false.

I can live with using `import.meta.env.DEV`. Just letting you know.

**Comment by ryansolid** [comment]
I think `import.meta.env.DEV` might have to be the answer because doing conditional logic will always be wrong in Dev from solid itself even if we made an `isDev` false.
