### ISSUE TITLE
Problem using ref={} to assign on mount

### ISSUE THREAD

**Issue by benstahl** [solidjs/solid-start#844]
I'm trying to use ref={} to assign/bind variables, as seen in the tutorials here: https://www.solidjs.com/tutorial/bindings_refs. There are no errors, but when I try to use them in onMount(), they are undefined. I created a very simple project with SolidStart ("with Vitest" template, no SSR, yes TypeScript) v0.2.25.

Here is a simple component that is inserted into the index HTML:

```
import { createSignal, onMount } from "solid-js"

let testDiv: HTMLDivElement
let testCanvas: HTMLCanvasElement

onMount(() => {
	console.log(testDiv ?? 'Div is undefined')
	console.log(testCanvas ?? 'Canvas is undefined')
})

export default function Test() {
	return (
		<div ref={testDiv}>
			<canvas ref={testCanvas} width='800' height='400' />
		</div>
	)
}
```

When run (using "pnpm run dev"), both the div and canvas are reported as being undefined inside onMount(), same in both Chrome and Safari. Is there some other step I'm missing?

**Comment by boehs** [comment]
Could you just close it

**Comment by benstahl** [comment]
> Could you just close it

I was about to, but I had an actual issue, so I'm re-using it.

**Comment by benstahl** [comment]
All right, I'm just dumb. It turns out to be simple of course, onMount() needs to be _inside_ the component function, and I had it outside, where it doesn't work.

Curious if there's ever a reason to use onMount() outside of a component function, or if it should generate an error?
