### ISSUE TITLE
Document type-safe locals usage

### ISSUE THREAD

**Issue by parisholley** [solidjs/solid-start#848]
An update was made to support a `locals` object that can be populated in middlewhere but it isn't clear what the best practice is to utilize it.

https://github.com/solidjs/solid-start/issues/642

For my project I have a custom types definition so that I can change the `Record` into a known type like so: 

```typescript
declare module 'solid-start' {
  interface ServerFunctionEvent {
    locals: MyCustomType;
  }
}
```

To consume locals in a typesafe way, I have to do the following:

```typescript
server$(async function (this: ServerFunctionEvent) {
  this.locals.myCustomFunction();
});

createServerAction$(async function (this: ServerFunctionEvent) {
  this.locals.myCustomFunction();
});
```

If using an API that makes `FetchEvent` available as an argument, that can be used as well but its availability is not consistent (eg: cannot access via an argument with `server$`).

Is the usage of `this` a blessed approach? If so, is there a way to update the API interfaces to enforce the type of `this` so it does not have to be explicitly defined?

**Comment by austins** [comment]
+1. This is a very powerful feature. An example of how to configure a custom types file to type them, and where to assign locals would be good.

**Comment by ryansolid** [comment]
Good idea.. we should document how to extend locals on FetchEvent

**Comment by ryansolid** [comment]
Documented now https://start.solidjs.com/api/RequestEventLocals
