### ISSUE TITLE
Supported "defined" useRouteData when deferStream = true

### ISSUE THREAD

**Issue by parisholley** [solidjs/solid-start#849]
Coming from remix, one of the features I enjoyed was data guarantees in hooks when using loaders. At the moment, the return type (and runtime behavior) of combining `createServerData$` and `useRouterData` is to return `undefined` on the first render, forcing the consumer to always add runtime checks (eg: loading fallbacks or empty fragments). Looking through the code, it seems plausible that we could eliminate the need for this when `deferStream` =  true. 

It would require some coordination between a few files/packages but I believe a possible solution could look like this:

https://github.com/solidjs/solid-router/blob/b2b13137710ef528919677e3465ca9f0cf68f87b/src/components.tsx#L190-L197

Instead of just waiting for `route.child`, we could also wait for a new property eg: `route.deferred`, which would be set to true in the presence of a `deferStream` resource.

https://github.com/solidjs/solid-router/blob/b2b13137710ef528919677e3465ca9f0cf68f87b/src/routing.ts#L534-L541

We could somehow expose the `TempRoute` to the underlying `createServerData$` call, so that it could set `route.deferred` = true when the option is passed in. Alternatively we could maybe add a symbol to `Resource` that is returned from `createServerData$` to denote it has deferred the stream and the `Outlet` component could check it there instead of passing `TempRoute` around.

**Comment by ryansolid** [comment]
Hmm... the router isn't aware of the resources so this could never be the general solution and generally we are non-blocking. Now createRouteData could be aware so that is an interesting proposal although it means that stuff like Tanstack Query wouldn't get the same treatment. My gut is if there is a change in Suspense propagation that would come from core, and short of that any specific mechanism is too specialized for the case.

**Comment by parisholley** [comment]
I want to expand on this a bit having read the documentation a little more and also noticing a similar conversation in #772.

When exploring the differences between `renderAsync`, `renderStream` and `renderSync`, it is clear that that are render scenarios in which (to the user) the loading/rendering is effectively serial/synchronous. Of the three, two of them guarantee that data will always be there before sending a rendered component the client.

Comparing (conceptually) to react router, where it allows for async functions to be invoked prior to component rendering, it seems odd that a similar concept doesn't exist here. 

> My gut is if there is a change in Suspense propagation that would come from core

I'm not familiar enough with how the projects are intertwined to interpret this, but is the limitation here that solid router from core has no concept of "await before render" and "start" isn't building much on top of the core router? The idea of `useRouteData()` in my opinion is a client-side concept/design decision and I would argue that another layer on top is appropriate for an SSR-style framework.

If I were guess about the current implementation, is that it is simply reading the file "routes", compiling them into a component and passing "as-is" to `<Route />`? In the case of wanting to get rid of undefined, could we not have `useRouteData` (or perhaps introduce a new hook eg: useServerData) rely on suspend/throw promise when executing on the server and "wrap" the component in a "NoOp" component that never makes to the client side? For example:

```typescript
function SolidRoute(component){
 if(IS_SERVER){
   // useRouteData() throws promise on server side
   return (<Suspense>{component}</Suspense>
 }

 // current behavior applies
 return {component}
}
```

```jsx
      <Routes>
        <Route path="/" component={<SolidRoute component={MyRoute} />} />
      </Routes>
```

Unless I am missing something, there isn't a case client-side in which `useRouteData()` would "revert" back to undefined, so once the server renders, there is always guaranteed to be a value (either on initial load or if refreshing). 

I suppose what could break the proposal above is it will depend on how the lifecycle of a navigation event works. eg: If loading a new page always result in a SSR response (html + hydrate) then it seems simple enough. But if other routes are pre-loaded client side and only the "loader" functions/XHR is invoked then passed to the component, then I could understand why doing the above would cause a lot of complexity (eg: initial render vs subsequent renders behaving completely different).

**Comment by parisholley** [comment]
and to add a little more color :)

in an attempt to make the "pattern" a bit more ergonomic and abstract away the concept of undefined, the challenge becomes clear in this example:


```jsx

// route.tsx

export default function(){
   return (
  <RouteComponent title='Order Review' fn={routeData}>
        {(data) => <></>}
  </RouteComponent>
);
}


// utilit.tsx
export function RouteComponent<T>(props: { title: string; fn: (args: RouteDataFuncArgs) => Resource<T | undefined>; children: (data: T) => JSX.Element }) {
  const data = useRouteData<typeof props.fn>();

  return (
    <>
      <Title>{props.title}</Title>
      <Show when={data()}>
        {(data) => props.children(data())}
      </Show>
    </>
  );
}
```

given the "magic" of the compilation process, routeData as a "value" will never be available and compilation will fail on the client-side bundle. without passing the function as a value, there is no good way to "type" the generic component and know what T is without casting it explicitly adding more DX headaches :)

**Comment by ryansolid** [comment]
Router and data loading patterns don't really belong here and/or have changed.

In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
