### ISSUE TITLE
config.solidOptions is undefined when using pnpm

### ISSUE THREAD

**Issue by untlsn** [solidjs/solid-start#85]
```
/node_modules/.pnpm/solid-start-node@0.1.0-alpha.8_solid-start@0.1.0-alpha.61/node_modules/solid-start-node/index.js:9
  const { preferStreaming } = config.solidOptions;
                                     ^

TypeError: Cannot read properties of undefined (reading 'solidOptions')
```

The error only occurs when using pnpm (shamefully-hoist=true does not fix the error). Dev server works the same as npm / yarn

**Comment by ryansolid** [comment]
Hmm.. it's not installing the `@next` version it looks like. It's grabbing `latest`. Which is werd as I think we stipulate `next` everywhere.

**Comment by untlsn** [comment]
On monorepo, solid-start and solid-start-node are correctly fetched from packages
In a clear project, pnpm uses 2 versions of solid-start-node
solid-start-node@0.1.0-alpha.8_solid-start@0.1.0-alpha.61 -> from project
solid-start-node@0.1.0-alpha.61_eee059c8297e3fec60c932ec02fc65cf -> from solid-start@0.1.0-alpha.61_6c55d0c327054e42333054f10197b1c4

**Comment by russelgal** [comment]
> On monorepo, solid-start and solid-start-node are correctly fetched from packages In a clear project, pnpm uses 2 versions of solid-start-node [solid-start-node@0.1.0-alpha.61_eee059c8297e3fec60c932ec02fc65cf](mailto:solid-start-node@0.1.0-alpha.61_eee059c8297e3fec60c932ec02fc65cf) solid-start-node@0.1.0-alpha.8_solid-start@0.1.0-alpha.61
> 
> And only one solid-start solid-start@0.1.0-alpha.61_6c55d0c327054e42333054f10197b1c4

my temporary workaround
`		"postinstall": "rm -rf node_modules/.pnpm/solid-start-node@0.1.0-alpha.8_solid-start@0.1.0-alpha.61"`

**Comment by MarvinRudolph** [comment]
Looks like `solid-start` wants the incorrect alpha.8 dependency, maybe because it's an optional dependency of `solid-start-node` is set to `*`?
Running `pnpm why solid-start-node` shows this:
<img width="332" alt="CleanShot 2022-03-07 at 12 58 24@2x" src="https://user-images.githubusercontent.com/6840287/157030393-863e5a84-f8d9-4054-bd6e-f5e5731a0e8c.png">
