### ISSUE TITLE
Typo in api/refetchRouteData Doc

### ISSUE THREAD

**Issue by medinillag** [solidjs/solid-start#857]
Link: https://start.solidjs.com/api/refetchRouteData
Section: Reference
Title: refetchRouteData(keys)
Error: Call **retchRouteData()** to refetch either all the route data on the page, or specific ones based on the key.
Solution: Call **refetchRouteData()** to refetch either all the route data on the page, or specific ones based on the key.

**Comment by dayvster** [comment]
Made a [PR](https://github.com/solidjs/solid-start/pull/861) for this
