### ISSUE TITLE
SSR Hydration Error

### ISSUE THREAD

**Issue by BigDog1400** [solidjs/solid-start#881]
# Bug description
If you create a createServerData$ route data, and try to return an array of elements that are instance of a class, in a SSR page it will break the hydration of the elements, but if you go to that route using client side navigation, it will work fine, i guess that the SSR should work exactly as the client side navigation does. 

## Minimal reproduction example
[CodeSanbox](https://codesandbox.io/p/github/BigDog1400/solid-start-hydration-bug/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clhmujmta000a356p1ybi4e0n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clhmujmta000c356pzjwsnmz5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B33.39078901499012%252C66.60921098500988%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clhmujmta000a356p1ybi4e0n%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clhmujmta0009356pzdq834ch%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clhmujmta000a356p1ybi4e0n%2522%252C%2522activeTabId%2522%253A%2522clhmujmta0009356pzdq834ch%2522%257D%252C%2522clhmujmta000c356pzjwsnmz5%2522%253A%257B%2522id%2522%253A%2522clhmujmta000c356pzjwsnmz5%2522%252C%2522activeTabId%2522%253A%2522clhmujus400dn356pm2kek0sv%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clhmujrnr007m356p5v36jqbj%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clhmujus400dn356pm2kek0sv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) (to see the alerts in the /structured-clone route, open in a new tab the instance created by codesanbox)
[Github Repo](https://github.com/BigDog1400/solid-start-hydration-bug)
## Steps to reproduce
Run the project. Go to the index page, the buttons doesn't trigger the alert callback that is attached in the onClick event. Go to the /structured-clone, the buttons works properly, then go to the index with the <A/> link, and test the button again (it will work properly)
## Expected behavior
The page access directly, with SSR should work exactly as it does when the client side navigation happens.

**Comment by LiamMartens** [comment]
I don't believe this is a supported use case anyways. Objects passed through SSR should always be fully serializable as noted in the docs
> The data returned from the fetcher function must also be JSON serializable object or a Response object.

https://start.solidjs.com/api/createServerData#serializing

**Comment by lxsmnsyc** [comment]
This fails for two reasons:
- the serializer is limited to only a handful of data types. `createServerData$` is limited to JSON types.
- `structuredClone` is also limited to [a list of data types](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#supported_types) too.

So the usual solution here is to convert your class instance into a value that the serializer supports, and then reconstructing that data (or retaining it as-is).
