### ISSUE TITLE
dev mode 

### ISSUE THREAD

**Issue by darkship** [solidjs/solid-start#882]
Hey, 
when I start a new project with vitest and SSR, `pnpm dev` seems to not build properly and the simple increment button doesn't increment.

![image](https://github.com/solidjs/solid-start/assets/3523710/f06bc862-fcf4-499b-bf1b-8c43248c7d12)

error: Uncaught The browser resolved template HTML does not match JSX input:
<solid-children></solid-children>

<solid-children>. Is your HTML properly formed?

repo: https://github.com/darkship/solid-demo
pnpm: 8.5.0

**Comment by ryansolid** [comment]
This looks like using the latest babel plugin with an older version of Solid. Are you using Solid 1.7.x

**Comment by darkship** [comment]
it's the one given by solid-start `"solid-js": "^1.6.11",`

**Comment by darkship** [comment]
I upgraded every package and it worked. Still, this shouldn't happen  on a fresh install

**Comment by siduck** [comment]
can confirm I face this issue too, none of my buttons are clickable as a sideeffect @darkship

**Comment by ryansolid** [comment]
Yeah this issue is odd as solid-start only inclues solid as a dev dep so people doing installs shouldn't have an issue. In any case it appears to be fixed now.
