### ISSUE TITLE
Sourcemap for . . . points to missing source files

### ISSUE THREAD

**Issue by shareable-vision** [solidjs/solid-start#884]
This bug appears similar to what @Vexcited [was experiencing](https://discord.com/channels/722131463138705510/722349143024205824/1034581842034184222)⁠, and possibly related to what Vite/React users were experiencing [here](https://github.com/vitejs/vite/issues/5438).

solid-start v0.2.26
vite v4.1.4

The files reported as missing are present and the code is functioning perfectly despite the error message.
Each of the files reported as missing refer to files which exclusively export a server function defined normally, written in Typescript, e.g.:

```ts
import server$ from 'solid-start/server'
import { destroyMemberSession } from '~/services/MemberSession';

export default server$(async (): Promise<Response> => {
    const cookie = await destroyMemberSession(server$.request)
    return new Response(null, { headers: { "Set-Cookie": cookie }})
})
```

**Comment by shareable-vision** [comment]
It makes sense that this happens: The client code is importing a server function, which only runs on the server and which the inner workings of cannot be exposed to the client. Thus, the source files are missing. I'm not sure what this bug reveals about Babel transforms, and if there is an actual "issue" at the root of the symptom.

I honestly just wanted to suppress the warning error. Tracing the warning back to Vite's  /node/server/sourcemap.ts, I realize that it's being called by the `logger.warnOnce` function --pretty obvious in retrospect, so to suppress the warning, create a custom logger, for example:

vite.config.ts:
```
import { createLogger, defineConfig } from "vite";
//* Suppress "missing source files" warning for server functions:
//? https://vitejs.dev/config/shared-options.html#customlogger
const logger = createLogger()
const warnOnce = logger.warnOnce
logger.warnOnce = (message, options) => {
    if (message.includes('points to missing source files') && message.includes('/rpc/')) return
    warnOnce(message, options)
}

export default defineConfig({
    customLogger: logger
})
```

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
