### ISSUE TITLE
Feature request: allow customizing Server Function HTTP method

### ISSUE THREAD

**Issue by Coretteket** [solidjs/solid-start#902]
Currently, all requests done on the client-side for a `server$` function are POST requests. This makes sense as a default, but there are many possible use-cases for `server$` for simply querying data, where a GET request would be more appropriate. This is not _just_ semantics, with the problem I run into the impossibility of caching `server$` requests on [Vercel's Edge Network](https://vercel.com/docs/concepts/edge-network/caching#cacheable-response-criteria). Therefore, I would appreciate the option to select a different HTTP method. For context, I raised this issue for pRPC (OrJDev/prpc#73), which uses `server$` for a `query$` function under the hood, which therefore is limited by Solid Start.

**Comment by Coretteket** [comment]
Awesome – can't wait!

**Comment by Download** [comment]
Not sure why POST would even make sense as the default, actually...

What is the default of HTML (`<form>` tag without `method` specified)?: GET
What is the default CURL uses?: GET
What is the default of `fetch`?: GET

IMHO there is only one sane default for requests and that is GET...

**Comment by lxsmnsyc** [comment]
@Download The only reason POST makes sense is because the server functions utilizes the request body, something that GET cannot offer. However, GET can be potentially supported, ideally if the function has no arguments or if the arguments can be safely encoded in the url.

Other methods should work just fine

**Comment by ryansolid** [comment]
This has been implemented in SolidStart in 0.5.x via the GET method.
