### ISSUE TITLE
`root.tsx`'s fallback `<Title>` isn't applied on client side routing

### ISSUE THREAD

**Issue by UnlimitedBytes** [solidjs/solid-start#903]
### Describe the bug

When you set a fallback `<Title>` in the `root.tsx` it's ignored on CSR (Client Side Routing), when you didn't initially loaded a page that used the default title. So for example when we have an application with 2 routes `/` and `/about` and we're setting the `<Title>` in `root.tsx` to `"Default"` and change it on the `/` route to `"Home"` while not setting any title on the `/about` route. We will get the following results:
- Server Side Rendering
  - `/` = "Home"
  - `/about` = "Default"
- Client Side Routing
  - `/` = "Home"
  - `/about` = "http://..." (default browser title) or "Default"

### Reproduction
You can find a repository which contains the code to reproduce this bug here:
https://github.com/UnlimitedBytes/solidstart-bug.

I also hosted the above linked repository here:
https://solidstart-csr-fallback-bug.surge.sh/

Using the hosted version we can see what should happen by:
- Opening https://solidstart-csr-fallback-bug.surge.sh/about
- Clicking on "Home"
- Clicking on "About"
which will give us the title "Default"

And what actually happens (the bug) by:
- Opening https://solidstart-csr-fallback-bug.surge.sh/
- Clicking on "About"
which will give us the title "http://..." (default browser title)

### Severity

serious, but I can work around it

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
