### ISSUE TITLE
Properties from an object returned by createRouteData are undefined for a moment after page load

### ISSUE THREAD

**Issue by cs-clarence** [solidjs/solid-start#907]
## Problem

I have a route which for some reason has a undefined properties when accessing some properties/methods on it even though the object returned has no undefined properties on it.

```tsx
// sample object returned from routeData
// -- snip --
const data = {
        body: "body",
        title: "title",
        closed: false,
        creator: { username: "Test", displayPictureURL: null },
        createdAt: new Date(),
};

// When the data above is returned from routeData, 
// you can't access properties/methods on it's properties without conditional chaining
const data = useRouteData<typeof routeData>();

// this is ok
return <p>{data()?.title}</p>

// this is NOT ok, throws TypeError: Cannot read properties of undefined 
return <p>{data()?.title.toUppercase()}</p>

// unless we conditionally chain
return <p>{data()?.title?.toUppercase()}</p>
```
This does not agree with the return type inferred from routeData because title can't be undefined.
This is the case with every property from the object, accessing properties or invoking methods on them without conditional chaining leads to a `TypeError`:
![image](https://github.com/solidjs/solid-start/assets/71768661/be0a664c-0915-42a3-a54b-c31ce173c5fc)

Clicking `Clear errors and retry` displays the page properly without the error.

During SSR, the page displays properly. When the page fully loads, that is when the error appears. I assume this is an issue during hydration.

This is the general structure of the code I'm working on that his this issue:
```tsx
import { createRouteData, useRouteData, type RouteDataArgs } from "solid-start";
import { Show } from "solid-js";

export function routeData({ params }: RouteDataArgs) {
  return createRouteData(
    async (_, event) => {

      // fake data
      return {
        body: "body",
        title: "title",
        closed: false,
        creator: { username: "Test", displayPictureURL: null },
        deleted: false,
        createdAt: new Date(),
      };
    },
    {
      key: () => ["discussion"],
    },
  );
}

export default function DiscusionPage() {
  const data = useRouteData<typeof routeData>();

  return (
    <Show
      when={data()}
      fallback={<div>Loading...</div>}
    >
      {(data) => (
        <div class={container}>
          <div class={discussionContainer}>
            <div class={discussionHeader}>
              <h3 class={discussionTitle}>{data().title}</h3>
              <div>
                <h4 class={discussionCreator}>
                  Posted by {data().creator.username}
                </h4>
                <h5 class={discussionDate}>
                  Posted on {data().createdAt.toLocaleString()}
                </h5>
              </div>
            </div>

            <p class={discussionBody}>{data().body}</p>
          </div>
        </div>
      )}
    </Show>

  );
}
```

### Conditional Chaining
The code which errors are:
`{data()?.creator.username}` and `{data()?.createdAt.toLocaleString()}`. As I said above, using conditional chaining on them removes the TypeErrors.

### Wrap the return value in an array
Additionally, the problem isn't present when wrapping the value in an array.

Return value of routeData
```ts
return [{
  boardID: BigInt(boardID),
  id: BigInt(discussionID),
  body: "body",
  title: "title",
  closed: false,
  creator: { username: "Test", displayPictureURL: null },
  deleted: false,
  createdAt: new Date(),
  creatorID: 1n,
  updatedAt: new Date(),
}];
```
Access it in the component:
```ts
const d = useRouteData<typeof routeData>();
const data = () => d()?.[0];
```

## Package Verions
```
"solid-js": "^1.7.6",
"solid-start": "^0.2.26",
"solid-start-node": "^0.2.26",
"undici": "^5.22.1",
"vite": "^4.3.9",
```

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
