### ISSUE TITLE
solid-start-cloudflare-pages Error

### ISSUE THREAD

**Issue by rattleSSnake** [solidjs/solid-start#918]
As soon as I include Cloudflare adapter to vite config, I get this error.
![image](https://github.com/solidjs/solid-start/assets/89637856/64aef517-ebd4-4ca7-a15a-20acfb539a52)

**Comment by davycoe** [comment]
This is due to using node v19+ that already assigns Web Crypto API on globalThis.crypto.

See this PR #933 

You could use node v18 and lower in the meantime.

**Comment by rattleSSnake** [comment]
All right... thanks
