### ISSUE TITLE
[Bug?]: useLocation not updating during nested route changes

### ISSUE THREAD

**Issue by caseybaggz** [solidjs/solid-start#937]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When you use nested routing via the `Outlet` component, the `A` keeps the `activeClass` and `aria` set to current for the every path of the child Outlet.

For example, with the current route structure:
- @me.tsx (global nav)
  - (@me).tsx
  - profiles.tsx

The attributes will remain active no matter if the URL is either `/@me` or `@me/profiles`. This seems to be due to the router not recognizing the change in the child pathname via the `const { pathname } = useLocation()` hook.

### Expected behavior 🤔

The `useLocation` hook should be able to identify the route structure and URL change with nested routes using the `Outlet` component.

### Steps to reproduce 🕹

Steps:

1. Create a new SS project using SSR
2. Create 2 levels of routing using the Outlet component with a global nav in the parent
3. Set active styles for the `A` component
4. Navigate to different child pages
5. 🛑 LINKS DO NOT CHANGE - validate in the dev console and aria attrs and log with `useLocation` hook

### Context 🔦

When you log the result of `const { pathname } = useLocation()` it appears the parent is not updating the pathname even though a route  and pathname changes. The `A` component logic looks fine, so it seems to be a router issue?

### Your environment 🌎

```shell
"dependencies": {
    "@solidjs/meta": "^0.28.2",
    "@solidjs/router": "^0.8.2",
    "rollbar": "^2.26.2",
    "sanitize.css": "^13.0.0",
    "solid-js": "^1.7.7",
    "solid-start": "^0.2.26",
    "undici": "^5.15.1",
    "yup": "^1.2.0"
  }
```

**Comment by JesusP2** [comment]
that's the intended behavior, if you want activeClass to only work if the route is exactly the same you can use the "end" attribute. You can check the docs: https://docs.solidjs.com/guides/how-to-guides/routing-in-solid/solid-router#creating-links-to-other-routes
