### ISSUE TITLE
[Bug?]: Solid Start should be a dev dependency instead of a dependency

### ISSUE THREAD

**Issue by edivados** [solidjs/solid-start#942]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

All examples declare solid-start as a dependency and because of that the solid-start package is installed in production. I don't think it is required beyond creating the final build. When building for node (default) the server can be started with 
`node dist/server.js` and does not rely on the package. Installing it is an additional `92MB`.

The start command is more of a preview build and other adapters like aws for example don't do anything on start.

### Expected behavior 🤔

The solid-start package should be declared as a dev dependency so that only the necessary packages are installed in production, reducing the size of node_modules.

### Steps to reproduce 🕹

Steps:

Create a bare project with (typescript, ssr)

1. npm init solid@latest
2. npm i
3. npm run build
4. rm -rf node_modules
5. NODE_ENV=production npm ci
6. du -sh node_modules
7. node dist/server.js

Final `node_modules` size `106 MB`

The same but without solid-start in production

1. npm init solid@latest
2. npm i
3. npm run build
4. npm uninstall solid-start
5. rm -rf node_modules
6. NODE_ENV=production npm ci
9. du -sh node_modules
10. node dist/server.js

Final `node_modules` size `4.9 MB`

### Your environment 🌎

```shell
Binaries:
  Node: 18.17.0
  NPM: 9.6.7
OS
  NAME="Alpine Linux"
  ID=alpine
  VERSION_ID=3.18.2
  PRETTY_NAME="Alpine Linux v3.18"
```

**Comment by joseph-lozano** [comment]
for what its worth, `node dist/server.js` works for me in a bare project, but as soon I add Prisma, I need the full `solid-start start`.

**Comment by edivados** [comment]
> for what its worth, `node dist/server.js` works for me in a bare project, but as soon I add Prisma, I need the full `solid-start start`.

Hey appriciate the input. I tried to see if this is the case with my smaple repo here https://github.com/edivados/solid-trpc-prisma but cloudn't reproduce it. Do you have a repo I could take a look at or a minimal example?

I don't think that there should be anything that makes prisma depend on solid-start. But there is the possibility that I am missing something.

**Comment by joseph-lozano** [comment]
Actually, I get this same error, regardless of if I do `node dist/server.js` or `solid-start start`. I think I am just holding Prisma wrong.

**Comment by edivados** [comment]
> Actually, I get this same error, regardless of if I do `node dist/server.js` or `solid-start start`. I think I am just holding Prisma wrong.

@joseph-lozano Add `ssr: { external: ["@prisma/client"] }` to your vite config and the error will be gone.

**Comment by edivados** [comment]
For some reason the last package.json snippet does not work with pnpm but does with npm. I will close this for now.
