### ISSUE TITLE
[Bug?]: On internal navigation, middleware doesn't work correctly

### ISSUE THREAD

**Issue by rattleSSnake** [solidjs/solid-start#949]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The following issues only applies on **internal navigation** (meaning when you navigate to another route using `A` or`useNavigate`):

- Middleware returns a wrong pathname. For login for example, I get `/_m/src/routes/login.tsx/0/routeData`
- The middleware isn't even executed when you don't access the session cookie in the route, so `console.log(pathname)` is not even shown.

### Expected behavior 🤔

That the pathname always returns the correct pathname and middleware is executed on both page load or internal navigation

### Steps to reproduce 🕹

Steps:

1. run `npm init solid@latest` and chose auth version
2. add a middleware in entry server which redirects to `/` when being logged in and wanting to access `/login`. The one is used: 
```ts
export default createHandler(
  ({ forward }) =>
    async event => {
      const { pathname } = new URL(event.request.url);
      const session = await getUser(event.request);
      console.log(pathname); //here
      if (session && pathname === "/login") return redirect("/");
      return forward(event);
    },
  renderAsync(event => <StartServer event={event} />)
);
```
3. Comment out this part in login because we want to use middleware:
```ts
export function routeData() {
  return createServerData$(async (_, { request }) => {
    if (await getUser(request)) {
      //throw redirect("/"); remove here because we use redirection in middleware
    }
    return {};
  });
}
```
4. create new route to demonstrate my second point:
```ts
export default function Empty() {
  return <div>Empty Route</div>
}
```
5. add `A` links in `/index` pointing to both `/login` and new route `/empty`.
6. register and test out the behavior by clicking the links you just added on `/`

But because I'm so nice, you can just test it out here with everything ready ;)
[my-app.zip](https://github.com/solidjs/solid-start/files/12144004/my-app.zip)

### Context 🔦

Protecting, hiding routes using redirection.

### Your environment 🌎

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K
    Memory: 1 GB / 16 GB
Binaries:
    Node: 20.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.183)
```

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
