### ISSUE TITLE
[Bug?]: Cookie unsign fails if cookie includes special character

### ISSUE THREAD

**Issue by GiyoMoon** [solidjs/solid-start#954]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If I manually set a cookie in the client to include a special character (`%`, `&` etc.), unsigning it on the server fails and results in a error.

### Expected behavior 🤔

Unsigning the cookie shouldn't throw an error.

### Steps to reproduce 🕹

I created an example here: https://github.com/GiyoMoon/solid-start-cookie-unsign

Steps to reproduce:

```
git clone https://github.com/GiyoMoon/solid-start-cookie-unsign
cd solid-start-cookie-unsign
pnpm install
pnpm dev
```
1. Navigate to http://localhost:3000
2. Manually set the cookie on the client side (in your browser inspect for example). Set the name to `cookie` and the value to a special character like `%` or `&`
3. Click the "Get cookie" button and watch solid start explode
4. If the cookie doesn't include a special character, it works just fine and you should see undefined printed in the server console because the cookie isn't signed properly (expected behaviour)

### Context 🔦

Of course this isn't a bug which happens in normal use as users usually don't go and set their cookies manually. I wouldn't have noticed it if I didn't have the cookie set on localhost:3000 by another application which used to include `%`.

### Your environment 🌎

```shell
System: Apple M1 Pro v13.4.1
Nodejs: v18.16.1
```
[package.json](https://github.com/GiyoMoon/solid-start-cookie-unsign/blob/main/package.json)

**Comment by edivados** [comment]
The server tries to usign `&` but is expecting something in this format `<value>.<hash>`. Splits at the dot but there is no hash part so it passes the `&` to `atob('&')` and atob will throw if it encounters non valid base64 characters.

Using the secret in your example the value should be: `&.AqyMrDRyEIsDNXJ66ke+cnVmQqVZe5c/I+Wr9k0Jhbw`

https://github.com/solidjs/solid-start/blob/5dd795f74b46ca38938e17b9bdb632a922117bad/packages/start/session/cookieSigning.ts#L27C1-L38C3

**Comment by GiyoMoon** [comment]
Yes I know. But this shouldn't cause an error and the get cookie function should return undefined because the cookie isn't signed properly right?

**Comment by edivados** [comment]
Agree and would expect the same.

Side note: *I overlooked the context part. Sorry about that.*

**Comment by coleea** [comment]
Hi. Can I take this issue ?

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
