### ISSUE TITLE
[Bug?]: Cloudflare 404 error when last query param contains a "."

### ISSUE THREAD

**Issue by mr-14** [solidjs/solid-start#963]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Navigating to the following url would result in a 404 error when deployed on Cloudflare:

`https://pool.kapybara.io/?utm_source=cexplorer.io`

I've tried the following changes to make the problem go away, which led me to believe that there's a possible bug in the Cloudflare adapter that interprets the above query param as part of the domain string. 

- Deploying the code to Netlify works
- Using React framework on Cloudflare works
- Appending another query param to the end works. (i.e. `https://pool.kapybara.io/?utm_source=cexplorer.io&v=1`)

Any advice? Thanks!

### Expected behavior 🤔

Should not result in 404 error

### Steps to reproduce 🕹

Steps:

1. Create a Solid bare project by following [Project setup](https://start.solidjs.com/getting-started/project-setup)
2. Deploy to Cloudflare by following [Deploy a Solid site](https://developers.cloudflare.com/pages/framework-guides/deploy-a-solid-site/)
3. You should be able to see the example site on Cloudflare. Append `?foo=google.com` to the end of the url

### Context 🔦

I'm using a third party service that will list my site on their website. However, they would append an extra query string, `?utm_source=cexplorer.io`, to the end of my url. Hence, resulting in a 404 error when linking from their website.

**Comment by edivados** [comment]
The entire url including query params is used to determine if it is a static asset which causes a 404 in this case.

**Comment by mr-14** [comment]
I've just updated `solid-start-cloudflare-pages` to `0.2.32`. It seem that the problem still persists. Am I missing something?
I appreciate the help!

**Comment by edivados** [comment]
The fix is in `0.3.3`.
