### ISSUE TITLE
[Bug?]: `clientAddress` doesn't honour the `X-Forwarded-For` header

### ISSUE THREAD

**Issue by cjdell** [solidjs/solid-start#967]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'd have expected to be able to set a trusted proxy somewhere like you can in `express`:
```
app.set("trust proxy", ["127.0.0.1", "::1"]);
```
As a workaround I can observed the header directly, but not having this is surprising and may trip people up. The convention of using `x-forwarded-for` and `x-forwarded-proto` headers is well established and should be relatively easy to implement. If someone can show me where to look I will try to make a pull request myself.

Thanks!

### Expected behavior 🤔

Sample API route demonstrating the issue:
```
export async function GET({ request, clientAddress }: APIEvent) {
  return json({ myIP: clientAddress, myRealIP: request.headers.get("x-forwarded-for") });
}
```
The two IP addresses should be the same, but instead we see the IP address of the proxy.

### Steps to reproduce 🕹

Steps:

1. Start a SolidStart app behind a proxy, i.e. NGINX or Traefik
2. Make sure the proxy is configured to proxy `X-Forwarded-*` headers
3. Add the API route above.
4. Visit the API route directly via the browser.
5. Observe the differences between the two IP address. They should be the same.

### Context 🔦

Use SolidStart behind a SSL terminating proxy for both development and production. In my case, Traefik.

### Your environment 🌎

```shell
Linux environment
Node 18
Traefik SSL terminating proxy with Let's Encrypt
```

**Comment by edivados** [comment]
Looked if other adatpers were doing anything with it. The vercel adapter is the only one.
https://github.com/search?q=repo%3Asolidjs%2Fsolid-start+x-forwarded-for&type=code

I think this should give the desired result:

```js
clientAddress: req.headers["x-forwarded-for"] || req.socket.remoteAddress,
```

Two places here:

https://github.com/solidjs/solid-start/blob/b2a09b38f13024b706fe71e572c4231c92d4d15b/packages/start-node/server.js#L48-L66

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
