### ISSUE TITLE
[Bug?]: strange issue when going back the homepage from a `mdx` generated page

### ISSUE THREAD

**Issue by xarthurx** [solidjs/solid-start#968]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

This is a very strange problem that I cannot even determine if this is a solid-start specific issue, but I only experienced it when I recently started to use solidjs as my amin js framework.

# Problem description

I have three pages created: Home, About, News.
The `About` page is generated from a markdown file `credits.mdx`, while the `News` page is purely generated by a `jsx`.
![image](https://github.com/solidjs/solid-start/assets/1921878/c7780abd-e6fb-4e8c-bd2b-608f2e5fe070)

# with JSON IO
On the Homepage, I have a table, using `fetch` to read from a local `.json` file and create with "AG Grid".

- refreshing / landing on the `Home` ==> No problem.
- click `News` and then click `Home` ==> no problem.
- click `About` and then click `Home` ==> json issue:
![image](https://github.com/solidjs/solid-start/assets/1921878/8447e599-7095-49eb-961c-ca1ff6587bff)
  - then if I refresh the `Home` page, things are fine again.

# no JSON IO
If I disable the table generation section in the `Home` ==> everything works fine.

# Guess
Rationally thinking, this should be related to the IO process of the json file, where
```javascript
export async function loadJson(query) {

  const response = await fetch("src/schedule.json");
  const res = await response.json();
  const curYr = res[query];

  // console.log(curYr);
  return curYr;
}

function Schedule() {

  // todo: craete multiple entry in the schedule.json for different years
  const [rowData] = createResource(2023, loadJson);

  const columnDefs = [
    { headerName: "Week", field: 'week' },
    { headerName: "Date", field: 'date' },
    { headerName: "Topic", field: 'topic' },
  ];

  const defaultColDef = {
    flex: 1,
    editable: false,
    // suppressNavigable: true,
    // cellClass: 'no-border'
  };

  const gridOptions = {
    suppressCellFocus: true
  }

  // todo: add auto selection of the current week
  return (
    <>

      <div text-slate-8 grid text-center mx-auto mb-10 py-4 dark:text-white-2>
        <h2 mb-0>
          2023 Fall Schedule
        </h2>
      </div>

      <Show
        when={rowData()}
        fallback={
          <h1>loading schedule...</h1>
        }
      >
        <div dark class="ag-theme-material ag-grid">
          <AgGridSolid
            gridOptions = {gridOptions}
            columnDefs={columnDefs}
            defaultColDef={defaultColDef}
            rowSelection={'single'}
            rowData={rowData()}
          />
        </div>
      </Show>

    </>
  );
}

```

Is the problem caused by the `async` func?  or what happens behind the scene when going back to `Home` from the `mdx`-generated `About` page?

### Expected behavior 🤔

Jumping back-forth from the Nav bar should not generate doctype issue.

### Steps to reproduce 🕹

Steps:

1. clone the repo: https://github.com/xarthurx/debugWeb
2. run the website
3. do the above steps

### Context 🔦

source code: https://github.com/xarthurx/debugWeb

**Comment by xarthurx** [comment]
OK, I found out what is the problem:
In
```
export async function loadJson(query) {

  const response = await fetch("src/schedule.json");
  const res = await response.json();
  const curYr = res[query];

  // console.log(curYr);
  return curYr;
}
```

If I do
`  const res = response.json();` (without the `await`) func, then everything seems to be fine now.
Closing the issue.

**Comment by edivados** [comment]
The json file is in the src directory so fetch will not work.

You can import the json data like this.

```js
const res = await import("~/schedule.json").then(m => m.default);
```

Or move the json file to your public folder and use fetch.

```js
const res = await fetch('/schedule.json').then(res => res.json());
```

Also I would recommend to add `ag-grid-community` to your dependencies.

**Comment by xarthurx** [comment]
> The json file is in the src directory so fetch will not work.
> 
> You can import the json data like this.
> 
> ```js
> const res = await import("~/schedule.json").then(m => m.default);
> ```
> 
> Or move the json file to your public folder and use fetch.
> 
> ```js
> const res = await fetch('/schedule.json').then(res => res.json());
> ```
> 
> Also I would recommend to add `ag-grid-community` to your dependencies.

Thank you for the fix.
My questions is, why does it work in the first try? (When not browsing to the mdx-generate page, everything works)

**Comment by edivados** [comment]
The reason you have access to src file like 'schedule.json' in dev is because vite's server is serving them. In production they would not be around.

The behavior is caused by using a relative path `src/schedule.json` and not absolute `/src/schedule.json` in the browser.

### Case 1: Navigating to Home directly
At the time the fetch request is executed you are at `http://localhost:3000/` so the request becomes `http://localhost:3000/src/schedule.json`

### Case 2: Using `A` from About to Home or News to Home
The client side router kicks in and no full page reload is done. The page just gets updated client side. At the time the fetch request is executed you are still on `http://localhost:3000/docs/credits` so the request becoms `http://localhost:3000/docs/src/schedule.json` which does not exist.

Same applies to News => Home but since there is only one extra path segment the request becoms `http://localhost:3000/src/schedule.json`.

**Comment by edivados** [comment]
> > The json file is in the src directory so fetch will not work.
> > You can import the json data like this.
> > ```js
> > const res = await import("~/schedule.json").then(m => m.default);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or move the json file to your public folder and use fetch.
> > ```js
> > const res = await fetch('/schedule.json').then(res => res.json());
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also I would recommend to add `ag-grid-community` to your dependencies.
> 
> Thank you for the fix. My questions is, why does it work in the first try? (When not browsing to the mdx-generate page, everything works)

Also pls be aware of the following things here:

Example 1:

Basically embeds the data into your build. To update it you have to rebuild your application

Example 2:

If you are going to turn on ssr it will not work on the server because `/schedule.json` is not a valid url in this context.

**Comment by xarthurx** [comment]
@edivados  Brilliant explanation! 
Thank you. I'm closing this issue.

**Comment by xarthurx** [comment]
It seems I need to "route" the file first?
Does it mean something like:
```
<Routes>
  <Route my-file />
  <FileRoutes />
</Routes>
```

**Comment by edivados** [comment]
Did you move the file to public directory?

**Comment by xarthurx** [comment]
Yes, it is in the public folder.

**Comment by edivados** [comment]
I am assuming you are still using the resource in Schedule function. I can't come up with a definitive/reliable solution.
With the file in the public directory I see this two options during ssr:

- Do an http request (fetch) for the file (You would have to know the server url somehow like you mentioned.)
- Read the file from the file system (How would you reliably get the path to public dir? (Does it break in in dev, edge etc.) 

I would suggest to ask in the discord channel for advice on this. I am sure someone with more experience can give you a proper solution.

A temporary solution that I can offer is to only run the resource on the client:
```jsx
import { isServer } from 'solid-js/web';

export async function loadJson(query) {
  const res = await fetch('/schedule.json').then(res => res.json());
  const curYr = res[query];
  return curYr;
}

function Schedule() {
  // todo: craete multiple entry in the schedule.json for different years
  const [rowData] = createResource(() => isServer ? false : 2023, loadJson);

...
```
