### ISSUE TITLE
[Bug?]: Cant run trpc-example

### ISSUE THREAD

**Issue by vladmelnikov** [solidjs/solid-start#969]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I am trying to run trpc example i got error 
```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/user/Projects/pet/Solid/dist/server.js' imported from /Users/user/Projects/pet/Solid/node_modules/.pnpm/solid-start-node@0.2.19_solid-start@0.2.30_undici@5.15.1_vite@4.4.6/node_modules/solid-start-node/index.js
```

### Steps to reproduce 🕹

Steps:

1. pnpm create
2. pnpm install
3. choose trpc, typescript, ssr
4. pnpm start

### Your environment 🌎

```shell
macos ventur 13.5, node v18.15.0, pnpm 8.3.0, solid-start - 0.2.30
```

**Comment by ryansolid** [comment]
I think you need to build before the start command.

`pnpm dev` runs it in dev mode

Otherwise you need to run `pnpm build` and then `pnpm start` to run it in prod mode.
