### ISSUE TITLE
Generated metadata.json clash with de facto standard web app manifest

### ISSUE THREAD

**Issue by lirbank** [solidjs/solid-start#970]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

A web app manifest file can have any name, but is commonly named manifest.json and served from the root (your website's top-level directory). https://web.dev/add-manifest/#create

Placing a web app manifest file in `/public/manifest.json` or generating one in `/src/routes/manifest.json.ts` works in dev mode but not when building, since they are overwritten by SolidStart's own manifest.json file.

### Expected behavior 🤔

Can we rename the SolidStart manifest.json to `client.manifest.json` or such so my manifest.json file is served?

### Steps to reproduce 🕹

Steps:

1. Create a /public/manifest.json file
2. npm run build
3. npm run start
4. Access http://localhost:3000/metadata.json ← Wrong metadata.json file served.

### Context 🔦

I am porting an existing Next.js app to SolidStart. I can rename my web app manifest.json, but since most ppl probably expect manifest.json to be available, perhaps it would be better to release the manifest.json name space for arbitrary dev use.

**Comment by ryansolid** [comment]
Interesting. That manifest is the one that Vite generates: https://vitejs.dev/guide/backend-integration.html

I wonder if there is a way to rename it or have it generate in a different location. Ah yes: https://vitejs.dev/config/build-options.html#build-manifest

Ok. We can look at renaming it to something like `asset-manifest.json`.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
