### ISSUE TITLE
[Bug?]: forcing to use https in version 0.2.31 is breaking AuthJS in localhost

### ISSUE THREAD

**Issue by phouverneyuff** [solidjs/solid-start#971]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I try to log in using AuthJS in localhost, it's redirecting  me to HTTPS  instead of HTTP, and it's the only protocol available in localhost

### Expected behavior 🤔

I should redirect to http://localhost:3000/api/auth/signin/auth0 when I click on the sign. When I change solid-start to use 0.2.30 it backs to work.

### Steps to reproduce 🕹

Steps:

1. Follow the AuthJS tutorial 
2. Set AUTH_URL=http://localhost:3000 in your .env file
3. Use solid-start dependency - version 0.2.31 
4. Start your app: ```pnpm dev```
5. Try to login

### Context 🔦

I'm trying to log in using AuthJS using Solid Start 

### Your environment 🌎

```shell
System: Ubuntu 23
Node: v.19.8.1
pnpm: 8.6.11

Deps:
"@auth/core": "^0.10.0",
"@auth/solid-start": "^0.1.1",
"@solid-auth/base": "^2.0.3",
"@solidjs/meta": "^0.28.6",
"@solidjs/router": "^0.8.2",
"solid-js": "^1.7.9",
"solid-start": "0.2.30",
"solid-ts-hooks": "^0.0.9",

.env:
AUTH_URL=http://localhost:3000
AUTH0_BASE_URL='http://localhost:3000'
```

**Comment by ryansolid** [comment]
Ok. One PRs says this fixes AuthJS the other issue says it breaks it. I need some clarity here. This is the PR that made the change: https://github.com/solidjs/solid-start/pull/966. @zimonitrome any thoughts?

@OrJDev could use your wisdom. What is the expectation here?

**Comment by OrJDev** [comment]
Hey there, can you create a brand new app using create jd app, and select authjs, the issue might have been fixed in one of the latest releases as everything seems to work fine on our end

https://github.com/orjdev/create-jd-app

This will use this authjs adapter:

https://mediakit-taupe.vercel.app/auth/install

**Comment by phouverneyuff** [comment]
For those who have the same issue, you will be probably doing these changes on your app, if it was created using the create-jd-app template:
https://github.com/OrJDev/create-jd-app/commit/0a81a7bbe0d20e5db476ba90277ececb75e00bd6

**Comment by emdede** [comment]
I had the same issue as the author of the PR. The `x-forwarded-proto` is essential if you run a reverse proxy.

Before it was working on localhost and broken in production (with proxy)
Now it's the other way around.

The addition of the `x-forwarded-proto` check is important, however the fix also changed the fallback protocol from `http` to `https`. I guess by leaving in the header check and reverting the fallback value `|| 'https'` back to `|| http`, this should be resolved adequately for both local and prod environments.

**Comment by phouverneyuff** [comment]
worked at 0.2.32 

Thanks: @ryansolid  @emdede
