### ISSUE TITLE
[Bug]: "undefined is not a valid base path" after setting `base: 'http://localhost:3000'` w/ or w/o trailing slash

### ISSUE THREAD

**Issue by devinrhode2** [solidjs/solid-start#979]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In a new solid app:
```
npm init solid@latest
  create-solid@0.3.1
create-solid version 0.2.30

✔ Which template do you want to use? › bare
✔ Server Side Rendering? … yes
✔ Use TypeScript? … yes
found matching commit hash: 2f44d456e4814b997058fb366d7361f0d6b1e4e8
/Users/drhode/.degit/github/solidjs/solid-start/2f44d456e4814b997058fb366d7361f0d6b1e4e8.tar.gz already exists locally
```

Add `base` to vite.config.ts:
```ts
import solid from 'solid-start/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  base: 'http://localhost:3000/',
  plugins: [solid()],
});
```

Run `npm run build && npm run start` *error does not appear in dev mode*:
<img width="1312" alt="ScreenShot 2023-08-09 at 09 24 26@2x" src="https://github.com/solidjs/solid-start/assets/539816/75bd4938-fe31-4b3b-9efd-8133b3b11fba">
Here's where the exception occurred:
<img width="1312" alt="ScreenShot 2023-08-09 at 09 24 56@2x" src="https://github.com/solidjs/solid-start/assets/539816/4027878f-cd66-45e8-8ed0-6ff0d8abe355">

Here's same code, where error does not occur, in dev mode:
<img width="1312" alt="ScreenShot 2023-08-09 at 09 25 31@2x" src="https://github.com/solidjs/solid-start/assets/539816/e39f538c-fc0b-486e-b6d8-54b003abf87d">

Removing or adding trailing slash on `localhost:3000` doesn't affect the issue.

I'm not sure if changing base path to `http://localhost:3000/foo` or `/foo` fixes the error, because the file that has the error just doesn't load:
<img width="791" alt="ScreenShot 2023-08-09 at 09 29 11@2x" src="https://github.com/solidjs/solid-start/assets/539816/afc801a0-6d60-4da5-9625-e5827d45d072">

Setting to `'/'` makes the error disappear, but I need to set it to a different origin.

### Expected behavior 🤔

base path should not be undefined!

### Steps to reproduce 🕹

1. Create a new SolidStart app with SSR
2. Add a `base: 'http://localhost:3000'` to `vite.config.ts`
3. Run production app: `npm run build && npm run start`
4. View error in browser console

### Context 🔦

I need to load assets from a different origin.

I initially prefixed paths in index.html via some scripting, but that only goes so far, entry-client will load more scripts, and there's no good way to prefix those outside of vite.

(Core need is to add `Access-Control-Allow-Origin` headers to html requests and `.js` files, so they can be loaded on other origins.)

### Your environment 🌎

```shell
what command do I run?
```

**Comment by devinrhode2** [comment]
Although this seemed benign at first, I noticed that my mui inputs seem to have no javascript, that leads me to think that all scripts not in index.html aren't getting loaded.

**Comment by devinrhode2** [comment]
wherefortthousometimeswereadcompiledcodeaslastresort

<img width="1252" alt="ScreenShot 2023-08-10 at 16 06 30@2x" src="https://github.com/solidjs/solid-start/assets/539816/ac2ab930-a96c-4055-9ae9-b3511875ccf7">

<img width="645" alt="ScreenShot 2023-08-10 at 16 12 44@2x" src="https://github.com/solidjs/solid-start/assets/539816/e206605b-48df-4db6-bbcf-02e1788a822b">

Trace this a few function calls up,
<img width="1252" alt="ScreenShot 2023-08-10 at 16 04 15@2x" src="https://github.com/solidjs/solid-start/assets/539816/380f30dd-0b72-4d21-b7f5-8c43a2b4d521">

vite my replace this in here ^^^.

So now we can focus in on:
```ts
resolvePath('', base)
```
My first question is, what is this line of code really intending to do?

Second, given these args:
```ts
resolvePath('', 'http://localhost:2227/')
```

Specifically: why do these arguments case the function to return undefined?

It seems the first arg is intended for the `base`, second arg is for the path.
![Uploading ScreenShot 2023-08-10 at 16.18.01@2x.png…]()

And then we have this commit `172e86b`:
<img width="1260" alt="ScreenShot 2023-08-10 at 16 18 47@2x" src="https://github.com/solidjs/solid-start/assets/539816/22cde926-49e1-4d00-8b81-fa61fbd1a948">

...

**Comment by devinrhode2** [comment]
Read the test cases: https://github.com/solidjs/solid-router/blob/379a396e3c1857ff15bbbc56dfdd059d121d0d47/test/utils.spec.ts

It seems this function was NOT intended to handle origins at all

Here's a SMOKING GUN, but doesn't really do much other than grab my attention:
if a `path` quote `hasSchemeRegex` then we just `return undefined` when that should probably be a `throw new Error('A path should never have a scheme.');`
<img width="772" alt="ScreenShot 2023-08-10 at 16 35 28@2x" src="https://github.com/solidjs/solid-start/assets/539816/b6a427b1-031d-4a4f-a1b3-1fc012ecec35">

Here's the REALLY fishy thing.

In @solidjs/router, order or args passed to `resolvePath` seems correct:

In this file in solid-start, the order of the args appears to be swapped, which is really confusing, this seems to be a central to the problem..
<img width="1200" alt="ScreenShot 2023-08-10 at 16 34 16@2x" src="https://github.com/solidjs/solid-start/assets/539816/a937dfa3-7d42-4101-afd7-0b956920db02">


I would like to keep reading the rest of this `resolvePath` function, but it's quite clear now. The order of these args is getting swapped somehow, the `base` from vite is getting passed in as the `path` to `resolvePath`.

**Comment by devinrhode2** [comment]
Next question: How are the args passed to `resolvePath(` getting swapped??

They are clearly defined in `@solidjs/router`, it has type definitions, whereas the code without type definitions is on line ... 1597 does not.

And.. looks like it's swapped BECAUSE I FREAKING JUST SWAPPED IT.

Swapping it causes this test to fail:
<img width="857" alt="ScreenShot 2023-08-10 at 16 52 37@2x" src="https://github.com/solidjs/solid-start/assets/539816/23596a0a-bbd4-4972-bc3f-d46453416775">

I tried adding some tests around origin handling, and those tests fail, confirming the thinking that this function isn't really mean to handle origins, just paths. `base` is not expected to be an origin.

<img width="1247" alt="ScreenShot 2023-08-10 at 16 55 11@2x" src="https://github.com/solidjs/solid-start/assets/539816/10fb444d-e88f-4e1c-ac1e-a9fde395c8a3">

**Comment by devinrhode2** [comment]
Can we go up the stack now, back to `resolvePath('', base)`?

Clearly Solid.js is not expecting users to set `base: 'http://alternate-domain.com/'` in their vite config.

The obvious/easy/simple change, when we detect a base looks like an origin, throw an error, which will simply have better wording than "undefined is not a valid base path". (We could say "SolidStart does not support alternate origins as a base path"). However, vite does support this, getting to Ryan's original comment: Should SolidStart support this just because vite supports it?

My alternate domain is actually just an nginx proxy, which adds cors headers to html responses and <script> tags. Vite's `cors: true` option was not adding these headers for me.

Nginx is nice to have for an extra layer of security, but wrt SolidStart, this is what I am trying to use an alternate origin for: just add these headers.

For now, we could improve the error message, and revisit support for alternate origins in a new thread?

**Comment by devinrhode2** [comment]
Setting `base: 'http://nginx:1234/'`, we see this in preview/prod server::
![ScreenShot 2023-08-10 at 18 08 10@2x](https://github.com/solidjs/solid-start/assets/539816/f74611dd-749d-4e5a-8f0a-f6eb6c330ada)


Setting it to `base: 'http://localhost:2227/'` (port set via `solid-start --port 2227 start`), we get this:
![ScreenShot 2023-08-10 at 18 10 20@2x](https://github.com/solidjs/solid-start/assets/539816/fef9b2d6-78a2-4d4c-9a4e-ac56b6379204)

So somehow it IS applying to index.html, but not subsequent requests.

One idea I've had, is to do a hack, somehow entry-client indicates where it loaded from, and other scripts use that same origin.

**Comment by devinrhode2** [comment]
I had this same problem a few months ago:
 - As some code loaded via some `<script>` tag, which origin did I load from?
 - We can use `document.currentScript` as a really strong indicator, but otherwise it's best to have an `id` attribute on our "home" script (entry-client here)
 - Given we've basically poly-filled `document.currentScript`, we just parse the `src` attribute with `new URL(scriptSrc).origin`.

The entry-client script appears in index.html like this, today:
```
<script type="module" async src="http://localhost:2227/assets/entry-client-45dd5eb0.js">
```

Now... my nginx proxy does get it's own copy of the build `dist/public` folder, but the browser isn't connecting to multiple origins: It just connects to nginx, and nginx forwards basically everything to Solid's node server, adding some headers in some cases. (I've prefixed all solid routes with a `/ui` folder, so that makes it easy to identify them in nginx).

So from a browsers perspective, html and scripts come from the same origin.

**Comment by devinrhode2** [comment]
Now, I'll outline how such a "hack" could be implemented:
1. We'll add/modify code around this `resolvePath('', base)` call. (obviously)
2. We will take the `base` (as search/replaced by Vite's build) and split this into: A. Origin, and B. basePath.
3. I could create an initial PR, which throws an error when `Origin` is detected, and passes `base` on to `resolvePath` as it is today. (No functional change, just improved error message.)
4. In a second PR, I could take that `Origin`, and somehow "pass" it over to other code that is appending more `<script>` tags. This will certainly be the more difficult PR.

> I think being able to customize the origin is a pretty powerful feature. It allows solid apps to load into other apps with just a little bit of script injection. I have this idea for a library called "FakeFrame" (could be built for any framework), which is essentially like an iframe:
> ```tsx
> <FakeFrame
>   shadowDom={false}
>   origin={getOriginForEnv('local')}
>   uiRoute={'/ui/add'}
>   componentProps={{
>     // Getting nice typing here is the main challenge of this lib :)
>   }}
> />
> ```
> I briefly [took a stab at adding scripts support to justin fanani's `<html-include>` vanilla-js web component](https://github.com/devinrhode2/html-include-element-with-scripts/tree/devin/add-scripts-support), but have since put that on hold, creating a "bespoke" react component. As that component matures, it could be refactored into a generic piece, `<FakeFrame>` or `<html-include>`, etc.

**Comment by devinrhode2** [comment]
Exploring around the code to determine how I might get scripts other than `entry-client` to be properly prefixed.

I have this `instant` page, and.. there are urls for these files which are already prefixed:
![ScreenShot 2023-08-10 at 22 57 21@2x](https://github.com/solidjs/solid-start/assets/539816/99191fad-c33f-4414-b021-bf0c783fc8f4)

I think it's just a matter of getting SolidStart to use these prefixed urls

I think this will be quite hard in terms of just understanding how all the code is orchestrated. Feels like the change could possible be just a couple lines of some config somewhere... but that's surely not the case... just has that type of feeling.

**Comment by devinrhode2** [comment]
Ok.. so I think I definitely want to set `base` in `vite.config.ts`. I want the alternate origin to proliferate across the build.

I don't necessarily KNOW that other scripts aren't loading from the "wrong" origin: they simply aren't loading at all.

Perhaps if I just make a tiny fix around the `resolvePath('', base)` line, we can basically "skip over" the parsing error (`undefined is not a valid base path`) and... see what happens then...

**Comment by devinrhode2** [comment]
Ok, looks like all we had to do is "skip over" this little error!!!

Change:

<img width="783" alt="ScreenShot 2023-08-10 at 23 18 34@2x" src="https://github.com/solidjs/solid-start/assets/539816/09e0b33c-5bfc-40bf-be1e-7ef256b8f8dc">

Result:
![ScreenShot 2023-08-10 at 23 15 02@2x](https://github.com/solidjs/solid-start/assets/539816/50e0755d-cbcc-4f4e-a5a1-4dceec94b428)

I can get a PR submitted. Just for record, or copy/pasting, here's main snippet:
```tsx
  const BASE_URL = import.meta.env.BASE_URL;
  let basePath = BASE_URL;
  if (BASE_URL.startsWith("http")) {
    try {
      const url = new URL(BASE_URL);
      basePath = url.pathname;
      // No need to try and pass the Origin around:
      // Vite already proliferates BASE_URL across the build.
      // We just want to avoid crashing.
    } catch (e) {
      console.warn('BASE_URL starts with http, but `new URL` failed to parse it:', BASE_URL);
    }
  }
```

**Comment by ryansolid** [comment]
Yeah looks good something like this is what I was going to propose.
