### ISSUE TITLE
[Bug?]: SolidStart issue deploying to Vercel

### ISSUE THREAD

**Issue by MariuzM** [solidjs/solid-start#983]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I think I've done everything correct to setup for Vercel but getting Error :( 

Repo: https://github.com/MariuzM/test__solidstart-vercel

<img width="616" alt="image" src="https://github.com/solidjs/solid-start/assets/36937039/624899b4-004c-4624-b573-b9f3f9f748cc">

<img width="943" alt="image" src="https://github.com/solidjs/solid-start/assets/36937039/3e75b9f4-7677-4059-b9c4-22cdd281eaa5">

<img width="950" alt="image" src="https://github.com/solidjs/solid-start/assets/36937039/34821496-081e-467d-8503-b938a9131dbd">

**Comment by edivados** [comment]
Node 16 support was dropped in 0.3.x. and the vercel adapter sets the runtime config to node 16.

**Comment by MariuzM** [comment]
Hm i'm still having same issue after updates

    "solid-start-vercel": "^0.3.3",


```
export default defineConfig({
  plugins: [
    solid({
      ssr: true,
      adapter: solidStartVercel({ edge: false }),
    }),
  ],
});
```

**Comment by MariuzM** [comment]
Oh, ignore, something must be wrong on my other project but tried with the one i posted works
